### ISSUE TITLE
Error when running gcn example

### ISSUE THREAD

**Issue by yshenaw** [pyg-team/pytorch_geometric#1019]
## 🐛 Bug

I install the pytorch geometry from pip. When I run the gcn example, the following error occurs 

Traceback (most recent call last):
  File "examples/gcn.py", line 6, in <module>
    from torch_geometric.datasets import Planetoid
  File "/usr/local/lib/python3.8/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/usr/local/lib/python3.8/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/usr/local/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/usr/local/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.8/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/usr/local/lib/python3.8/site-packages/torch_sparse/__init__.py", line 44, in <module>
    from .tensor import SparseTensor  # noqa
  File "/usr/local/lib/python3.8/site-packages/torch_sparse/tensor.py", line 5, in <module>
    import scipy.sparse
  File "/usr/local/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/usr/local/lib/python3.8/site-packages/scipy/sparse/base.py", line 7, in <module>
    from scipy._lib._numpy_compat import broadcast_to
  File "/usr/local/lib/python3.8/site-packages/scipy/_lib/_numpy_compat.py", line 16, in <module>
    _assert_warns = np.testing.assert_warns
  File "/usr/local/lib/python3.8/site-packages/numpy/__init__.py", line 213, in __getattr__
    import numpy.testing as testing
  File "/usr/local/lib/python3.8/site-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/usr/local/lib/python3.8/unittest/__init__.py", line 60, in <module>
    from .async_case import IsolatedAsyncioTestCase
  File "/usr/local/lib/python3.8/unittest/async_case.py", line 1, in <module>
    import asyncio
  File "/usr/local/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/local/lib/python3.8/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/home/npz/GNN/pytorch_geometric/examples/logging.py", line 5, in <module>
    from torch_geometric.datasets import Planetoid
  File "/usr/local/lib/python3.8/site-packages/torch_geometric/datasets/__init__.py", line 1, in <module>
    from .karate import KarateClub
  File "/usr/local/lib/python3.8/site-packages/torch_geometric/datasets/karate.py", line 4, in <module>
    from torch_geometric.data import InMemoryDataset, Data
ImportError: cannot import name 'InMemoryDataset' from partially initialized module 'torch_geometric.data' (most likely due to a circular import) (/usr/local/lib/python3.8/site-packages/torch_geometric/data/__init__.py)

There is no error when I merely run the following code:

from torch_geometric.data import InMemoryDataset

## Environment

* OS: Ubuntu 16.04
* Python version: 3.8
* PyTorch version: 1.4
* CUDA/cuDNN version: None
* GCC version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
* Any other relevant information:

**Comment by yshenaw** [comment]
I think gcn.py and logging.py cannot be placed in the same folder.

**Comment by rusty1s** [comment]
Mh I am not really sure why this error occurs, but I can replicate it. I renamed the `logging.py` example and it seems to be fixed. There is some weird Python import stuff going on.
