### ISSUE TITLE
import error When I excute python gcn.py

### ISSUE THREAD

**Issue by pandabaoo** [pyg-team/pytorch_geometric#1079]
## Environment

* OS:Linux
* Python version:3.7.4
* PyTorch version:1.4.0
* CUDA/cuDNN version:10.1
* GCC version:7.3.0
* How did you try to install PyTorch Geometric and its extensions (pip, source):pip

## Additional context
Traceback (most recent call last):
  File "/Share/home/E18301151/anaconda3/envs/env1/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 44, in <module>
    from ._check_build import check_build  # noqa
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gcn.py", line 6, in <module>
    import torch_geometric
  File "/Share/home/Program/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/Share/home/Program/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 10, in <module>
    from .models import *  # noqa
  File "/Share/home/Program/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/nn/models/__init__.py", line 2, in <module>
    from .node2vec import Node2Vec
  File "/Share/home/Program/anaconda3/envs/env1/lib/python3.7/site-packages/torch_geometric/nn/models/node2vec.py", line 2, in <module>
    from sklearn.linear_model import LogisticRegression
  File "/Share/home/Program/anaconda3/envs/env1/lib/python3.7/site-packages/sklearn/__init__.py", line 81, in <module>
    from . import __check_build  # noqa: F401
  File "/Share/home/Program/anaconda3/envs/env1/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 46, in <module>
    raise_build_error(e)
  File "/Share/home/Program/anaconda3/envs/env1/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 41, in raise_build_error
    %s""" % (e, local_dir, ''.join(dir_content).strip(), msg))
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /Share/home/Program/anaconda3/envs/env1/lib/python3.7/site-packages/sklearn/__check_build:
__init__.py               setup.py                  _check_build.cpython-37m-x86_64-linux-gnu.so
__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

**Comment by rusty1s** [comment]
Is that a issue related to PyG?

**Comment by luyiyun** [comment]
I also have this error. When I downgrade sklearn to 0.21.3 or older version. The error doesn't happened.

**Comment by luyiyun** [comment]
It seems not be the problem of pyg. I make a experiment. When I just have torch 1.6.0 and sklearn 0.23.3 without pyg, the error still happens.
