### ISSUE TITLE
AttributeError: Can't pickle local object 'ClusterLoader.__init__.<locals>.HelperDataset'

### ISSUE THREAD

**Issue by CristinaMarsh** [pyg-team/pytorch_geometric#1236]
## ❓ Questions & Help

Hello, I try to run the example 'cluster_gcn'. But I got an error.

  `Partioning the graph... (this may take a while)
Done!
Traceback (most recent call last):
  File "C:/Users/Nihil/PycharmProjects/untitled2/cluster_gcn.py", line 73, in <module>
    loss = train()
  File "C:/Users/Nihil/PycharmProjects/untitled2/cluster_gcn.py", line 40, in train
    for data in loader:
  File "C:\Users\Nihil\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Nihil\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\Nihil\Anaconda3\envs\pytorch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Nihil\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Nihil\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Nihil\Anaconda3\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Nihil\Anaconda3\envs\pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ClusterLoader.__init__.<locals>.HelperDataset'`

Thank you in advance

**Comment by rusty1s** [comment]
Seems to be some weird pickling windows error. This may be caused by the fact that `HelperDataset` is only defined inside the class, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/cluster.py#L123-L138). It would be great if you could tell me if it helps to define it outside of the class.
