### ISSUE TITLE
DefaultCPUAllocator: can't allocate memory

### ISSUE THREAD

**Issue by prashantpandey** [pyg-team/pytorch_geometric#1306]
## ❓ Questions & Help

I have a small(ish) graph with ~28K nodes and ~48K edges. Each node has feature vector of size 64. However, when I try to run this GCN it is trying to allocate >300GB of RAM. Is that expected?

Data:
```
Data(edge_index=[2, 48638], test_mask=[28986], train_mask=[28986], val_mask=[28986], x=[28986, 64], y=[28986])
```

```
  class Net(torch.nn.Module):                                                        
      def __init__(self):                                                            
          super(Net, self).__init__()                                                
          self.conv1 = GCNConv(dataset.num_features, 16, cached=True)                
          self.conv2 = GCNConv(16, int(dataset.num_classes), cached=True)            
          # self.conv1 = ChebConv(data.num_features, 16, K=2)                        
          # self.conv2 = ChebConv(16, data.num_features, K=2)                        
                                                                                     
          self.reg_params = self.conv1.parameters()                                  
          self.non_reg_params = self.conv2.parameters()                              
                                                                                     
      def forward(self):                                                             
          x, edge_index, edge_weight = data.x, data.edge_index, data.edge_attr       
          x = F.relu(self.conv1(x, edge_index, edge_weight))                         
          x = F.dropout(x, training=self.training)                                   
          x = self.conv2(x, edge_index, edge_weight)                                 
          return F.log_softmax(x, dim=1)                                             
                                                                                     
  def train():                                                                       
      model.train()                                                                  
      optimizer.zero_grad()                                                          
      F.nll_loss(model()[data.train_mask], data.y[data.train_mask].long()).backward()
      optimizer.step() 
```

Error:
```
Traceback (most recent call last):
  File "src/meta_gnn.py", line 425, in <module>
    train()
  File "src/meta_gnn.py", line 307, in train
    F.nll_loss(model()[data.train_mask], data.y[data.train_mask].long()).backward()
  File "/home/ppandey/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "src/meta_gnn.py", line 301, in forward
    x = self.conv2(x, edge_index, edge_weight)
  File "/home/ppandey/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ppandey/.local/lib/python3.6/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 87, in forward
    x = torch.matmul(x, self.weight)
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 315503798256 bytes. Error code 12 (Cannot allocate memory)
```

**Comment by rusty1s** [comment]
No, that shouldn't consume such an amount of memory. My guess is that `data.num_features` or `data.num_classes` returns a very big number. Can you check that?

**Comment by prashantpandey** [comment]
Thanks for the response. You are right. 
```
Num features: 64 (data.num_features)
Num classes: 2721174 (dataset.num_classes)
```

So, I changed the out channels
```
          self.conv1 = GCNConv(dataset.num_features, 16, cached=True)                
          self.conv2 = GCNConv(16, 1, cached=True) 
```

But then I got this error:
```
Traceback (most recent call last):
  File "src/meta_gnn.py", line 397, in <module>
    train()
  File "src/meta_gnn.py", line 307, in train
    F.nll_loss(model()[data.train_mask], data.y[data.train_mask].long()).backward()
  File "/home/ppandey/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 2115, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
IndexError: Target 190192 is out of bounds.
```

Also, how can I set the `num_classes` in dataset to be 1. Because `y` attribute is 1-dimensional.

**Comment by rusty1s** [comment]
In case `y` is a one-dimensional `LongTensor`, `num_classes` will return the maximum value in `y` as the number of classes. What does your `y` encode exactly?

**Comment by prashantpandey** [comment]
Each node in the graph is assigned a single `long` value as a classifier. `Y` encodes the classifiers for each node in the graph.

**Comment by prashantpandey** [comment]
Also, the length of `Y` is 28,996. But `num_classes` is 2,721,174.
```
Data(edge_index=[2, 48638], test_mask=[28986], train_mask=[28986], val_mask=[28986], x=[28986, 64], y=[28986]
```

**Comment by rusty1s** [comment]
Well, I'm not sure against what do you want to train your model. If `num_classes` return 2,821,174, then that means that `y` holds a value that big.

**Comment by prashantpandey** [comment]
Ok. That makes sense. The maximum value in `Y` is the same as num_classes. I think I can change map the actual values in `Y` to a smaller subset and then try to run it.
