### ISSUE TITLE
SSL error downloading MNIST dataset

### ISSUE THREAD

**Issue by theveloped** [pyg-team/pytorch_geometric#1428]
## ❓ Questions & Help

Trying to run on of the MNIST examples I'm receiving an error about the SSL certificate. Is there a way I can manually download the dataset and place it in the correct folder? Please see the error below:

```
Traceback (most recent call last):
  File "mnist_voxel_grid.py", line 15, in <module>
    train_dataset = MNISTSuperpixels(path, True, transform=transform)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\site-packages\torch_geometric\datasets\mnist_superpixels.py", line 43, in __init__
    pre_filter)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\site-packages\torch_geometric\data\dataset.py", line 89, in __init__
    self._download()
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\site-packages\torch_geometric\data\dataset.py", line 141, in _download
    self.download()
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\site-packages\torch_geometric\datasets\mnist_superpixels.py", line 56, in download
    path = download_url(self.url, self.raw_dir)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\site-packages\torch_geometric\data\download.py", line 31, in download_url
    data = urllib.request.urlopen(url)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\Theveloped\.conda\envs\pytorch\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
```

**Comment by theveloped** [comment]
I'll leave this open for now as running the example by default causes an error but for anyone running into a similar error you can indeed simply download the tarball ([mnist_superpixels.tar.gz](https://ls7-www.cs.uni-dortmund.de/cvpr_geometric_dl/mnist_superpixels.tar.gz)) manually and place it in the correct location. Your project folder should be structured like so:

```
--- main_dir
   |-- examples
      |-- mnist_graclus.py
      |-- mnist_nn_conv.py
      |-- mnist_voxel_grid.py
      |-- etc.

  |-- data
     |-- MNIST
        |-- raw
           |-- mnist_superpixels.tar.gz
```

**Comment by AndreaCossu** [comment]
Hi @theveloped, @rusty1s . I was trying to download MNIST Superpixels dataset, but I ran into a 404 error. Apparently the link is broken. 
`superpix = MNISTSuperpixels(root='/path/to/folder)`

I also tried the link @theveloped provided but it returns 404 error. 
Do you have any idea on how to download the dataset? Thank you!

**Comment by rusty1s** [comment]
That is already fixed in master, sorry for that :)

You can install PyG from master via:
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```

**Comment by AndreaCossu** [comment]
Great, thanks!
