### ISSUE TITLE
Errors with ASAPooling when using CUDA

### ISSUE THREAD

**Issue by thorzhong** [pyg-team/pytorch_geometric#1463]
## ❓ Questions & Help
Hi:
    I can run this code successfully, https://github.com/rusty1s/pytorch_geometric/blob/d27e9cdc8936068821f90e3c7941471e19369288/test/nn/pool/test_asap.py. but error occurs after I add those codes, any suggestions will be helpful, thank you!

`devices = torch.device('cuda')
  edge_index = edge_index.to(devices)
  x = x.to(devices)`

the Traceback is as follows:

Traceback (most recent call last):
  File "test.py", line 30, in <module>
    test_asap()
  File "test.py", line 20, in test_asap
    out = pool(x, edge_index)
  File "/home/zhonglei/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhonglei/.local/lib/python3.6/site-packages/torch_geometric/nn/pool/asap.py", line 80, in forward
    edge_weight=edge_weight)
  File "/home/zhonglei/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhonglei/.local/lib/python3.6/site-packages/torch_geometric/nn/conv/graph_conv.py", line 60, in forward
    out = self.lin_l(out)
  File "/home/zhonglei/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhonglei/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/zhonglei/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1610, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_addmm

**Comment by rusty1s** [comment]
You need to also transfer your model/operator to the GPU, *e.g.*, `model = model.cuda()`.
