### ISSUE TITLE
Issue using Cluster Loader

### ISSUE THREAD

**Issue by shalinkpatel** [pyg-team/pytorch_geometric#1490]
## ❓ Questions & Help

I am attempting to use ClusterData and ClusterLoader to partition my computational graph and I keep getting the following.

Code:
```python
from torch_geometric.data import ClusterData, ClusterLoader
G = torch_geometric.data.Data(edge_index = extract[0], 
                              edge_attr = extract[1], 
                              x = torch.tensor(hms[:mat.shape[0]]).float().reshape(-1, 1, 100, 5), 
                              y = torch.tensor(labs[:,-2]).long())

cluster_data = ClusterData(G, num_parts=10, recursive=False,
                           save_dir='/gpfs_home/spate116/singhlab/GCN_Integration/notebooks/JX')
train_loader = ClusterLoader(cluster_data, batch_size=2, shuffle=True,
                             num_workers=6)

for d in train_loader:
    print(d)
```

Error:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-c90f2385ce8b> in <module>
      6                              num_workers=6)
      7 
----> 8 for d in train_loader:
      9     print(d)

/gpfs_home/spate116/ml/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

/gpfs_home/spate116/ml/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    854             else:
    855                 del self._task_info[idx]
--> 856                 return self._process_data(data)
    857 
    858     def _try_put_index(self):

/gpfs_home/spate116/ml/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
    879         self._try_put_index()
    880         if isinstance(data, ExceptionWrapper):
--> 881             data.reraise()
    882         return data
    883 

/gpfs_home/spate116/ml/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    392             # (https://bugs.python.org/issue2651), so we work around it.
    393             msg = KeyErrorMessage(msg)
--> 394         raise self.exc_type(msg)

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/gpfs_home/spate116/ml/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/gpfs_home/spate116/ml/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/gpfs_home/spate116/ml/lib/python3.7/site-packages/torch_geometric/data/cluster.py", line 148, in __collate__
    start = self.cluster_data.partptr[batch].tolist()
RuntimeError: CUDA error: initialization error
```

This is strange because I don't even invoke CUDA at this point. Any help would be great!

**Comment by rusty1s** [comment]
I'm not really sure what happens here, although there are similar issues in the [PyTorch issues page](https://github.com/pytorch/pytorch/issues/21092). Are you sure that none of the attributes in `G` sits on the GPU?
