### ISSUE TITLE
A error in install geometric

### ISSUE THREAD

**Issue by TuGengs** [pyg-team/pytorch_geometric#1505]
ERROR: Command errored out with exit status 1:
     command: /root/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5dbq37ht/torch-geometric/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5dbq37ht/torch-geometric/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ce6c1gaz
         cwd: /tmp/pip-install-5dbq37ht/torch-geometric/
    Complete output (33 lines):
    WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
    ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
    ERROR: No matching distribution found for pytest-runner
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/root/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmphca8zxm_', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5dbq37ht/torch-geometric/setup.py", line 44, in <module>
        include_package_data=True,
      File "/root/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/root/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/root/miniconda3/lib/python3.7/site-packages/setuptools/dist.py", line 702, in fetch_build_eggs
        replace_conflicting=True,
      File "/root/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
        replace_conflicting=replace_conflicting
      File "/root/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/root/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/root/miniconda3/lib/python3.7/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/root/miniconda3/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/root/miniconda3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmphca8zxm_', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rusty1s** [comment]
That's weird. Can you try to install `pytest-runner` first and try to re-install afterwards?

**Comment by ucasiggcas** [comment]
@rusty1s Thanks
got it

**Comment by zhouzhiqian** [comment]
met the same problem. my solution is 
```
pip uninstall pytest-runner
pip install pytest-runner
pip install torch-geometric
```
then, everything is OK.
