### ISSUE TITLE
Error in GED dataset download

### ISSUE THREAD

**Issue by Hafplo** [pyg-team/pytorch_geometric#1640]
## 🐛 Bug

While running main.py from [Extended-SimGNN](https://github.com/gospodima/Extended-SimGNN)
I am getting an error when downloading GEDDataset from the Google Drive URL
I suspect this happens because the url has invalid characters for filename such as "?"

**Note: I am using Windows 10 pro with venv, without docker or virtualization

## To Reproduce

1. run main.py from [Extended-SimGNN](https://github.com/gospodima/Extended-SimGNN)
alternatively - download any GEDDataset directly from pyg 

## Expected behavior

the dataset file is supposed to be downloaded from url and save to self.raw_dir for further processing

## Environment

* OS: Windows 10 Pro
* Python version: 3.7.7
* PyTorch version: 1.6.0+cpu
* CUDA/cuDNN version: N/A
* GCC version: N/A
* Any other relevant information:

## Additional context
Downloading https://drive.google.com/uc?export=download&id=10czBPJDEzEDI2tq7Z7mkBjLhj55F-a2z
Traceback (most recent call last):
  File "<ROOT_DIR>/Extended-SimGNN/src/main.py", line 36, in <module>
    main()
  File "<ROOT_DIR>/Extended-SimGNN/src/main.py", line 15, in main
    trainer = SimGNNTrainer(args)
  File "<ROOT_DIR>\Extended-SimGNN\src\simgnn.py", line 192, in __init__
    self.process_dataset()
  File "<ROOT_DIR>\Extended-SimGNN\src\simgnn.py", line 207, in process_dataset
    self.training_graphs = GEDDataset(r'datasets\{}'.format(self.args.dataset), self.args.dataset, train=True)
  File "<ROOT_DIR>\pyg_sandbox\venv\lib\site-packages\torch_geometric\datasets\ged_dataset.py", line 89, in __init__
    pre_filter)
  File "<ROOT_DIR>\pyg_sandbox\venv\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "<ROOT_DIR>\pyg_sandbox\venv\lib\site-packages\torch_geometric\data\dataset.py", line 89, in __init__
    self._download()
  File "<ROOT_DIR>\pyg_sandbox\venv\lib\site-packages\torch_geometric\data\dataset.py", line 141, in _download
    self.download()
  File "<ROOT_DIR>\pyg_sandbox\venv\lib\site-packages\torch_geometric\datasets\ged_dataset.py", line 107, in download
    path = download_url(self.url.format(name), self.raw_dir)
  File "<ROOT_DIR>\pyg_sandbox\venv\lib\site-packages\torch_geometric\data\download.py", line 33, in download_url
    with open(path, 'wb') as f:
OSError: [Errno 22] Invalid argument: 'datasets\\AIDS700nef\\raw\\uc?export=download&id=10czBPJDEzEDI2tq7Z7mkBjLhj55F-a2z'

**Comment by rusty1s** [comment]
The download works for me. Can you test if the following code works for you?
```python
from torch_geometric.datasets import GEDDataset

dataset = GEDDataset(root, name="LINUX")
```

**Comment by Indradyumna** [comment]
Hi, 
The download link seems to be broken now. Could you please check.
