### ISSUE TITLE
Unable to run the SNLI in pytorch examples

### ISSUE THREAD

**Issue by rburraAMD** [pyg-team/pytorch_geometric#1643]
## To Reproduce

1. git clone https://github.com/pytorch/examples
2. pip install -r examples/snli/requirements.txt && python3 examples/snli/train.py

Observed below error :
python3 train.py --epochs 1 --dev_every 1 --no-bidirectional --dry-run
CATraceback (most recent call last):
  File "train.py", line 9, in <module>
    from torchtext import data
  File "/opt/conda/lib/python3.6/site-packages/torchtext/__init__.py", line 42, in <module>
    _init_extension()
  File "/opt/conda/lib/python3.6/site-packages/torchtext/__init__.py", line 38, in _init_extension
    torch.ops.load_library(ext_specs.origin)
  File "/root/.local/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/lib/python3.6/site-packages/torchtext/_torchtext.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

## Environment

* OS:UB-18.04
* Python version: 3.6 
* PyTorch version:1.7.0a0+fc1103a
* CUDA/cuDNN version:
* GCC version:7.5.0
* Any other relevant information:

**Comment by rusty1s** [comment]
This doesn't seem to be a PyG issue. Can you clarify?
