### ISSUE TITLE
Can not pass kwarg 'aggr' to PPFConv

### ISSUE THREAD

**Issue by jaredsagendorf** [pyg-team/pytorch_geometric#1691]
``` 
from torch_geometric.nn import PPFConv
P = PPFConv(aggr='mean')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home1/sagendor/miniconda/envs/geobind/lib/python3.8/site-packages/torch_geometric/nn/conv/ppf_conv.py", line 65, in __init__
    super(PPFConv, self).__init__(aggr='max', **kwargs)
TypeError: __init__() got multiple values for keyword argument 'aggr' 
```

**Comment by rusty1s** [comment]
Yes, that is intended since `PPFConv` is defined to use `max` aggregation. You can always change it later on though, *e.g.*:
```python
conv = PPFConv(nn)
conv.aggr = 'mean'
```
