### ISSUE TITLE
one error when I run function topk() on the last batch

### ISSUE THREAD

**Issue by zeyuanyin** [pyg-team/pytorch_geometric#1738]
## ❓ Questions & Help

I change the parameter `x` in `topk()` of example code.
There are 4 batches in dataset, and it runs correctly on the first three batches. When it run on the last batch, it will appear `RuntimeError` (as following).

```
Traceback (most recent call last):
  File "E:/REASEARCH/SUGPool/SAGPool-master/SAGPool-master/main.py", line 79, in <module>
    out = model(data)
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\REASEARCH\SUGPool\SAGPool-master\SAGPool-master\networks.py", line 41, in forward
    x, edge_index, _, batch, _ = self.pool2(x, edge_index, None, batch)
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\REASEARCH\SUGPool\SAGPool-master\SAGPool-master\layers.py", line 72, in forward
    perm = topk(s, self.ratio, batch)
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch_geometric\nn\pool\topk_pool.py", line 18, in topk
    num_nodes = scatter_add(batch.new_ones(x.size(0)), batch, dim=0)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch_scatter\scatter.py", line 31, in scatter_add
                out: Optional[torch.Tensor] = None,
                dim_size: Optional[int] = None) -> torch.Tensor:
    return scatter_sum(src, index, dim, out, dim_size)
           ~~~~~~~~~~~ <--- HERE
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch_scatter\scatter.py", line 12, in scatter_sum
                out: Optional[torch.Tensor] = None,
                dim_size: Optional[int] = None) -> torch.Tensor:
    index = broadcast(index, src, dim)
            ~~~~~~~~~ <--- HERE
    if out is None:
        size = src.size()
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch_scatter\utils.py", line 13, in broadcast
    for _ in range(src.dim(), other.dim()):
        src = src.unsqueeze(-1)
    src = src.expand_as(other)
          ~~~~~~~~~~~~~ <--- HERE
    return src
RuntimeError: The expanded size of the tensor (15907) must match the existing size (15908) at non-singleton dimension 0.  Target sizes: [15907].  Tensor sizes: [15908]

Process finished with exit code 1
```

I'd like to know why and how to solve it? Thanks.

**Comment by rusty1s** [comment]
It's hard for me to say what went wrong solely based on the error message. Can you show me a minimal example to reproduce?

**Comment by SourceCode1037** [comment]
> It's hard for me to say what went wrong solely based on the error message. Can you show me a minimal example to reproduce?

I know why, my score is used in topk(), and score is calculated by `A@k`.(A is adjacency matrix  (dimension：node_num x node_num) ，k is a mtatrix (dimension：node_num x 1))
I use `A = SparseTensor.from_edge_index(edge_index=edge_index, edge_attr=edge_attr)` , in this batch, size of `A` should be 15908x15908, but `A` is 15907x15907 when program is running. 
IMO, there must be an isolated node which is not recorded in `edge_index`, after I convert `edge_index` to `A` ,this node is missing.
How can I correct my code?

**Comment by rusty1s** [comment]
You can use
```python
A = SparseTensor.from_edge_index(edge_index, edge_attr, sparse_sizes=(N, N))
```
