### ISSUE TITLE
DataLoader seems to infer more Data objects than exist?

### ISSUE THREAD

**Issue by vymao** [pyg-team/pytorch_geometric#1931]
## 🐛 Bug

I am trying to train a model using the PyTorch Geometric Dataloader. However, I noticed that sometimes it gives me this error: 

```
100%|██████████| 2301/2301 [01:39<00:00, 23.11it/s]
100%|██████████| 203/203 [00:09<00:00, 22.01it/s]
100%|█████████▉| 203/204 [00:09<00:00, 21.07it/s]
Traceback (most recent call last):
  File "/path/to/run2.py", line 459, in <module>
    results = test_model()
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/path/to/run2.py", line 130, in test_model
    for data in tqdm(test_loader):
  File "/home/vym1/nn2/lib/python3.7/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 11.
Original Traceback (most recent call last):
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 187, in __getitem__
    data = self.get(self.indices()[idx])
  File "/path/to/DataSet.py", line 171, in get
    data = torch.load(osp.join(self.processed_dir, 'data_{}_{}.pt'.format(idx, self.split)))
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/vym1/nn2/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/social_network.line_graph/processed/data_3045_test.pt'
```
You can see from the status bars above the error that this only occurs with the test dataset (the last bar), and not the train (top) or validation (middle). The code for Data generation is the same; just a name change. 

There are 3045 test Data files that I wrote out (0 - 3044). I'm not sure why it's asking for the 3045th one. I also noticed that sometimes if I restart the run this error vanishes and doesn't appear. Is there a reason why this might be happening?

**Comment by rusty1s** [comment]
This is weird. I guess `self.len` is set to the correct value? Are you using `num_workers > 0`?

**Comment by vymao** [comment]
Yes, I am using 16

**Comment by rusty1s** [comment]
Can you test if the same error occurs in case if less workers/zero workers?

**Comment by vymao** [comment]
I will try it. Will zero workers still allow it to run? Is `num_workers` the number of additional workers?

**Comment by rusty1s** [comment]
`num_workers=0` means that data loading will happen in the main thread.

**Comment by vymao** [comment]
Seems to work better now, thanks.
