### ISSUE TITLE
error in building docker image

### ISSUE THREAD

**Issue by bsaghafi** [pyg-team/pytorch_geometric#2002]
## ❓ Questions & Help

I am trying to build docker image for pytorch geometric, but facing an error when installing torch-scatter, saying No torch is found, after installing torch!
My docker requirements file is as following:
```
torch==1.5.0
torch-scatter
torch-sparse
torch_geometric

```
The error message is as follows: 
```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0dzo7n79/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0dzo7n79/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-hzrjdah9
         cwd: /tmp/pip-install-0dzo7n79/torch-scatter/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0dzo7n79/torch-scatter/setup.py", line 6, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by rusty1s** [comment]
You need to separate `torch` installation from the extension packages (no single requirement file), since `torch` is required to install those. As far as I know, the only way to prevent this is to install `torch-scatter` and `torch-sparse` via wheels (as we recommend in your installation guide).

**Comment by bsaghafi** [comment]
Thank you for your help!
