### ISSUE TITLE
IndexError in GCN training on custom dataset

### ISSUE THREAD

**Issue by Sowmya-R-Krishnan** [pyg-team/pytorch_geometric#2073]
## 🐛 Bug

I have been training a VGAE model with an encoder defined using GCNConv layers and the Inner Product decoder. The dataset is a custom dataset and each graph has varying number of nodes. I have implemented the Dataset class and used the in-built DataLoader for preparing the mini-batches. During training, for a few graphs the model trains without any error while in the middle there is an **IndexError: index out of range in self**. Also the loss value is nan for the graphs which train without any error. I'm trying to reconstruct the adjacency matrix from the z vector obtained using the GCNConv encoder.

## To Reproduce

1. **Model code**
This is my GCN encoder and the training loop

```
class GCNEncoder(torch.nn.Module):
	def __init__(self, in_channels, out_channels):
	        super(GCNEncoder, self).__init__()
		self.conv1 = GCNConv(in_channels, out_channels, cached=True)
		self.conv_mu = GCNConv(out_channels, out_channels, cached=True)
		self.conv_logstd = GCNConv(out_channels, out_channels, cached=True)

	def forward(self, x, edge_index, edge_weight):
		x = self.conv1(x, edge_index, edge_weight)
		x = F.relu(x)
		mean = self.conv_mu(x, edge_index, edge_weight)
		logvar = self.conv_logstd(x, edge_index, edge_weight)
		return mean, logvar

def train(dataset, vae_model, optimizer, batch_size, ntrain):
	vae_model.train()

	batches = ntrain
	total_loss = 0.

	for data in dataset:
		#data.num_nodes = data.x.size(0)
		optimizer.zero_grad()
		loss = torch.zeros(1, 1).to(device, dtype=torch.float64)
		print(data.num_nodes, data.x.size(), data.edge_index.size(), data.edge_attr.size())
		z = vae_model.encode(data.x, data.edge_index, data.edge_attr)
		loss = vae_model.recon_loss(z, data.edge_index)
		loss = loss + (1 / data.num_nodes) * vae_model.kl_loss()
		loss.backward()
		optimizer.step()
		print(loss.item())
		total_loss += loss.item()

	total_loss = total_loss/len(dataset)
	return total_loss
```

2. **Stack trace** - With batch_size = 1. For each graph, the number of nodes, the size of the node feature vector, edge index vector and the edge attribute vector are shown.
```
Graphs split into train and test batches...
Dataset construction done.
Dataset construction done.
Training and test batches prepared...
Graph embedding begins now...
20 torch.Size([20, 9]) torch.Size([2, 328]) torch.Size([328])
nan
58 torch.Size([58, 9]) torch.Size([2, 2838]) torch.Size([2838])
nan
24 torch.Size([24, 9]) torch.Size([2, 508]) torch.Size([508])
nan
36 torch.Size([36, 9]) torch.Size([2, 1094]) torch.Size([1094])
nan
63 torch.Size([63, 9]) torch.Size([2, 3142]) torch.Size([3142])
nan
45 torch.Size([45, 9]) torch.Size([2, 1738]) torch.Size([1738])
nan
46 torch.Size([46, 9]) torch.Size([2, 1712]) torch.Size([1712])
nan
30 torch.Size([30, 9]) torch.Size([2, 780]) torch.Size([780])
nan
76 torch.Size([76, 9]) torch.Size([2, 4938]) torch.Size([4938])
nan
44 torch.Size([44, 9]) torch.Size([2, 1584]) torch.Size([1584])
nan
34 torch.Size([34, 9]) torch.Size([2, 950]) torch.Size([950])
nan
25 torch.Size([25, 9]) torch.Size([2, 464]) torch.Size([464])
nan
46 torch.Size([46, 9]) torch.Size([2, 1826]) torch.Size([1826])
nan
50 torch.Size([50, 9]) torch.Size([2, 2080]) torch.Size([2080])
nan
48 torch.Size([48, 9]) torch.Size([2, 2040]) torch.Size([2040])
nan
49 torch.Size([49, 9]) torch.Size([2, 1994]) torch.Size([1994])
nan
43 torch.Size([43, 9]) torch.Size([2, 1534]) torch.Size([1534])
nan
64 torch.Size([64, 9]) torch.Size([2, 3626]) torch.Size([3626])
nan
53 torch.Size([53, 9]) torch.Size([2, 2410]) torch.Size([2410])
nan
39 torch.Size([39, 9]) torch.Size([2, 1412]) torch.Size([1412])
nan
44 torch.Size([44, 9]) torch.Size([2, 1654]) torch.Size([1654])
nan
37 torch.Size([37, 9]) torch.Size([2, 1178]) torch.Size([1178])
nan
66 torch.Size([66, 9]) torch.Size([2, 3740]) torch.Size([3740])
nan
35 torch.Size([35, 9]) torch.Size([2, 1080]) torch.Size([1080])
nan
62 torch.Size([62, 9]) torch.Size([2, 3080]) torch.Size([3080])
nan
50 torch.Size([50, 9]) torch.Size([2, 2282]) torch.Size([2282])
nan
39 torch.Size([39, 9]) torch.Size([2, 1240]) torch.Size([1240])
nan
43 torch.Size([43, 9]) torch.Size([2, 1554]) torch.Size([1554])
nan
40 torch.Size([40, 9]) torch.Size([2, 1416]) torch.Size([1416])
nan
17 torch.Size([17, 9]) torch.Size([2, 226]) torch.Size([226])
Traceback (most recent call last):
  File "gcn_vae_pytorch_geometric_v1.py", line 347, in <module>
    train_loss, val_loss = trainingloop(train_batches, test_batches, model, 100, learning_rate=0.005, batch_size=batch_size, savecpt=10, ntrain=nbatches_train, nval=nbatches_val)
  File "gcn_vae_pytorch_geometric_v1.py", line 271, in trainingloop
    train_loss = train(trainset, model, optimizer, batch_size, ntrain)
  File "gcn_vae_pytorch_geometric_v1.py", line 212, in train
    z = vae_model.encode(data.x, data.edge_index, data.edge_attr)
  File "/home/sowmya/anaconda3/envs/pygeom/lib/python3.6/site-packages/torch_geometric/nn/models/autoencoder.py", line 155, in encode
    self.__mu__, self.__logstd__ = self.encoder(*args, **kwargs)
  File "/home/sowmya/anaconda3/envs/pygeom/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "gcn_vae_pytorch_geometric_v1.py", line 188, in forward
    x = self.conv1(x, edge_index, edge_weight)
  File "/home/sowmya/anaconda3/envs/pygeom/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sowmya/anaconda3/envs/pygeom/lib/python3.6/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 182, in forward
    size=None)
  File "/home/sowmya/anaconda3/envs/pygeom/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 234, in propagate
    kwargs)
  File "/home/sowmya/anaconda3/envs/pygeom/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 158, in __collect__
    j if arg[-2:] == '_j' else i)
  File "/home/sowmya/anaconda3/envs/pygeom/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 127, in __lift__
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self
```

## Expected behavior
The reconstruction loss from the VGAE should not be 'nan' and the index error should be explained more clearly. Not able to understand why the error arises for certain graphs and not the others.

## Environment

* OS: Ubuntu 18.04 LTS
* Python version: 3.6
* PyTorch version: 1.7.0
* CUDA/cuDNN version: None
* GCC version: 5.5.0
* Any other relevant information: I'm using a conda environment with the necessary libraries installed.

## Additional context
Kindly let me know if I have made any mistakes in implementing the VGAE encoder or while calculating the loss using the functions.

**Comment by Sowmya-R-Krishnan** [comment]
Update: I was looking at issue #1861 for which the suggestion was to remove **cached=True** argument from the GCNConv layer. This solved the IndexError for me too. But the loss values from the VGAE still remains 'nan' for me. Any suggestions to resolve this would be of great help to me.

**Comment by rusty1s** [comment]
It‘s best to evaluate any NaN occurencies via `torch.autograd.detect_anomaly`.

**Comment by Sowmya-R-Krishnan** [comment]
Thank you for the suggestion! I will see how the edge weights can be converted to positive values and try to train the model.
