### ISSUE TITLE
failed to import 

### ISSUE THREAD

**Issue by yangxiao2** [pyg-team/pytorch_geometric#2180]
## 📚 Installation

"import torch_geometric.transforms as T" failed,and
```
Traceback (most recent call last):
  File "/data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/site-packages/torch_sparse/__init__.py", line 14, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/site-packages/torch/_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "/data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/site-packages/torch_sparse/_version.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_ogbnarxiv.py", line 5, in <module>
    import torch_geometric.transforms as T
  File "/data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/site-packages/torch_sparse/__init__.py", line 23, in <module>
    raise OSError(e)
OSError: /data/Disk_A/yangxiao/.conda/envs/Pytorch/lib/python3.8/site-packages/torch_sparse/_version.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
```

## Environment

* OS:
* Python version:3.8
* PyTorch version:1.4.0
* CUDA/cuDNN version:10.1
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (wheel, source):download the package from https://pytorch-geometric.com/whl/torch-1.4.0+cu101.html and  installed using pip
* Any other relevant information:

## Checklist

- [y] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [y] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [y] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
This error usually indicates a version conflict between PyTorch CUDA and the CUDA version installed on your system. You should check that both match.
