### ISSUE TITLE
`T.RandomRotate((0 ,10), axis=0)` cause `RuntimeError: CUDA error: device-side assert triggered`

### ISSUE THREAD

**Issue by zhangxiann** [pyg-team/pytorch_geometric#2552]
## 🐛 Bug

I try to add data augmentation to my graph data.  While `T.RandomScale([0.95, 1])` works, `T.RandomRotate((0 ,10), axis=0)`  and `T.RandomFlip(axis=0, p=0.5)`  throws error **RuntimeError: CUDA error: device-side assert triggered**. 

```
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:381: indexAddLargeIndex: block: [101,0,0], thread: [54,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:381: indexAddLargeIndex: block: [101,0,0], thread: [55,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:381: indexAddLargeIndex: block: [101,0,0], thread: [56,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:381: indexAddLargeIndex: block: [101,0,0], thread: [57,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:381: indexAddLargeIndex: block: [101,0,0], thread: [58,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:381: indexAddLargeIndex: block: [101,0,0], thread: [59,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:381: indexAddLargeIndex: block: [101,0,0], thread: [60,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:381: indexAddLargeIndex: block: [101,0,0], thread: [61,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:381: indexAddLargeIndex: block: [101,0,0], thread: [62,0,0] Assertion `dstIndex < dstAddDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:381: indexAddLargeIndex: block: [101,0,0], thread: [63,0,0] Assertion `dstIndex < dstAddDimSize` failed.
  0%|▏                                                                                            | 65/30000 [00:01<15:03, 33.12it/s]
Traceback (most recent call last):
  File "train_2d_graph.py", line 140, in <module>
    data = data.to(device)
  File "/home/sduu/anaconda3/envs/gnn_zx/lib/python3.7/site-packages/torch_geometric/data/data.py", line 340, in to
    return self.apply(lambda x: x.to(device, **kwargs), *keys)
  File "/home/sduu/anaconda3/envs/gnn_zx/lib/python3.7/site-packages/torch_geometric/data/data.py", line 326, in apply
    self[key] = self.__apply__(item, func)
  File "/home/sduu/anaconda3/envs/gnn_zx/lib/python3.7/site-packages/torch_geometric/data/data.py", line 305, in __apply__
    return func(item)
  File "/home/sduu/anaconda3/envs/gnn_zx/lib/python3.7/site-packages/torch_geometric/data/data.py", line 340, in <lambda>
    return self.apply(lambda x: x.to(device, **kwargs), *keys)
RuntimeError: CUDA error: device-side assert triggered
```

## To Reproduce

I try to add data augmentation to my graph data.  While `T.RandomScale([0.95, 1])` works, `T.RandomRotate((0 ,10), axis=0)`  and `T.RandomFlip(axis=0, p=0.5)`  throws error **RuntimeError: CUDA error: device-side assert triggered**. 

The code and data is hosted here: [https://github.com/zhangxiann/graph_bug](https://github.com/zhangxiann/graph_bug)

To reproduce this error:
1.  `git clone https://github.com/zhangxiann/graph_bug.git`
2. `cd graph_bug`
3. `python train_2d_graph.py`

## Environment

* OS: Ubuntu
* Python version: 3.6
* PyTorch version: 1.8
* CUDA/cuDNN version: 11.1
* GCC version:
* Any other relevant information:
```
torch                 1.8.0+cu111
torch-cluster         1.5.9
torch-geometric       1.7.0
torch-scatter         2.0.6
torch-sparse          0.6.9
torch-spline-conv     1.2.1
torchaudio            0.8.0
torchsummary          1.5.1
torchvision           0.9.0+cu111
```

**Comment by zhangxiann** [comment]
And it works well in the first few epochs , then throws error in the next epoch. It is very weird.
![image](https://user-images.githubusercontent.com/12131262/117534720-3c7c7500-b025-11eb-8d4e-cbc144567f9c.png)

**Comment by rusty1s** [comment]
Sadly, your code does not run for me. It crashes with
```
RuntimeError: index 4599643497065087066 is out of bounds for dimension
```
I'm not sure what's causing this. Especially the CUDA error is weird since the transforms operate on CPU. Can you call your script with `CUDA_LAUNCH_BLOCKING=1` to identify the exact issue?

In addition, please note that you want to apply the `Cartesian()` transform *after* augmentation :)
