### ISSUE TITLE
install pytorch-geometric with LinkError: post-link script failed for package conda-forge::cudatoolkit-11.1.1-heb2d755_7

### ISSUE THREAD

**Issue by xyqbest** [pyg-team/pytorch_geometric#2834]
## Environment

* OS: win 10 19043
* Python version: python 3.95
* PyTorch version: 1.9.0
* CUDA/cuDNN version: 11.1
* GCC version: 
* \>\>\>import torch; torch.cuda.is_available()
   True
* How did you try to install PyTorch Geometric and its extensions (wheel, source):

## conda install
I try 
`conda install pytorch-geometric -c rusty1s -c conda-forge`
to install pytorch-geometric 
however, I get the error and do not solve it with google.
## here is error messages:

```
(pytorchdemo) PS C:\Users\admin> conda install pytorch-geometric -c rusty1s -c conda-forge -v
Collecting package metadata: ...working... done
Solving environment: ...working...
Warning: >10 possible package resolutions (only showing differing packages):
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::certifi-2021.5.30-py39hcbf5309_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::openssl-1.1.1k-h8ffe710_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scikit-learn-0.24.2-py39he931e04_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scipy-1.7.0-py39hc0c34ad_0
  - conda-forge::scikit-learn-0.24.2-py39he931e04_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::certifi-2021.5.30-py39hcbf5309_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::openssl-1.1.1k-h8ffe710_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scipy-1.7.0-py39hc0c34ad_0
  - conda-forge::scipy-1.7.0-py39hc0c34ad_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::certifi-2021.5.30-py39hcbf5309_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::openssl-1.1.1k-h8ffe710_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scikit-learn-0.24.2-py39he931e04_0
  - conda-forge::scikit-learn-0.24.2-py39he931e04_0, conda-forge::scipy-1.7.0-py39hc0c34ad_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::certifi-2021.5.30-py39hcbf5309_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::openssl-1.1.1k-h8ffe710_0
  - conda-forge::certifi-2021.5.30-py39hcbf5309_0, conda-forge::scipy-1.7.0-py39hc0c34ad_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::openssl-1.1.1k-h8ffe710_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scikit-learn-0.24.2-py39he931e04_0
  - conda-forge::certifi-2021.5.30-py39hcbf5309_0, conda-forge::scikit-learn-0.24.2-py39he931e04_0, conda-forge::scipy-1.7.0-py39hc0c34ad_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::openssl-1.1.1k-h8ffe710_0
  - conda-forge::certifi-2021.5.30-py39hcbf5309_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::openssl-1.1.1k-h8ffe710_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scikit-learn-0.24.2-py39he931e04_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scipy-1.7.0-py39hc0c34ad_0
  - conda-forge::certifi-2021.5.30-py39hcbf5309_0, conda-forge::scikit-learn-0.24.2-py39he931e04_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::openssl-1.1.1k-h8ffe710_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scipy-1.7.0-py39hc0c34ad_0
  - conda-forge::certifi-2021.5.30-py39hcbf5309_0, conda-forge::openssl-1.1.1k-h8ffe710_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scikit-learn-0.24.2-py39he931e04_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scipy-1.7.0-py39hc0c34ad_0
  - conda-forge::openssl-1.1.1k-h8ffe710_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::certifi-2021.5.30-py39hcbf5309_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scikit-learn-0.24.2-py39he931e04_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::scipy-1.7.0-py39hc0c34ad_0
  ... and othersdone


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.8
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda


initializing UnlinkLinkTransaction with
  target_prefix: F:\ProgramData\Anaconda3\envs\pytorchdemo
  unlink_precs:

  link_precs:
    conda-forge::mkl-include-2021.2.0-hb70f87d_389
    conda-forge::msys2-conda-epoch-20160418-1
    conda-forge::m2w64-gmp-6.1.0-2
    conda-forge::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
    conda-forge::ninja-1.10.2-h5362a0b_0
    conda-forge::cudatoolkit-11.1.1-heb2d755_7



## Package Plan ##

  environment location: F:\ProgramData\Anaconda3\envs\pytorchdemo

  added / updated specs:
    - pytorch-geometric


The following NEW packages will be INSTALLED:

  cudatoolkit        conda-forge/win-64::cudatoolkit-11.1.1-heb2d755_7
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  mkl-include        conda-forge/win-64::mkl-include-2021.2.0-hb70f87d_389
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1
  ninja              conda-forge/win-64::ninja-1.10.2-h5362a0b_0


Proceed ([y]/n)? y

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... ===> LINKING PACKAGE: conda-forge::mkl-include-2021.2.0-hb70f87d_389 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo
  source=F:\ProgramData\Anaconda3\pkgs\mkl-include-2021.2.0-hb70f87d_389


===> LINKING PACKAGE: conda-forge::msys2-conda-epoch-20160418-1 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo
  source=F:\ProgramData\Anaconda3\pkgs\msys2-conda-epoch-20160418-1


===> LINKING PACKAGE: conda-forge::m2w64-gmp-6.1.0-2 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo
  source=F:\ProgramData\Anaconda3\pkgs\m2w64-gmp-6.1.0-2


===> LINKING PACKAGE: conda-forge::m2w64-libwinpthread-git-5.0.0.4634.697f757-2 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo
  source=F:\ProgramData\Anaconda3\pkgs\m2w64-libwinpthread-git-5.0.0.4634.697f757-2


===> LINKING PACKAGE: conda-forge::ninja-1.10.2-h5362a0b_0 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo
  source=F:\ProgramData\Anaconda3\pkgs\ninja-1.10.2-h5362a0b_0


===> LINKING PACKAGE: conda-forge::cudatoolkit-11.1.1-heb2d755_7 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo
  source=F:\ProgramData\Anaconda3\pkgs\cudatoolkit-11.1.1-heb2d755_7


$ C:\WINDOWS\system32\cmd.exe /d /c F:\ProgramData\Anaconda3\envs\pytorchdemo\.tmpaahb9dg8.bat
==> cwd: F:\ProgramData\Anaconda3\envs\pytorchdemo\Scripts <==
==> exit code: 1 <==
==> stdout <==
b'\r\nF:\\ProgramData\\Anaconda3\\envs\\pytorchdemo\\Scripts>rem post install EULA message; `pre-link.bat` does not show message and shows warning \r\n\r\nF:\\ProgramData\\Anaconda3\\envs\\pytorchdemo\\Scripts>echo "By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"  1>>F:\\ProgramData\\Anaconda3\\envs\\pytorchdemo\\.messages.txt \r\n'
==> stderr <==
b'\xcf\xb5\xcd\xb3\xd5\xd2\xb2\xbb\xb5\xbd\xd6\xb8\xb6\xa8\xb5\xc4\xc2\xb7\xbe\xb6\xa1\xa3\r\n'


"By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"

An error occurred while installing package 'conda-forge::cudatoolkit-11.1.1-heb2d755_7'.
LinkError: post-link script failed for package conda-forge::cudatoolkit-11.1.1-heb2d755_7
running your command again with `-v` will provide additional information
location of failed script: F:\ProgramData\Anaconda3\envs\pytorchdemo\Scripts\.cudatoolkit-post-link.bat
==> script messages <==
"By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"


Attempting to roll back.


===> REVERSING PACKAGE LINK: conda-forge::cudatoolkit-11.1.1-heb2d755_7 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo


failed
An error occurred while installing package 'conda-forge::cudatoolkit-11.1.1-heb2d755_7'.
LinkError: post-link script failed for package conda-forge::cudatoolkit-11.1.1-heb2d755_7
running your command again with `-v` will provide additional information
location of failed script: F:\ProgramData\Anaconda3\envs\pytorchdemo\Scripts\.cudatoolkit-post-link.bat
==> script messages <==
"By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"


Attempting to roll back.


Rolling back transaction: ...working... ===> REVERSING PACKAGE LINK: conda-forge::ninja-1.10.2-h5362a0b_0 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo


===> REVERSING PACKAGE LINK: conda-forge::m2w64-libwinpthread-git-5.0.0.4634.697f757-2 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo


===> REVERSING PACKAGE LINK: conda-forge::m2w64-gmp-6.1.0-2 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo


===> REVERSING PACKAGE LINK: conda-forge::msys2-conda-epoch-20160418-1 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo


===> REVERSING PACKAGE LINK: conda-forge::mkl-include-2021.2.0-hb70f87d_389 <===
  prefix=F:\ProgramData\Anaconda3\envs\pytorchdemo


done
Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 1080, in run_script
    subprocess_call(command_args, env=env, path=dirname(path))
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\subprocess.py", line 58, in subprocess_call
    output=_format_output(command_str, cwd, rc, stdout, stderr))
subprocess.CalledProcessError: Command '['C:\\WINDOWS\\system32\\cmd.exe', '/d', '/c', 'F:\\ProgramData\\Anaconda3\\envs\\pytorchdemo\\.tmpaahb9dg8.bat']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 649, in _execute_post_link_actions
    activate=True)
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 1096, in run_script
    raise LinkError(message)
conda.exceptions.LinkError: post-link script failed for package conda-forge::cudatoolkit-11.1.1-heb2d755_7
running your command again with `-v` will provide additional information
location of failed script: F:\ProgramData\Anaconda3\envs\pytorchdemo\Scripts\.cudatoolkit-post-link.bat
==> script messages <==
"By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 558, in _execute
    cls._execute_post_link_actions(pkg_idx_tracked, axngroup)
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 664, in _execute_post_link_actions
    reverse_excs,
conda.CondaMultiError: post-link script failed for package conda-forge::cudatoolkit-11.1.1-heb2d755_7
running your command again with `-v` will provide additional information
location of failed script: F:\ProgramData\Anaconda3\envs\pytorchdemo\Scripts\.cudatoolkit-post-link.bat
==> script messages <==
"By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"




During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1002, in __call__
    return func(*args, **kwargs)
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 275, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 304, in handle_txn
    unlink_link_transaction.execute()
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 241, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "F:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 587, in _execute
    rollback_excs,
conda.CondaMultiError: post-link script failed for package conda-forge::cudatoolkit-11.1.1-heb2d755_7
running your command again with `-v` will provide additional information
location of failed script: F:\ProgramData\Anaconda3\envs\pytorchdemo\Scripts\.cudatoolkit-post-link.bat
==> script messages <==
"By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"
```

## pip install
I also try 
```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
pip install torch-geometric
```
to install pytorch-geometric 
however, I get the error and do not solve it with google.
## here is error messages:

```
(pytorchdemo) PS C:\Users\admin> pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
>> pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
>> pip install torch-geometric
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in links: https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
Requirement already satisfied: torch-scatter in f:\programdata\anaconda3\envs\pytorchdemo\lib\site-packages (2.0.7)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in links: https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
Requirement already satisfied: torch-sparse in f:\programdata\anaconda3\envs\pytorchdemo\lib\site-packages (0.6.10)
Requirement already satisfied: scipy in f:\programdata\anaconda3\envs\pytorchdemo\lib\site-packages (from torch-sparse) (1.7.0)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in f:\programdata\anaconda3\envs\pytorchdemo\lib\site-packages (from scipy->torch-sparse) (1.21.0)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torch-geometric in f:\programdata\anaconda3\envs\pytorchdemo\lib\site-packages (1.7.2)
Requirement already satisfied: pandas in f:\programdata\anaconda3\envs\pytorchdemo\lib\site-packages (from torch-geometric) (1.3.0)
Requirement already satisfied: numpy in f:\programdata\anaconda3\envs\pytorchdemo\lib\site-packages (from torch-geometric) (1.21.0)
Requirement already satisfied: scikit-learn in f:\programdata\anaconda3\envs\pytorchdemo\lib\site-packages (from torch-geometric) (0.24.2)
Requirement already satisfied: python-louvain in f:\programdata\anaconda3\envs\pytorchdemo\lib\site-packages (from torch-geometric) (0.15)
Requirement already satisfied: scipy in f:\programdata\anaconda3\envs\pytorchdemo\lib\site-packages (from torch-geometric) (1.7.0)
ERROR: Exception:
Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\commands\install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 367, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 203, in _get_criteria_to_update
    name, crit = self._merge_into_criterion(r, parent=candidate)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 30, in _iter_built
    for version, func in infos:
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 269, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\index\package_finder.py", line 879, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\index\package_finder.py", line 824, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\index\package_finder.py", line 783, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\index\collector.py", line 512, in fetch_page
    return _get_html_page(location, session=self.session)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\index\collector.py", line 422, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\index\collector.py", line 120, in _get_html_response
    resp = session.get(
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_internal\network\session.py", line 449, in request
    return super().request(method, url, *args, **kwargs)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "F:\ProgramData\Anaconda3\envs\pytorchdemo\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
```

## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [x] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
For your `conda` related error, it is required that PyTorch and the `cudatoolkit` is already installed:
```
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
```
before running
```
conda install pytorch-geometric -c rusty1s -c conda-forge
```

For your `pip` installation issue, this looks like a proxy issue to me. Do you can install other packages via `pip`?

**Comment by xyqbest** [comment]
Thanks for you comments. I follow your suggestions but do not fix it. There are same `LinkError` when run  
`conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia`
For your `pip` installation issue, I solve the proxy issue and get same `LinkError` in `conda` installation issue.

**Comment by rusty1s** [comment]
If the
```
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
```
command does not work for you, then I guess this is a problem with your conda installation rather than a problem within PyG. I'm not entirely sure what's causing this, but you should probably start with updating your conda installation first:
```
conda update -n base -c defaults conda
```

**Comment by xyqbest** [comment]
The command `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia` does not work. 
I agree with you that this is a problem with conda installation. 

Specifically， I cannot install `cudatoolkit=11.1` and the `LinkError` is from installing `conda install cudatoolkit=11.1`.

However, PyG works, if I install `pytorch` with `cudatoolkit=10.2` rather than `cudatoolkit=11.1`.

**Comment by xyqbest** [comment]
finally, I install the pytorch with cuda 10.2 and pip install
