### ISSUE TITLE
Sample code on chapter "Heterogeneous Graph Learning" does not work

### ISSUE THREAD

**Issue by tetsu9923** [pyg-team/pytorch_geometric#3131]
Hi, I am trying to run the sample code on chapter "Heterogeneous Graph Learning" [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/heterogeneous.html?highlight=bipartite#automatically-converting-gnn-models).
But it does not work due to the following error.

```
import torch
from torch_geometric.nn import SAGEConv, to_hetero
from torch_geometric.datasets import OGB_MAG

dataset = OGB_MAG(root='./data', preprocess='metapath2vec')
data = dataset[0]
print(data)

class GNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = SAGEConv((-1, -1), hidden_channels)
        self.conv2 = SAGEConv((-1, -1), out_channels)

    def forward(self, x, edge_index):
        print(x)
        print(edge_index)
        x = self.conv1(x, edge_index).relu()
        x = self.conv2(x, edge_index)
        return x

model = GNN(hidden_channels=64, out_channels=dataset.num_classes)
model = to_hetero(model, data.metadata(), aggr='sum')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
data = data.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

def train():
    model.train()
    optimizer.zero_grad()
    out = model(data.x_dict, data.edge_index_dict)
    mask = data['paper'].train_mask
    loss = F.cross_entropy(out[mask], data['paper'].y[mask])
    loss.backward()
    optimizer.step()
    return float(loss)
  
train()
```

```
HeteroData(
  paper={
    x=[736389, 128],
    y=[736389],
    train_mask=[736389],
    val_mask=[736389],
    test_mask=[736389]
  },
  author={ x=[1134649, 128] },
  institution={ x=[8740, 128] },
  field_of_study={ x=[59965, 128] },
  (author, affiliated_with, institution)={ edge_index=[2, 1043998] },
  (author, writes, paper)={ edge_index=[2, 7145660] },
  (paper, cites, paper)={ edge_index=[2, 5416271] },
  (paper, has_topic, field_of_study)={ edge_index=[2, 7505078] }
)
Proxy(x)
Proxy(edge_index)
Traceback (most recent call last):
  File "/opt/layers/datascience/site-packages/torch/fx/graph_module.py", line 505, in wrapped_call
    return cls_call(self, *args, **kwargs)
  File "/opt/layers/datascience/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key_3>", line 17, in forward
    relu__author = None.relu()
AttributeError: 'NoneType' object has no attribute 'relu'

Call using an FX-traced Module, line 17 of the traced Module's generated forward function:
    relu__paper = conv1__paper.relu();  conv1__paper = None
    relu__author = None.relu()

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    relu__institution = conv1__institution.relu();  conv1__institution = None

    relu__field_of_study = conv1__field_of_study.relu();  conv1__field_of_study = None

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_15174/2980630347.py in <module>
     38     return float(loss)
     39 
---> 40 train()

/tmp/ipykernel_15174/2980630347.py in train()
     31     model.train()
     32     optimizer.zero_grad()
---> 33     out = model(data.x_dict, data.edge_index_dict)
     34     mask = data['paper'].train_mask
     35     loss = F.cross_entropy(out[mask], data['paper'].y[mask])

/opt/layers/datascience/site-packages/torch/fx/graph_module.py in wrapped_call(self, *args, **kwargs)
    511                     print(generate_error_message(topmost_framesummary),
    512                           file=sys.stderr)
--> 513                 raise e.with_traceback(None)
    514 
    515         cls.__call__ = wrapped_call

AttributeError: 'NoneType' object has no attribute 'relu'
```

How can I deal with this error?
I installed PyG from master via pip install git+https://github.com/rusty1s/pytorch_geometric.git.
Thank you.

**Comment by qoffee** [comment]
+
I have the same problem.

**Comment by rusty1s** [comment]
Oh, I'm really sorry. The reason that fails is due to `OGB_MAG` only having unidirectional edges. For example, there is no edge type that updates authors, leading to its feature representation becoming `None`. This is easily fixable by adding reverse edges to the heterogeneous graph:
```python
dataset = OGB_MAG(root='/tmp/OGB', preprocess='metapath2vec', transform=T.ToUndirected())
```

**Comment by tetsu9923** [comment]
Thank you for your quick reply!
The sample code ran successfully by adding reverse edges as you taught and by modifying the code from
`loss = F.cross_entropy(out[mask], data['paper'].y[mask])`
to
`loss = F.cross_entropy(out['paper'][mask], data['paper'].y[mask])`.

**Comment by rusty1s** [comment]
Thanks for spotting the typo. This is now fixed.
