### ISSUE TITLE
InMemoryDataset error with code that used to work with older PyG version

### ISSUE THREAD

**Issue by Olimoyo** [pyg-team/pytorch_geometric#3144]
## ❓ Questions & Help

Hi,

I have an InMemoryDataset:
```
class CachedDataset(InMemoryDataset):
    def __init__(self, data_list):
        super(CachedDataset, self).__init__(None)
        self.data, self.slices = self.collate(data_list)
```

That takes a list of data objects defined as:
```
class TripletData(Data):
    def __init__(
        self,
        type=None,
        pos_partial=None,
        pos_full=None,
        pos_init=None,
        edge_index_partial=None,
        edge_index_full=None,
        edge_attr_partial=None,
        edge_attr_full=None,
        edge_attr_init=None,
        anchor_partial=None,
        anchor_full=None,
        lower_bounds=None,
        upper_bounds=None,
    ):
        super(TripletData, self).__init__()
        self.pos_partial = pos_partial
        self.anchor_partial = anchor_partial
        self.edge_index_partial = edge_index_partial
        self.edge_attr_partial = edge_attr_partial
        self.pos_full = pos_full
        self.anchor_full = anchor_full
        self.edge_index_full = edge_index_full
        self.edge_attr_full = edge_attr_full
        self.pos_init = pos_init
        self.edge_attr_init = edge_attr_init
        self.type = type
        self.lower_bounds = lower_bounds
        self.upper_bounds = upper_bounds

    def __inc__(self, key, value):
        if key == "edge_index_partial":
            return self.pos_partial.size(0)
        if key == "edge_index_full":
            return self.pos_full.size(0)
        else:
            return super().__inc__(key, value)
```

When I go use the loader (i.e., `for idx, data in enumerate(loader):`) I get the following error:

```
raceback (most recent call last):
  File "/home/olimoyo/generative-graphik/saved_models/baseline_model/train.py", line 294, in <module>
    train(args)
  File "/home/olimoyo/generative-graphik/saved_models/baseline_model/train.py", line 234, in train
    summary_train = opt_epoch(
  File "/home/olimoyo/generative-graphik/saved_models/baseline_model/train.py", line 55, in opt_epoch
    for idx, data in enumerate(loader):
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch_geometric/loader/dataloader.py", line 39, in __call__
    return self.collate(batch)
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch_geometric/loader/dataloader.py", line 19, in collate
    return Batch.from_data_list(batch, self.follow_batch,
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 45, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 76, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 142, in _collate
    incs = get_incs(key, values, data_list, stores)
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 187, in get_incs
    repeats = [
  File "/home/olimoyo/miniconda3/envs/gik/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 188, in <listcomp>
    data.__inc__(key, value, store)
TypeError: __inc__() takes 3 positional arguments but 4 were given
```

I am pretty sure that this code used to run fine on an older version of PyG and that this error only showed up recently once I updated to the latest PyG. I was wondering if I was doing anything wrong or if it was a bug?

Thanks!

**Comment by wsad1** [comment]
A quick fix you be to modify the overridden `__inc__` function to 
``` def __inc__(self, key, value, *args)```.

**Comment by rusty1s** [comment]
Yes, that is mentioned in the breaking changes of PyG 2.0, see [here](https://github.com/pyg-team/pytorch_geometric/releases/tag/2.0.0).

**Comment by Olimoyo** [comment]
Thank you! I didn't catch that
