### ISSUE TITLE
An error in obtaining the mini-batch of the dataset

### ISSUE THREAD

**Issue by XinEDprob** [pyg-team/pytorch_geometric#3156]
## 🐛 Bug

I'm using the latest pyg and trying to build a bipartite batch for training.
The code is listed as follows:

```
import torch
from torch_geometric.data import Data, DataLoader

class BipartiteData(Data):
    def __init__(self, edge_index, x_src, x_dst):
        super(BipartiteData, self).__init__()
        self.edge_index = edge_index
        self.x_src = x_src
        self.x_dst = x_dst
        
    def __inc__(self, key, value):
        if key == 'edge_index':
            return torch.tensor([[self.x_src.size(0)], [self.x_dst.size(0)]])
        else:
            return super(BipartiteData, self).__inc__(key, value)


x_src = torch.randn(100, 32)
x_dst = torch.randn(50, 32)
row = torch.randint(0, x_src.size(0), (200, ), dtype=torch.long)
col = torch.randint(0, x_dst.size(0), (200, ), dtype=torch.long)
edge_index = torch.stack([row, col], dim=0)

data = BipartiteData(x_src=x_src, x_dst=x_dst, edge_index=edge_index)

loader = DataLoader([data] * 8, batch_size=4, follow_batch=['x_src', 'x_dst'])
for batch in loader:
    print(batch)
```

The error message:

```
Traceback (most recent call last):
  File "/data/.miniconda3/envs/orml/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/data/.miniconda3/envs/orml/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/data/.miniconda3/envs/orml/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/data/.miniconda3/envs/orml/lib/python3.9/site-packages/torch_geometric/loader/dataloader.py", line 39, in __call__
    return self.collate(batch)
  File "/data/.miniconda3/envs/orml/lib/python3.9/site-packages/torch_geometric/loader/dataloader.py", line 19, in collate
    return Batch.from_data_list(batch, self.follow_batch,
  File "/data/.miniconda3/envs/orml/lib/python3.9/site-packages/torch_geometric/data/batch.py", line 63, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/data/.miniconda3/envs/orml/lib/python3.9/site-packages/torch_geometric/data/collate.py", line 76, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/data/.miniconda3/envs/orml/lib/python3.9/site-packages/torch_geometric/data/collate.py", line 142, in _collate
    incs = get_incs(key, values, data_list, stores)
  File "/data/.miniconda3/envs/orml/lib/python3.9/site-packages/torch_geometric/data/collate.py", line 187, in get_incs
    repeats = [
  File "/data/.miniconda3/envs/orml/lib/python3.9/site-packages/torch_geometric/data/collate.py", line 188, in <listcomp>
    data.__inc__(key, value, store)
TypeError: __inc__() takes 3 positional arguments but 4 were given
```

I traced back to the place where the error happens.  It seems [this line](https://github.com/pyg-team/pytorch_geometric/blame/356496483f7b5d117b20c6d320c197634f899da9/torch_geometric/data/collate.py#L188)
should be 
`data.__inc__(key, value, data, store)`

**Comment by rusty1s** [comment]
Replacing
```python
def __inc__(self, key, value):
```
with
```python
def __inc__(self, key, value, *args):
```
should fix this error.

This is one of the very few breaking changes in our PyG 2.0 release, see [here](https://github.com/pyg-team/pytorch_geometric/releases/tag/2.0.0). I'm sorry for the inconveniences!

**Comment by XinEDprob** [comment]
Thanks for the prompt response! It makes sense.
