### ISSUE TITLE
TypeError: can't pickle generator objects

### ISSUE THREAD

**Issue by lxy444** [pyg-team/pytorch_geometric#3210]
Hi, I upgraded the package `torch-geometric` from 1.7.2 to the latest 2.0.1, then the previous worked code now returns an error when fetch data from `train_dataloader`, the error is:
```
Start training.
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.6.8/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/data/miniconda3/envs/env-3.6.8/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle generator objects
```

It did not give more specific information. When I downgrade the `torch-geometric` to 1.7.2, the code run normally. So what is the reason?

**Comment by rusty1s** [comment]
Can you show me a minimal example to reproduce?

**Comment by lxy444** [comment]
> Can you show me a minimal example to reproduce?

Thanks for your reply! I will try to make an example.
