### ISSUE TITLE
Adding additional attributes to ```torch_geometric.data.Dataset``` object

### ISSUE THREAD

**Issue by Ipsit1234** [pyg-team/pytorch_geometric#3246]
## ❓ Questions & Help

I am trying to make a custom dataset class to load my data from raw files and store them as tensors. I am using a custom dataset. I followed the procedure mentioned [here(CREATING YOUR OWN DATASETS)](https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html). I want to add an additional attribute to the class that I am creating. Here is an example:
```py
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch_geometric as pyg
import torch_scatter
import numpy as np
import networkx as nx
import snap
import os

class BarabassiDataSet(pyg.data.Dataset):
    def __init__(self, root, dim, transform=None, pre_transform=None):
        super(BarabassiDataSet, self).__init__(root, transform)
        self.dim = dim
        
    @property
    def raw_file_names(self):
        raw_filenames = []
        for i in os.listdir(self.root + f"/raw/barabassi"):
            raw_filenames.append(f"barabassi/" + i)
        return raw_filenames
    
    @property
    def processed_file_names(self):
        processed_filenames = []
        for i in os.listdir(self.root + f"/raw/barabassi"):
            processed_filenames.append(f"barabassi_data_{self.dim}_" + i.rstrip(".gml") + ".pt")
#             print(processed_filenames[-1])
        return processed_filenames
    
    def process(self):
        for idx, raw_path in enumerate(self.raw_paths):
#             print(raw_path)
            G = nx.read_gml(raw_path, destringizer=int)
            x = torch.rand((G.number_of_nodes(), self.dim), dtype=torch.float) # initializing the node embeddings
            adj = nx.to_scipy_sparse_matrix(G).tocoo() # adjacency matrix
            row = torch.from_numpy(adj.row.astype(np.int64)).to(torch.long)
            col = torch.from_numpy(adj.col.astype(np.int64)).to(torch.long)
            edge_index = torch.stack([row, col], dim=0) # edge index
            edge_index = pyg.utils.remove_self_loop(edge_index)
            s = torch.rand((G.number_of_nodes(), G.number_of_nodes(), self.dim)) 
            try:
                data = pyg.data.Data(x=x, edge_index=edge_index, s=s)
                torch.save(data, os.path.join(self.processed_dir, self.processed_file_names[idx]))
            except Exception as e:
                l = self.processed_file_names[idx]
                self.processed_file_names.remove(l)
                print(l)
    
    def len(self):
        return len(self.raw_paths)
    
    def get(self, idx):
        data = torch.load(os.path.join(self.processed_dir, self.processed_file_names[idx]))
        return data

def load_barabassi(args):
    return BarabassiDataSet(root="./Data", dim=12)

### calling this in a different file
x = load_barabassi(args)
```
On doing this, I am getting the following error:
```
Traceback (most recent call last):
  File "prepare_data.py", line 27, in <module>
    x = load_barabassi(args)
  File "D:\Autumn 2021\BTP\Codes\load_graphs.py", line 60, in load_barabassi
    return BarabassiDataSet(root="./Data", dim=12)
  File "D:\Autumn 2021\BTP\Codes\load_graphs.py", line 14, in __init__
    super(BarabassiDataSet, self).__init__(root, dim, transform)
  File "C:\Users\mmkip\anaconda3\envs\btp\lib\site-packages\torch_geometric\data\dataset.py", line 88, in __init__
    self._process()
  File "C:\Users\mmkip\anaconda3\envs\btp\lib\site-packages\torch_geometric\data\dataset.py", line 165, in _process
    if files_exist(self.processed_paths):  # pragma: no cover
  File "C:\Users\mmkip\anaconda3\envs\btp\lib\site-packages\torch_geometric\data\dataset.py", line 138, in processed_paths
    files = to_list(self.processed_file_names)
  File "D:\Autumn 2021\BTP\Codes\load_graphs.py", line 28, in processed_file_names
    processed_filenames.append(f"barabassi_data_{self.dim}_" + i.rstrip(".gml") + ".pt")
AttributeError: 'BarabassiDataSet' object has no attribute 'dim'
```
How to resolve this error?

**Comment by wsad1** [comment]
The `processed_file_names` is one function that gets called when `super(BarabassiDataSet, self).__init__(root, transform)` is run, by which time `self.dim` hasn't been created. Could you trying moving `self.dim=dim` above the `super(BarabassiDataSet, self).__init__(root, transform)` call.

**Comment by Ipsit1234** [comment]
Thanks for this suggestion. It worked.
