### ISSUE TITLE
data.Data does not support None attributes

### ISSUE THREAD

**Issue by mariolinovIC** [pyg-team/pytorch_geometric#3271]
Hi, 

I am working on a package that uses PyTorch Geometric. I updated today to use the master version on github and this cause an error in my code.

I have class Graph which inherits from data.Data and initialises some attributes to None. When I try to access this None attributes I get an error: `AttributeError: 'GlobalStorage' object has no attribute 'glob'`

This is the example I am talking about:

```
from torch_geometric.data import Data

class Graph(Data):
        def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.glob = None

g = Graph()
print(g.glob)
```

Many thanks for your help

**Comment by rusty1s** [comment]
Thanks for reporting. This is currently indeed intented, as we remove attributes in case they are set to `None`. Do you think this needs fixing? What's the use-case of accessing `None`-type attributes? A simple fix is to use the `get` method (https://www.programiz.com/python-programming/methods/dictionary/get):
```python
glob = data.get('glob')  # glob is set to `data.glob` or `None` in case the key does not exist.
```

**Comment by mariolinovIC** [comment]
Thank you very much Matthias. I do not think it needs fixing, I can use `get` as you suggested.
However, the  `get` method does not work for batches. If I create a batch using loader.DataLoader and the class Graph I defined in my previous comment, I get the following error when trying `glob = data.get('glob')` :


`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mal1218/bin/miniconda3/envs/deepx2mpi/lib/python3.9/site-packages/torch_geometric-2.0.1-py3.9.egg/torch_geometric/data/batch.py", line 96, in get
    data = separate(
  File "/home/mal1218/bin/miniconda3/envs/deepx2mpi/lib/python3.9/site-packages/torch_geometric-2.0.1-py3.9.egg/torch_geometric/data/separate.py", line 40, in separate
    data_store[attr] = _separate(attr, batch_store[attr], idx, slices,
  File "/home/mal1218/bin/miniconda3/envs/deepx2mpi/lib/python3.9/site-packages/torch_geometric-2.0.1-py3.9.egg/torch_geometric/data/separate.py", line 85, in _separate
    start, end = slices[idx], slices[idx + 1]
IndexError: too many indices for tensor of dimension 1`

Any suggestion? I can use a combination of `hasattr` and `getattr` to deal with this, but, probably having the same behaviour with  graphs and batches of graph is more convenient.

**Comment by rusty1s** [comment]
Oh, you are right. This is now fixed in master.
