### ISSUE TITLE
Batch.from_data_list() error on dataset slices

### ISSUE THREAD

**Issue by dtortorella** [pyg-team/pytorch_geometric#3332]
## 🐛 Bug in `Batch.from_data_list`

`Batch.from_data_list()` fails on _dataset slices_ in latest pytorch_geometric version (2.0.1), while it worked at least up to version `1.7.2`.

## To Reproduce

```python
from torch_geometric.data import Batch
from torch_geometric.datasets import TUDataset

dataset = TUDataset(root='/tmp', name='ENZYMES')
batch = Batch.from_data_list(dataset[:100])
```

## Expected behavior

The code above produces the following error message for torch_geometric v2.0.1
```
Traceback (most recent call last):
  File "/home/domenico/.anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 48, in __getattr__
    return self[key]
  File "/home/domenico/.anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 68, in __getitem__
    return self._mapping[key]
KeyError: 'num_nodes'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/domenico/.anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 63, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/home/domenico/.anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 96, in collate
    and stores[0].num_nodes is not None):
  File "/home/domenico/.anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 50, in __getattr__
    raise AttributeError(
AttributeError: 'GlobalStorage' object has no attribute 'num_nodes'
```

At the best of my knowledge, at least up to v1.7.2 this should have produced a batch object such as `Batch(edge_index=[2, 11954], x=[3118, 3], y=[100], batch=[3118])`.

## Environment

* OS: Linux 5.14.10-200.fc34.x86_64 SMP x86_64 x86_64 x86_64 GNU/Linux (Fedora 34)
* Python version: 3.8.11
* PyTorch version: 2.0.1 [installed via `conda install pyg -c pyg -c conda-forge`]
* CUDA/cuDNN version: N/A (cpu)
* GCC version: 11.2.1
* Any other relevant information: ---

## Additional context

Transforming a dataset slice into a list produces the normal expected behaviour 
```python
>>> Batch.from_data_list(list(iter(dataset[:100])))

Batch(edge_index=[2, 11954], x=[3118, 3], y=[100], batch=[3118], ptr=[101])
```
However, this trick is potentially wasteful for lager datasets, since it requires the explicit creation of a list.

**Comment by rusty1s** [comment]
Thanks for reporting. This is now fixed in master, see https://github.com/pyg-team/pytorch_geometric/commit/d514751c300227231b607479384a1d7f351cdf9d. The only way to fix this was to materialize `data_list`. Not that this is not wasteful as we need access to individual data objects anyway, and the data objects created from a dataset will share their memory storage.

**Comment by guojy18** [comment]
File "d:\software\anaconda\Anaconda3_2020\envs\ddpgstarlink\lib\site-packages\torch_geometric\data\batch.py", line 97, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "d:\software\anaconda\Anaconda3_2020\envs\ddpgstarlink\lib\site-packages\torch_geometric\data\collate.py", line 61, in collate
    out.stores_as(data_list[0])  # type: ignore
AttributeError: 'listBatch' object has no attribute 'stores_as'
pytorch 2.2.0, python3.8
