### ISSUE TITLE
AttributeError when importing torch_geometric using ipython in spyder

### ISSUE THREAD

**Issue by jajupmochi** [pyg-team/pytorch_geometric#3422]
## 🐛 Bug

Hi, I am using the `torch_geometric` library with `IPython` command line in `Spyder`.  When I do 
```
import torch_geometric
```
It returns an error:
```
Traceback (most recent call last):

  File "/media/ljia/DATA/research-repo/courses/Pytorch geometric tutorial/tutorial 1/tutorial1.py", line 10, in <module>
    import torch_geometric

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/data/data.py", line 14, in <module>
    from torch_geometric.data.storage import (BaseStorage, NodeStorage,

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 15, in <module>
    from torch_geometric.utils import is_undirected

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/utils/__init__.py", line 2, in <module>
    from .softmax import softmax

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/utils/softmax.py", line 11, in <module>
    def softmax(src: Tensor, index: Optional[Tensor] = None,

  File "/home/ljia/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 1310, in script
    fn = torch._C._jit_script_compile(

  File "/home/ljia/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 1374, in _get_overloads
    _compile_function_with_overload(overload_fn, qual_name, obj)

  File "/home/ljia/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 1338, in _compile_function_with_overload
    overload_signature = torch.jit.annotations.get_signature(

  File "/home/ljia/.local/lib/python3.8/site-packages/torch/jit/annotations.py", line 85, in get_signature
    signature = parse_type_line(type_line, rcb, loc)

  File "/home/ljia/.local/lib/python3.8/site-packages/torch/jit/annotations.py", line 150, in parse_type_line
    arg_ann = eval(arg_ann_str, {}, EvalEnv(rcb))  # type: ignore[arg-type] # noqa: P204

  File "<string>", line 1, in <module>

  File "/usr/local/lib/python3.8/bdb.py", line 90, in trace_dispatch
    return self.dispatch_call(frame, arg)

  File "/usr/local/lib/python3.8/bdb.py", line 128, in dispatch_call
    if not (self.stop_here(frame) or self.break_anywhere(frame)):

  File "/usr/local/lib/python3.8/site-packages/spyder_kernels/customize/spyderpdb.py", line 258, in stop_here
    and frame.f_locals.get(

AttributeError: 'EvalEnv' object has no attribute 'get'
```

This error does not appear when I run the script from a console.

The versions of the libraries used:
```
python==3.8.5
spyder==5.1.5
ipython==7.29.0
torch==1.10.0+cu113
torch_geometric==2.0.2
```
The OS is Ubuntu 18.04.6 LTS X64.

May I ask the cause of this problem? Thanks a lot!

**Comment by rusty1s** [comment]
It seems that `Spyder` has problems with `@torch.jit.script` annotations. Can you check whether the following method definition produces an error for you?
```python
from typing import Optional

import torch
from torch import Tensor

@torch.jit.script
def softmax(src: Tensor, index: Optional[Tensor] = None,
            ptr: Optional[Tensor] = None, num_nodes: Optional[int] = None,
            dim: int = 0) -> Tensor:
    return src
```

**Comment by jajupmochi** [comment]
Hi @rusty1s, I tried your code, it works. Then I tried
```
import torch_geometric
```
And it works too!

I don't know what happened, as I did not change anything. Thank you anyway for your time, and I will let you know if the bug happens again.

**Comment by rusty1s** [comment]
Super! Closing this for now. Feel free to re-open once you encounter the issue again.
