### ISSUE TITLE
`OSError: [WinError 127] The specified procedure could not be found` when importing torch_geometric

### ISSUE THREAD

**Issue by j-geuter** [pyg-team/pytorch_geometric#3430]
## 🐛 Bug

I could install torch-geometric via `pip install torch-geometric` without errors in my venv. Now when I run `import torch_geometric` a window pops up saying "The procedure entry point could not be located in the dynamic link library `...\env\Lib\site-packages\torch_sparse\_version_cpu.pyd`." The complete error message in the terminal reads:
```
(env) C:\Users\jonat\Documents\Studium\Masterarbeit>py
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jonat\Documents\Studium\Masterarbeit\env\lib\site-packages\torch_geometric\__init__.py", line 7, in <module>
    import torch_geometric.data
  File "C:\Users\jonat\Documents\Studium\Masterarbeit\env\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\Users\jonat\Documents\Studium\Masterarbeit\env\lib\site-packages\torch_geometric\data\data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "C:\Users\jonat\Documents\Studium\Masterarbeit\env\lib\site-packages\torch_geometric\typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "C:\Users\jonat\Documents\Studium\Masterarbeit\env\lib\site-packages\torch_sparse\__init__.py", line 15, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "C:\Users\jonat\Documents\Studium\Masterarbeit\env\lib\site-packages\torch\_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found
```
So I also tried it outside the venv and got another error in the terminal (without a window popping up):
```
C:\Users\jonat\Documents\Studium\Masterarbeit>py
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\site-packages\torch_geometric\__init__.py", line 7, in <module>
    import torch_geometric.data
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\site-packages\torch_geometric\data\data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\site-packages\torch_geometric\typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\site-packages\torch_sparse\__init__.py", line 15, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
```
I already read here https://github.com/pyg-team/pytorch_geometric/issues/2304 that `*.so` files in `...\torch_sparse` might play a role; there are none in that folder. In most problems I could find about similar bugs, CUDA seems to have been the problem; however, I don't even use CUDA. Does anyone know what could cause the problem and how I could go about fixing it?

## Environment

* OS: Windows 10
* Python version: 3.9.0
* PyTorch version: 1.7.1+cu110
* CUDA/cuDNN version: no CUDA

**Comment by rusty1s** [comment]
Can you give some details about how you tried to install the external packages (`torch-scatter`, `torch-sparse`, ...). Keep in mind that [for older PyTorch versions, you may have to specify the version as well](https://data.pyg.org/whl/torch-1.7.1%2Bcu110.html):
```
pip install torch-scatter==2.0.7 torch-sparse==0.6.9 torch-cluster==1.5.9 torch-spline-conv==1.2.1 -f https://data.pyg.org/whl/torch-1.7.1+Bcu110.html
```

**Comment by j-geuter** [comment]
I installed them exactly like it said on the [PyG webiste](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html), i.e. via
```
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.9.0+cpu.html
```
I just realized that inside the venv I was running `torch 1.10` while outside `1.7.1+cu110` so now I updated everything and my versions are:
```
torch: 1.10.0
torch-cluster: 1.5.9
torch-geometric: 2.0.2
torch-scatter: 2.0.9
torch-sparse: 0.6.12
torch-spline-conv: 1.2.1
torchaudio: 0.10.0
torchvision: 0.11.1
```
With `torch 1.10`, also outside the venv I am getting the same error now as inside the venv (looks like the difference in errors was caused by the difference in PyTorch versions), i.e. the window popping up and `OSError: [WinError 127] The specified procedure could not be found`. So could that be a problem with the versions?

**Comment by rusty1s** [comment]
Do the `*.so` files now exist in the respective `site-package` directories? Other-wise, please feel free to send me the installation logs.

**Comment by j-geuter** [comment]
No there's no `.so` files in any of them. I've attached the log files of `torch` (`torch_logfile.txt`) and of all of `pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.9.0+cpu.html
` (`pyg_logfile.txt`). (I'm not super familiar with pip but I think it doesn't create logs by default? So I created another venv and installed all packages again so I can create log files there, it still comes with the same error.)
[pyg_logfile.txt](https://github.com/pyg-team/pytorch_geometric/files/7486031/pyg_logfile.txt)
[torch_logfile.txt](https://github.com/pyg-team/pytorch_geometric/files/7486032/torch_logfile.txt)
.

**Comment by rusty1s** [comment]
Thank you! Can you try to run
```bash
pip install --verbose --no-index torch-scatter==2.0.7 -f https://data.pyg.org/whl/torch-1.7.1+Bcu110.html
```
as well, and report back the log?

**Comment by j-geuter** [comment]
I am just getting this error:
```
(env2) C:\Users\jonat\Documents\Studium\Masterarbeit>pip install --verbose --no-index torch-scatter==2.0.7 -f https://data.pyg.org/whl/torch-1.7.1+Bcu110.html
Using pip 21.3.1 from c:\users\jonat\documents\studium\masterarbeit\env2\lib\site-packages\pip (python 3.9)
Looking in links: https://data.pyg.org/whl/torch-1.7.1+Bcu110.html
ERROR: Could not find a version that satisfies the requirement torch-scatter==2.0.7 (from versions: none)
ERROR: No matching distribution found for torch-scatter==2.0.7
```

**Comment by rusty1s** [comment]
Fixed the link, sorry :)
```
pip install --verbose --no-index torch-scatter==2.0.7 -f https://data.pyg.org/whl/torch-1.7.1+cu110.html
```

**Comment by rusty1s** [comment]
Ah, I see. For PyTorch 1.7.1, we only provide wheels up to Python 3.8. Python 3.9 support is only available for PyTorch 1.8 and onwards.

**Comment by j-geuter** [comment]
Oh yes I am just noticing that these are the links for 1.7.1, like I said above I have upgraded to 1.10.0 already. What would be the correct link then?

**Comment by rusty1s** [comment]
Depends with which CUDA version you have installed PyTorch (`torch.version.cuda`):
```
pip install --verbose --no-index torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
```

**Comment by j-geuter** [comment]
Oh I see these are the CUDA links. I'm not using any CUDA (unfortunately my GPU is not compatible). I tried running `pip install --verbose --no-index torch-scatter==2.0.7 -f https://data.pyg.org/whl/torch-1.9.1%2Bcpu.html` now (hope that was the correct link). However, all output in the console is
```
(env2) C:\Users\jonat\Documents\Studium\Masterarbeit>pip install --verbose --no-index torch-scatter==2.0.7 -f https://data.pyg.org/whl/torch-1.9.1%2Bcpu.html
Using pip 21.3.1 from c:\users\jonat\documents\studium\masterarbeit\env2\lib\site-packages\pip (python 3.9)
Looking in links: https://data.pyg.org/whl/torch-1.9.1%2Bcpu.html
Collecting torch-scatter==2.0.7
  Downloading https://data.pyg.org/whl/torch-1.9.0%2Bcpu/torch_scatter-2.0.7-cp39-cp39-win_amd64.whl (304 kB)
     |████████████████████████████████| 304 kB 312 kB/s
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.0.7
```
Shouldn't `verbose` write in the console? Or is the output in some file somewhere?

**Comment by rusty1s** [comment]
That looks good. Does `import torch_scatter` still yield an error?

**Comment by j-geuter** [comment]
Yes, still looking the same:
```
(env2) C:\Users\jonat\Documents\Studium\Masterarbeit>py
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jonat\Documents\Studium\Masterarbeit\env2\lib\site-packages\torch_scatter\__init__.py", line 13, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "C:\Users\jonat\Documents\Studium\Masterarbeit\env2\lib\site-packages\torch\_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found
```
with a window popping up before the error message appears, which again says "The procedure entry point could not be located in the dynamic link library `...\env\Lib\site-packages\torch_scatter\_version_cpu.pyd`." Do you have any other ideas how this could be solved? If not, I've been thinking about just implementing some GNNs from scratch now, so you don't have to spend any more time on this if you don't feel like we can easily solve it.

**Comment by rusty1s** [comment]
Just googled a bit. Another reason might be that there is still a version mismatch between PyTorch and the PyTorch version `torch-scatter` was compiled with. How did you install PyTorch in the first-place? It is recommended to install PyTorch as outlined on their "get started" page. Other PyTorch versions, e.g, coming from `conda-forge` may result in this error.

**Comment by bharathwajan** [comment]
@Maria-UET  Hey that actually works for me, thank you so much

**Comment by DominikRoB** [comment]
Had the same error.
Managed to fix it by installing PyTorch 1.12.0, instead of installing the latest version that comes from the Installation page from pytorch, 1.13.0.

On the Installation-Page it says "Ensure that at least PyTorch 1.11.0 is installed:";  Maybe that can be clarified :D

**Comment by rusty1s** [comment]
We are updating to PyTorch 1.13 soon :)

**Comment by Arkajyoti-alien** [comment]
> Just googled a bit. Another reason might be that there is still a version mismatch between PyTorch and the PyTorch version `torch-scatter` was compiled with. How did you install PyTorch in the first-place? It is recommended to install PyTorch as outlined on their "get started" page. Other PyTorch versions, e.g, coming from `conda-forge` may result in this error.



> Yes, still looking the same:
> 
> ```
> (env2) C:\Users\jonat\Documents\Studium\Masterarbeit>py
> Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch_scatter
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\jonat\Documents\Studium\Masterarbeit\env2\lib\site-packages\torch_scatter\__init__.py", line 13, in <module>
>     torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
>   File "C:\Users\jonat\Documents\Studium\Masterarbeit\env2\lib\site-packages\torch\_ops.py", line 110, in load_library
>     ctypes.CDLL(path)
>   File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 127] The specified procedure could not be found
> ```
> 
> with a window popping up before the error message appears, which again says "The procedure entry point could not be located in the dynamic link library `...\env\Lib\site-packages\torch_scatter\_version_cpu.pyd`." Do you have any other ideas how this could be solved? If not, I've been thinking about just implementing some GNNs from scratch now, so you don't have to spend any more time on this if you don't feel like we can easily solve it.

I am having the same error please help me with this

**Comment by rusty1s** [comment]
Can you upgrade to PyG master? This should fix it.
