### ISSUE TITLE
hetero_conv: 'tuple' object has no attribute 'size'

### ISSUE THREAD

**Issue by diegocervera** [pyg-team/pytorch_geometric#3487]
Hi, I am trying to run a toy example using HeteroData. I have two different types of nodes: 'links' and 'paths'. These are connected as follow: path_1: [0, 1, 2, 3], path_2: [6, 3, 4].
This is what I have so far:
```Python
data = tg.data.HeteroData()
links = list(range(7))
paths = list(range(2))
path2link = np.array([
    [0, 0, 0, 0, 1, 1, 1],
    [0, 1, 2, 3, 6, 3, 4]
])
link2path = torch.from_numpy(np.flip(path2link, axis=0).copy())
path2link = torch.from_numpy(path2link)

data['link'].val = torch.from_numpy(np.array([[10, 20, 30] for _ in range(7)]))
data['path'].val = torch.from_numpy(np.array([[5, 10, 20] for _ in range(2)]))
data['link'].num_nodes = len(links)
data['path'].num_nodes = len(paths)
data['path', 'to', 'link'].edge_index = path2link
data['link', 'to', 'path'].edge_index = link2path

hetero_conv = tg.nn.HeteroConv({
    ('link', 'to', 'path'): tg.nn.GCNConv(-1, 2),
    ('path', 'to', 'link'): tg.nn.GCNConv(-1, 2)
})

out_dict = hetero_conv(data.val_dict, data.edge_index_dict)
```
When I run the above, I get the following error message:
```
Traceback (most recent call last):
  File "[...]/toy_example.py", line 47, in <module>
    out_dict = hetero_conv(data.val_dict, data.edge_index_dict)
  File "[...]/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "[...]/torch_geometric/nn/conv/hetero_conv.py", line 114, in forward
    out = conv((x_dict[src], x_dict[dst]), edge_index, *args,
  File "[...]/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "[...]/torch_geometric/nn/conv/gcn_conv.py", line 163, in forward
    edge_index, edge_weight, x.size(self.node_dim),
AttributeError: 'tuple' object has no attribute 'size'
```
Am I missing anything?
Many thanks!

**Comment by rusty1s** [comment]
The `GCNConv` can not be used as part of the `HeteroConv` as it not supports bipartite message passing flow. See [here](https://github.com/pyg-team/pytorch_geometric/discussions/3479) for a more detailed discussion. Furthermore, you need to convert `val` to floating-point type:
```python
data['link'].val = data['link'].val.float()
data['path'].val = data['path'].val.float()
```
After that, the following code works for me:
```python
hetero_conv = tg.nn.HeteroConv({
    ('link', 'to', 'path'): tg.nn.SAGEConv(-1, 2),
    ('path', 'to', 'link'): tg.nn.SAGEConv(-1, 2)
})

out_dict = hetero_conv(data.val_dict, data.edge_index_dict)
```

**Comment by diegocervera** [comment]
Many thanks for your quick response. With your modifications the code does work. I was using GCNCove since it was used in the example shown in the [documentation](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.HeteroConv), but I hadn't realised that the source node and the target node were the same type of nodes.
```Python
hetero_conv = HeteroConv({
    ('paper', 'cites', 'paper'): GCNConv(-1, 64),
    ('author', 'writes', 'paper'): SAGEConv((-1, -1), 64),
    ('paper', 'written_by', 'author'): GATConv((-1, -1), 64),
}, aggr='sum')

out_dict = hetero_conv(x_dict, edge_index_dict)
```
