### ISSUE TITLE
AttributeError: module 'numba' has no attribute 'jit' trying to import torch_geometric

### ISSUE THREAD

**Issue by Fauntman** [pyg-team/pytorch_geometric#3493]
I'm suddenly getting an error while trying to import `torch_geometric` .

Traceback (most recent call last):

  File "C:\Users\hp\untitled0.py", line 9, in <module>
    class MyCompositionalDataset(Dataset):

NameError: name 'Dataset' is not defined

runcell(0, 'C:/Users/hp/untitled0.py')
Traceback (most recent call last):

  File "C:\Users\hp\untitled0.py", line 8, in <module>
    import torch_geometric

  File "C:\Users\hp\anaconda3\lib\site-packages\torch_geometric\__init__.py", line 6, in <module>
    import torch_geometric.transforms

  File "C:\Users\hp\anaconda3\lib\site-packages\torch_geometric\transforms\__init__.py", line 38, in <module>
    from .gdc import GDC

  File "C:\Users\hp\anaconda3\lib\site-packages\torch_geometric\transforms\gdc.py", line 28, in <module>
    class GDC(object):

  File "C:\Users\hp\anaconda3\lib\site-packages\torch_geometric\transforms\gdc.py", line 512, in GDC
    def __calc_ppr__(indptr, indices, out_degree, alpha, eps):

  File "C:\Users\hp\anaconda3\lib\site-packages\torch_geometric\transforms\gdc.py", line 21, in decorator
    return numba.jit(cache=True, **kwargs)(func)

```
AttributeError: module 'numba' has no attribute 'jit'


runcell(0, 'C:/Users/hp/untitled0.py')
Traceback (most recent call last):

  File "C:\Users\hp\untitled0.py", line 8, in <module>
    import torch_geometric

  File "C:\Users\hp\anaconda3\lib\site-packages\torch_geometric\__init__.py", line 6, in <module>
    import torch_geometric.transforms

  File "C:\Users\hp\anaconda3\lib\site-packages\torch_geometric\transforms\__init__.py", line 38, in <module>
    from .gdc import GDC

  File "C:\Users\hp\anaconda3\lib\site-packages\torch_geometric\transforms\gdc.py", line 28, in <module>
    class GDC(object):

  File "C:\Users\hp\anaconda3\lib\site-packages\torch_geometric\transforms\gdc.py", line 512, in GDC
    def __calc_ppr__(indptr, indices, out_degree, alpha, eps):

  File "C:\Users\hp\anaconda3\lib\site-packages\torch_geometric\transforms\gdc.py", line 21, in decorator
    return numba.jit(cache=True, **kwargs)(func)

AttributeError: module 'numba' has no attribute 'jit'
```

I haven't updated nor installed any package so how is it possible that I'm encountering this issue?

**Comment by rusty1s** [comment]
Which PyG version are you using? What happens when you uninstall `numba`?

**Comment by Fauntman** [comment]
Hi and thanks for reaching out.

I just solved the issue by reinstalling on a fresh environment that now I'm using specifically for the project. I've also read that it is recommended to install pyg on a separate environment, in general.

Many thanks.
