### ISSUE TITLE
AttributeError: Can't get attribute 'DataBatch' on module 'torch_geometric.data.batch'

### ISSUE THREAD

**Issue by tiantz17** [pyg-team/pytorch_geometric#3530]
## 🐛 Bug

I encountered AttributeError: Can't get attribute 'DataBatch' on module 'torch_geometric.data.batch' when set num_workers>0 for DataLoader.
```
Traceback (most recent call last):
  File "runTrain.py", line 430, in <module>
    main()
  File "runTrain.py", line 426, in main
    model.train_and_save()
  File "runTrain.py", line 187, in train_and_save
    best_results = self.train_one_fold()
  File "runTrain.py", line 256, in train_one_fold
    self.train_one_epoch()
  File "runTrain.py", line 295, in train_one_epoch
    for batch, data in enumerate(self.Dataloader):
  File "/data/tiantingzhong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/data/tiantingzhong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/data/tiantingzhong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/data/tiantingzhong/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/data/tiantingzhong/anaconda3/envs/torch/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'DataBatch' on <module 'torch_geometric.data.batch' from '/data/tiantingzhong/anaconda3/envs/torch/lib/python3.7/site-packages/torch_geometric/data/batch.py'>
```

And the reason seemed to be the name of the Batch class became ```DataDataBatch()``` instead of ```DataBatch()```.
When I changed line 21 in ```torch_geometric/data/batch.py``` from 
```        base_cls = kwargs.pop('_base_cls', Data)```
to
```        base_cls = kwargs.pop('_base_cls', Batch)```,
the problem seemed solved.
But I don't think this is the optimal solution, is there a better way?

## To Reproduce

```
import torch
from torch_geometric.data import Data, Batch
a = [Data(x=torch.rand(10, 10))]*10
b = Batch().from_data_list(a)
```

## Expected behavior

```
b
>>> DataDataBatch(x=[100, 10], batch=[100], ptr=[11])
```

## Environment

* OS: Ubuntu 18.04
* Python version: 3.7.12
* PyTorch version: 1.9.1
* CUDA/cuDNN version: 11.3
* pyg: 2.0.2

**Comment by rusty1s** [comment]
It needs to be
```python
import torch
from torch_geometric.data import Data, Batch
a = [Data(x=torch.rand(10, 10))]*10
b = Batch.from_data_list(a)
```

**Comment by tiantz17** [comment]
@rusty1s Problem solved, thanks!
