### ISSUE TITLE
Run custom dataset with worker_per_gpu>0, multiprocessing error

### ISSUE THREAD

**Issue by ZhangHanbo** [pyg-team/pytorch_geometric#3559]
## To Reproduce

Run custom dataset with worker_per_gpu>0.

## Environment

* OS: Ubuntu 18.04
* Python version: Python 3.7.10
* PyTorch version: 1.10.0
* CUDA/cuDNN version: 10.2
* GCC version: 6.5.0
* Any other relevant information:

## Additional context

Traceback (most recent call last):
  File "./scripts/vmrn/train.py", line 189, in <module>
    main()
  File "./scripts/vmrn/train.py", line 185, in main
    meta=meta)
  File "/home/hanbo/ws/vmrn_mmdet/invigorate/apis/train.py", line 211, in train_detector
    runner.run(data_loaders, cfg.workflow)   
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)  
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj) 
AttributeError: Can't pickle local object 'Dataset.register_datapipe_as_function.<locals>.class_function'

**Comment by ZhangHanbo** [comment]
> 

Sorry for raising a wrong issue in this repo. 

Actually, I met some problems when using mmdetecion, and simultaneously I was reading the codes of pytorch geometric, and I mistook this repo as mmdetection and raised a wrong issue here. However, when I realized that I might have raised a wrong issue, it was too late because I didn't remember which repo I posed my issue in.

Sorry again for wasting your time to reply to me.
