### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'view'

### ISSUE THREAD

**Issue by YueeXiang** [pyg-team/pytorch_geometric#3786]
I don't know why I can't use message_passing for my code. The bug and my environment are shown as follows:

## 🐛 Bug

```
Traceback (most recent call last):
  File "/home/miniconda3/envs/pytorch/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-f79c60be7b62>", line 1, in <module>
    runfile('/home/test.py', wdir='/home/SG')
  File "/home/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/test.py", line 35, in <module>
    model_ft = train_model(model=model1,
  File "/home/learning.py", line 49, in train_model
    pred_nodes, pred_edges = model(x=history.x,
  File "/home/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/models.py", line 114, in forward
    pred_nodes = sgb(x=x, weight=coeff[:, 1], batch=batch, num=num, num_layer=self.gwb_layers, prior=y)
  File "/home/optimal_transport.py", line 53, in sgwb
    tmp += weight[k] * mp(x_k, edge_idx)
  File "/home/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch_geometric/nn/conv/appnp.py", line 110, in forward
    x = self.propagate(edge_index, x=x, edge_weight=edge_weight,
  File "/home/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py", line 309, in propagate
    out = self.message(**msg_kwargs)
  File "/home/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch_geometric/nn/conv/appnp.py", line 118, in message
    return edge_weight.view(-1, 1) * x_j
AttributeError: 'NoneType' object has no attribute 'view'
```

### Environment

* PyG version (`torch_geometric.__version__`): 2.0.2
* PyTorch version: (`torch.__version__`): 1.10.0
* OS : linux
* Python version: 3.9
* CUDA/cuDNN version: 11.4

**Comment by rusty1s** [comment]
Can you show me an example to reproduce?

**Comment by YueeXiang** [comment]
Hi, I want to compute a tensor like this
```
for k in range(batch_size):
    tmp += weight[k] * torch.matmul(to_dense_adj(edge_idx)[0, :, :], x_k)
```
where `edge_idx` is a [2, 50] tensor.
If I use message passing as shown below instead of `torch.maltul`, the computation may be much faster:
```
for k in range(batch_size):
    tmp += weight[k] * mp(x_k, edge_idx)
```
However, the code with `mp` will get the error:
`AttributeError: 'NoneType' object has no attribute 'view'`.
The traceback is shown in the first comment.

**Comment by rusty1s** [comment]
Thanks for reporting. This is now fixed in master, see https://github.com/pyg-team/pytorch_geometric/commit/690a01de7aaee053569c8944232cde590a4e3c8e.

**Comment by YueeXiang** [comment]
Thanks! It works now.
