### ISSUE TITLE
Getting CUDA error on Tesla M40 but not Tesla V100

### ISSUE THREAD

**Issue by jasperhyp** [pyg-team/pytorch_geometric#3822]
## 🐛 Bug

Hi!  I am using PyG with my school's HPC.  Because of resource allocation issues, I am not able to get the same GPU every time, but usually, I would get a Nvidia Tesla V100.  Today I got a Tesla M40, but then when running a program that worked well previously, I got this CUDA error `RuntimeError: CUDA error: no kernel image is available for execution on the device`.  I tried several times and this error persists.  I then managed to switch to a Quadro RTX 8000, and it works well.

However, PyTorch forum says M40 basically covers what V100 supports, so it is a bit weird why this is happening with `torch_scatter`. 

### To Reproduce

Just run my training code on M40, which worked well with V100 and RTX8000

### Expected behavior

Successfully train the model.

### Environment

* PyG version (`torch_geometric.__version__`): 2.0.2
* PyTorch version: (`torch.__version__`): 1.8.1
* OS (*e.g.*, Linux): Linux
* Python version (*e.g.*, `3.9`): 3.8
* CUDA/cuDNN version: 10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): I forgot, maybe pip.
* Any other relevant information (*e.g.*, version of `torch-scatter`): I forgot, but it should be the default version accompanied with PyG 

### Additional context

```python
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    main()
  File "train.py", line 283, in main
    train(epoch, model, optimizer, train_batch_num, val_batch_num)
  File "train.py", line 97, in train
    p_x, c_x = model(p_x, c_x, p_paths_train, c_paths_train, p_data, c_data)
  File "/home/xxx/.conda/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/project_name/pipeline/repr_learning/model.py", line 69, in forward
    p_x, c_x = self.conv1_up(p_x, c_x, p_paths, c_paths, p_index, c_index)
  File "/home/xxx/.conda/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/project_name/pipeline/repr_learning/conv.py", line 98, in forward
    ppi_x[ct] = self._per_data_forward(x, paths[ct], self.node_gats)
  File "/home/xxx/project_name/pipeline/repr_learning/conv.py", line 70, in _per_data_forward
    out = [gat(x, path) for gat, path in zip(node_gats, paths) if path.shape[1] > 0]
  File "/home/xxx/project_name/pipeline/repr_learning/conv.py", line 70, in <listcomp>
    out = [gat(x, path) for gat, metapath in zip(node_gats, paths) if path.shape[1] > 0]
  File "/home/xxx/.conda/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/.conda/envs/my_env/lib/python3.8/site-packages/torch_geometric/nn/conv/gat_conv.py", line 218, in forward
    out = self.propagate(edge_index, x=x, alpha=alpha, edge_attr=edge_attr,
  File "/home/xxx/.conda/envs/my_env/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 309, in propagate
    out = self.message(**msg_kwargs)
  File "/home/xxx/.conda/envs/my_env/lib/python3.8/site-packages/torch_geometric/nn/conv/gat_conv.py", line 258, in message
    alpha = softmax(alpha, index, ptr, size_i)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/xxx/.conda/envs/my_env/lib/python3.8/site-packages/torch_scatter/scatter.py", line 160, in softmax
        return scatter_min(src, index, dim, out, dim_size)[0]
    elif reduce == 'max':
        return scatter_max(src, index, dim, out, dim_size)[0]
               ~~~~~~~~~~~ <--- HERE
    else:
        raise ValueError
  File "/home/xxx/.conda/envs/my_env/lib/python3.8/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
        out: Optional[torch.Tensor] = None,
        dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

**Comment by rusty1s** [comment]
Thanks for reporting. Can you do me a favor and re-install `torch-scatter` via:
```
export TORCH_CUDA_ARCH_LIST="3.5;5.0+PTX;6.0;7.0;7.5" pip install --verbose git+https://github.com/rusty1s/pytorch_scatter.git
```
This might have been already fixed in master.

**Comment by jasperhyp** [comment]
> Thanks for reporting. Can you do me a favor and re-install `torch-scatter` via:
> 
> ```
> export TORCH_CUDA_ARCH_LIST="3.5;5.0+PTX;6.0;7.0;7.5" pip install --verbose git+https://github.com/rusty1s/pytorch_scatter.git
> ```
> 
> This might have been already fixed in master.

Thanks!  I'll try this, but I can't tell when I'll get an M40 again since there're few machines of this kind in the HPC.  Will update you when I get an M40 to test.

**Comment by jasperhyp** [comment]
Oh yes it's fixed now.  Thank you!
