### ISSUE TITLE
Distributed Batching example : AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by QuanticDisaster** [pyg-team/pytorch_geometric#3845]
## 🐛 Bug

When using the distributed batching example, the following error appears : 

```python
Traceback (most recent call last):

  File "/home/user/Downloads/trash.py", line 152, in <module>
    mp.spawn(run, args=args, nprocs=world_size, join=True)

  File "/home/user/anaconda3/envs/pt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')

  File "/home/user/anaconda3/envs/pt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():

  File "/home/user/anaconda3/envs/pt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)

ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/user/Downloads/trash.py", line 100, in run
    logits = model(data.x, data.adj_t, data.batch)
  File "/home/user/anaconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/pt/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/user/anaconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/Downloads/trash.py", line 55, in forward
    print(edge_attr.shape)
AttributeError: 'NoneType' object has no attribute 'shape'
```

### To Reproduce

Run the https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_batching.py example

### Expected behavior

Process should go smoothly

### Environment

* PyG version (`torch_geometric.__version__`): 2.0.2
* PyTorch version: (`torch.__version__`): 1.9.0
* OS (*e.g.*, Linux): Ubuntu LTS 20.04
* Python version (*e.g.*, `3.9`): 3.7
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): 1 GPU used

### Additional context

Problem comes from line 52, where adj_t.coo() gives `(tensor([   0,    1,    1,  ..., 3418, 3418, 3419], device='cuda:0'), tensor([   1,    0,    2,  ..., 3417, 3419, 3418], device='cuda:0'), None)` so edge_attr gets assigned `None`

adj_t representation : `SparseTensor(row=tensor([   0,    1,    1,  ..., 3418, 3418, 3419], device='cuda:0'),
             col=tensor([   1,    0,    2,  ..., 3417, 3419, 3418], device='cuda:0'),
             size=(3420, 3420), nnz=7326, density=0.06%)`

**Comment by rusty1s** [comment]
Thanks for reporting. This is now fixed, see https://github.com/pyg-team/pytorch_geometric/commit/cb6f2fd36994adf463cc035de76b14eab45f8a72.
