### ISSUE TITLE
Unable to train using Ubuntu or CentOS

### ISSUE THREAD

**Issue by pjuangph** [pyg-team/pytorch_geometric#3850]
## 🐛 Bug

There seems to be a bug with detecting the CPU in torch_sparse. Has anyone encountered this on their end? 

### To Reproduce

I would love to share with you all the code but at the moment I can't. I am training with SplineConv. It works fine with windows and mac. It fails on Ubuntu OS and CentOS. I am running with latest drivers Nvidia 470 

### Environment

* PyG version (`torch_geometric.__version__`):
* PyTorch version: (`torch.__version__`):
* OS (*e.g.*, Linux): both centos and ubuntu 
* Python version (*e.g.*, `3.9`): 3.95
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): torch 1.10.1 from pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

### Additional context
Traceback (most recent call last):
  File "/u/pjuangph/github/Airfoil-Learning/pytorch/train_gnn.py", line 7, in <module>
    from torch_geometric.loader import DataLoader
  File "/u/pjuangph/.conda/envs/gnn/lib/python3.9/site-packages/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data
  File "/u/pjuangph/.conda/envs/gnn/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/u/pjuangph/.conda/envs/gnn/lib/python3.9/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor
  File "/u/pjuangph/.conda/envs/gnn/lib/python3.9/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/u/pjuangph/.conda/envs/gnn/lib/python3.9/site-packages/torch_sparse/__init__.py", line 15, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/u/pjuangph/.conda/envs/gnn/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/u/pjuangph/.conda/envs/gnn/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /u/pjuangph/.conda/envs/gnn/lib/python3.9/site-packages/torch_sparse/_version_cpu.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

**Comment by rusty1s** [comment]
This error is typically related to some version inconsistency during installation. You may try to install the package from source to fix, *e.g.*, via
```
pip install --verbose torch-scatter torch-sparse
```
Let me know if that works for you (might take some time to compile).
