### ISSUE TITLE
Add additional attributes in Data

### ISSUE THREAD

**Issue by zhaoyu-li** [pyg-team/pytorch_geometric#3861]
### 🐛 Describe the bug

Hi, there seems to be a bug when the attributes of Data can be `None`. It seems like when calling self.collate, pyg first calls the constructor function of PairData without any arguments and at that time, self.has_edges is `None`, which leads to the problem.

Is there something wrong :)

```python
from torch_geometric.data import Data
import torch

from torch_geometric.data import InMemoryDataset
class PairData(Data):
    def __init__(self, edge_index_s=None, x_s=None, edge_index_t=None, x_t=None):
        super().__init__()
        self.edge_index_s = edge_index_s
        self.x_s = x_s
        self.edge_index_t = edge_index_t
        self.x_t = x_t
        if edge_index_s is not None:
            self.has_edges = True
        else:
            self.has_edges = None # here, self.has_edges may be None, if it can not be None, there is no problem.
        print(self.has_edges)
    def __inc__(self, key, value, *args, **kwargs):
        if key == 'edge_index_s':
            return self.x_s.size(0)
        if key == 'edge_index_t':
            return self.x_t.size(0)
        else:
            return super().__inc__(key, value, *args, **kwargs)

edge_index_s = torch.tensor([
    [0, 0, 0, 0],
    [1, 2, 3, 4],
])
x_s = torch.randn(5, 16)  # 5 nodes.
edge_index_t = torch.tensor([
    [0, 0, 0],
    [1, 2, 3],
])
x_t = torch.randn(4, 16)  # 4 nodes.

data = PairData(edge_index_s, x_s, edge_index_t, x_t)
data_list = [data, data]


class SATDataset(InMemoryDataset):
    def __init__(self, data_dir):
        super().__init__(data_dir)
        self.data, self.slices = torch.load(self.processed_paths[0])
    
    @property
    def processed_file_names(self):
        return ['d.pt']
    
    def process(self):
        data, slices = self.collate(data_list)
        torch.save((data, slices), self.processed_paths[0])

d = SATDataset('.')
print(d[0])
```

The error message is
```
Traceback (most recent call last):
  File "5.py", line 54, in <module>
    print(d[0])
  File "torch_geometric/data/dataset.py", line 198, in __getitem__
    data = self.get(self.indices()[idx])
  File "torch_geometric/data/in_memory_dataset.py", line 96, in get
    decrement=False,
  File "torch_geometric/data/separate.py", line 20, in separate
    data = cls().stores_as(batch)
  File "5.py", line 16, in __init__
    print(self.has_edges)
  File torch_geometric/data/data.py", line 346, in __getattr__
    return getattr(self._store, key)
  File "torch_geometric/data/storage.py", line 51, in __getattr__
    f"'{self.__class__.__name__}' object has no attribute '{key}'")
AttributeError: 'GlobalStorage' object has no attribute 'has_edges'
```

### Environment

* PyG version: 2.0.2
* PyTorch version: 1.10.0
* OS: Ubuntu
* Python version: 3.7.9
* CUDA/cuDNN version: 10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): `pip`
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by zhaoyu-li** [comment]
Oh, in this example the bool attribute `has_edges` is just a simple example, it actually can be any Tensors. And it may hard to set the Tensors to any default value, for they can be any shape of Tensors :)

**Comment by rusty1s** [comment]
Yes, we actually remove any attributes from `data` that are set to `None`. As such, you can either do:
```python
if 'has_edges' in self:
    print(self.has_edges)
```
or
```python
print(self.get('has_edges', None))
```
to resolve this.

**Comment by zhaoyu-li** [comment]
Got it, Thanks very much!
