### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_geometric.loader'

### ISSUE THREAD

**Issue by janathent** [pyg-team/pytorch_geometric#3868]
### 😵 Describe the installation problem

Hello, when I use the command”from torch_geometric.loader import DataLoader“ , I will report an error”ModuleNotFoundError: No module named 'torch_geometric.loader“.
What's the problem?
thanks a lot.

### Environment

* PyG version:1.7.1
* PyTorch version:1.9.0+cu102
* OS:Linux 4.15.0-153-generic x86_64
* Python version:3.8
* CUDA/cuDNN version:11.5
* How you installed PyTorch and PyG (`conda`, `pip`, source):pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
You need to either use `torch_geometric.data.DataLoader` or upgrade to PyG >= 2.0.*

**Comment by janathent** [comment]
> You need to either use `torch_geometric.data.DataLoader` or upgrade to PyG >= 2.0.*

thanks a lot!!!!!!!!!!!!

**Comment by qm-intel** [comment]
@rusty1s Hi, thanks for your great contribution to the science:

I have installed the following pytorch and pytorch_gemetric versions as you have mentioned [in this link](https://github.com/pyg-team/pytorch_geometric/issues/5358#issuecomment-1238207056):

```
conda create -n tox-env python=3.6
conda install pytorch=1.6.0 torchvision torchaudio cudatoolkit=10.2 -c pytorch
pip install torch-scatter==2.0.6 torch-sparse==0.6.9 -f https://pytorch-geometric.com/whl/torch-1.6.0+cu102.html
pip install torch-geometric==2.0.0
```
The reason is that I am trying to run the code from a GitHub repositorty, when it reaches to `this line`, it was raising an error (in the latest version of pytorch). Then I had to downgrade the `pyG` and `pytorch` versions, however, I am getting the following error:


```
/home/es/anaconda3/envs/tox-env/bin/python /home/es/PycharmProjects/1-Meta-MGNN/Meta-MGNN/main.py 
/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch/cuda/__init__.py:125: UserWarning: 
NVIDIA GeForce RTX 3090 Ti with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3090 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
tox21
Iteration:   0%|          | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/es/PycharmProjects/1-Meta-MGNN/Meta-MGNN/main.py", line 131, in <module>
    main("tox21", "model_gin/supervised_contextpred.pth", "gin", True, True, True, 0.1, 5)
  File "/home/es/PycharmProjects/1-Meta-MGNN/Meta-MGNN/main.py", line 105, in main
    support_grads = model(epoch)
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/es/PycharmProjects/1-Meta-MGNN/Meta-MGNN/meta_model.py", line 183, in forward
    for step, batch in enumerate(tqdm(support_loaders[task], desc="Iteration")):
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 198, in __getitem__
    data = self.get(self.indices()[idx])
  File "/home/es/PycharmProjects/1-Meta-MGNN/Meta-MGNN/loader.py", line 142, in get
    for key in self.data.keys:
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch_geometric/data/data.py", line 103, in keys
    for store in self.stores:
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch_geometric/data/data.py", line 393, in stores
    return [self._store]
  File "/home/es/anaconda3/envs/tox-env/lib/python3.6/site-packages/torch_geometric/data/data.py", line 341, in __getattr__
    "The 'data' object was created by an older version of PyG. "
RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.


Process finished with exit code 1
```

How can I resolve this?

Thanks in advance

**Comment by rusty1s** [comment]
Is this a custom dataset? PyG 2.0 slightly changed the way we store datasets on disk, so you are seeing
```
RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.
```
when loading a dataset processed with PyG < 2.0 in PyG 2.*. As such, you would need to re-process it from the raw data by deleting the `dataset_root_dir/processed` directory.

**Comment by qm-intel** [comment]
@rusty1s I am trying to run the [this github code](https://github.com/zhichunguo/Meta-MGNN/blob/b76c04057ebbf19e164cb101e8a9b9b758f9f008/loader.py#L135) in which they are using `tox21` datasets and they are loading from a folder in [this function](https://github.com/zhichunguo/Meta-MGNN/blob/b76c04057ebbf19e164cb101e8a9b9b758f9f008/loader.py#L160), I am not sure what do you mean. Sorry I am new to pytorch and pytorch geometric. 



> when loading a dataset processed with PyG < 2.0 in PyG 2.*. As such, you would need to re-process it from the raw data by deleting the dataset_root_dir/processed directory.

How to do that?

**Comment by rusty1s** [comment]
The `MoleculeDataset` has a `root` argument which indicates where the data is stored. You should be able to simply delete the `root/processed` directory and try again.

**Comment by YafanWu** [comment]
> You need to either use `torch_geometric.data.DataLoader` or upgrade to PyG >= 2.0.*

Hi Matthias, I got the same error ModuleNotFoundError: No module named 'torch_geometric.loader'...I tried using torch_geometric.data.DataLoader, didn't work for me. I then checked docs on the official website, it seems there isn't a 'DataLoader' in torch_geometric.data?... here's what my Environment looks like:

PyG version:1.6.3
PyTorch version:1.7.1+cu102
OS:Linux 18.04
Python version:3.8
CUDA Version:10.2

Thanks in advance!
