### ISSUE TITLE
On CPU-only machine: OSError: libc10_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ferdiko** [pyg-team/pytorch_geometric#3904]
### 😵 Describe the installation problem

I tried to install torch_geometric for CPU using conda on a CPU-only machine: `conda install pyg -c pyg -c conda-forge` 

After that I tried uninstalled `torch-scatter` and `torch-sparse` and reinstalled them, because they gave me errors (`torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c10lsERSoNS_12TensorTypeIdE` and `torch_sparse/_convert_cpu.so: undefined symbol: _ZNK2at6Tensor6deviceEv`). That resolved the errors but gave me `OSError: libc10_cuda.so: cannot open shared object file: No such file or directory`. I don't have any cuda libs installed since my machine doesn't have a GPU. I tried to reinstall pytorch_geometric but wasn't able to resolve the error.

Full error message:
```
Traceback (most recent call last):
  File "placement_optimizer.py", line 2, in <module>
    from torch_geometric.data import Data
  File "/data/scratch/ferdi/miniconda3/envs/hybrid/lib/python3.7/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/data/scratch/ferdi/miniconda3/envs/hybrid/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/data/scratch/ferdi/miniconda3/envs/hybrid/lib/python3.7/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/data/scratch/ferdi/miniconda3/envs/hybrid/lib/python3.7/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/data/scratch/ferdi/miniconda3/envs/hybrid/lib/python3.7/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/data/scratch/ferdi/miniconda3/envs/hybrid/lib/python3.7/site-packages/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "/data/scratch/ferdi/miniconda3/envs/hybrid/lib/python3.7/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/data/scratch/ferdi/miniconda3/envs/hybrid/lib/python3.7/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/data/scratch/ferdi/miniconda3/envs/hybrid/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc10_cuda.so: cannot open shared object file: No such file or directory
```

Conda packages:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
attrs                     21.4.0             pyhd3eb1b0_0  
blas                      1.0                         mkl  
bottleneck                1.3.2            py37heb32a55_1  
brotlipy                  0.7.0           py37h27cfd23_1003  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py37h06a4308_2  
cffi                      1.15.0           py37hd667e15_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
coverage                  6.2              py37h7f8727e_0  
cryptography              36.0.0           py37h9ce1e76_0  
cudatoolkit               11.1.1               h6406543_8    conda-forge
future                    0.18.2                   py37_1  
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
html5lib                  1.1                pyhd3eb1b0_0  
idna                      3.3                pyhd3eb1b0_0  
importlib-metadata        4.8.2            py37h06a4308_0  
importlib_metadata        4.8.2                hd3eb1b0_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intel-openmp              2021.4.0          h06a4308_3561  
isodate                   0.6.0              pyhd3eb1b0_1  
jinja2                    3.0.2              pyhd3eb1b0_0  
joblib                    1.1.0              pyhd3eb1b0_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libblas                   3.9.0            12_linux64_mkl    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libprotobuf               3.16.0               h780b84a_0    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17  
markupsafe                2.0.1            py37h27cfd23_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
ncurses                   6.3                  h7f8727e_2  
networkx                  2.6.3              pyhd3eb1b0_0  
ninja                     1.10.2           py37hd09550d_3  
numexpr                   2.8.1            py37h6abb31d_0  
numpy                     1.21.2           py37h20f2e39_0  
numpy-base                1.21.2           py37h79a1101_0  
openssl                   1.1.1m               h7f8727e_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.3.5            py37h8c16a72_0  
pip                       21.2.2           py37h06a4308_0  
pluggy                    1.0.0            py37h06a4308_0  
py                        1.10.0             pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyg                       2.0.3           py37_torch_1.9.0_cu111    pyg
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pysocks                   1.7.1                    py37_1  
pytest                    6.2.5            py37h06a4308_2  
pytest-cov                3.0.0              pyhd3eb1b0_0  
python                    3.7.11               h12debd9_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-louvain            0.15               pyhd3eb1b0_0  
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.9.0           cpu_py37hb06efa0_2    conda-forge
pytorch-cluster           1.5.9           py37_torch_1.9.0_cu111    pyg
pytorch-cpu               1.9.0           cpu_py37h718b53a_2    conda-forge
pytorch-scatter           2.0.9           py37_torch_1.9.0_cu111    pyg
pytorch-sparse            0.6.12          py37_torch_1.9.0_cu111    pyg
pytorch-spline-conv       1.2.1           py37_torch_1.9.0_cu111    pyg
pytorch_geometric         2.0.3              pyh6c4a22f_0    conda-forge
pytorch_scatter           2.0.7            py37h4415eb7_0    conda-forge
pytorch_sparse            0.6.10           py37h4415eb7_1    conda-forge
pytz                      2021.3             pyhd3eb1b0_0  
pyyaml                    6.0              py37h7f8727e_1  
rdflib                    6.1.1              pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd3eb1b0_0  
scikit-learn              1.0.2            py37h51133e4_1  
scipy                     1.7.3            py37hc147768_0  
setuptools                58.0.4           py37h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sleef                     3.5.1                h7f98852_1    conda-forge
sqlite                    3.37.0               hc218d9a_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.11               h1ccaba5_0  
toml                      0.10.2             pyhd3eb1b0_0  
torch-scatter             2.0.9            py37h980ed9f_0    conda-forge
torch-sparse              0.4.3            py37hf484d3e_0    ostrokach-forge
tqdm                      4.62.3             pyhd3eb1b0_1  
typing_extensions         3.10.0.2           pyh06a4308_0  
urllib3                   1.26.7             pyhd3eb1b0_0  
webencodings              0.5.1                    py37_1  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.6              pyhd3eb1b0_1  
yaml                      0.2.5                h7b6447c_0  
zipp                      3.7.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7f8727e_4  
```

System info:
- Ubuntu 18.04.6 LTS
- lscpu:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           4
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               79
Model name:          Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:            1
CPU MHz:             2194.916
BogoMIPS:            4389.83
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear
```

Thanks for helping!

### Environment

* PyG version: 2.0.3
* PyTorch version: 1.9.0
* OS: Ubuntu 18.04.06
* Python version: 3.7.11
* CUDA/cuDNN version: N/A
* How you installed PyTorch and PyG: `conda`

**Comment by rusty1s** [comment]
It looks like you have installed PyTorch with CUDA support (there exists a `cudatoolkit` conda package). As such, `torch-scatter` and `torch-sparse` are also installed with CUDA support (unlike PyTorch, they currently require that CUDA exists but this will be fixed in an upcoming version). For now, it's best to install the PyTorch CPU version:
```
conda install pytorch cpuonly -c pytorch
conda install pyg -c pyg -c conda-forge
```

**Comment by ferdiko** [comment]
Thanks a lot (!), this seems to have worked.
