### ISSUE TITLE
AttributeError: 'BaseStorage' object has no attribute 'edge_index' for hetero graph

### ISSUE THREAD

**Issue by Yoloniverse** [pyg-team/pytorch_geometric#4013]
### 🐛 Describe the bug

I tried to remove isolated nodes in my hetero graph. My hetero graph is as below:

data
Out[117]: 
HeteroData(
  card={ x=[15910, 300] },
  user={ x=[12363, 300] },
  (user, solved, card)={ edge_index=[88552, 2] }
)

When I use 'has_isolated_nodes()', it shows True

data.has_isolated_nodes()
Out[119]: True

Then I tried to remove the isolated nodes, but I got an error. 

`import torch`
`from torch_geometric.data import HeteroData`
`import torch_geometric.transforms as T`
`data = T.RemoveIsolatedNodes()(data)`

```
Traceback (most recent call last):

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/data/storage.py", line 48, in __getattr__
    return self[key]

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/data/storage.py", line 68, in __getitem__
    return self._mapping[key]

KeyError: 'edge_index'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-120-2f26aa6d93fc>", line 1, in <module>
    data = T.RemoveIsolatedNodes()(data)

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/transforms/remove_isolated_nodes.py", line 13, in __call__
    out = remove_isolated_nodes(data.edge_index, data.edge_attr, num_nodes)

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/data/hetero_data.py", line 118, in __getattr__
    return getattr(self._global_store, key)

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/data/storage.py", line 51, in __getattr__
    f"'{self.__class__.__name__}' object has no attribute '{key}'")

AttributeError: 'BaseStorage' object has no attribute 'edge_index'
```

As it is hetero graph, I do not have edge_index alone. My metadata() shows as below:

data.metadata()
Out[124]: (['card', 'user'], [('user', 'solved', 'card')])

How can I use RemoveIsolatedNodes in hetero graph?

### Environment

* PyG version: 2.0.3
* PyTorch version: 1.10.1+cu102
* OS: LINUX
* Python version: 3.6
* CUDA/cuDNN version: cuda 10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by Yoloniverse** [comment]
I found the edge_index is not [2, x..] but [x.., 2]

**Comment by rusty1s** [comment]
The `RemoveIsolatedNodes` transform does not support yet `HeteroData` objects. That's why you are seeing this error.

**Comment by Padarn** [comment]
Do you still think this is P0 @rusty1s , if so I don't mind taking a look at adding support into `RemoveIsolatedNodes`

**Comment by rusty1s** [comment]
It would be great to finally fix this. Thanks @Padarn. It shouldn‘t be too hard to fix as well. Let me know if there are any questions.
