### ISSUE TITLE
OGB_MAG download url seems to be broken

### ISSUE THREAD

**Issue by Yoloniverse** [pyg-team/pytorch_geometric#4014]
### 🐛 Describe the bug

It seems that OGB dataset is a broken one. 
When I do `dataset = OGB_MAG(path, preprocess='metapath2vec', transform=transform)`, this returns below:
```Using existing file mag_metapath2vec_emb.zip

Traceback (most recent call last):

  File "<ipython-input-474-084c20c49593>", line 1, in <module>
    dataset = OGB_MAG(path, preprocess='metapath2vec', transform=transform)

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/datasets/ogb_mag.py", line 58, in __init__
    super().__init__(root, transform, pre_transform)

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 85, in __init__
    self._download()

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 146, in _download
    self.download()

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/datasets/ogb_mag.py", line 107, in download
    extract_zip(path, self.raw_dir)

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/site-packages/torch_geometric/data/extract.py", line 39, in extract_zip
    with zipfile.ZipFile(path, 'r') as f:

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()

  File "/home/hojun/anaconda3/envs/geometric/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")

BadZipFile: File is not a zip file
```

I guess the URL should be updated.

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Looks like `snap.stanford.edu` servers were down. Can you remove `{root_dir}/mag/raw` and try again? It runs fine for me now.

**Comment by Yoloniverse** [comment]
You are right. It worked when I did today again. Thank you.
