### ISSUE TITLE
Potential issue converting batch normalisation from homogeneous GNN using `to_hetero()` method to heterogeneous version

### ISSUE THREAD

**Issue by anniekmyatt** [pyg-team/pytorch_geometric#4023]
### 🐛 Describe the bug

When I include batch normalisation in the GNN of the example [hetero_link_pred.py](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/hetero/hetero_link_pred.py), an error is thrown in the first model call of the lazy initialisation. Note that the code below is exactly copied from the link prediction example, only the two lines related to batch normalisation in the `GNNEncoder` class are added.

```
import argparse
import os.path as osp

import torch
import torch.nn.functional as F
from torch.nn import Linear

import torch_geometric.transforms as T
from torch_geometric.datasets import MovieLens
from torch_geometric.nn.norm.batch_norm import BatchNorm
from torch_geometric.nn import SAGEConv, to_hetero

parser = argparse.ArgumentParser()
parser.add_argument('--use_weighted_loss', action='store_true',
                    help='Whether to use weighted MSE loss.')
args = parser.parse_args()

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

path = osp.join(osp.dirname(osp.realpath(__file__)), '../../data/MovieLens')
dataset = MovieLens(path, model_name='all-MiniLM-L6-v2')
data = dataset[0].to(device)

# Add user node features for message passing:
data['user'].x = torch.eye(data['user'].num_nodes, device=device)
del data['user'].num_nodes

# Add a reverse ('movie', 'rev_rates', 'user') relation for message passing:
data = T.ToUndirected()(data)
del data['movie', 'rev_rates', 'user'].edge_label  # Remove "reverse" label.

# Perform a link-level split into training, validation, and test edges:
train_data, val_data, test_data = T.RandomLinkSplit(
    num_val=0.1,
    num_test=0.1,
    neg_sampling_ratio=0.0,
    edge_types=[('user', 'rates', 'movie')],
    rev_edge_types=[('movie', 'rev_rates', 'user')],
)(data)

# We have an unbalanced dataset with many labels for rating 3 and 4, and very
# few for 0 and 1. Therefore we use a weighted MSE loss.
if args.use_weighted_loss:
    weight = torch.bincount(train_data['user', 'movie'].edge_label)
    weight = weight.max() / weight
else:
    weight = None


def weighted_mse_loss(pred, target, weight=None):
    weight = 1. if weight is None else weight[target].to(pred.dtype)
    return (weight * (pred - target.to(pred.dtype)).pow(2)).mean()


class GNNEncoder(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.batch_norm1 = BatchNorm(hidden_channels) 
        self.conv1 = SAGEConv((-1, -1), hidden_channels)
        self.conv2 = SAGEConv((-1, -1), out_channels)
               

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        x = self.batch_norm1(x)
        x = self.conv2(x, edge_index)
        return x


class EdgeDecoder(torch.nn.Module):
    def __init__(self, hidden_channels):
        super().__init__()
        self.lin1 = Linear(2 * hidden_channels, hidden_channels)
        self.lin2 = Linear(hidden_channels, 1)

    def forward(self, z_dict, edge_label_index):
        row, col = edge_label_index
        z = torch.cat([z_dict['user'][row], z_dict['movie'][col]], dim=-1)

        z = self.lin1(z).relu()
        z = self.lin2(z)
        return z.view(-1)


class Model(torch.nn.Module):
    def __init__(self, hidden_channels):
        super().__init__()
        self.encoder = GNNEncoder(hidden_channels, hidden_channels)
        self.encoder = to_hetero(self.encoder, data.metadata(), aggr='sum')
        self.decoder = EdgeDecoder(hidden_channels)

    def forward(self, x_dict, edge_index_dict, edge_label_index):
        z_dict = self.encoder(x_dict, edge_index_dict)
        return self.decoder(z_dict, edge_label_index)


model = Model(hidden_channels=32).to(device)

# Due to lazy initialization, we need to run one model step so the number
# of parameters can be inferred:
with torch.no_grad():
    model.encoder(train_data.x_dict, train_data.edge_index_dict)

```

Result:

```
Traceback (most recent call last):
  File ".../hetero_link_pred.py", line 98, in <module>
    model = Model(hidden_channels=32).to(device)
  File ".../hetero_link_pred.py", line 90, in __init__
    self.encoder = to_hetero(self.encoder, data.metadata(), aggr='sum')
  File "...\lib\site-packages\torch_geometric\nn\to_hetero_transformer.py", line 111, in to_hetero
    return transformer.transform()
  File "...\lib\site-packages\torch_geometric\nn\fx.py", line 175, in transform 
    self.gm.graph.lint()
  File "...\lib\site-packages\torch\fx\graph.py", line 1057, in lint
    raise RuntimeError(f'Node {node} target {node.target} references nonexistent attribute '
RuntimeError: Node batch_norm1_module__movie target batch_norm1.module.movie references nonexistent attribute module of batch_norm1
```

### Environment

* PyG version: from source (pip install git+https://github.com/pyg-team/pytorch_geometric.git)
* PyTorch version:  torch==1.9.0+cpu
* OS: Windows 10
* Python version: 3.8 (also tried with 3.9 with same issue)
* CUDA/cuDNN version: cpu
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thank you. This is indeed a bug and I fixed it in https://github.com/pyg-team/pytorch_geometric/pull/4027.

The reason of the bug is that `torch.fx` traces down child modules, which we cannot yet lift to the heterogeneous graph setting. The issue does not occur when using `torch.nn.BatchNorm1d` so I never noticed it :)

**Comment by ashkspark** [comment]
I also face the same error with `GENConv` and `DeepGCNLayer` similar to the [ogbn_proteins_deepgcn](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/ogbn_proteins_deepgcn.py), but for the link prediction task following [medium link-prediction-on-heterogeneous-graphs](https://medium.com/@pytorch_geometric/link-prediction-on-heterogeneous-graphs-with-pyg-6d5c29677c70). Here is the error:
```python
Traceback (most recent call last):
  File "/home/Hetero_GNN/GENConv.py", line 287, in <module>
    model = Model(hidden_channels = 64, data = graphdata)
  File "/home/Hetero_GNN/models_GENConv.py", line 172, in __init__
    self.gnn = to_hetero(self.gnn, metadata = data.metadata())
  File "/home/svenv/lib/python3.9/site-packages/torch_geometric/nn/to_hetero_transformer.py", line 120, in to_hetero
    return transformer.transform()
  File "/home/svenv/lib/python3.9/site-packages/torch_geometric/nn/fx.py", line 183, in transform
    self.gm.graph.lint()
  File "/home/svenv/lib64/python3.9/site-packages/torch/fx/graph.py", line 1248, in lint
    raise RuntimeError(f'Node {node} target {node.target} references nonexistent attribute '
RuntimeError: Node layers_0_conv__movie_node target layers.0.conv.user_node__rates__movie_node references nonexistent attribute user_node__rates__movie_node of layers.0.conv
```
Environment Details:

* torch-geometric==2.3.1
* torch==1.12.0+cpu
* torch-scatter==2.0.9
* torch-sparse==0.6.15
* torchaudio==0.12.0+cpu
* torchvision==0.13.0+cpu
* Python 3.9.13

**Comment by rusty1s** [comment]
I am afraid to tell you that `DeepGCNLayer` is not compatible with bipartite message passing at the moment, and there is no easy way to achieve this at the moment. As such, it can also not be used within `to_hetero` :(

**Comment by rusty1s** [comment]
What you can do is define a model similar to `DeepGCNLayer`, e.g.
python
def forward(self, x, edge_index):
    x = self.conv1(x, edge_index)
    x = self.norm1(x)
    x = self.act(x)
    ...
```
and input that into `to_hetero`.

**Comment by ashkspark** [comment]
Hi @rusty1s! Out of curiosity, what is the primary reason `[DeepGCNLayer](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/models/deepgcn.html#DeepGCNLayer.forward)` is not compatible with bipartite message passing? Is this because of if/else statement for residual connections? Thanks!

**Comment by rusty1s** [comment]
No particular reason, we just didn't manage to implement it yet :(
