### ISSUE TITLE
RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions.

### ISSUE THREAD

**Issue by LindaSt** [pyg-team/pytorch_geometric#4073]
### 😵 Describe the installation problem

Hi :)!

So I've been trying to install PyG, and the installation went fine. However when I run `rom torch_geometric.datasets import TUDataset` I get the following error:

```
>>> from torch_geometric.datasets import TUDataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch_sparse/__init__.py", line 37, in <module>
    from .storage import SparseStorage  # noqa
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch_sparse/storage.py", line 5, in <module>
    from torch_scatter import segment_csr, scatter_add
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch_scatter/__init__.py", line 58, in <module>
    raise RuntimeError(
RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions. PyTorch has CUDA version 10.1 and torch_scatter has CUDA version 11.2. Please reinstall the torch_scatter that matches your PyTorch install.
```

I've installed torch-scatter using the command `pip install torch-scatter -f https://data.pyg.org/whl/torch-1.8.1+cu101.html` so I don't understand how I ended up with the one for cuda version 11.2. I've tried uninstalling and re-installing, but it did not help, unfortunately.

Thanks for your help!

### Environment

* PyTorch version: 1.8.1
* OS: linux
* Python version: 3.8
* CUDA/cuDNN version: 10.1
* How you installed PyTorch and PyG (`conda`, `pip`, source):
`pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`
`pip install torch-scatter -f https://data.pyg.org/whl/torch-1.8.1+cu101.html`
`pip install torch-sparse -f https://data.pyg.org/whl/torch-1.8.1+cu101.html`
`pip install torch-cluster -f https://data.pyg.org/whl/torch-1.8.1+cu101.html`

**Comment by rusty1s** [comment]
For older PyTorch versions (<= 1.8), you will need to specify the version of the respective packages, see https://data.pyg.org/whl/torch-1.8.1+cu101.html:
```
pip install torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.1+cu101.html
```

**Comment by LindaSt** [comment]
Thank you!

**Comment by guihuzhang** [comment]
> For older PyTorch versions (<= 1.8), you will need to specify the version of the respective packages, see https://data.pyg.org/whl/torch-1.8.1+cu101.html:
> 
> ```
> pip install torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.1+cu101.html
> ```
> 
> Otherwise, it will try to compile the latest version from source.

thank you so much!!!
