### ISSUE TITLE
CPU only installation looks for CUDA when using mamba

### ISSUE THREAD

**Issue by Zethson** [pyg-team/pytorch_geometric#4160]
### 😵 Describe the installation problem

Fresh 3.8 Python env

Then

```
mamba install pytorch torchvision torchaudio cpuonly -c pytorch
mamba install pyg -c pyg -c conda-forge
```

```
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.8/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.8/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.8/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.8/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/home/zeth/miniconda3/envs/cellvgae/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc10_cuda.so: cannot open shared object file: No such file or directory
```

### Environment

* PyG version: 2.0.3
* PyTorch version: 1.10.2
* OS: Arch Linux
* Python version: 3.8.12
* CUDA/cuDNN version: None
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda <- see above

**Comment by Zethson** [comment]
I can reproduce this with a second PC. Interested in learning what I am doing wrong or what's going on here.

**Comment by rusty1s** [comment]
Can you share the outputs of `conda list`?

**Comment by Zethson** [comment]
Sure:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
blas                      1.0                         mkl  
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1003    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.15.0           py38h3931269_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cpuonly                   2.0                           0    pytorch
cryptography              36.0.0           py38h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
fonttools                 4.29.1           py38h497a2fe_0    conda-forge
freetype                  2.11.0               h70c0345_0  
giflib                    5.2.1                h7b6447c_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h7f8727e_0  
kiwisolver                1.3.2            py38h1fd1430_1    conda-forge
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libblas                   3.9.0            12_linux64_mkl    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0            12_linux64_mkl    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgfortran-ng            11.2.0              h69a702a_12    conda-forge
libgfortran5              11.2.0              h5c6108e_12    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libiconv                  1.15                 h63c8f33_5  
libidn2                   2.3.2                h7f8727e_0  
liblapack                 3.9.0            12_linux64_mkl    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h3942068_0  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.1.0            py38h0a891b7_0    conda-forge
matplotlib-base           3.5.1            py38hf4fb855_0    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.1            py38hd3c417c_0  
mkl_random                1.2.2            py38h51133e4_0  
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h7f8727e_2  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
numpy                     1.21.2           py38h20f2e39_0  
numpy-base                1.21.2           py38h79a1101_0  
olefile                   0.46               pyhd3eb1b0_0  
openh264                  2.1.1                h4ff587b_0  
openssl                   3.0.0                h7f98852_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py38h43a58ef_0    conda-forge
pillow                    8.4.0            py38h5aabda8_0  
pip                       21.2.4           py38h06a4308_0  
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyg                       2.0.3           py38_torch_1.10.0_cu113    pyg
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_4    conda-forge
python                    3.8.12          h0744224_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-louvain            0.15               pyhd8ed1ab_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.10.2              py3.8_cpu_0    pytorch
pytorch-cluster           1.5.9           py38_torch_1.10.0_cu113    pyg
pytorch-mutex             1.0                         cpu    pytorch
pytorch-scatter           2.0.9           py38_torch_1.10.0_cu113    pyg
pytorch-sparse            0.6.12          py38_torch_1.10.0_cu113    pyg
pytorch-spline-conv       1.2.1           py38_torch_1.10.0_cu113    pyg
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38h497a2fe_3    conda-forge
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
scikit-learn              1.0.2            py38h1561384_0    conda-forge
scipy                     1.8.0            py38h56a6a73_1    conda-forge
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.37.2               hc218d9a_0  
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h1ccaba5_0  
torchaudio                0.10.2               py38_cu113    pytorch
torchvision               0.11.3               py38_cu113    pytorch
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyh06a4308_0  
unicodedata2              14.0.0           py38h497a2fe_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.4.9                haebb681_0  
```

Thank you!

**Comment by rusty1s** [comment]
Seems like you deleted your message. But nonetheless, you should remove the `cudatoolkit` dependency inside `conda` and try again.

**Comment by Zethson** [comment]
Yeah, I deleted it because I thought I'd do it again to ensure that I don't paste bad output to you.

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
blas                      1.0                         mkl  
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1003    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.15.0           py38h3931269_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cpuonly                   2.0                           0    pytorch
cryptography              36.0.0           py38h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
fonttools                 4.29.1           py38h497a2fe_0    conda-forge
freetype                  2.11.0               h70c0345_0  
giflib                    5.2.1                h7b6447c_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h7f8727e_0  
kiwisolver                1.3.2            py38h1fd1430_1    conda-forge
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libblas                   3.9.0            12_linux64_mkl    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0            12_linux64_mkl    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgfortran-ng            11.2.0              h69a702a_12    conda-forge
libgfortran5              11.2.0              h5c6108e_12    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libiconv                  1.15                 h63c8f33_5  
libidn2                   2.3.2                h7f8727e_0  
liblapack                 3.9.0            12_linux64_mkl    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h3942068_0  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.1.0            py38h0a891b7_0    conda-forge
matplotlib-base           3.5.1            py38hf4fb855_0    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.1            py38hd3c417c_0  
mkl_random                1.2.2            py38h51133e4_0  
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h7f8727e_2  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
numpy                     1.21.2           py38h20f2e39_0  
numpy-base                1.21.2           py38h79a1101_0  
olefile                   0.46               pyhd3eb1b0_0  
openh264                  2.1.1                h4ff587b_0  
openssl                   3.0.0                h7f98852_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py38h43a58ef_0    conda-forge
pillow                    8.4.0            py38h5aabda8_0  
pip                       21.2.4           py38h06a4308_0  
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyg                       2.0.3           py38_torch_1.10.0_cu113    pyg
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_4    conda-forge
python                    3.8.12          h0744224_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-louvain            0.15               pyhd8ed1ab_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.10.2              py3.8_cpu_0    pytorch
pytorch-cluster           1.5.9           py38_torch_1.10.0_cu113    pyg
pytorch-mutex             1.0                         cpu    pytorch
pytorch-scatter           2.0.9           py38_torch_1.10.0_cu113    pyg
pytorch-sparse            0.6.12          py38_torch_1.10.0_cu113    pyg
pytorch-spline-conv       1.2.1           py38_torch_1.10.0_cu113    pyg
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38h497a2fe_3    conda-forge
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
scikit-learn              1.0.2            py38h1561384_0    conda-forge
scipy                     1.8.0            py38h56a6a73_1    conda-forge
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.37.2               hc218d9a_0  
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h1ccaba5_0  
torchaudio                0.10.2               py38_cu113    pytorch
torchvision               0.11.3               py38_cu113    pytorch
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyh06a4308_0  
unicodedata2              14.0.0           py38h497a2fe_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.4.9                haebb681_0  
```

But why would it install the cudatoolkit in the first place? I always just request the CPU versions, no?

**Comment by rusty1s** [comment]
Are you sure that PyG installs the `cudatoolkit`? IMO, PyG installs its CUDA version in case it founds a `cudatoolkit` already installed (which might explain your errors).

**Comment by Zethson** [comment]
I think so. Because when I remove the cudatoolkit it removes everything PyG related?

```
⋊> ~/P/chicago_munich_covid on master ⨯ conda remove cudatoolkit                                                                                                           (cellvgae) 10:24:00
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/zeth/miniconda3/envs/cellvgae

  removed specs:
    - cudatoolkit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-4.5          |            1_gnu          22 KB
    intel-openmp-2022.0.1      |    h06a4308_3633         4.2 MB
    mkl-2022.0.1               |     h06a4308_117       127.7 MB
    ------------------------------------------------------------
                                           Total:       131.9 MB

The following packages will be REMOVED:

  brotli-1.0.9-h7f98852_6
  brotli-bin-1.0.9-h7f98852_6
  brotlipy-0.7.0-py38h497a2fe_1003
  bzip2-1.0.8-h7b6447c_0
  cffi-1.15.0-py38h3931269_0
  charset-normalizer-2.0.12-pyhd8ed1ab_0
  colorama-0.4.4-pyh9f0ad1d_0
  cryptography-36.0.0-py38h9ce1e76_0
  cudatoolkit-11.3.1-h2bc3f7f_2
  cycler-0.11.0-pyhd8ed1ab_0
  ffmpeg-4.3-hf484d3e_0
  fonttools-4.29.1-py38h497a2fe_0
  freetype-2.11.0-h70c0345_0
  giflib-5.2.1-h7b6447c_0
  gmp-6.2.1-h2531618_2
  gnutls-3.6.15-he1e5248_0
  googledrivedownloader-0.4-pyhd3deb0d_1
  idna-3.3-pyhd8ed1ab_0
  jinja2-3.0.3-pyhd8ed1ab_0
  joblib-1.1.0-pyhd8ed1ab_0
  jpeg-9d-h7f8727e_0
  kiwisolver-1.3.2-py38h1fd1430_1
  lame-3.100-h7b6447c_0
  lcms2-2.12-h3be6417_0
  libblas-3.9.0-12_linux64_mkl
  libbrotlicommon-1.0.9-h7f98852_6
  libbrotlidec-1.0.9-h7f98852_6
  libbrotlienc-1.0.9-h7f98852_6
  libcblas-3.9.0-12_linux64_mkl
  libgfortran-ng-11.2.0-h69a702a_12
  libgfortran5-11.2.0-h5c6108e_12
  libiconv-1.15-h63c8f33_5
  libidn2-2.3.2-h7f8727e_0
  liblapack-3.9.0-12_linux64_mkl
  libnsl-2.0.0-h7f98852_0
  libpng-1.6.37-hbc83047_0
  libtasn1-4.16.0-h27cfd23_0
  libtiff-4.2.0-h3942068_0
  libunistring-0.9.10-h27cfd23_0
  libwebp-1.2.2-h55f646e_0
  libwebp-base-1.2.2-h7f8727e_0
  libzlib-1.2.11-h36c2ea0_1013
  lz4-c-1.9.3-h295c915_1
  markupsafe-2.1.0-py38h0a891b7_0
  matplotlib-base-3.5.1-py38hf4fb855_0
  mkl-service-2.4.0-py38h7f8727e_0
  mkl_fft-1.3.1-py38hd3c417c_0
  mkl_random-1.2.2-py38h51133e4_0
  munkres-1.1.4-pyh9f0ad1d_0
  nettle-3.7.3-hbbd107a_1
  networkx-2.6.3-pyhd8ed1ab_1
  numpy-1.21.2-py38h20f2e39_0
  numpy-base-1.21.2-py38h79a1101_0
  olefile-0.46-pyhd3eb1b0_0
  openh264-2.1.1-h4ff587b_0
  packaging-21.3-pyhd8ed1ab_0
  pandas-1.4.1-py38h43a58ef_0
  pillow-8.4.0-py38h5aabda8_0
  pycparser-2.21-pyhd8ed1ab_0
  pyg-2.0.3-py38_torch_1.10.0_cu113
  pyopenssl-22.0.0-pyhd8ed1ab_0
  pyparsing-3.0.7-pyhd8ed1ab_0
  pysocks-1.7.1-py38h578d9bd_4
  python-dateutil-2.8.2-pyhd8ed1ab_0
  python-louvain-0.15-pyhd8ed1ab_1
  python_abi-3.8-2_cp38
  pytorch-cluster-1.5.9-py38_torch_1.10.0_cu113
  pytorch-scatter-2.0.9-py38_torch_1.10.0_cu113
  pytorch-sparse-0.6.12-py38_torch_1.10.0_cu113
  pytorch-spline-conv-1.2.1-py38_torch_1.10.0_cu113
  pytz-2021.3-pyhd8ed1ab_0
  pyyaml-6.0-py38h497a2fe_3
  requests-2.27.1-pyhd8ed1ab_0
  scikit-learn-1.0.2-py38h1561384_0
  scipy-1.8.0-py38h56a6a73_1
  six-1.16.0-pyhd3eb1b0_1
  threadpoolctl-3.1.0-pyh8a188c0_0
  torchaudio-0.10.2-py38_cu113
  torchvision-0.11.3-py38_cu113
  tqdm-4.62.3-pyhd8ed1ab_0
  unicodedata2-14.0.0-py38h497a2fe_0
  urllib3-1.26.8-pyhd8ed1ab_1
  yacs-0.1.8-pyhd8ed1ab_0
  yaml-0.2.5-h7f98852_2
  zstd-1.4.9-haebb681_0

The following packages will be UPDATED:

  _openmp_mutex                                 conda-forge --> pkgs/main
  certifi            conda-forge::certifi-2021.10.8-py38h5~ --> pkgs/main::certifi-2021.10.8-py38h06a4308_2
  intel-openmp                       2021.4.0-h06a4308_3561 --> 2022.0.1-h06a4308_3633
  mkl                                 2021.4.0-h06a4308_640 --> 2022.0.1-h06a4308_117

The following packages will be SUPERSEDED by a higher-priority channel:

  _libgcc_mutex      conda-forge::_libgcc_mutex-0.1-conda_~ --> pkgs/main::_libgcc_mutex-0.1-main
  libffi               conda-forge::libffi-3.4.2-h7f98852_5 --> pkgs/main::libffi-3.3-he6710b0_2
  libgcc-ng          conda-forge::libgcc-ng-11.2.0-h1d223b~ --> pkgs/main::libgcc-ng-9.3.0-h5101ec6_17
  libgomp            conda-forge::libgomp-11.2.0-h1d223b6_~ --> pkgs/main::libgomp-9.3.0-h5101ec6_17
  libstdcxx-ng       conda-forge::libstdcxx-ng-11.2.0-he4d~ --> pkgs/main::libstdcxx-ng-9.3.0-hd4cf53a_17
  openssl             conda-forge::openssl-3.0.0-h7f98852_2 --> pkgs/main::openssl-1.1.1m-h7f8727e_0
  python             conda-forge::python-3.8.12-h0744224_3~ --> pkgs/main::python-3.8.12-h12debd9_0
  zlib               conda-forge::zlib-1.2.11-h36c2ea0_1013 --> pkgs/main::zlib-1.2.11-h7f8727e_4


Proceed ([y]/n)? y


Downloading and Extracting Packages
mkl-2022.0.1         | 127.7 MB  | ################################################################################################################################################### | 100% 
_openmp_mutex-4.5    | 22 KB     | ################################################################################################################################################### | 100% 
intel-openmp-2022.0. | 4.2 MB    | ################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
```

**Comment by Zethson** [comment]
Just checked again. `mamba install pyg -c pyg -c conda-forge` install the cudatoolkit.

**Comment by Zethson** [comment]
> Ok, weird. Can you also check if that is related to `mamba`? I don't see any issues with that when using `conda`.

Huh, it works when using only conda and not mamba. ?!?

**Comment by rusty1s** [comment]
Interesting. Seems like `mamba` cannot accurately resolve the existing PyTorch/CUDA environment. Not really sure what to do about this :(

**Comment by Zethson** [comment]
I will open an issue at mamba.

**Comment by jaimergp** [comment]
If you want to know more, [this issue](https://github.com/conda/conda-libmamba-solver/issues/131#issuecomment-1440745813) has further context on why this happens and what can be done from the packaging side.
