### ISSUE TITLE
Conflicts during installation

### ISSUE THREAD

**Issue by ily-R** [pyg-team/pytorch_geometric#4238]
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```
```
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8    24W / 149W |     13MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       875      G   /usr/lib/xorg/Xorg                  8MiB |
|    0   N/A  N/A      1251      G   /usr/bin/gnome-shell                3MiB |
+-----------------------------------------------------------------------------+
```
```
cat /usr/local/cuda/version.txt
CUDA Version 10.2.89
```
I tried two different installation using **conda** . I created two different environment: 

env1:
I installed pytorch using : `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`
pytroch version : 1.11.0
cudatoolkit: 10.2.89
python : 3.9.7

```
import torch
torch.cuda.is_available()
True
```
Now I try to install pyg using : `conda install pyg -c pyg -c conda-forge` 
I get a big conflict report  from conda that took 10min to be generated then the installation was aborted. The log is too big to be put here, Ill put a small portion of it:
```
Package libxml2 conflicts for:
ffmpeg -> libxml2[version='>=2.9.12,<2.10.0a0']
libidn2 -> gettext[version='>=0.19.8.1,<1.0a0'] -> libxml2[version='>=2.9.10,<2.10.0a0']
torchvision -> ffmpeg[version='>=4.2'] -> libxml2[version='>=2.9.12,<2.10.0a0']

Package lame conflicts for:
torchvision -> ffmpeg[version='>=4.2'] -> lame[version='>=3.100,<3.101.0a0']
ffmpeg -> lame[version='>=3.100,<3.101.0a0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - blas -> libgfortran-ng -> __glibc[version='>=2.17']
  - brotlipy -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - bzip2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - cffi -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - cryptography -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - cudatoolkit=10.2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - ffmpeg -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - freetype -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - giflib -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - gmp -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - gnutls -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - jpeg -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - lame -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - lcms2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
```
I realised that maybe I shouldnt have installed pytorch before since many conflicts occurred.

env2:

on a fresh environment I launched `conda install pyg -c pyg -c conda-forge` 

cudatoolkit               10.2.89             h8f6ccaa_10    conda-forge
python                    3.9.10          h85951f9_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-louvain            0.15               pyhd8ed1ab_1    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.8.1           cpu_py39h60491be_0  
pytorch-cluster           1.5.9           py39_torch_1.8.0_cu102    pyg
pytorch-scatter           2.0.8           py39_torch_1.8.0_cu102    pyg
pytorch-sparse            0.6.12          py39_torch_1.8.0_cu102    pyg
pytorch-spline-conv       1.2.1           py39_torch_1.8.0_cu102    pyg

```
import torch
torch.cuda.is_available()
False
```
```
import torch_geometric


Traceback (most recent call last):
  File "/home/ubuntu/ilyas_exp/script.py", line 2, in <module>
    import torch_geometric
  File "/home/ubuntu/miniconda/envs/gatv2/lib/python3.9/site-packages/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data
  File "/home/ubuntu/miniconda/envs/gatv2/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/ubuntu/miniconda/envs/gatv2/lib/python3.9/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor
  File "/home/ubuntu/miniconda/envs/gatv2/lib/python3.9/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/home/ubuntu/miniconda/envs/gatv2/lib/python3.9/site-packages/torch_sparse/__init__.py", line 15, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/home/ubuntu/miniconda/envs/gatv2/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/ubuntu/miniconda/envs/gatv2/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ubuntu/miniconda/envs/gatv2/lib/python3.9/site-packages/torch_sparse/_version_cpu.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
```

### Environment

* PyG version:
* PyTorch version: 
* OS: **ubuntu 20.04.2 LTS**
* Python version: **3.9.10** 
* CUDA/cuDNN version: **CUDA Version 10.2.89 / No cuDNN**
* How you installed PyTorch and PyG (`conda`, `pip`, source): **conda**
* Any other relevant information (*e.g.*, version of `torch-scatter`): **NVIDIA-SMI 460.91.03**

**Comment by rusty1s** [comment]
I am currently in the process of providing PyG packages for PyTorch 1.11 (it just got released yesterday). A simple workaround is:
```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
conda install pytorch-sparse -c pyg
pip install git+https://github.com/pyg-team/pytorch_geometric.git
```

**Comment by ily-R** [comment]
Thank you. This works
