### ISSUE TITLE
ImportError: cannot import name 'set_out_dir' from 'torch_geometric.graphgym.config' 

### ISSUE THREAD

**Issue by angup143** [pyg-team/pytorch_geometric#4367]
### 🐛 Describe the bug

When trying to run the basic graphgym example with "bash run_single.sh ", I get the following error:
```Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from torch_geometric.graphgym.config import (
ImportError: cannot import name 'set_out_dir' from 'torch_geometric.graphgym.config' (/opt/conda/lib/python3.7/site-packages/torch_geometric/graphgym/config.py)
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from torch_geometric.graphgym.config import (
ImportError: cannot import name 'set_out_dir' from 'torch_geometric.graphgym.config' (/opt/conda/lib/python3.7/site-packages/torch_geometric/graphgym/config.py)
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from torch_geometric.graphgym.config import (
ImportError: cannot import name 'set_out_dir' from 'torch_geometric.graphgym.config' (/opt/conda/lib/python3.7/site-packages/torch_geometric/graphgym/config.py)
```

I noticed that this might be caused due to a recent change (https://github.com/pyg-team/pytorch_geometric/pull/4338) so I tried updating my pytorch geometric version using`pip install torch-geometric --upgrade` but that does not fix the issue.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.10.0
* OS: Linux
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
This seems to be indeed caused by the recent changes in #4338. You would need to install PyG from master for this:
```
pip install git+https://github.com/pyg-team/pytorch_geometric.git
```

**Comment by rusty1s** [comment]
Installing PyG master should yield version `2.0.5`. Please ensure that you uninstall all other PyG versions first.

**Comment by willy20040711** [comment]
I[m also facing the same issue. 
PyG version: 2.0.4
Torch 1.11/ CUDA11.3

**Comment by rusty1s** [comment]
Using PyG from master is currently only supported through `pip`.

**Comment by qingchu123** [comment]
I have install by this
`pip install git+https://github.com/pyg-team/pytorch_geometric.git` and the  version is torch-geometric-2.0.5
but I still get this
`fyx@fyx:~/GNN/GraphGym/run$ bash run_single.sh 
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from graphgym.config import cfg, dump_cfg, load_cfg, set_run_dir, set_out_dir
ImportError: cannot import name 'set_out_dir' from 'graphgym.config' (/home/fyx/.local/lib/python3.8/site-packages/graphgym/config.py)`

**Comment by qingchu123** [comment]
ImportError: cannot import name 'set_out_dir' from 'graphgym.config'

**Comment by rusty1s** [comment]
It looks like you have https://github.com/snap-stanford/GraphGym installed rather than the version by PyG.

**Comment by qingchu123** [comment]
oh I have solved it by remove the graphgym package and run install.sh again,thank you!

**Comment by AlexCHEN-Engineer** [comment]
> oh I have solved it by remove the graphgym package and run install.sh again,thank you!

Did you finally get it to run? I use 
`$ pip install git+https://github.com/pyg-team/pytorch_geometric.git`
`$ pip install torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://data.pyg.org/whl/torch-1.11.0+cu113.html`
`$ pip install ogb, pytorch_lightning, yacs`
and git clone 
`$git clone https://github.com/pyg-team/pytorch_geometric.git`
`$cd pytorch_geometric/graphgym`
`$bash run_single.sh`
But it just doesn't work either.

**Comment by linlin0312** [comment]
> 

Hello, is there any other way to download pyg version 2.5.0? I can't by using this command: pip install git+https://github.com/pyg-team/pytorch_geometric.git

**Comment by linlin0312** [comment]
> This seems to be indeed caused by the recent changes in #4338. You would need to install PyG from master for this:
> 
> ```
> pip install git+https://github.com/pyg-team/pytorch_geometric.git
> ```

Hello, is there any other way to download pyg version 2.5.0? I can't by using this command: pip install git+https://github.com/pyg-team/pytorch_geometric.git

**Comment by rusty1s** [comment]
You can install from our nightly builds, see https://github.com/pyg-team/pytorch_geometric#nightly-and-master
