### ISSUE TITLE
All packages are installed correctly. But when i import module an error occurred

### ISSUE THREAD

**Issue by Sjp1974986104** [pyg-team/pytorch_geometric#4472]
### 🐛 Describe the bug

All packages are installed correctly. But when i import module an error occurred.

'''
import torch
from torch_geometric.data import Data
'''

'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guest/anaconda3/envs/smart_construction/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/guest/anaconda3/envs/smart_construction/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/guest/anaconda3/envs/smart_construction/lib/python3.8/site-packages/torch_geometric/data/data.py", line 9, in <module>
    from torch_sparse import SparseTensor
  File "/home/guest/anaconda3/envs/smart_construction/lib/python3.8/site-packages/torch_sparse/__init__.py", line 41, in <module>
    from .tensor import SparseTensor  # noqa
  File "/home/guest/anaconda3/envs/smart_construction/lib/python3.8/site-packages/torch_sparse/tensor.py", line 13, in <module>
    class SparseTensor(object):
  File "/home/guest/anaconda3/envs/smart_construction/lib/python3.8/site-packages/torch/jit/_script.py", line 974, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/guest/anaconda3/envs/smart_construction/lib/python3.8/site-packages/torch/jit/_script.py", line 67, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError:
Tried to access nonexistent attribute or method 'crow_indices' of type 'Tensor'.:
  File "/home/guest/anaconda3/envs/smart_construction/lib/python3.8/site-packages/torch_sparse/tensor.py", line 109
    def from_torch_sparse_csr_tensor(self, mat: torch.Tensor,
                                     has_value: bool = True):
        rowptr = mat.crow_indices()
                 ~~~~~~~~~~~~~~~~ <--- HERE
        col = mat.col_indices()

'''
Can you help me solve this problem?


### Environment

* PyG version: torch-geometric==2.0.4 
* PyTorch version:torch==1.8.1+cu111 
* OS:
* Python version:3.8.13
* CUDA/cuDNN version:cuda_11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source):pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):
torch-scatter:2.0.9 torch-cluster:1.6.0 torch-sparse  :0.6.13

**Comment by rusty1s** [comment]
For PyTorch 1.8. you need to install `torch-sparse==0.6.12`. Sorry for the inconveniences
