### ISSUE TITLE
Can't use custom hetero dataset with edge_attr.

### ISSUE THREAD

**Issue by vv19** [pyg-team/pytorch_geometric#4594]
### 🐛 Describe the bug

When using a custom hetero dataset that has edge_attr, indexing of the edges produces an error. If I don't use edge_attr or if the number of nodes for each node_type is the same, then everything works fine.

An example code that reproduces the error:
```
from torch_geometric.nn import GATv2Conv, to_hetero
from torch_geometric.data import HeteroData
import torch


class Net(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels, edge_dim=3):
        super().__init__()
        self.conv1 = GATv2Conv((-1, -1), hidden_channels, heads=1, edge_dim=edge_dim)

    def forward(self, x, edge_index, edge_attr):
        x = self.conv1(x, edge_index, edge_attr)

        return x


if __name__ == '__main__':
    data = HeteroData()

    data['v1'].x = torch.randn(size=(5, 2))
    data['v2'].x = torch.randn(size=(6, 2))
    data['v3'].x = torch.randn(size=(7, 2))

    data['v1', 'e1', 'v1'].edge_index = torch.cartesian_prod(torch.arange(data['v1'].num_nodes, dtype=torch.int64),
                                                             torch.arange(data['v1'].num_nodes, dtype=torch.int64)).t()
    data['v1', 'e1', 'v1'].edge_attr = torch.randn(size=(data['v1'].num_nodes * data['v1'].num_nodes, 3))
    data['v2', 'e2', 'v2'].edge_index = torch.cartesian_prod(torch.arange(data['v2'].num_nodes, dtype=torch.int64),
                                                             torch.arange(data['v2'].num_nodes, dtype=torch.int64)).t()
    data['v2', 'e2', 'v2'].edge_attr = torch.randn(size=(data['v2'].num_nodes * data['v2'].num_nodes, 3))
    data['v3', 'e3', 'v3'].edge_index = torch.cartesian_prod(torch.arange(data['v3'].num_nodes, dtype=torch.int64),
                                                             torch.arange(data['v3'].num_nodes, dtype=torch.int64)).t()
    data['v3', 'e3', 'v3'].edge_attr = torch.randn(size=(data['v3'].num_nodes * data['v3'].num_nodes, 3))

    data['v1', 'e4', 'v2'].edge_index = torch.cartesian_prod(torch.arange(data['v1'].num_nodes, dtype=torch.int64),
                                                             torch.arange(data['v2'].num_nodes, dtype=torch.int64)).t()
    data['v1', 'e4', 'v2'].edge_attr = torch.randn(size=(data['v1'].num_nodes * data['v2'].num_nodes, 3))

    print(data)

    model = Net(2, 2)
    model = to_hetero(model, data.metadata())

    model(data.x_dict, data.edge_index_dict, data.edge_attr_dict)
```

It gets me this error:

```
Traceback (most recent call last):
  File "graph_example.py", line 46, in <module>
    model(data.x_dict, data.edge_index_dict, data.edge_attr_dict)
  File "/home/vv19/projects/shared/venvs/venv_basic/lib/python3.8/site-packages/torch/fx/graph_module.py", line 513, in wrapped_call
    raise e.with_traceback(None)
RuntimeError: index 5 is out of bounds for dimension 0 with size 5
```

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.9.0+cu111
* OS: Ubuntu 20.04
* Python version: 3.8
* CUDA/cuDNN version: 11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
This error is currently thrown in case `GATConv` operates on a bipartite graph with `add_self_loops=True`.
```python
        self.conv1 = GATv2Conv((-1, -1), hidden_channels, heads=1,
                               edge_dim=edge_dim, add_self_loops=False)
```
fixes this issue.
