### ISSUE TITLE
Getting "RuntimeError: std::bad_alloc" when using nn.set2set

### ISSUE THREAD

**Issue by runxuanjiang** [pyg-team/pytorch_geometric#4603]
### 😵 Describe the installation problem

I have been trying to install pytorch geometric on a computing cluster but I keep running into the following issue. When I try to train a model that uses the [set2set](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.glob.Set2Set) component I get the following error:

```
Traceback (most recent call last):
  File "/home/user/conformer_generation/testspace/test.py", line 49, in <module>
    agent.run_steps()
  File "/home/user/conformer_generation/conformer-ml/src/conformer_rl/agents/base_agent.py", line 75, in run_steps
    self.step()
  File "/home/user/conformer_generation/conformer-ml/src/conformer_rl/agents/base_ac_agent.py", line 41, in step
    self._sample()
  File "/home/user/conformer_generation/conformer-ml/src/conformer_rl/agents/base_ac_agent.py", line 61, in _sample
    prediction = self.network(states)
  File "/home/user/anaconda3/envs/rl-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/conformer_generation/conformer-ml/src/conformer_rl/models/RTGN.py", line 93, in forward
    logits = self.actor(obs)
  File "/home/user/anaconda3/envs/rl-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/conformer_generation/conformer-ml/src/conformer_rl/models/RTGN.py", line 155, in forward
    pool = self.set2set(out, data.batch)
  File "/home/user/anaconda3/envs/rl-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/rl-pip/lib/python3.9/site-packages/torch_geometric/nn/glob/set2set.py", line 82, in forward
    a = softmax(e, batch, num_nodes=size)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/user/anaconda3/envs/rl-pip/lib/python3.9/site-packages/torch_geometric/utils/softmax.py", line 41, in softmax
    elif index is not None:
        N = maybe_num_nodes(index, num_nodes)
        src_max = scatter(src, index, dim, dim_size=N, reduce='max')
                  ~~~~~~~ <--- HERE
        src_max = src_max.index_select(dim, index)
        out = (src - src_max).exp()
  File "/home/user/anaconda3/envs/rl-pip/lib/python3.9/site-packages/torch_scatter/scatter.py", line 160, in scatter
        return scatter_min(src, index, dim, out, dim_size)[0]
    elif reduce == 'max':
        return scatter_max(src, index, dim, out, dim_size)[0]
               ~~~~~~~~~~~ <--- HERE
    else:
        raise ValueError
  File "/home/user/anaconda3/envs/rl-pip/lib/python3.9/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
        out: Optional[torch.Tensor] = None,
        dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: std::bad_alloc
```

The Python file and line causing this error is [here](https://github.com/ZimmermanGroup/conformer-rl/blob/alpha/src/conformer_rl/models/RTGN.py#L153) for reference.

I believe that this is an installation issue because I have been able to succesfully run this code a few months ago (before January 2022) using an older version of pytorch geometric. I have also succesfully ran the code (using the latest version of pytorch geometric) on my laptop, which is using Ubuntu.

One thing to note that might be related to this issue is that I originally tried to install both pytorch and pytorch geometric using conda using the command
```
conda install pyg -c pyg
```
but when I tried to import pytorch_geometric I got the following error: `OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found`. I think this is because the cluster is using Glibc 2.17, but since I am not an admin for the cluster I am unable to change the glibc version. I am not sure if this issue is also causing the issue when installing using pip.

Any help would be appreciated!

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: CentOS 7
* Python version: 3.9
* CUDA/cuDNN version: 10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): Using pip: I ran the following commands:
```
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.11.0+cu102.html
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.11.0+cu102.html
pip install torch-geometric
```
* Any other relevant information (*e.g.*, version of `torch-scatter`):
torch-scatter==2.0.9
torch-sparse==0.6.13

**Comment by rusty1s** [comment]
Thanks for reporting. Can you confirm that [this](https://github.com/rusty1s/pytorch_scatter#example) example works (in case both tensors are on GPU)?

Can you also try to install PyG in a fresh environment via `pip`, i.e. without `conda` and WITHOUT installing `torch-spline-conv`?
