### ISSUE TITLE
Error with heads>1 in HeteroConv - GATConv

### ISSUE THREAD

**Issue by KevinCrp** [pyg-team/pytorch_geometric#4605]
### 🐛 Describe the bug

Hi
I'm working on Heterogeneous graph and I want to test a model built with GATConv.
I use HeteroConv wrapper to do it.
When I use GatConv with heads > 1, it fails:

````python
import os.path as osp
import torch
from torch_geometric.loader import NeighborLoader
import torch_geometric.transforms as T
from torch_geometric.datasets import OGB_MAG
from torch_geometric.nn import (GATConv, HeteroConv, SAGEConv, GCNConv, Linear)

path = osp.join(osp.dirname(osp.realpath(__file__)), '../../data/OGB')
transform = T.ToUndirected(merge=True)
dataset = OGB_MAG(path, preprocess='metapath2vec', transform=transform)
data = dataset[0]

train_input_nodes = ('paper', data['paper'].train_mask)
val_input_nodes = ('paper', data['paper'].val_mask)
kwargs = {'batch_size': 16, 'num_workers': 6, 'persistent_workers': True}

train_loader = NeighborLoader(data, num_neighbors=[10] * 2, shuffle=True,
                              input_nodes=train_input_nodes, **kwargs)
val_loader = NeighborLoader(data, num_neighbors=[10] * 2,
                            input_nodes=val_input_nodes, **kwargs)

print(data)


class HeteroGNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels, num_layers):
        super().__init__()

        self.convs = torch.nn.ModuleList()
        for _ in range(num_layers):
            conv = HeteroConv({
                ('paper', 'cites', 'paper'): GCNConv(-1, hidden_channels),
                ('author', 'writes', 'paper'): SAGEConv((-1, -1), hidden_channels),
                ('paper', 'rev_writes', 'author'): GATConv((-1, -1), hidden_channels, heads=2),
            }, aggr='sum')
            self.convs.append(conv)

        self.lin = Linear(hidden_channels, out_channels)

    def forward(self, x_dict, edge_index_dict):
        for conv in self.convs:
            x_dict = conv(x_dict, edge_index_dict)
            x_dict = {key: x.relu() for key, x in x_dict.items()}
        return self.lin(x_dict['author'])


model = HeteroGNN(hidden_channels=64, out_channels=dataset.num_classes,
                  num_layers=2)


@torch.no_grad()
def init_params():
    # Initialize lazy parameters via forwarding a single batch to the model:
    batch = next(iter(train_loader))
    model(batch.x_dict, batch.edge_index_dict)


def train():
    model.train()

    total_examples = total_loss = 0
    for batch in train_loader:
        optimizer.zero_grad()
        batch_size = batch['paper'].batch_size
        out = model(batch.x_dict, batch.edge_index_dict)
        break


optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
for epoch in range(1, 2):
    loss = train()

````
And I got the following issue:
````bash
Traceback (most recent call last):
  File "./bug.py", line 79, in <module>
    loss = train()
  File "./bug.py", line 66, in train
    out = model(batch.x_dict, batch.edge_index_dict)
  File "conda_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "./bug.py", line 48, in forward
    return self.lin(x_dict['author'])
  File "conda_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "conda_env/lib/python3.9/site-packages/torch_geometric/nn/dense/linear.py", line 118, in forward
    return F.linear(x, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (507x128 and 64x349)
````

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11
* OS: Ubuntu 18
* Python version: 3.9.11
* CUDA/cuDNN version: 
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by Padarn** [comment]
I think if you set `heads=2` you want to half the `hidden_channels` input. Changing to 
```
                ('paper', 'rev_writes', 'author'): GATConv((-1, -1), hidden_channels // 2, heads=2),
```
The code runs for me.

**Comment by KevinCrp** [comment]
It runs also for me with 'hidden_channels // heads'
Thanks
