### ISSUE TITLE
Failed to run the captum_explainability.py

### ISSUE THREAD

**Issue by YOLO-jbc** [pyg-team/pytorch_geometric#4649]
### 🐛 Describe the bug

Hello!!!
I am trying to run your example `captum_explainability.py`. When it goes to 
```python
ig_attr_edge = ig.attribute(edge_mask.unsqueeze(0), target=target,
                            additional_forward_args=(data.x, data.edge_index),
                            internal_batch_size=1)
```
I got an error: `IndexError: index 1 is out of bounds for dimension 0 with size 1`

The whole error report are as follows:
```python
Traceback (most recent call last):
  File "d:/Artificial_Intelligence/project/DL/Graph defense/Bacldoor graph defense/Backdoor_graph_defense/test.py", line 56, in <module>
    ig_attr_edge = ig.attribute(edge_mask.unsqueeze(0), target=target,
  File "D:\Artificial_Intelligence\Anaconda\lib\site-packages\captum\attr\_core\integrated_gradients.py", line 278, in attribute
  File "D:\Artificial_Intelligence\Anaconda\lib\site-packages\captum\attr\_utils\common.py", line 500, in _run_forward
    output = forward_func(
  File "D:\Artificial_Intelligence\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Artificial_Intelligence\Anaconda\lib\site-packages\torch_geometric\nn\models\explainer.py", line 64, in forward
    set_masks(self.model, mask.squeeze(0), args[1],
  File "D:\Artificial_Intelligence\Anaconda\lib\site-packages\torch_geometric\nn\models\explainer.py", line 16, in set_masks
    loop_mask = edge_index[0] != edge_index[1]
IndexError: index 1 is out of bounds for dimension 0 with size 1
```
Thanks a lot! :)

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.8.1+cu111
* OS: windows
* Python version: 3.8.5
* CUDA/cuDNN version:  11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
I cannot reproduce this. Are you operating on a custom dataset? What's your Captum version?

**Comment by YOLO-jbc** [comment]
Thanks for your reply, I am using Cora dataset  by `dataset = Planetoid('./datasets', 'Cora', transform=T.NormalizeFeatures())` .
My Captum version is 0.2.0.
Concretely, my code is just the same as [code](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/captum_explainability.py)

**Comment by rusty1s** [comment]
Can you try to upgrade `captum` and test again?
```
pip install --upgrade captum
```

**Comment by YOLO-jbc** [comment]
It works!!!!  Really appreciate your help. I never thought about the Captum's version.
Wish you best life ;)
