### ISSUE TITLE
KarateClub dataset does not load 

### ISSUE THREAD

**Issue by EtienneGagnon1** [pyg-team/pytorch_geometric#4659]
### 🐛 Describe the bug

Importing the KarateClub dataset 
```python
from torch_geometric.datasets import KarateClub
dataset = KarateClub()
```

appears to yield the following error. 

```
Traceback (most recent call last):
  File "C:\Users\Gagnon\Anaconda3\envs\sandbox_dev_env\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\Gagnon\Anaconda3\envs\sandbox_dev_env\lib\site-packages\torch_geometric\datasets\karate.py", line 50, in __init__
    adj = nx.to_scipy_sparse_array(G).tocoo()
  File "C:\Users\Gagnon\Anaconda3\envs\sandbox_dev_env\lib\site-packages\networkx\convert_matrix.py", line 921, in to_scipy_sparse_array
    A = sp.sparse.coo_array((d, (r, c)), shape=(nlen, nlen), dtype=dtype)
AttributeError: module 'scipy.sparse' has no attribute 'coo_array'
```

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: windows 11
* Python version: 3.9.12
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
This issue is discussed here as well: https://github.com/pyg-team/pytorch_geometric/issues/4378

In general, it is fixable by installing PyG from nightly or master for now, see [here](https://github.com/pyg-team/pytorch_geometric#nightly-and-master).
