### ISSUE TITLE
Batch.from_data_list() internal call returning None args for Data object

### ISSUE THREAD

**Issue by cwfparsonson** [pyg-team/pytorch_geometric#4725]
### 🐛 Describe the bug

I have a `list` of objects which inherit from `torch_geometric.data.data.Data`. When I call `Batch.from_data_list()` on this list of `Data` objects, I get the following error message:

```
Traceback (most recent call last):
  File "scripts/dqn_trainer.py", line 415, in <module>
    learner.train(int(5e6)) # 5e5 100 500
  File "/home/zciccwf/phd_project/projects/retro_branching/retro_branching/src/learners/dqn_learner.py", line 2178, in train                                                                              
    self.step_optimizer(use_cer=self.use_cer)
  File "/home/zciccwf/phd_project/projects/retro_branching/retro_branching/src/learners/dqn_learner.py", line 1630, in step_optimizer                                                                     
    loss, stats = self.accumulate_gradients(use_cer)
  File "/home/zciccwf/phd_project/projects/retro_branching/retro_branching/src/learners/dqn_learner.py", line 1220, in accumulate_gradients                                                               
    state, action, reward, done, next_state, n_step_return, n_step_state, n, n_step_done, indices, importance_sampling_weights = self.buffer.sample(batch_size=self.batch_size, use_cer=use_cer, per_beta=self.get_per_beta())
  File "/home/zciccwf/phd_project/projects/retro_branching/retro_branching/src/learners/dqn_learner.py", line 641, in sample                                                                              
    return (Batch.from_data_list(state),
  File "/scratch/zciccwf/py36/envs/rlgnn/lib/python3.7/site-packages/torch_geometric/data/batch.py", line 74, in from_data_list                                                                           
    exclude_keys=exclude_keys,
  File "/scratch/zciccwf/py36/envs/rlgnn/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 32, in collate                                                                                
    out = cls(_base_cls=data_list[0].__class__)  # Dynamic inheritance.
  File "/scratch/zciccwf/py36/envs/rlgnn/lib/python3.7/site-packages/torch_geometric/data/batch.py", line 40, in __call__                                                                                 
    return super(DynamicInheritance, new_cls).__call__(*args, **kwargs)
  File "/home/zciccwf/phd_project/projects/retro_branching/retro_branching/src/learners/dqn_learner.py", line 337, in __init__                                                                            
    self.constraint_features = torch.FloatTensor(constraint_features)
TypeError: new(): data must be a sequence (got NoneType)
```

It seems that internally `Batch.from_data_list()` is trying to initialise a `Data` object from my `Data` class, but the args used to initialise `Data` seem to be `None`. 

This code previously worked with `pytorch_geometric=1.7.0` but no longer seems to work with `pytorch_geometric=2.0.4` (although I have updated other modules such as `torch`, `numpy`, etc.). It's part of a fairly large project so I'm currently working on making a minimal working example to reproduce this error and will post it here as soon as I do. In the mean time, I wanted to ask if there is any obvious quick fix.

My `Data` class is defined as:

```python
class BipartiteNodeData(torch_geometric.data.Data):
    """
    This class encode a node bipartite graph observation as returned by the `ecole.observation.NodeBipartite` 
    observation function in a format understood by the pytorch geometric data handlers.
    """
    def __init__(self, constraint_features, edge_index, edge_features, variable_features, candidates):
        super().__init__()
        self.constraint_features = torch.FloatTensor(constraint_features)
        self.edge_index = torch.LongTensor(edge_index)
        self.edge_attr = torch.from_numpy(edge_features).unsqueeze(1)
        self.variable_features = torch.FloatTensor(variable_features)
        self.candidates = torch.from_numpy(candidates).long()
        self.raw_candidates = torch.from_numpy(candidates).long()
        
        self.num_candidates = len(candidates)
        self.num_variables = self.variable_features.size(0)
        self.num_nodes = self.constraint_features.size(0) + self.variable_features.size(0)

    def __inc__(self, key, value):
        """
        We overload the pytorch geometric method that tells how to increment indices when concatenating graphs 
        for those entries (edge index, candidates) for which this is not obvious. This
        enables batching.
        """
        if key == 'edge_index':
            # constraint nodes connected via edge to variable nodes
            return torch.tensor([[self.constraint_features.size(0)], [self.variable_features.size(0)]])
        elif key == 'candidates':
            # actions are variable nodes
            return self.variable_features.size(0)
        else:
            return super().__inc__(key, value)
```

The list of initialised `Data` objects being passed to `Batch.from_data_list()` does not have any `None` values:

```
[BipartiteNodeData(constraint_features=[166, 5], edge_index=[2, 5746], edge_attr=[5746, 1], variable_features=[227, 43], candidates=[58], raw_candidates=[58], num_candidates=58, num_variables=227, num_nodes=393), BipartiteNodeData(constraint_features=[151, 5], edge_index=[2, 3818], edge_attr=[3818, 1], variable_features=[228, 43], candidates=[47], raw_candidates=[47], num_candidates=47, num_variables=228, num_nodes=379)]

```

Any help would be much appreciated!

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.10.0
* OS: CentOS 8
* Python version: 3.7.1
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): pytorch-cluster=1.6.0 pytorch-mutex=1.0 pytorch-scatter=0.6.13 pytorch-sparse=0.6.13 pytorch-spline-conv=1.2.1

**Comment by rusty1s** [comment]
I see. This is indeed a bit tricky to resolve since your `BipartiteNodeData` object requires non-optional attributes during `__init__`. A simple way to fix this is to make all of them optional:
```python
class BipartiteNodeData(torch_geometric.data.Data):
    def __init__(self, constraint_features = None, edge_index = None, edge_features = None, variable_features = None, candidates = None):
        super().__init__()
        if constraint_features is not None:
            self.constraint_features = torch.FloatTensor(constraint_features)
        ...
```

**Comment by rusty1s** [comment]
Yes, this is a breaking change in PyG 2.0 as well. Your fix is suitable :)
