### ISSUE TITLE
Cannot `torch.jit.script` a `@staticmethod`

### ISSUE THREAD

**Issue by latent-reason** [pyg-team/pytorch_geometric#4763]
### 🐛 Describe the bug

Same issue as described in https://github.com/pytorch/pytorch/issues/70047. When trying to JIT custom class using pytorch_geometric. 

```python
import torch
from torch import Tensor
from typing import Optional
from torch_geometric.nn.conv import MessagePassing

class CustomMP(MessagePassing):

    propagate_type = {'x': Tensor, 'edge_weight': Optional[Tensor] }

    def __init__(self, **kwargs):
        super(CustomMP, self).__init__(aggr="add", **kwargs)

    @torch.jit.script
    @staticmethod
    def norm(edge_index: Tensor, num_nodes: Tensor, edge_weight: Tensor):
        # calculate norm... use placeholder
        norm = Tensor([1])
        return edge_index, norm

    def forward(self, x: Tensor, edge_index: Tensor, edge_weight: Tensor):
        edge_index, norm = self.norm(edge_index, x.size(0), edge_weight)
        return self.propagate(edge_index, x=x, norm=norm)

# jit
custom = CustomMP().jittable()
torch.jit.script(custom)
```

This results in `AttributeError: 'wrapper_descriptor' object has no attribute '__globals__'`:

<details>
  <summary>Click to expand!</summary>
  
  ```Traceback (most recent call last):
  File "/deepmirror-serving/ex.py", line 6, in <module>
    class CustomMP(MessagePassing):
  File "/deepmirror-serving/ex.py", line 15, in CustomMP
    def norm(edge_index: Tensor, num_nodes: Tensor, edge_weight: Tensor):
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_script.py", line 1318, in script
    return torch.jit._recursive.create_script_class(obj)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 417, in create_script_class
    rcb = _jit_internal.createResolutionCallbackForClassMethods(type(obj))
  File "/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py", line 394, in createResolutionCallbackForClassMethods
    captures.update(get_closure(fn))
  File "/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py", line 168, in get_closure
    captures.update(fn.__globals__)
AttributeError: 'wrapper_descriptor' object has no attribute '__globals__'
  ```
</details>

### Environment

* PyG version: `>>> print(torch_geometric.__version__)
2.0.4`
* PyTorch version: `>>> print(torch.__version__)
1.10.0`
* OS: Linux
* Python version: `Python 3.7.11`
* CUDA/cuDNN version: cu111
* How you installed PyTorch and PyG (`conda`, `pip`, source): Dockerfile (`pytorch/pytorch:1.9.1-cuda11.1-cudnn8-runtime`) via pip install PyG
* Any other relevant information (*e.g.*, version of `torch-scatter`): `torch-scatter, torch-sparse, torch-cluster, torch-spline-conv, torch-geometric` on `cu111`

**Comment by rusty1s** [comment]
Thanks for reporting. It looks like this is nothing we can fix on our side. How about simply adding this method without the `@staticmethod` decorator?
