### ISSUE TITLE
download QM9 dataset

### ISSUE THREAD

**Issue by SyounenZ** [pyg-team/pytorch_geometric#4770]
### 🐛 Describe the bug

code:
`from torch_geometric.datasets import QM9 `
`path = './dataset/QM9'`
`dataset = QM9(path)`

bug:
Downloading https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/molnet_publish/qm9.zip
Extracting dataset\QM9\raw\qm9.zip
Downloading https://ndownloader.figshare.com/files/3195404
Traceback (most recent call last):
  File "D:\anaconda\envs\py37\lib\urllib\request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "D:\anaconda\envs\py37\lib\http\client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\anaconda\envs\py37\lib\http\client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\anaconda\envs\py37\lib\http\client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\anaconda\envs\py37\lib\http\client.py", line 1036, in _send_output
    self.send(msg)
  File "D:\anaconda\envs\py37\lib\http\client.py", line 976, in send
    self.connect()
  File "D:\anaconda\envs\py37\lib\http\client.py", line 1443, in connect
    super().connect()
  File "D:\anaconda\envs\py37\lib\http\client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "D:\anaconda\envs\py37\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "D:\anaconda\envs\py37\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Remtan/Desktop/postgraduated/GNN/test.py", line 6, in <module>
    dataset = QM9(path)
  File "D:\anaconda\envs\py37\lib\site-packages\torch_geometric\datasets\qm9.py", line 135, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "D:\anaconda\envs\py37\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 56, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "D:\anaconda\envs\py37\lib\site-packages\torch_geometric\data\dataset.py", line 84, in __init__
    self._download()
  File "D:\anaconda\envs\py37\lib\site-packages\torch_geometric\data\dataset.py", line 145, in _download
    self.download()
  File "D:\anaconda\envs\py37\lib\site-packages\torch_geometric\datasets\qm9.py", line 172, in download
    file_path = download_url(self.raw_url2, self.raw_dir)
  File "D:\anaconda\envs\py37\lib\site-packages\torch_geometric\data\download.py", line 34, in download_url
    data = urllib.request.urlopen(url, context=context)
  File "D:\anaconda\envs\py37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\anaconda\envs\py37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\anaconda\envs\py37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "D:\anaconda\envs\py37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\anaconda\envs\py37\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "D:\anaconda\envs\py37\lib\urllib\request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Process finished with exit code 1

maybe i cannot get in https://ndownloader.figshare.com/files/3195404
I really want to solve this bug,
and i also want to know what `rdkit` do in QM9 dataset.
Thanks！

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: Win11
* Python version: 3.7.13
* CUDA/cuDNN version: cu11.3 cuDNN8.0
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):
* rdkit: 2020.09.1.0

**Comment by rusty1s** [comment]
This is weird, downloading works for me. Does manually downloading https://ndownloader.figshare.com/files/3195404 works? You could then just move this file to `./dataset/QM9/raw/uncharacterized.txt`.

**Comment by SyounenZ** [comment]
thanks for replying so fast.
i can't get in https://ndownloader.figshare.com/files/3195404.
and i also want to know what `rdkit` do to QM9 dataset.





------------------&nbsp;Original message&nbsp;------------------
From: "Matthias Fey"; 
Sendtime: Monday, Jun 6, 2022 4:01 PM
To: "pyg-team/pytorch_geometric"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [pyg-team/pytorch_geometric] download QM9 dataset (Issue #4770)





 
This is weird, downloading works for me. Does manually downloading https://ndownloader.figshare.com/files/3195404 works? You could then just move this file to ./dataset/QM9/raw/uncharacterized.txt.

**Comment by rusty1s** [comment]
If `rdkit` is installed, we use it to process the raw data. Otherwise, we will load the pre-processed data directly. If you cannot access it, you can consider temporarily disabling `rdkit` such that the pre-processed data is used.

**Comment by SyounenZ** [comment]
i check the raw data of QM9 from the file named `gdb9.sdf`, find that each node feature has three coordinates.
So how to adds them to each node feature.
Thanks!

**Comment by rusty1s** [comment]
The coordinates are already present in `data.pos`. You can add them to the node features via
```python
x = torch.cat([data.x, data.pos], dim=-1)
```

**Comment by Mirza-PU** [comment]
Removed existing 'data/QM9' directory to force fresh download.
Downloading https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/molnet_publish/qm9.zip
Extracting data/QM9/raw/qm9.zip
Downloading https://ndownloader.figshare.com/files/3195404
Processing...
  4%|▎         | 4805/133885 [00:07<03:10, 677.15it/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_10597/1934167611.py in <cell line: 0>()
     34     print("Removed existing 'data/QM9' directory to force fresh download.")
     35 
---> 36 dataset = QM9(root="data/QM9")
     37 num_mols = len(dataset)
     38 print(f"Total molecules in QM9: {num_mols}")

4 frames/usr/local/lib/python3.12/dist-packages/torch_geometric/datasets/qm9.py in __init__(self, root, transform, pre_transform, pre_filter, force_reload)
    152         force_reload: bool = False,
    153     ) -> None:
--> 154         super().__init__(root, transform, pre_transform, pre_filter,
    155                          force_reload=force_reload)
    156         self.load(self.processed_paths[0])

/usr/local/lib/python3.12/dist-packages/torch_geometric/data/in_memory_dataset.py in __init__(self, root, transform, pre_transform, pre_filter, log, force_reload)
     79         force_reload: bool = False,
     80     ) -> None:
---> 81         super().__init__(root, transform, pre_transform, pre_filter, log,
     82                          force_reload)
     83 

/usr/local/lib/python3.12/dist-packages/torch_geometric/data/dataset.py in __init__(self, root, transform, pre_transform, pre_filter, log, force_reload)
    113 
    114         if self.has_process:
--> 115             self._process()
    116 
    117     def indices(self) -> Sequence:

/usr/local/lib/python3.12/dist-packages/torch_geometric/data/dataset.py in _process(self)
    263 
    264         fs.makedirs(self.processed_dir, exist_ok=True)
--> 265         self.process()
    266 
    267         path = osp.join(self.processed_dir, 'pre_transform.pt')

/usr/local/lib/python3.12/dist-packages/torch_geometric/datasets/qm9.py in process(self)
    247                 continue
    248 
--> 249             N = mol.GetNumAtoms()
    250 
    251             conf = mol.GetConformer()

AttributeError: 'NoneType' object has no attribute 'GetNumAtoms'


Facing this error, kindly help to solve
