### ISSUE TITLE
Dataloader get wrong batch size of graphs

### ISSUE THREAD

**Issue by JueXiuHuang** [pyg-team/pytorch_geometric#4783]
### 🐛 Describe the bug

I'm trying to calculate the attention between graph and sequences (text). But I found that when I set batch_size to 4, in one batch it will only take 3 graph into batch, and all other batches take 4 (or just like the number of the sequences).

Below is my code and I simplify some unrelated part.

```
class Model():
    def __init__(self):
        self.embedding = nn.Embedding(50000, 768)
        self.gat = GATConv(200, 200, heads=2, dropout=0.2, edge_dim=200,
                           concat=False, add_self_loops=False)
        self.linear1 = nn.Linear(200, 1024)
        self.linear2 = nn.Linear(1024, 200)
        self.cross_attn = nn.MultiheadAttention(embed_dim=768,
                                                num_heads=2,
                                                kdim=200,
                                                vdim=200,
                                                batch_first=True)

    def forward(self, srcidx, graph):
        src = self.embedding(srcidx)
        graph.x = self.gat(graph.x, graph.edge_index, graph.edge_attr)
        graph.x = self.linear1(graph.x)
        graph.x = F.relu(graph.x)
        graph.x = self.linear2(graph.x)
        graph.x = F.relu(graph.x)
        # graph.x.shape >>> torch.Size([1080, 200])
        # src.shape >>> torch.Size([4, 128, 768])

        dbx, _ = torch_geometric.utils.to_dense_batch(graph.x, batch=graph.batch)
        # dbx.shape >>> torch.Size([3, 605, 200])
        attn_out = self.cross_attn(src, dbx, dbx, need_weights=False)[0]
        
        return src

for bid, (graph, text) in enumerate(zip(trainloader_g, trainloader_t)):
    srcidx = text['srcidx'].to(device)
    graph = graph.to(device)
    logits = model(srcidx, graph)
```

below is the error message:

> Traceback (most recent call last):
>   File "main.py", line 455, in <module>
>     logits = model(graph, srcidx, srcmsk, tgtidx[:, :-1], tgtmsk[:, :-1])
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "main.py", line 333, in forward
>     src = self.kae(src, dbx)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "main.py", line 291, in forward
>     attn_out = self.cross_attn(src, x, x, need_weights=False)[0]
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 1001, in forward
>     v_proj_weight=self.v_proj_weight)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 5044, in multi_head_attention_forward
>     k = k.contiguous().view(k.shape[0], bsz * num_heads, head_dim).transpose(0, 1)
> RuntimeError: shape '[605, 8, 384]' is invalid for input of size 1393920

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.10.0
* OS: Linux
* Python version: 1.10.0
* CUDA/cuDNN version: cuda11.3-cudnn8
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by JueXiuHuang** [comment]
I found that this might because I didnt set batch_size to to_dense_batch, after giving the argument, the error disappear. But the implementation of to_dense_batch has below code:
```
if batch_size is None:
    batch_size = int(batch.max()) + 1
```
I did give batch argument, so the program should execute this part. So here is the same question, if dataload did select #batch_size graphs, why `int(batch.max()) + 1` is less than #batch_size? or the dataload didnt pick #batch_size graphs into batch? why?

**Comment by JueXiuHuang** [comment]
I check the padding mask returned by to_dense_batch(), and found that the missing part are all paddings, so dataloader didnt pick #batch_size graphs into batch.
