### ISSUE TITLE
CUDA error: an illegal memory access - possible PyTorch Geometric bug

### ISSUE THREAD

**Issue by j-adamczyk** [pyg-team/pytorch_geometric#4811]
### 🐛 Describe the bug

I have opened a bug issue at PyTorch repo: https://github.com/pytorch/pytorch/issues/79603. The error is about `GIN` model in PyTorch Geometric, but also happens for other models:
```
import pytorch_geometric.nn as pyg_nn

model = pyg_nn.GIN(512, 512, num_layers=5, jk="LSTM")
```

Error:
```
Traceback (most recent call last):
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\main_gnn.py", line 81, in <module>
    best_params, test_metrics = perform_experiment(
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\main_gnn.py", line 23, in perform_experiment
    train_results: optuna.Study = optimize_and_train(
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\gnn\training.py", line 247, in optimize_and_train
    study.optimize(objective, n_trials=n_hyperparam_trials)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\study.py", line 400, in optimize
    _optimize(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 264, in _run_trial
    raise func_err
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\gnn\training.py", line 222, in objective
    trainer.fit(model, datamodule=data_module)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 738, in _call_and_handle_interrupt
    self._teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1300, in _teardown
    self.strategy.teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\single_device.py", line 93, in teardown
    super().teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 444, in teardown
    optimizers_to_device(self.optimizers, torch.device("cpu"))
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\optimizer.py", line 27, in optimizers_to_device
    optimizer_to_device(opt, device)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\optimizer.py", line 33, in optimizer_to_device
    optimizer.state[p] = apply_to_collection(v, torch.Tensor, move_data_to_device, device)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 107, in apply_to_collection
    v = apply_to_collection(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 354, in move_data_to_device
    return apply_to_collection(batch, dtype=dtype, function=batch_to)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 347, in batch_to
    data_output = data.to(device, **kwargs)
RuntimeError: CUDA error: an illegal memory access was encountered
```

When I run with `CUDA_LAUNCH_BLOCKING=1`, I get:
```
Trial 0 failed because of the following error: RuntimeError('CUDA error: unspecified launch failure')
Traceback (most recent call last):
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1234, in _run
    results = self._run_stage()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1351, in _run_train
    self.fit_loop.run()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 268, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 203, in advance
    result = self._run_optimization(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 369, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1593, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\core\lightning.py", line 1644, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\core\optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 155, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\torch\optim\optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\torch\optim\adam.py", line 100, in step
    loss = closure()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 140, in _wrap_closure
    closure_result = closure()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 143, in closure
    self._backward_fn(step_output.closure_loss)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 311, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 168, in backward
    self.precision_plugin.backward(self.lightning_module, closure_loss, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 80, in backward
    model.backward(closure_loss, optimizer, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\core\lightning.py", line 1389, in backward
    loss.backward(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\torch\_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: unspecified launch failure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\gnn\training.py", line 222, in objective
    trainer.fit(model, datamodule=data_module)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 736, in _call_and_handle_interrupt
    self._teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1298, in _teardown
    self.strategy.teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\single_device.py", line 93, in teardown
    super().teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 444, in teardown
    optimizers_to_device(self.optimizers, torch.device("cpu"))
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\optimizer.py", line 27, in optimizers_to_device
    optimizer_to_device(opt, device)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\optimizer.py", line 33, in optimizer_to_device
    optimizer.state[p] = apply_to_collection(v, torch.Tensor, move_data_to_device, device)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 107, in apply_to_collection
    v = apply_to_collection(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 354, in move_data_to_device
    return apply_to_collection(batch, dtype=dtype, function=batch_to)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 347, in batch_to
    data_output = data.to(device, **kwargs)
RuntimeError: CUDA error: unspecified launch failure
Traceback (most recent call last):
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1234, in _run
    results = self._run_stage()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1351, in _run_train
    self.fit_loop.run()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 268, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 203, in advance
    result = self._run_optimization(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 369, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1593, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\core\lightning.py", line 1644, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\core\optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 155, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\torch\optim\optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\torch\optim\adam.py", line 100, in step
    loss = closure()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 140, in _wrap_closure
    closure_result = closure()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 143, in closure
    self._backward_fn(step_output.closure_loss)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 311, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 168, in backward
    self.precision_plugin.backward(self.lightning_module, closure_loss, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 80, in backward
    model.backward(closure_loss, optimizer, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\core\lightning.py", line 1389, in backward
    loss.backward(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\torch\_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: unspecified launch failure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\main_gnn.py", line 84, in <module>
    best_params, test_metrics = perform_experiment(
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\main_gnn.py", line 26, in perform_experiment
    train_results: optuna.Study = optimize_and_train(
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\gnn\training.py", line 247, in optimize_and_train
    study.optimize(objective, n_trials=n_hyperparam_trials)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\study.py", line 400, in optimize
    _optimize(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 264, in _run_trial
    raise func_err
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\gnn\training.py", line 222, in objective
    trainer.fit(model, datamodule=data_module)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 736, in _call_and_handle_interrupt
    self._teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1298, in _teardown
    self.strategy.teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\single_device.py", line 93, in teardown
    super().teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 444, in teardown
    optimizers_to_device(self.optimizers, torch.device("cpu"))
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\optimizer.py", line 27, in optimizers_to_device
    optimizer_to_device(opt, device)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\optimizer.py", line 33, in optimizer_to_device
    optimizer.state[p] = apply_to_collection(v, torch.Tensor, move_data_to_device, device)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 107, in apply_to_collection
    v = apply_to_collection(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 354, in move_data_to_device
    return apply_to_collection(batch, dtype=dtype, function=batch_to)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 347, in batch_to
    data_output = data.to(device, **kwargs)
RuntimeError: CUDA error: unspecified launch failure
```

I checked other models and problem persists for many models and many JK options, not only LSTM. Can this be a Pytorch Geometric problem, rather than PyTorch? All of this works on GTX 1666 Ti without any problems, using exactly the same version of Python, PyTorch, CUDA and CuDNN.

### Environment

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 511.79
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.6.4
[pip3] torch==1.11.0
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.0.4
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torch-spline-conv==1.2.1
[pip3] torchmetrics==0.9.1
[conda] blas 1.0 mkl
[conda] cudatoolkit 11.3.1 h59b6b97_2
[conda] mkl 2021.4.0 haa95532_640
[conda] mkl-service 2.4.0 py310h2bbff1b_0
[conda] mkl_fft 1.3.1 py310ha0764ea_0
[conda] mkl_random 1.2.2 py310h4ed8f06_0
[conda] numpy 1.22.3 py310h6d2d95c_0
[conda] numpy-base 1.22.3 py310h206c741_0
[conda] pyg 2.0.4 py310_torch_1.11.0_cu113 pyg
[conda] pytorch 1.11.0 py3.10_cuda11.3_cudnn8_0 pytorch
[conda] pytorch-cluster 1.6.0 py310_torch_1.11.0_cu113 pyg
[conda] pytorch-lightning 1.6.4 pypi_0 pypi
[conda] pytorch-mutex 1.0 cuda pytorch
[conda] pytorch-scatter 2.0.9 py310_torch_1.11.0_cu113 pyg
[conda] pytorch-sparse 0.6.13 py310_torch_1.11.0_cu113 pyg
[conda] pytorch-spline-conv 1.2.1 py310_torch_1.11.0_cu113 pyg
[conda] torchmetrics 0.9.1 pypi_0 pypi

**Comment by j-adamczyk** [comment]
Update: I only get errors on JK models

**Comment by rusty1s** [comment]
Do you have a minimal example to reproduce?

**Comment by j-adamczyk** [comment]
It was not a PyTorch Geometric problem after all, closing the issue.
