### ISSUE TITLE
multiprocessing/connection.py exceptions while training

### ISSUE THREAD

**Issue by davodogster** [pyg-team/pytorch_geometric#4860]
### 🐛 Describe the bug

Hi guys, I face this error below while training various models. It still trains after the error but I am wondering what might cause it.

```
Exception ignored in: <function _ConnectionBase.__del__ at 0x7f3b7a28cca0>
Traceback (most recent call last):
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 137, in __del__
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f3b7a00d550>
Traceback (most recent call last):
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
Traceback (most recent call last):
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
Traceback (most recent call last):
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/queues.py", line 241, in _feed
    close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
OSError: [Errno 9] Bad file descriptor
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 182, in close
    self._close()
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
  File "/home/scion.local/davidsos/anaconda3/envs/pyg/lib/python3.9/multiprocessing/connection.py", line 366, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
OSError: [Errno 9] Bad file descriptor
OSError: [Errno 9] Bad file descriptor
OSError: [Errno 9] Bad file descriptor
OSError: [Errno 9] Bad file descriptor
```

Thanks, Sam

### Environment

Env:

Python: 3.9.7
Torch: 1.10.0
Ubuntu: 20.04
CUDA: 11.3.1
PyG: 2.0.3

**Comment by rusty1s** [comment]
Two things:
* Can you upgrade to latest PyG and see if this already fixes these issues?
* Which scripts/examples did you run for this?

**Comment by davodogster** [comment]
@rusty1s I ran conda update pyg and it updated the packages but when I run torch_geometric.__version__ it still says 2.0.3. I just train a PointNet OR a GraphNN or A GCN and they all give the same warning/error when training but they continue training after.

**Comment by rusty1s** [comment]
Is it possible for you to run that in a fresh environment and confirm that it is working on 2.0.4? If you run `conda update pyg` but the version is still `2.0.3` there is likely something unexpected going on in your environment (e.g., duplicated PyG versions via `pip` and `conda`, etc).

**Comment by tommasogiannantonio** [comment]
Hi, is there any update on this? I seem to be getting the same issue in 2.1.0.

**Comment by rusty1s** [comment]
There's no update on that since we couldn't reproduce it yet on our end. Do you can help us track this down with a small toy example?
