### ISSUE TITLE
  ImportError of import torch_scatter.scatter_cpu

### ISSUE THREAD

**Issue by jiaruHithub** [pyg-team/pytorch_geometric#4902]
### 😵 Describe the installation problem

When I run the code of GPT-GNN, It report that

```
Traceback (most recent call last):
  File "finetune_OAG_PF.py", line 3, in <module>
    from GPT_GNN.model import *
  File "/home/DYT/GPTuning/GPT-GNN/example_OAG/GPT_GNN/model.py", line 1, in <module>
    from .conv import *
  File "/home/DYT/GPTuning/GPT-GNN/example_OAG/GPT_GNN/conv.py", line 5, in <module>
    from torch_geometric.nn import GCNConv, GATConv, RGCNConv
  File "/home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "/home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: /home/chenliyi/anaconda3/envs/pygt1.5/lib/python3.6/site-packages/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
```

Is there any method to fix it?
thank you!

### Environment

* PyG version: 1.3.2
* PyTorch version: 1.5.0
* OS: ubuntu18.04
* Python version: 3.6.13
* CUDA/cuDNN version: 10.22 7605
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip 
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch-scatter==1.3.2
torch-cluster==1.4.5
torch-sparse==0.4.3
torch-spline-conv==1.1.1
torch-geometric==1.3.2

**Comment by rusty1s** [comment]
Can you share information about installation logs? There also are wheels available for pyTorch 1.5.0 which should simplify installation, see [here](https://data.pyg.org/whl/index.html).
