### ISSUE TITLE
ModuleNotFoundError: No module named 'class_resolver'

### ISSUE THREAD

**Issue by ewroginek** [pyg-team/pytorch_geometric#5035]
### 🐛 Describe the bug

In the examples folder, running _dgcnn_classification.py_ and/or _pointnet2_classification.py_ produces the following error:

```
Traceback (most recent call last):
  File "~/pytorch_geometric/examples/pointnet2_classification.py", line 98, in <module>
    model = Net().to(device)
  File "~/pytorch_geometric/examples/pointnet2_classification.py", line 48, in __init__
    self.sa1_module = SAModule(0.5, 0.2, MLP([3, 64, 64, 128]))
  File "~/.conda/envs/MCB/lib/python3.10/site-packages/torch_geometric/nn/models/mlp.py", line 83, in __init__
    from class_resolver.contrib.torch import activation_resolver
ModuleNotFoundError: No module named 'class_resolver'
```

I think this might be a new bug that emerged recently since the last few weeks

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.12.0
* OS: Mac
* Python version: 3.10.4
* CUDA/cuDNN version: 11.3/8.3.2_0
* How you installed PyTorch and PyG (`conda`, `pip`, source): 
* `conda install pytorch torchvision -c pytorch`
* `pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric` 
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch-cluster 1.6.0, torch-scatter 2.0.9, torch-sparse 0.6.14, torchvision 0.13.0

**Comment by rusty1s** [comment]
The `class-resolver` is an optional dependency in 2.0.4 (and dropped completely in master right now). You can fix the issue by just running `pip install class-resolver`.
