### ISSUE TITLE
OSError: libcusparse.so.10

### ISSUE THREAD

**Issue by faziii0** [pyg-team/pytorch_geometric#5218]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "/home/fazal/anaconda3/envs/dev3/lib/python3.6/site-packages/torch_sparse/__init__.py", line 15, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/fazal/anaconda3/envs/dev3/lib/python3.6/site-packages/torch/_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "/home/fazal/anaconda3/envs/dev3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "track_gnn.py", line 20, in <module>
    from tracker.multitracker import GNNTracker
  File "/home/fazal/Downloads/MOT/GSDT-main/src/lib/tracker/multitracker.py", line 8, in <module>
    from models.model import create_model, load_model
  File "/home/fazal/Downloads/MOT/GSDT-main/src/lib/models/model.py", line 9, in <module>
    from .networks.pose_dla_dcn import get_pose_net_with_gnn as get_dla_dcn_gnn
  File "/home/fazal/Downloads/MOT/GSDT-main/src/lib/models/networks/pose_dla_dcn.py", line 14, in <module>
    from torch_geometric.nn import GATConv, GraphConv, GCNConv, AGNNConv, EdgeConv
  File "/home/fazal/anaconda3/envs/dev3/lib/python3.6/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/fazal/anaconda3/envs/dev3/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/fazal/anaconda3/envs/dev3/lib/python3.6/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/home/fazal/anaconda3/envs/dev3/lib/python3.6/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/home/fazal/anaconda3/envs/dev3/lib/python3.6/site-packages/torch_sparse/__init__.py", line 23, in <module>
    raise OSError(e)
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory

### Environment

* PyG version:
* PyTorch version:1.4
* OS: 22.04 lts
* Python version: 3.6
* CUDA/cuDNN version: 10.1
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`): i have tried many different solution but cannot slove this problem. i am working on this code https://github.com/yongxinw/GSDT

**Comment by rusty1s** [comment]
Can you share some more information about how you tried to install PyG? I am seeing that you are using PyTorch 1.4.0 on CUDA 10.1, so it might be best to directly install from wheels using this link: https://data.pyg.org/whl/torch-1.4.0%2Bcu101.html. Note that you may need to specify older versions for `torch-sparse`, `torch-scatter`, etc.

**Comment by faziii0** [comment]
CUDA=$1
pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.4.0+${CUDA}z.html
pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.4.0+${CUDA}.html
pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-1.4.0+${CUDA}.html
pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.4.0+${CUDA}.html
pip install torch-geometric

i use these commands

**Comment by rusty1s** [comment]
Try
```
pip install --no-index torch-scatter==2.0.4 torch-sparse==0.5.1 torch-cluster==1.5.2 torch-spline-conv==1.2.0 -f https://pytorch-geometric.com/whl/torch-1.4.0+cu101.html
```

**Comment by faziii0** [comment]
I have tried but got the same error



Traceback (most recent call last):
  File "/home/fazal/anaconda3/envs/dev/lib/python3.6/site-packages/torch_sparse/__init__.py", line 13, in <module>
    '_version', [osp.dirname(__file__)]).origin)
  File "/home/fazal/anaconda3/envs/dev/lib/python3.6/site-packages/torch/_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "/home/fazal/anaconda3/envs/dev/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "track_gnn.py", line 20, in <module>
    from tracker.multitracker import GNNTracker
  File "/home/fazal/Downloads/MOT/GSDT-main/src/lib/tracker/multitracker.py", line 8, in <module>
    from models.model import create_model, load_model
  File "/home/fazal/Downloads/MOT/GSDT-main/src/lib/models/model.py", line 9, in <module>
    from .networks.pose_dla_dcn import get_pose_net_with_gnn as get_dla_dcn_gnn
  File "/home/fazal/Downloads/MOT/GSDT-main/src/lib/models/networks/pose_dla_dcn.py", line 14, in <module>
    from torch_geometric.nn import GATConv, GraphConv, GCNConv, AGNNConv, EdgeConv
  File "/home/fazal/anaconda3/envs/dev/lib/python3.6/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/fazal/anaconda3/envs/dev/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/fazal/anaconda3/envs/dev/lib/python3.6/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/home/fazal/anaconda3/envs/dev/lib/python3.6/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/home/fazal/anaconda3/envs/dev/lib/python3.6/site-packages/torch_sparse/__init__.py", line 22, in <module>
    raise OSError(e)
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory

**Comment by rusty1s** [comment]
I am sorry to hear. Are you sure that `nvcc --version` refers to CUDA 10? Does `libcusparse.so.10` exist in `/usr/local/cuda/lib`?

**Comment by faziii0** [comment]
libcusparse.so.10.3.0.243
libcusparse.so.10

yes found those two

**Comment by rusty1s** [comment]
Super, can you add the root directory of these two files to the `LD_LIBRARY_PATH` environment variable?

**Comment by faziii0** [comment]
in the virtual env or from home dir. Can you guide me little bit how can i do it.
thanks

**Comment by rusty1s** [comment]
This would something like this
```
export LD_LIBRARY_PATH=/usr/local/cuda/lib:$LD_LIBRARY_PATH
```
Note that you may adjust the path dependent on your CUDA installation. After that, `libcusparse.so.10` should be picked up correctly.
