### ISSUE TITLE
Could not find module '_version_cpu' in c:\Users\.conda\envs\env3\lib\site-packages\torch_sparse

### ISSUE THREAD

**Issue by 1AngelUS** [pyg-team/pytorch_geometric#5301]
### 😵 Describe the installation problem

I am trying to install pytorch-geometric for my project. I have installed 
**python**==3.7.13
**pytorch**==1.12.1+cu113
**torch-scatter** : pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --trusted-host download.pytorch.org --trusted-host data.pyg.org --verbose --no-cache-dir torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
**torch-sparse** : pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --trusted-host download.pytorch.org --trusted-host data.pyg.org --verbose --no-cache-dir torch-scatter==0.6.15 -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
**torch-geometric**: pip install torch-geometric
But I am import the torch-geometric, I am getting the following error:
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp\2\ipykernel_33204\1307000670.py in <module>
      1 import torch
----> 2 import torch_geometric

c:\Users\.conda\envs\env3\lib\site-packages\torch_geometric\__init__.py in <module>
      2 from importlib import import_module
      3 
----> 4 import torch_geometric.data
      5 import torch_geometric.loader
      6 import torch_geometric.transforms

c:\Users\.conda\envs\env3\lib\site-packages\torch_geometric\data\__init__.py in <module>
----> 1 from .data import Data
      2 from .hetero_data import HeteroData
      3 from .temporal import TemporalData
      4 from .batch import Batch
      5 from .dataset import Dataset

c:\Users\.conda\envs\env3\lib\site-packages\torch_geometric\data\data.py in <module>
     18 import torch
     19 from torch import Tensor
---> 20 from torch_sparse import SparseTensor
21 
...
---> 21         raise ImportError(f"Could not find module '{library}_cpu' in "
     22                           f"{osp.dirname(__file__)}")
     23 

**ImportError: Could not find module '_version_cpu' in c:\Users\.conda\envs\env3\lib\site-packages\torch_sparse**

**This is the complete list:**
**conda env export**
name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.1=py37h2bbff1b_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.12=py37_0
  - anaconda=2022.05=py37_0
  - anaconda-client=1.9.0=py37haa95532_0
  - anaconda-project=0.10.2=pyhd3eb1b0_0
  - anyio=3.5.0=py37haa95532_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h2bbff1b_0
  - arrow=1.2.2=pyhd3eb1b0_0
  - astroid=2.6.6=py37haa95532_0
  - astropy=4.3.1=py37hc7d831d_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - asynctest=0.13.0=py_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py37he774522_0
  - beautifulsoup4=4.11.1=py37haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bitarray=2.4.1=py37h2bbff1b_0
  - bkcharts=0.2=py37_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h19a0ad4_0
  - bokeh=2.4.2=py37haa95532_0
  - boto3=1.21.32=pyhd3eb1b0_0
  - botocore=1.24.32=pyhd3eb1b0_0
  - bottleneck=1.3.4=py37h080aedc_0
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.3.29=haa95532_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.10.8=py37haa95532_2
  - cffi=1.15.0=py37h2bbff1b_1
  - cfitsio=3.470=he774522_6
  - chardet=4.0.0=py37haa95532_1003
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py37haa95532_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py37_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - colorcet=2.0.6=pyhd3eb1b0_0
  - comtypes=1.1.10=py37haa95532_1002
  - conda=4.14.0=py37haa95532_0
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.8.1=py37h8cc25b3_0
  - conda-token=0.3.0=pyhd3eb1b0_0
  - console_shortcut=0.1.1=4
  - constantly=15.1.0=py37h28b3542_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=3.4.8=py37h71e12ea_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - curl=7.82.0=h2bbff1b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.28=py37hd77b12b_0
  - cytoolz=0.11.0=py37he774522_0
  - daal4py=2021.5.0=py37h8cb3d55_0
  - dal=2021.5.0=haa95532_796
  - dask=2021.10.0=pyhd3eb1b0_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - datashader=0.13.0=pyhd3eb1b0_1
  - datashape=0.5.4=py37haa95532_1
  - debugpy=1.5.1=py37hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - distributed=2021.10.0=py37haa95532_0
  - docutils=0.17.1=py37haa95532_1
  - entrypoints=0.4=py37haa95532_0
  - et_xmlfile=1.1.0=py37haa95532_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - frozenlist=1.2.0=py37h2bbff1b_0
  - fsspec=2022.2.0=pyhd3eb1b0_0
  - future=0.18.2=py37_1
  - gensim=4.1.2=py37hd77b12b_0
  - giflib=5.2.1=h62dcd97_0
  - glob2=0.7=pyhd3eb1b0_0
  - google-api-core=1.25.1=pyhd3eb1b0_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-cloud-core=1.7.1=pyhd3eb1b0_0
  - google-cloud-storage=1.41.0=pyhd3eb1b0_0
  - google-crc32c=1.1.2=py37h2bbff1b_0
  - google-resumable-media=1.3.1=pyhd3eb1b0_1
  - googleapis-common-protos=1.53.0=py37h2eaa2aa_0
  - greenlet=1.1.1=py37hd77b12b_0
  - grpcio=1.42.0=py37hc60d5dd_0
  - h5py=2.10.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.14.8=pyhd3eb1b0_0
  - hvplot=0.7.3=pyhd3eb1b0_1
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=3.3=pyhd3eb1b0_0
  - imagecodecs=2021.8.26=py37ha1f97ea_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py37haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py37haa95532_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.5=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.9.1=py37haa95532_0
  - ipython=7.31.1=py37haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.18.1=py37haa95532_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_0
  - jq=1.6=haa95532_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.4.0=py37haa95532_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py37haa95532_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyring=23.4.0=py37haa95532_0
  - kiwisolver=1.3.2=py37hd77b12b_0
  - lazy-object-proxy=1.6.0=py37h2bbff1b_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libarchive=3.4.2=h5e25573_0
  - libcrc32c=1.1.1=ha925a31_2
  - libcurl=7.82.0=h86230a5_0
  - libdeflate=1.8=h2bbff1b_5
  - libiconv=1.16=h2bbff1b_2
  - liblief=0.11.5=hd77b12b_1
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.19.1=h23ce68f_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libssh2=1.10.0=hcd4344a_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.44.2=h8ffe710_0
  - libwebp=1.2.2=h2bbff1b_0
  - libxml2=2.9.12=h0ad7f3c_0
  - libxslt=1.1.34=he774522_0
  - libzopfli=1.0.3=ha925a31_0
  - llvmlite=0.38.0=py37h23ce68f_0
  - locket=0.2.1=py37haa95532_2
  - lxml=4.8.0=py37h1985fb9_0
  - lz4-c=1.9.3=h2bbff1b_1
  - lzo=2.10=he774522_2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.3.4=py37haa95532_0
  - markupsafe=2.0.1=py37h2bbff1b_0
  - matplotlib=3.5.1=py37haa95532_1
  - matplotlib-base=3.5.1=py37hd77b12b_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py37_1
  - menuinst=1.4.18=py37h59b6b97_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - mock=4.0.3=pyhd3eb1b0_0
  - mpmath=1.2.1=py37haa95532_0
  - msgpack-python=1.0.2=py37h59b6b97_1
  - msys2-conda-epoch=20160418=1
  - multidict=5.1.0=py37h2bbff1b_2
  - multipledispatch=0.6.0=py37_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py37haa95532_1
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py37haa95532_0
  - nbconvert=6.4.4=py37haa95532_0
  - nbformat=5.3.0=py37haa95532_0
  - nest-asyncio=1.5.5=py37haa95532_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - nltk=3.7=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.4.8=py37haa95532_0
  - numba=0.55.1=py37hf11a4ad_0
  - numexpr=2.8.1=py37hb80d3ca_0
  - numpy=1.21.5=py37h7a0a035_1
  - numpy-base=1.21.5=py37hca35cd5_1
  - numpydoc=1.2=pyhd3eb1b0_0
  - olefile=0.46=py37_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - openssl=1.1.1n=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h6214cd6_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.13.0=py37haa95532_0
  - param=1.12.0=pyhd3eb1b0_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parsel=1.6.0=py37haa95532_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pathspec=0.7.0=py_0
  - patsy=0.5.2=py37haa95532_1
  - pep8=1.7.1=py37_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py37hdc2b20a_0
  - pip=21.2.4=py37haa95532_0
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - plotly=5.6.0=pyhd3eb1b0_0
  - pluggy=1.0.0=py37haa95532_1
  - powershell_shortcut=0.0.1=3
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protego=0.1.16=py_0
  - protobuf=3.19.1=py37hd77b12b_0
  - psutil=5.8.0=py37h2bbff1b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.11.0=pyhd3eb1b0_0
  - py-lief=0.11.5=py37hd77b12b_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py37h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pycrypto=2.6.1=py37he774522_10
  - pyct=0.4.8=py37_0
  - pycurl=7.44.1=py37hcd4344a_1
  - pydispatcher=2.0.5=py37haa95532_2
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyerfa=2.0.0=py37h2bbff1b_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyhamcrest=2.0.2=pyhd3eb1b0_2
  - pylint=2.9.6=py37haa95532_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.4.0=py37h62dcd97_1
  - pyodbc=4.0.32=py37hd77b12b_1
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37hd77b12b_6
  - pyreadline=2.1=py37_1
  - pyrsistent=0.18.0=py37h196d8e1_0
  - pysocks=1.7.1=py37_1
  - pytables=3.6.1=py37h1da0976_0
  - pytest=7.1.1=py37haa95532_0
  - python=3.7.13=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.0=py37hd77b12b_3
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=py3.7_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyviz_comms=2.0.2=pyhd3eb1b0_0
  - pywavelets=1.3.0=py37h2bbff1b_0
  - pywin32=302=py37h2bbff1b_2
  - pywin32-ctypes=0.2.0=py37_1001
  - pywinpty=2.0.2=py37h5da7b33_0
  - pyyaml=6.0=py37h2bbff1b_1
  - pyzmq=22.3.0=py37hd77b12b_2
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - queuelib=1.5.0=py37haa95532_0
  - regex=2022.3.15=py37h2bbff1b_0
  - requests=2.27.1=pyhd3eb1b0_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - rope=0.22.0=pyhd3eb1b0_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=0.9.7=py37h2eaa2aa_1
  - ruamel_yaml=0.15.100=py37h2bbff1b_0
  - s3transfer=0.5.0=pyhd3eb1b0_0
  - scikit-image=0.19.2=py37hf11a4ad_0
  - scikit-learn=1.0.2=py37hf11a4ad_1
  - scikit-learn-intelex=2021.5.0=py37haa95532_0
  - scrapy=2.6.1=py37haa95532_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py37haa95532_0
  - sip=4.19.13=py37hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.1.0=pyhd3eb1b0_0
  - snappy=1.1.9=h6c2663c_0
  - sniffio=1.2.0=py37haa95532_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=4.4.0=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.1.5=py37haa95532_1
  - spyder-kernels=2.1.3=py37haa95532_0
  - sqlalchemy=1.4.32=py37h2bbff1b_0
  - sqlite=3.38.2=h2bbff1b_0
  - statsmodels=0.13.2=py37h2bbff1b_0
  - sympy=1.10.1=py37haa95532_0
  - tabulate=0.8.9=py37haa95532_0
  - tbb=2021.5.0=h59b6b97_0
  - tbb4py=2021.5.0=py37h59b6b97_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.0.1=py37haa95532_0
  - terminado=0.13.1=py37haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.11=h2bbff1b_0
  - tldextract=3.2.0=pyhd3eb1b0_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=1.2.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py37_cu113
  - torchvision=0.13.1=py37_cu113
  - tornado=6.1=py37h2bbff1b_0
  - tqdm=4.64.0=py37haa95532_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - twisted=22.2.0=py37h2bbff1b_0
  - twisted-iocpsupport=1.0.2=py37h2bbff1b_0
  - typed-ast=1.4.3=py37h2bbff1b_1
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - ujson=5.1.0=py37hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.9=py37haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py37haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37haa95532_4
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py37haa95532_0
  - win_inet_pton=1.1.0=py37haa95532_0
  - win_unicode_console=0.5=py37_0
  - wincertstore=0.2=py37haa95532_2
  - winpty=0.4.3=4
  - wrapt=1.12.1=py37he774522_1
  - xarray=0.20.1=pyhd3eb1b0_1
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.3=pyhd3eb1b0_0
  - xlwings=0.24.9=py37haa95532_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yarl=1.5.1=py37he774522_0
  - zfp=0.5.5=hd77b12b_6
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.12=h8cc25b3_2
  - zope=1.0=py37_1
  - zope.interface=5.4.0=py37h2bbff1b_0
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - scipy==1.5.4
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.0.9
    - torch-sparse==0.6.15
    - yapf==0.11.1

I request to please guide me how could I resolve the error. I have spent many hours but no luck! Thanks very much!

### Environment

* PyG version:2.1.0.post1
* PyTorch version:1.12.1
* OS:windows10
* Python version:3.7.13
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):conda and pip respectively
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Can you upgrade to Python 3.8? We had problems providing wheels for Python 3.7 on PyTorch 1.12. Sorry for the inconveniences!

**Comment by 1AngelUS** [comment]
Thanks a lot for your kind help. 

I upgraded the python version as you suggested. I am getting following error:

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\e135581\.conda\envs\env5\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "C:\Users\e135581\.conda\envs\env5\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\e135581\.conda\envs\env5\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\e135581\.conda\envs\env5\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\e135581\.conda\envs\env5\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 140, in __bool__
    return any(self)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 32, in _iter_built
    candidate = func()
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 295, in __init__
    super().__init__(
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 305, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\operations\prepare.py", line 239, in unpack_url
    file = get_http_url(
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\network\download.py", line 145, in __call__
    for chunk in chunks:
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\cli\progress_bars.py", line 144, in iter
    for x in it:
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\e135581\.conda\envs\env5\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\e135581\.conda\envs\env5\lib\site-packages\pip\_vendor\urllib3\response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
**pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))**

Couldn't figure out the solution yet. This is when I am trying to install torch-scatter. 

Thank you!

**Comment by 1AngelUS** [comment]
Is it because I changed the python version?

**Comment by rusty1s** [comment]
I am not sure, never seen this error before. Can you install other packages normally?

**Comment by 1AngelUS** [comment]
These are the steps I followed:

1) conda create -n test_env python=3.8 anaconda
2) conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
3) pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --trusted-host download.pytorch.org --trusted-host data.pyg.org --verbose --no-cache-dir torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
**This command throws that error now.**

**Comment by rusty1s** [comment]
Sorry for the late reply. What happens if you simply do
```
pip install --no-index --verbose --no-cache-dir torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-1.12.1+cu113.html

**Comment by 1AngelUS** [comment]
Hi, thank you for your response!

I tried this too, but didn't work. I added **--trusted-host pypi.org --trusted-host files.pythonhosted.org --trusted-host download.pytorch.org --trusted-host data.pyg.org** because without this it throws **SSL certificate error**. 

I will re-set everything (starting from anaconda). Also, to my surprise, on Colab I was able to install and load torch-geometric library successfully even with python version 3.7x unlike the GPU machine.

Thank you once again for your continuous support.
