### ISSUE TITLE
number of edges is zero for shapenet data

### ISSUE THREAD

**Issue by weiminw** [pyg-team/pytorch_geometric#5417]
### 🐛 Describe the bug

import torch
import torch_geometric
from torch_geometric.datasets import TUDataset, ShapeNet
dataset = ShapeNet(root="./pytorch-geometric-datasets/SHAPENET")
print(f"PyG version: {torch_geometric.__version__}")
print(f"PyTorch version: {torch.__version__}")
print()
print(f'Dataset: {dataset}:')
print('====================')
print(f'Number of graphs: {len(dataset)}')
print(f'Number of features: {dataset.num_features}')
print(f'Number of classes: {dataset.num_classes}')

data = dataset[0]  # Get the first graph object.

print()
print(data)
print('=============================================================')

print(f'Number of nodes: {data.num_nodes}')
**print(f'Number of edges: {data.num_edges}') ```#we expect num_edges should not be 0 but  get 0 ```** 
print(f'Average node degree: {data.num_edges / data.num_nodes:.2f}')

```# NOTE: the bug is that data.num_edges should not be zero```

### Environment

* PyG version:2.1.0
* PyTorch version: 1.12.1
* OS: Mac OS
* Python version: 3.9
* CUDA/cuDNN version: None
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
`ShapeNet` is a point cloud dataset, so you first need to add edges by running `KNNGraph` or `RadiusGraph` transforms.

**Comment by weiminw** [comment]
> `ShapeNet` is a point cloud dataset, so you first need to add edges by running `KNNGraph` or `RadiusGraph` transforms.

Great thanks to your quickly reply, I add the KNNGraph in the pre-transform ,but I got another exception.

dataset = ShapeNet(root="/Users/wangweimin/Workspaces/pytorch-geometric-datasets/SHAPENET", **pre_transform=T.KNNGraph(k=6)**)

```/Users/wangweimin/opt/anaconda3/envs/pytorch/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py --mode=client --host=127.0.0.1 --port=60836 
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/Users/wangweimin/Workspaces/pytorch3d_workspace', '/Users/wangweimin/Workspaces/pytorch3d_workspace', '/Users/wangweimin/Workspaces/pytorch3d_workspace'])
PyDev console: starting.
Python 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ] on darwin
runfile('/Users/wangweimin/Workspaces/pytorch3d_workspace/pyg.py', wdir='/Users/wangweimin/Workspaces/pytorch3d_workspace')
/Users/wangweimin/opt/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'transforms.RandomTranslate' is deprecated, use 'transforms.RandomJitter' instead
  warnings.warn(out)
Processing...
Traceback (most recent call last):
  File "/Users/wangweimin/opt/anaconda3/envs/pytorch/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/wangweimin/Workspaces/pytorch3d_workspace/pyg.py", line 16, in <module>
    dataset = ShapeNet(root="/Users/wangweimin/Workspaces/pytorch-geometric-datasets/SHAPENET", pre_transform=T.KNNGraph(k=6), transform=T.RandomTranslate(0.01))
  File "/Users/wangweimin/opt/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch_geometric/datasets/shapenet.py", line 109, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/Users/wangweimin/opt/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch_geometric/data/in_memory_dataset.py", line 50, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/Users/wangweimin/opt/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 87, in __init__
    self._process()
  File "/Users/wangweimin/opt/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 170, in _process
    self.process()
  File "/Users/wangweimin/opt/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch_geometric/datasets/shapenet.py", line 188, in process
    data_list = self.process_filenames(filenames)
  File "/Users/wangweimin/opt/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch_geometric/datasets/shapenet.py", line 173, in process_filenames
    data = self.pre_transform(data)
  File "/Users/wangweimin/opt/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch_geometric/transforms/knn_graph.py", line 51, in __call__
    edge_index = torch_geometric.nn.knn_graph(
  File "/Users/wangweimin/opt/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch_geometric/nn/pool/__init__.py", line 130, in knn_graph
    return torch_cluster.knn_graph(x, k, batch, loop, flow, cosine,
AttributeError: 'NoneType' object has no attribute 'knn_graph ```

**AttributeError: 'NoneType' object has no attribute 'knn_graph**

**Comment by rusty1s** [comment]
Please install `torch-cluster` for this feature.

**Comment by weiminw** [comment]
> Please install `torch-cluster` for this feature.

great thanks to you , it's woking now.
