### ISSUE TITLE
undefined symbol: __cudaRegisterFatBinaryEnd

### ISSUE THREAD

**Issue by Binbose** [pyg-team/pytorch_geometric#556]
## 📚 Installation
After installation (which didnt throw any error) I am trying to run the test script, and get this error:

```
Traceback (most recent call last):
  File "graph_test.py", line 5, in <module>
    from torch_geometric.datasets import Planetoid
  File "/home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "/home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda
ImportError: /home/nmvision1/anaconda3/lib/python3.7/site-packages/torch_scatter/scatter_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd
```
I used the pytorch installer to install cuda, and I can use cuda to run normal pytorch models.

## Environment

* OS: Ubuntu 16.04.6 LTS
* Python version: 3.7.3
* PyTorch version: 1.1.0
* CUDA/cuDNN version: 9.0, V9.0.176
* GCC version: 5.4.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information: 

## Checklist

- [x] I followed the installation guide.
- [x] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [x] I do have multiple CUDA versions on my machine.
- [x] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by rusty1s** [comment]
You can read about this error [here](https://github.com/open-mmlab/mmdetection/issues/385). Hope this helps :)
