### ISSUE TITLE
`segment_matmul` in `RGCNConv` throws RuntimeError

### ISSUE THREAD

**Issue by isratnisa** [pyg-team/pytorch_geometric#5608]
### 🐛 Describe the bug
Installed `pyg_lib` and ran:
```
$cd pytorch_geometric
$python examples/rgcn.py --dataset BGS
```

Got the following error:
```Traceback (most recent call last):
  File "examples/rgcn.py", line 79, in <module>
    loss = train()
  File "examples/rgcn.py", line 62, in train
    out = model(data.edge_index, data.edge_type)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "examples/rgcn.py", line 48, in forward
    x = F.relu(self.conv1(None, edge_index, edge_type))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.1.0-py3.8.egg/torch_geometric/nn/conv/rgcn_conv.py", line 235, in forward
    out = self.propagate(edge_index, x=x_l,
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.1.0-py3.8.egg/torch_geometric/nn/conv/message_passing.py", line 409, in propagate
    out = self.message(**msg_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.1.0-py3.8.egg/torch_geometric/nn/conv/rgcn_conv.py", line 264, in message
    return segment_matmul(x_j, edge_type_ptr, self.weight)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyg_lib/ops/__init__.py", line 125, in segment_matmul
    return SegmentMatmul.apply(inputs, ptr, other)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyg_lib/ops/__init__.py", line 11, in forward
    return torch.ops.pyg.segment_matmul(inputs, ptr, other)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: expected scalar type Float but found Long
```
Tried to fix the issue with type casting but no luck.  When `pyg_lib` is disabled the code works fine.

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.12
* OS: Ubuntu
* Python version: 3.8
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Fixed in #5610

**Comment by isratnisa** [comment]
Thanks much for the quick fix! However, now it will skip the `segment_matmul` operator  when `x_l` is LongTensor and/or  `self.num_bases` is not `None`. Is there a way around with `self.num_bases` case? I want to use the `segment_matmul` operator.

**Comment by rusty1s** [comment]
Yes, I will provide a more optimized version using `pyg-lib` for the `num_bases` case soon.
