### ISSUE TITLE
Getting CUDA error on Tesla V100

### ISSUE THREAD

**Issue by wyq-li** [pyg-team/pytorch_geometric#5850]
### 🐛 Describe the bug

Hi! I am using PyG with my school's HPC (Tesla V100). I got this CUDA error `RuntimeError: CUDA error: no kernel image is available for execution on the device.`  when I run `python gat.py` in the `.../pytorch_geometric/examples/` directory.
## Additional context
```
Traceback (most recent call last):
  File "gat.py", line 74, in <module>
    loss = train()
  File "gat.py", line 54, in train
    out = model(data.x, data.edge_index)
  File "/root/anaconda3/envs/env_gnn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "gat.py", line 40, in forward
    x = F.elu(self.conv1(x, edge_index))
  File "/root/anaconda3/envs/env_gnn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pytorch_geometric/torch_geometric/nn/conv/gat_conv.py", line 243, in forward
    alpha = self.edge_updater(edge_index, alpha=alpha, edge_attr=edge_attr)
  File "/home/pytorch_geometric/torch_geometric/nn/conv/message_passing.py", line 472, in edge_updater
    out = self.edge_update(**edge_kwargs)
  File "/home/pytorch_geometric/torch_geometric/nn/conv/gat_conv.py", line 280, in edge_update
    alpha = softmax(alpha, index, ptr, size_i)
  File "/home/pytorch_geometric/torch_geometric/utils/softmax.py", line 62, in softmax
    src_max = scatter(src, index, dim, dim_size=N, reduce='max')
  File "/root/anaconda3/envs/env_gnn/lib/python3.8/site-packages/torch_scatter/scatter.py", line 160, in scatter
    return scatter_max(src, index, dim, out, dim_size)[0]
  File "/root/anaconda3/envs/env_gnn/lib/python3.8/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
  File "/root/anaconda3/envs/env_gnn/lib/python3.8/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.12.0a0+git664058f
* OS: ubuntu 18.04
* Python version: 3.8
* CUDA/cuDNN version: cuda 10.2 cudnn 7
* How you installed PyTorch and PyG (`conda`, `pip`, source): source
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch-scatter 2.0.9 torch-sparse 0.6.15

**Comment by wyq-li** [comment]
I fix it by reinstall `torch-scatter` and `torch-sparse` from source instead of using `pip`.
