### ISSUE TITLE
Error while running examples/proteins_topk_pool.py

### ISSUE THREAD

**Issue by vardaan123** [pyg-team/pytorch_geometric#5863]
### 🐛 Describe the bug

I get the following error while running the example `proteins_topk_pool.py`:
```
Traceback (most recent call last):
  File "proteins_topk_pool.py", line 103, in <module>
    loss = train(epoch)
  File "proteins_topk_pool.py", line 83, in train
    output = model(data)
  File "/home/pahuja.9/miniconda3/envs/pyg_3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "proteins_topk_pool.py", line 49, in forward
    x = F.relu(self.conv1(x, edge_index))
  File "/home/pahuja.9/miniconda3/envs/pyg_3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pahuja.9/miniconda3/envs/pyg_3.7/lib/python3.7/site-packages/torch_geometric/nn/conv/graph_conv.py", line 85, in forward
    out += self.lin_root(x_r)
RuntimeError: output with shape [128] doesn't match the broadcast shape [2239, 128]
```
It happens for every batch

### Environment

* PyG version: 2.1.0.post1
* PyTorch version: 1.12.0+cu102
* OS: Ubuntu
* Python version: 3.7.13
* CUDA/cuDNN version: 10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):
torch-scatter version: 2.0.9
torch-sparse version: 0.6.15

**Comment by rusty1s** [comment]
Mh, I cannot really reproduce this, not sure why. Any chance you can debug the shape of `x_r` and `out` in `torch_geometric/nn/conv/graph_conv.py` before the error?

**Comment by vardaan123** [comment]
Sure, here it is
```
x_r = torch.Size([2370, 0])
out = torch.Size([128])
```

**Comment by rusty1s** [comment]
Oh, this seems to be a bug in `PROTEINS` in `TUDataset` which is now fixed in master. Can you remove `data/processed`, install PyG from master and try again? Sorry for the inconveniences!

**Comment by vardaan123** [comment]
Thanks, that works!
