### ISSUE TITLE
`mamba install` of CPU build brings in GPU dependencies, `import` broken

### ISSUE THREAD

**Issue by ryan-williams** [pyg-team/pytorch_geometric#5904]
### 🐛 Describe the bug

Installing the pyg CPU build with `mamba` picks up GPU builds of {cluster,scatter,sparse}, resulting in a broken installation:
```bash
# open a shell in a Docker container with mamba
docker run --rm -it mambaorg/micromamba:1.0.0

# install pyg CPU build
micromamba install -y -c pytorch -c conda-forge -c pyg 'pyg=2.1.0[build=py39_torch_1.12.0_cpu]'

# GPU builds of torch-sparse et al were installed
micromamba list torch
# pytorch          1.12.1   py3.9_cpu_0              pytorch   ✅ cpu
# pytorch-cluster  1.6.0    py39_torch_1.12.0_cu116  pyg       ❌ cu116
# pytorch-mutex    1.0      cpu                      pytorch   ✅ cpu
# pytorch-scatter  2.0.9    py39_torch_1.12.0_cu116  pyg       ❌ cu116
# pytorch-sparse   0.6.15   py39_torch_1.12.0_cu116  pyg       ❌ cu116

# installation is broken
python -c 'import torch_sparse'
# Traceback (most recent call last):
#   File "<string>", line 1, in <module>
#   File "/opt/conda/lib/python3.9/site-packages/torch_sparse/__init__.py", line 19, in <module>
#     torch.ops.load_library(spec.origin)
#   File "/opt/conda/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
#     ctypes.CDLL(path)
#   File "/opt/conda/lib/python3.9/ctypes/__init__.py", line 374, in __init__
#     self._handle = _dlopen(self._name, mode)
# OSError: libc10_cuda.so: cannot open shared object file: No such file or directory
```

For some reason it seems to be OK with `conda`:
```bash
docker run --rm -it continuumio/miniconda3
conda install -y -c pytorch -c conda-forge -c pyg 'pyg=2.1.0[build=py39*cpu]'
conda list torch
# pytorch          1.12.0   py3.9_cpu_0              pytorch   ✅ cpu
# pytorch-cluster  1.6.0    py39_torch_1.12.0_cpu    pyg       ✅ cpu
# pytorch-mutex    1.0      cpu                      pytorch   ✅ cpu
# pytorch-scatter  2.0.9    py39_torch_1.12.0_cpu    pyg       ✅ cpu
# pytorch-sparse   0.6.15   py39_torch_1.12.0_cpu    pyg       ✅ cpu
```

I'm not sure if this is a bug in pytorch or mamba.

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.12.0
* OS: Linux
* Python version: 3.9
* CUDA/cuDNN version: N/A (CPU)
* How you installed PyTorch and PyG (`conda`, `pip`, source): `conda`
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by ryan-williams** [comment]
I've worked around it by making the `[build=*cpu]` explicit for {cluster,scatter,sparse}:

```bash
micromamba install \
    -c pytorch -c conda-forge -c pyg \
    'pyg=2.1.0[build=py39_torch_1.12.0_cpu]' \
    'pytorch-cluster=1.6.0[build=*cpu]' \
    'pytorch-scatter=2.0.9[build=*cpu]' \
    'pytorch-sparse=0.6.15[build=*cpu]'
```

If I omit the versions on the latter three, the `build=` constraint also gets ignored, so that's as simple a working command as I've found.
