### ISSUE TITLE
cannot install PyG+pyg-lib on a brand new macbook

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#5973]
### 😵 Describe the installation problem

```
python3 -m pip uninstall pyg-lib;git clone --recurse-submodules https://github.com/pyg-team/pyg-lib.git;cd pyg-lib; python3 -m pip install -e .;
  Running setup.py develop for pyg-lib
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/riship/workspace/pyg-lib/setup.py'"'"'; __file__='"'"'/Users/riship/workspace/pyg-lib/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/riship/workspace/pyg-lib/
    Complete output (16 lines):
    running develop
    running egg_info
    creating pyg_lib.egg-info
    writing pyg_lib.egg-info/PKG-INFO
    writing dependency_links to pyg_lib.egg-info/dependency_links.txt
    writing requirements to pyg_lib.egg-info/requires.txt
    writing top-level names to pyg_lib.egg-info/top_level.txt
    writing manifest file 'pyg_lib.egg-info/SOURCES.txt'
    reading manifest file 'pyg_lib.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file 'pyg_lib.egg-info/SOURCES.txt'
    running build_ext
    /Users/riship/workspace/pyg-lib/setup.py:62: UserWarning: Building times of 'pyg-lib' can be heavily improved by installing 'ninja': `pip install ninja`
      warnings.warn("Building times of 'pyg-lib' can be heavily improved"
    error: [Errno 2] No such file or directory: 'cmake'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/riship/workspace/pyg-lib/setup.py'"'"'; __file__='"'"'/Users/riship/workspace/pyg-lib/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

```
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cpu.html
Successfully installed torch-cluster-1.6.0 torch-geometric-2.1.0.post1 torch-scatter-2.0.9 torch-sparse-0.6.15 torch-spline-conv-1.2.1
riship@riship-mlt pyg-lib % python3
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_sparse/__init__.py", line 40, in <module>
    from .storage import SparseStorage  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_sparse/storage.py", line 5, in <module>
    from torch_scatter import segment_csr, scatter_add
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_scatter/_version_cpu.so, 0x0006): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_scatter/_version_cpu.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))
```

### Environment

* PyG version: both master branch and latest stable pip install wheels have same issues
* PyTorch version: tried both 1.12 and 1.13
* OS: 
<img width="584" alt="Screen Shot 2022-11-14 at 10 13 10 AM" src="https://user-images.githubusercontent.com/20074092/201735165-6726d96d-825c-4fc9-a25e-b71d0d721a88.png">

* Python version: 3.10
* How you installed PyTorch and PyG (`conda`, `pip`, source): tried pip and source build

**Comment by rusty1s** [comment]
Install `cmake`?

**Comment by puririshi98** [comment]
oh woops i was using pip install cmake, had to install it w/ homebrew for mac.

The install says its succesful but PyG still complains at import time:
```
riship@riship-mlt pyg-lib % python3 -m pip install -e .;  
Obtaining file:///Users/riship/workspace/pyg-lib
Installing collected packages: pyg-lib
  Attempting uninstall: pyg-lib
    Found existing installation: pyg-lib 0.1.0
    Uninstalling pyg-lib-0.1.0:
      Successfully uninstalled pyg-lib-0.1.0
  Running setup.py develop for pyg-lib
Successfully installed pyg-lib-0.1.0
pip uninstall -y torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric 
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cpu.html
Successfully installed torch-cluster-1.6.0 torch-geometric-2.1.0.post1 torch-scatter-2.0.9 torch-sparse-0.6.15 torch-spline-conv-1.2.1

riship@riship-mlt pyg-lib % python3
Python 3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_sparse/__init__.py", line 40, in <module>
    from .storage import SparseStorage  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_sparse/storage.py", line 5, in <module>
    from torch_scatter import segment_csr, scatter_add
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_scatter/_version_cpu.so, 0x0006): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_scatter/_version_cpu.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

**Comment by puririshi98** [comment]
pyg-lib works atleast on a basic check:
```

riship@riship-mlt pyg-lib % python3 -m pytest -s test/ops/test_matmul.py -v
=============================================================================================== test session starts ================================================================================================
platform darwin -- Python 3.10.2, pytest-7.2.0, pluggy-1.0.0 -- /usr/local/bin/python3
cachedir: .pytest_cache
rootdir: /Users/riship/workspace/pyg-lib, configfile: setup.cfg
collected 2 items                                                                                                                                                                                                  

test/ops/test_matmul.py::test_segment_matmul_autograd[device0] PASSED
test/ops/test_matmul.py::test_grouped_matmul_autograd[device0] PASSED

================================================================================================ 2 passed in 0.60s 
```

**Comment by rusty1s** [comment]
Can you post the output of `pip install --verbose torch-scatter`? I guess it is picking up a x64 compiler rather than `arm64`.

**Comment by puririshi98** [comment]
<img width="663" alt="Screen Shot 2022-11-14 at 12 10 25 PM" src="https://user-images.githubusercontent.com/20074092/201755951-0fa4ed08-6b14-4a30-b3f5-f5b64f62c325.png">
perhaps the instructions should be adjusted to remove the -f, although im not sure if everybody would have the same issue, but its possible

**Comment by aish793** [comment]
The problem still exist
