### ISSUE TITLE
latest update to linkneighborloader causes major oversamplinge

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#5989]
### 🐛 Describe the bug

I have no idea why but the clones added [here](https://github.com/pyg-team/pytorch_geometric/commit/c9608f124521b0121e02e8b2aed4efc89f34f633) causes major oversampling.

Example:
```
def pyg_num_work():
    num_work = None
    if hasattr(os, "sched_getaffinity"):
        try:
            num_work = len(os.sched_getaffinity(0)) / 2
        except Exception:
            pass
    if num_work is None:
        num_work = os.cpu_count() / 2
    return int(num_work)

data = FakeHeteroDataset(avg_num_nodes=50000).data

LinkNeighborLoader w/ batch_size=1024, num_neighbors=[50,50], num_workers=pyg_num_work()
```

->

```
Full graph:
HeteroData(
  targeted_edge_type=[3],
  v0={
    x=[58918, 79],
    y=[58918]
  },
  v1={ x=[61489, 68] },
  v2={ x=[54150, 53] },
  (v1, e0, v0)={ edge_index=[2, 614829] },
  (v2, e0, v0)={ edge_index=[2, 541453] },
  (v2, e0, v1)={ edge_index=[2, 541465] },
  (v2, e0, v2)={ edge_index=[2, 541451] },
  (v0, e0, v0)={ edge_index=[2, 589139] },
  (v0, e0, v2)={ edge_index=[2, 589135] }
)

MiniBatch:
HeteroData(
  targeted_edge_type=[3],
  labeled_node_type='v0',
  v0={
    x=[58899, 79],
    y=[58899],
    num_nodes=58899,
    n_id=[58899]
  },
  v1={
    x=[58623, 68],
    num_nodes=58623,
    n_id=[58623]
  },
  v2={
    x=[54135, 53],
    num_nodes=54135,
    n_id=[54135]
  },
  (v1, e0, v0)={
    edge_index=[2, 905300],
    e_id=[905300]
  },
  (v2, e0, v0)={
    edge_index=[2, 905150],
    e_id=[905150]
  },
  (v2, e0, v1)={
    edge_index=[2, 100600],
    e_id=[100600],
    input_id=[1024],
    edge_label_index=[2, 2048],
    edge_label=[2048]
  },
  (v2, e0, v2)={
    edge_index=[2, 1399400],
    e_id=[1399400]
  },
  (v0, e0, v0)={
    edge_index=[2, 905350],
    e_id=[905350]
  },
  (v0, e0, v2)={
    edge_index=[2, 1399550],
    e_id=[1399550]
  }
)
```

The error is occuring in one of the CI for our GNN tool using FakeHeteroDataset. Because we have ~2x more edges in the minibatch than in the full graph, we OOM on the first batch. Isolated repro attached in the comments below

### Environment

latest github master branches for PyG and pyg-lib built from source

**Comment by puririshi98** [comment]
isolated repro:
[hetero_linkneighbor_oversample.py](https://github.com/puririshi98/rgcn_pyg_lib_forward_bench/blob/main/hetero_linkneighbor_oversample.py)
output:
```
root@1e6a11d27e80:/workspace/rgcn_pyg_lib_forward_bench# python3 hetero_linkneighbor_oversample.py 
Let's use 1 GPUs!
Full graph: HeteroData(
  v0={
    x=[38476, 53],
    y=[38476]
  },
  v1={ x=[40570, 75] },
  v2={ x=[44664, 50] },
  (v1, e0, v0)={ edge_index=[2, 405654] },
  (v2, e0, v0)={ edge_index=[2, 446592] },
  (v2, e0, v1)={ edge_index=[2, 446586] },
  (v1, e0, v1)={ edge_index=[2, 405644] },
  (v2, e0, v2)={ edge_index=[2, 446584] },
  (v0, e0, v2)={ edge_index=[2, 384714] }
)
Minibatch: HeteroData(
  v0={
    x=[37725, 53],
    y=[37725]
  },
  v1={ x=[40054, 75] },
  v2={ x=[44650, 50] },
  (v1, e0, v0)={
    edge_index=[2, 50450],
    input_id=[1024],
    edge_label_index=[2, 1024],
    edge_label=[1024]
  },
  (v2, e0, v0)={ edge_index=[2, 50450] },
  (v2, e0, v1)={ edge_index=[2, 830950] },
  (v1, e0, v1)={ edge_index=[2, 830950] },
  (v2, e0, v2)={ edge_index=[2, 872750] },
  (v0, e0, v2)={ edge_index=[2, 872650] }
)
Traceback (most recent call last):
  File "hetero_linkneighbor_oversample.py", line 57, in <module>
    mp.spawn(run, args=(world_size, dataset), nprocs=world_size, join=True)
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/workspace/rgcn_pyg_lib_forward_bench/hetero_linkneighbor_oversample.py", line 41, in run
    assert batch_e_dim < fullgraph_e_dim, 'batch is bigger than full graph: ' + str((batch_e_dim)) + ' > ' + str(fullgraph_e_dim)
AssertionError: batch is bigger than full graph: 830950 > 446586
```

**Comment by rusty1s** [comment]
I think this works as expected. With `replace=True`, we will always sample 50 neighbors, potentially leading to oversampling of edges/duplicated edges if there exists fewer than 50 neighbors. You can see this [here](https://github.com/pyg-team/pyg-lib/blob/master/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp#L135). A simple fix would be to let the sampler pick up [this branch](https://github.com/pyg-team/pyg-lib/blob/master/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp#L128) even in case of `replace==True`, but I don't think this is expected behavior.

**Comment by puririshi98** [comment]
okay makes sense thnx for explaining
