### ISSUE TITLE
Testing with a single example (point cloud)

### ISSUE THREAD

**Issue by raj-shah** [pyg-team/pytorch_geometric#606]
I've trained PointNet++ for classification on ModelNet40. Unfortunately I am unable to test the trained net on a single input point cloud. 

Sample test script:
```
import torch
import torch_geometric.read as R
import torch_geometric.transforms as T
from model import PointNet2

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# load model weights
model = PointNet2()
model.load_state_dict(torch.load('./weights.pt'))
model.to(device)

# load input and pre-process
off_input = R.read_off('./bench_0174.off')
sampler = T.SamplePoints(1024)
normalise = T.NormalizeScale()
off_preprocessed = normalise(sampler(off_input))

# inference
print(model(off_preprocessed.to(device)))
```
This script results in `AttributeError: 'Data' object has no attribute 'batch'`. It seems unlikely to be able to set batch size without going through a dataloader. Any idea on how to proceed?

Full stack trace error in interested:
```
Traceback (most recent call last):
  File "/home/reddwarf/3d-feature-extraction/pointnet2/test.py", line 18, in <module>
    print(model(off_preprocessed.to(device)))
  File "/home/reddwarf/anaconda3/envs/3df/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/reddwarf/3d-feature-extraction/pointnet2/model.py", line 58, in forward
    sa0_out = (data.x, data.pos, data.batch)
AttributeError: 'Data' object has no attribute 'batch'
```

**Comment by rusty1s** [comment]
Just add a `batch` object to your test data: data.batch = torch.zeros(data.num_nodes, dtype=torch.long)

**Comment by raj-shah** [comment]
Excellent, thanks!

**Comment by raj-shah** [comment]
I can now perform inference on the trained model using a single point cloud example, however the network is predicting incorrectly (specifically either label 35 or 8). PointNet++ was trained successfully with train loss 0.2477 and train acc: 0.9250, and val loss: 0.3990 and val acc: 0.9048.

I suspect the problem to be with loading/pre-processing of the raw file. I have tried replicating what's done during the ModelNet dataset/dataloader process but to no avail. 

Relevant section of train script:
```
path = osp.join(osp.dirname(osp.realpath(__file__)), 'data/ModelNet40')
pre_transform, transform = T.NormalizeScale(), T.SamplePoints(1024)
train_dataset = ModelNet(path, '40', True, transform, pre_transform)
test_dataset = ModelNet(path, '40', False, transform, pre_transform)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=4)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=4)
```
Loading a raw file:
```
data = R.read_off('./data/ModelNet40/raw/airplane/train/airplane_0001.off')
sampler, normalise = T.SamplePoints(1024), T.NormalizeScale()
data = sampler(normalise(data))
data.batch = torch.zeros(data.num_nodes, dtype=torch.long)
```
Is there something I am missing here?

**Comment by rusty1s** [comment]
Looks correct to me, hard to say what may have cause this.

**Comment by rusty1s** [comment]
Closing this issue due to inactivity. Please feel free to re-open if there are still concerns.
