### ISSUE TITLE
Model expects dict instead of tensor?

### ISSUE THREAD

**Issue by LaurentBerder** [pyg-team/pytorch_geometric#6243]
### 🐛 Describe the bug

Hi,

I'm trying to apply the example you kindly made [here](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/hetero/hetero_link_pred.py) to some data of mine for an edge property prediction problem (here I'm trying to predict one variable on edge between "booking" and "container" nodes) .

My heterogeneous graph (which I transformed with `ToUndirected()`) looks like this:
```python
HeteroData(
  booking={ x=[9755, 5] },
  container={ x=[10076, 1] },
  shipper={ x=[5508, 2] },
  consignee={ x=[5300, 2] },
  (booking, has, container)={
    edge_index=[2, 7115],
    edge_attr=[7115, 22],
    y=[7115, 1],
    edge_label=[14230],
    edge_label_index=[2, 14230]
  },
  (shipper, sends, booking)={
    edge_index=[2, 10163],
    edge_attr=[10163, 2]
  },
  (consignee, receives, booking)={
    edge_index=[2, 10163],
    edge_attr=[10163, 2]
  },
  (container, rev_has, booking)={
    edge_index=[2, 7115],
    edge_attr=[7115, 22],
    y=[7115, 1]
  },
  (booking, rev_sends, shipper)={
    edge_index=[2, 10163],
    edge_attr=[10163, 2]
  },
  (booking, rev_receives, consignee)={
    edge_index=[2, 10163],
    edge_attr=[10163, 2]
  }
)
```
I then applied a `RandomLinkSplit` based on `edge_types=('booking', 'has', 'container')` and its reverse.

Afterwards, I adapted the code below for the model:

```python
import torch
import torch.nn.functional as F
from torch_geometric.data import HeteroData
import torch_geometric.transforms as T
from torch_geometric.nn import HeteroConv, Linear, SAGEConv, to_hetero

def weighted_mse_loss(pred, target, weight=None):
    weight = 1. if weight is None else weight[target].to(pred.dtype)
    return (weight * (pred - target.to(pred.dtype)).pow(2)).mean()

weight = None

class GNNEncoder(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = SAGEConv((-1, -1), hidden_channels)
        self.conv2 = SAGEConv((-1, -1), out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        x = self.conv2(x, edge_index)
        return x


class EdgeDecoder(torch.nn.Module):
    def __init__(self, hidden_channels):
        super().__init__()
        self.lin1 = Linear(2 * hidden_channels, hidden_channels)
        self.lin2 = Linear(hidden_channels, 1)

    def forward(self, z_dict, edge_label_index):
        row, col = edge_label_index
        z = torch.cat([z_dict['booking'][row], z_dict['container'][col]], dim=-1)

        z = self.lin1(z).relu()
        z = self.lin2(z)
        return z.view(-1)


class Model(torch.nn.Module):
    def __init__(self, hidden_channels):
        super().__init__()
        self.encoder = GNNEncoder(hidden_channels, hidden_channels)
        self.encoder = to_hetero(self.encoder, data.metadata(), aggr='sum')
        self.decoder = EdgeDecoder(hidden_channels)

    def forward(self, x_dict, edge_index_dict, edge_label_index):
        z_dict = self.encoder(x_dict, edge_index_dict)
        return self.decoder(z_dict, edge_label_index)


model = Model(hidden_channels=32).to(device)
train_data = train_data.to(device)
val_data = val_data.to(device)
test_data = test_data.to(device)
```

Now I'm able to run the train/test loop:
```python
# Due to lazy initialization, we need to run one model step so the number
# of parameters can be inferred:
with torch.no_grad():
    model.encoder(train_data.x_dict, train_data.edge_index_dict)

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)


def train():
    model.train()
    optimizer.zero_grad()
    pred = model(train_data.x_dict, train_data.edge_index_dict,
                 train_data['booking', 'container'].edge_label_index)
    target = train_data['booking', 'container'].edge_label
    loss = weighted_mse_loss(pred, target, weight)
    loss.backward()
    optimizer.step()
    return float(loss)


@torch.no_grad()
def test(data):
    model.eval()
    pred = model(data.x_dict, data.edge_index_dict,
                 data['booking', 'container'].edge_label_index)
    pred = pred.clamp(min=0, max=5)
    target = data['booking', 'container'].edge_label.float()
    rmse = F.mse_loss(pred, target).sqrt()
    return float(rmse)


for epoch in tqdm(range(1, 10)):
    loss = train()
    train_rmse = test(train_data)
    val_rmse = test(val_data)
    test_rmse = test(test_data)
    print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}, Train: {train_rmse:.4f}, '
          f'Val: {val_rmse:.4f}, Test: {test_rmse:.4f}')
```
However, that only returns NaNs:
```python
22%|██▏       | 2/9 [00:00<00:00, 14.44it/s]
Epoch: 001, Loss: nan, Train: nan, Val: nan, Test: nan
Epoch: 002, Loss: nan, Train: nan, Val: nan, Test: nan
Epoch: 003, Loss: nan, Train: nan, Val: nan, Test: nan
 67%|██████▋   | 6/9 [00:00<00:00, 14.77it/s]
Epoch: 004, Loss: nan, Train: nan, Val: nan, Test: nan
Epoch: 005, Loss: nan, Train: nan, Val: nan, Test: nan
Epoch: 006, Loss: nan, Train: nan, Val: nan, Test: nan
100%|██████████| 9/9 [00:00<00:00, 14.33it/s]
Epoch: 007, Loss: nan, Train: nan, Val: nan, Test: nan
Epoch: 008, Loss: nan, Train: nan, Val: nan, Test: nan
Epoch: 009, Loss: nan, Train: nan, Val: nan, Test: nan

```

So I tried to investigate the insides of the model with that line:

```python
model.encoder(train_data.x_dict, train_data['booking', 'container'].edge_label_index)
```
But I get this error:
```python
Traceback (most recent call last):
  File "/opt/dataiku/code-env/lib/python3.7/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/opt/dataiku/code-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.10", line 11, in forward
    edge_index__booking__has__container = edge_index_dict.get(('booking', 'has', 'container'), None)
AttributeError: 'Tensor' object has no attribute 'get'

Call using an FX-traced Module, line 11 of the traced Module's generated forward function:
    edge_index_dict = torch_geometric_nn_to_hetero_transformer_get_dict(edge_index);  edge_index = None
    edge_index__booking__has__container = edge_index_dict.get(('booking', 'has', 'container'), None)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    edge_index__shipper__sends__booking = edge_index_dict.get(('shipper', 'sends', 'booking'), None)

    edge_index__consignee__receives__booking = edge_index_dict.get(('consignee', 'receives', 'booking'), None)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-144-305668f4e805> in <module>
----> 1 model.encoder(train_data.x_dict, train_data['booking', 'container'].edge_label_index)

/opt/dataiku/code-env/lib/python3.7/site-packages/torch/fx/graph_module.py in call_wrapped(self, *args, **kwargs)
    650 
    651         def call_wrapped(self, *args, **kwargs):
--> 652             return self._wrapped_call(self, *args, **kwargs)
    653 
    654         cls.__call__ = call_wrapped

/opt/dataiku/code-env/lib/python3.7/site-packages/torch/fx/graph_module.py in __call__(self, obj, *args, **kwargs)
    273                 print(_WrappedCall._generate_error_message(topmost_framesummary),
    274                       file=sys.stderr)
--> 275                 raise e.with_traceback(None)
    276             else:
    277                 raise e

AttributeError: 'Tensor' object has no attribute 'get'
```

It seems like the model expects my `edge_label_index` to be a dict, but it's a tensor.

What am I doing wrong?

### Environment

* PyG version: 2.20
* PyTorch version: 1.12.1+cu116
* OS: Linux
* Python version: 3.7
* CUDA/cuDNN version: 1.16
* How you installed PyTorch and PyG: pip
* Torch-Scatter version: 2.1.0+pt112cu116

**Comment by LaurentBerder** [comment]
Thanks once again Matthias.

> Yes, the encoder expects a dictionary of edge indices, similar to x_dict.

Regarding this, I had mistakenly understood that the `forward` in GNNEncoder was calling for `edge_label_index` instead of `edge_index`, so that indeed is better, and I get prediction outputs on first iteration.

I guess I'm a bit puzzled by what the `edge_label` and `edge_label_index` really mean.

Now that I have some prediction however, the loss invariably returns NaN, which then throws further iterations into predicting NaNs.

> For your NaN problem, you may find some success in using torch.autograd.detect_anomaly().

Indeed, that's what using `torch.autograd.set_detect_anomaly(True)` confirms:
```python
RuntimeError: Function 'PowBackward0' returned nan values in its 0th output.
```

**Comment by LaurentBerder** [comment]
Surely enough, NaNs were produced because there were NaNs in the input. It all works out now.
Thanks a lot
