### ISSUE TITLE
Support pytorch 1.2.0

### ISSUE THREAD

**Issue by tchaton** [pyg-team/pytorch_geometric#632]
## 🚀 Feature

python
Python 3.6.4 (default, Jul 22 2019, 18:37:14) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: /home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeEN3c1013TensorOptionsE

It seems that torch_scatter doesn't work with torch 1.2.0

**Comment by rusty1s** [comment]
The package and the extensions run fine for PyTorch 1.2, but you need to rebuild them if your PyTorch version has changed.

**Comment by tchaton** [comment]
Ok I will give it a try :) Thanks you very much for always answering that fast.

**Comment by tchaton** [comment]
CONFIG:
Ubuntu 18.04

CUDA installed from: cuda_10.1.168_418.67_linux.run

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

Python 3.6.4 (default, Jul 22 2019, 18:37:14) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

torch '1.2.0'

    error: command '/usr/bin/nvcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-build-k3s1blyl/torch-scatter
Command "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k3s1blyl/torch-scatter/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bz55o6rl-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/thomas/.pyenv/versions/3.6.4/envs/pyg/include/site/python3.6/torch-scatter" failed with error code 1 in /tmp/pip-build-k3s1blyl/torch-scatter/
Exception information:
Traceback (most recent call last):
  File "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k3s1blyl/torch-scatter/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bz55o6rl-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/thomas/.pyenv/versions/3.6.4/envs/pyg/include/site/python3.6/torch-scatter" failed with error code 1 in /tmp/pip-build-k3s1blyl/torch-scatter/
You are using pip version 9.0.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Do you have any idea how to solve that ?

**Comment by tchaton** [comment]
CONFIG:
ubuntu 18.04
python 3.6.4
torch=1.2.0
cuda installed from cuda_10.1.168_418.67_linux.run
nvcc -V = release 9.1, V9.1.85

CMD:

```
pip install --verbose --no-cache-dir torch-scatter
```

RESULTS:

```
    error: command '/usr/bin/nvcc' failed with exit status 1
  Running setup.py install for torch-scatter ... error
Cleaning up...
  Removing source in /tmp/pip-install-m7y35awf/torch-scatter
Removed build tracker '/tmp/pip-req-tracker-ox2qhn54'
ERROR: Command errored out with exit status 1: /home/thomas/.pyenv/versions/3.6.4/envs/pyg/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m7y35awf/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m7y35awf/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sqpbex0f/install-record.txt --single-version-externally-managed --compile --install-headers /home/thomas/.pyenv/versions/3.6.4/envs/pyg/include/site/python3.6/torch-scatter Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 959, in install
    spinner=spinner,
  File "/home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 931, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/thomas/.pyenv/versions/3.6.4/envs/pyg/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m7y35awf/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m7y35awf/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sqpbex0f/install-record.txt --single-version-externally-managed --compile --install-headers /home/thomas/.pyenv/versions/3.6.4/envs/pyg/include/site/python3.6/torch-scatter
```

Do you have any idea how to solve this ?
Best tchaton

**Comment by tchaton** [comment]
But it works perfectly fine with torch==1.1.0.

``````
(pyg) ➜  Downloads pip install torch==1.1.0
Collecting torch==1.1.0
  Using cached https://files.pythonhosted.org/packages/69/60/f685fb2cfb3088736bafbc9bdbb455327bdc8906b606da9c9a81bae1c81e/torch-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: numpy in /home/thomas/.pyenv/versions/3.6.4/envs/pyg/lib/python3.6/site-packages (from torch==1.1.0) (1.17.0)
ERROR: pytorch-lightning 0.4.6 has requirement torch==1.2.0, but you'll have torch 1.1.0 which is incompatible.
Installing collected packages: torch
  Found existing installation: torch 1.2.0
    Uninstalling torch-1.2.0:
      Successfully uninstalled torch-1.2.0
Successfully installed torch-1.1.0
(pyg) ➜  Downloads pip install torch-scatter
Collecting torch-scatter
  Using cached https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py) ... done
  Created wheel for torch-scatter: filename=torch_scatter-1.3.1-cp36-cp36m-linux_x86_64.whl size=2869936 sha256=544207e924b473c646be8e2330438281d616344d0374f217b80842a8313b1a7f
  Stored in directory: /home/thomas/.cache/pip/wheels/7f/21/0b/c42fa9353ceec5e87464599e470a03e4250ec667b4a392fa7d
Successfully built torch-scatter
Installing collected packages: torch-scatter
Successfully installed torch-scatter-1.3.1
``````

**Comment by tchaton** [comment]
It seems it has to do with scatter_cpu. Can't be too sure there.

``````
>>> import torch
>>> from torch_scatter import scatter_max
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: /home/thomas/.pyenv/versions/pyg/lib/python3.6/site-packages/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeEN3c1013TensorOptionsE
``````

**Comment by rusty1s** [comment]
Our CI builds run just fine for PyTorch 1.2, but I believe this may be indeed a PyTorch issue. You should try to compile the official extension example and see if this works for you. If not, the PyTorch authors might be of better help than me.

**Comment by tchaton** [comment]
What do you mean by "You should try to compile the official extension example and see if this works for you" ?

And the installation doesn't work also with other pytorch-* libraries needed for pytorch geometric.
Therefore, I am going to stick to torch 1.1.0 for now, and remove some features from pytorch-light as Experiement (from test_tube doesn't work properly).

Best,
T.C

**Comment by rusty1s** [comment]
I mean [this repository](https://github.com/pytorch/extension-cpp) which is the official example on how to extend PyTorch. We just use this API to build our subpackages. If the installation fails for the official example, this might be more of a PyTorch 1.2 issue than a PyG issue. I would very much appreciate it if you could have a try.

**Comment by RuihongQiu** [comment]
Hey, I met with the same problem when I upgraded my PyTorch from 1.0 to 1.2 and upgraded the PyG from 1.2 to 1.3 using `pip install --upgrade torch-geometric`.

So I just stayed with PyTorch==1.2 and PyG==1.2 (this works fine).

Any idea?

**Comment by rusty1s** [comment]
You sadly need to recompile all external extension packages.

**Comment by RuihongQiu** [comment]
Ooops yeah.

Following [this issue](https://github.com/rusty1s/pytorch_geometric/issues/607), reinstall all the `torch-scatter`, `torch-sparse` and `torch-cluster` and then upgrade the PyG. It works. Thanks.
