### ISSUE TITLE
TUDataset permission error on loading

### ISSUE THREAD

**Issue by frankl1** [pyg-team/pytorch_geometric#6406]
### 🐛 Describe the bug

Hello, I am following the tutorial by examples on the documentation. I am having a permission error when loading TUDataset, but everything is fine when loading Planetoid for instance.

```python
from torch_geometric.datasets import TUDataset
import os

dataset = TUDataset(root='./Datasets/', name='ENZYMES')
len(dataset)
```

```
Downloading https://www.chrsmrrs.com/graphkerneldatasets/ENZYMES.zip
Extracting Datasets\ENZYMES\ENZYMES.zip
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Cell In [3], line 1
----> 1 dataset = TUDataset(root='./Datasets/', name='ENZYMES')

File ~\Miniconda3\envs\are\lib\site-packages\torch_geometric\datasets\tu_dataset.py:123, in TUDataset.__init__(self, root, name, transform, pre_transform, pre_filter, use_node_attr, use_edge_attr, cleaned)
    121 self.name = name
    122 self.cleaned = cleaned
--> 123 super().__init__(root, transform, pre_transform, pre_filter)
    125 out = torch.load(self.processed_paths[0])
    126 if not isinstance(out, tuple) or len(out) != 3:

File ~\Miniconda3\envs\are\lib\site-packages\torch_geometric\data\in_memory_dataset.py:55, in InMemoryDataset.__init__(self, root, transform, pre_transform, pre_filter, log)
     47 def __init__(
     48     self,
     49     root: Optional[str] = None,
   (...)
     53     log: bool = True,
     54 ):
---> 55     super().__init__(root, transform, pre_transform, pre_filter, log)
     56     self.data = None
     57     self.slices = None

File ~\Miniconda3\envs\are\lib\site-packages\torch_geometric\data\dataset.py:91, in Dataset.__init__(self, root, transform, pre_transform, pre_filter, log)
     88 self._indices: Optional[Sequence] = None
     90 if self.download.__qualname__.split('.')[0] != 'Dataset':
---> 91     self._download()
     93 if self.process.__qualname__.split('.')[0] != 'Dataset':
     94     self._process()

File ~\Miniconda3\envs\are\lib\site-packages\torch_geometric\data\dataset.py:185, in Dataset._download(self)
    182     return
    184 makedirs(self.raw_dir)
--> 185 self.download()

File ~\Miniconda3\envs\are\lib\site-packages\torch_geometric\datasets\tu_dataset.py:183, in TUDataset.download(self)
    181 os.unlink(path)
    182 shutil.rmtree(self.raw_dir)
--> 183 os.rename(osp.join(folder, self.name), self.raw_dir)

PermissionError: [WinError 5] Access is denied: 'Datasets\\ENZYMES\\ENZYMES' -> 'Datasets\\ENZYMES\\raw'
```

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.13.1
* OS: Windows 10 Pro
* Python version: 3.10.6
* CUDA/cuDNN version:  no cuda
* torch-cluster==1.6.0+pt113cpu
* torch-geometric==2.2.0
* torch-scatter==2.1.0+pt113cpu
* torch-sparse==0.6.15+pt113cpu
* torch-spline-conv==1.2.1+pt113cpu
* How you installed PyTorch and PyG (`conda`, `pip`, source): _conda_ for PyTorch and _pip_ for PyG

**Comment by rusty1s** [comment]
How are the permissions set in the root folder?

**Comment by Ripper346** [comment]
The same happens now with IMDB_MULTI (not with enzymes). I have the latest libraries, pyg 2.4.0 and torch 2.1.0. 
```
Downloading https://www.chrsmrrs.com/graphkerneldatasets/IMDB_MULTI.zip
Extracting data/IMDB_MULTI/IMDB_MULTI.zip
Traceback (most recent call last):
  File "/script/train.py", line 220, in <module>
    load_dataset('IMDB_MULTI', 0, 10)
  File "/script/train.py", line 70, in load_dataset
    dataset = TUDataset('data', dataset_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/torch_geometric/datasets/tu_dataset.py", line 130, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/venv/lib/python3.11/site-packages/torch_geometric/data/in_memory_dataset.py", line 76, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/venv/lib/python3.11/site-packages/torch_geometric/data/dataset.py", line 99, in __init__
    self._download()
  File "/venv/lib/python3.11/site-packages/torch_geometric/data/dataset.py", line 204, in _download
    self.download()
  File "/venv/lib/python3.11/site-packages/torch_geometric/datasets/tu_dataset.py", line 191, in download
    os.rename(osp.join(folder, self.name), self.raw_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'data/IMDB_MULTI/IMDB_MULTI' -> 'data/IMDB_MULTI/raw'
```
It doesn't seem a problem with permission, but with the hierarchy of the folders inside the zip file that have the name of the dataset and not "raw", with other TUDatasets it works without any problem
