### ISSUE TITLE
RGCNConv and FastRGCNConv doesn't work for other datatypes than torch.int64

### ISSUE THREAD

**Issue by bartekxk** [pyg-team/pytorch_geometric#6434]
RGCNConv and FastRGCNConv doesn't work for other datatypes than torch.int64 (RuntimeError). torch.int64 is default datatype if data is None. Reproducer with data created by torch.arrange (modified examples/rgcn.py) :
```python
import argparse
import os.path as osp

from numpy import arange

import torch
import torch.nn.functional as F

from torch_geometric.datasets import Entities
from torch_geometric.nn import FastRGCNConv, RGCNConv
from torch_geometric.utils import k_hop_subgraph

parser = argparse.ArgumentParser()
parser.add_argument('--dataset', type=str, default='AIFB',
                    choices=['AIFB', 'MUTAG', 'BGS', 'AM'])
args = parser.parse_args()

# Trade memory consumption for faster computation.
if args.dataset in ['AIFB', 'MUTAG']:
    RGCNConv = FastRGCNConv

path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'Entities')
dataset = Entities(path, args.dataset)
data = dataset[0]

# BGS and AM graphs are too big to process them in a full-batch fashion.
# Since our model does only make use of a rather small receptive field, we
# filter the graph to only contain the nodes that are at most 2-hop neighbors
# away from any training/test node.
node_idx = torch.cat([data.train_idx, data.test_idx], dim=0)
node_idx, edge_index, mapping, edge_mask = k_hop_subgraph(
    node_idx, 2, data.edge_index, relabel_nodes=True)

data.num_nodes = node_idx.size(0)
data.edge_index = edge_index
data.edge_type = data.edge_type[edge_mask]
data.train_idx = mapping[:data.train_idx.size(0)]
data.test_idx = mapping[data.train_idx.size(0):]


class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = RGCNConv(data.num_nodes, 16, dataset.num_relations,
                              num_bases=30)
        self.conv2 = RGCNConv(16, dataset.num_classes, dataset.num_relations,
                              num_bases=30)

    def forward(self, x, edge_index, edge_type):
        x = F.relu(self.conv1(x, edge_index, edge_type))
        x = self.conv2(x, edge_index, edge_type)
        return F.log_softmax(x, dim=1)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = torch.device('cpu') if args.dataset == 'AM' else device
model, data = Net().to(device), data.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=0.0005)


def train():
    model.train()
    optimizer.zero_grad()
    x = torch.arange(data.num_nodes, dtype=torch.float)
    out = model(x, data.edge_index, data.edge_type)
    loss = F.nll_loss(out[data.train_idx], data.train_y)
    loss.backward()
    optimizer.step()
    return float(loss)


@torch.no_grad()
def test():
    model.eval()
    x = torch.arange(data.num_nodes, dtype=torch.float)
    pred = model(x, data.edge_index, data.edge_type).argmax(dim=-1)
    train_acc = float((pred[data.train_idx] == data.train_y).float().mean())
    test_acc = float((pred[data.test_idx] == data.test_y).float().mean())
    return train_acc, test_acc


for epoch in range(1, 51):
    loss = train()
    train_acc, test_acc = test()
    print(f'Epoch: {epoch:02d}, Loss: {loss:.4f}, Train: {train_acc:.4f} '
          f'Test: {test_acc:.4f}')

```
This causes the following error:
```
Traceback (most recent call last):
  File "/pytorch_geometric/examples/rgcn.py", line 83, in <module>
    loss = train()
  File "/pytorch_geometric/examples/rgcn.py", line 65, in train
    out = model(x, data.edge_index, data.edge_type)
  File "/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/pytorch_geometric/examples/rgcn.py", line 50, in forward
    x = F.relu(self.conv1(x, edge_index, edge_type))
  File "/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/python3.8/site-packages/torch_geometric/nn/conv/rgcn_conv.py", line 297, in forward
    out = self.propagate(edge_index, x=x_l, edge_type=edge_type, size=size)
  File "/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 439, in propagate
    out = self.message(**msg_kwargs)
  File "/python3.8/site-packages/torch_geometric/nn/conv/rgcn_conv.py", line 334, in message
    return torch.bmm(x_j.unsqueeze(-2), weight[edge_type]).squeeze(-2)
RuntimeError: batch1 must be a 3D tensor
```

### Environment

* PyG version:  @ git+https://github.com/pyg-team/pytorch_geometric@f343295f7711e0d148e6ca937c68de41338b708c
* PyTorch version: 1.13.0
* OS: Ubuntu 18
* Python version: 3.8.
* CUDA/cuDNN version: -
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):-

**Comment by rusty1s** [comment]
Yes, this is expected. It should support floating-point matrices though, holding features of shape `[num_nodes, num_features]`.

**Comment by bartekxk** [comment]
@rusty1s  is it also expected for int32 format? Because it is also failing for int32. I dont see any information in documentation how to deal with formats in terms of passing `x`.
