### ISSUE TITLE
Default behaviour in config file generation w/ parameter budget generates an error. 

### ISSUE THREAD

**Issue by Sann5** [pyg-team/pytorch_geometric#6464]
### 🐛 Describe the bug

When running `graphgym/configs_gen.py` and specifying a config for the parameter budget, one must necessarily specify the field `gnn.head` in both configs (budget and base). If the field is not specified the default value is used (`gnn.head = 'default'`) and it generates a `KeyError` downstream. The `assert_cfg(cfg)` function in `/torch_geometric/graphgym/config.py` parses the default config values, specifically making `cfg.gnn.head = cfg.dataset.task` when `cfg.gnn.head == 'default'` (line 474). It is my suspicion that this function should be used somewhere before the `KeyError` is generated. Manually setting `cfg.gnn.head = cfg.dataset.task` in both configs (budget and base) solves the error.

The error can be reproduced using the example configs in GraphGym.

1. Clone `pytorch_geometric` from GitHub
2. `cd pytorch_geometric/graphgym`
3. Run `config_gen.py` with the example configs:

```
python configs_gen.py --config configs/pyg/example_node.yaml \
  --config_budget configs/pyg/example_node.yaml \
  --grid grids/pyg/example.txt \
  --out_dir configs
```

The error reads:

```
Variable label: [['gnn', 'layers_pre_mp'], ['gnn', 'layers_mp'], ['gnn', 'layers_post_mp'], ['gnn', 'stage_type'], ['gnn', 'dim_inner'], ['optim', 'base_lr'], ['optim', 'max_epoch']]
Variable alias: ['l_pre', 'l_mp', 'l_post', 'stage', 'dim', 'lr', 'epoch']
Traceback (most recent call last):
  File "configs_gen.py", line 240, in <module>
    gen_grid(args, config, config_budget)
  File "configs_gen.py", line 158, in gen_grid
    config_out = match_baseline_cfg(config_out, config_budget)
  File "/<location of your pytorch_geometric clone>/pytorch_geometric/torch_geometric/graphgym/utils/comp_budget.py", line 83, in match_baseline_cfg
    stats_baseline = dict_to_stats(cfg_dict_baseline)
  File "/<location of your pytorch_geometric clone>/pytorch_geometric/torch_geometric/graphgym/utils/comp_budget.py", line 65, in dict_to_stats
    stats = get_stats()
  File "/<location of your pytorch_geometric clone>/pytorch_geometric/torch_geometric/graphgym/utils/comp_budget.py", line 19, in get_stats
    model = create_model(to_device=False, dim_in=1, dim_out=1)
  File "/<location of your pytorch_geometric clone>/pytorch_geometric/torch_geometric/graphgym/model_builder.py", line 79, in create_model
    model = GraphGymModule(dim_in, dim_out, cfg)
  File "/<location of your pytorch_geometric clone>/pytorch_geometric/torch_geometric/graphgym/model_builder.py", line 20, in __init__
    self.model = network_dict[cfg.model.type](dim_in=dim_in,
  File "/<location of your pytorch_geometric clone>/pytorch_geometric/torch_geometric/graphgym/models/gnn.py", line 137, in __init__
    GNNHead = register.head_dict[cfg.gnn.head]
KeyError: 'default'
```

As I said before, to solve the error one simply specifies `gnn.head` in `configs/pyg/example_node.yaml`:

```
:
:
gnn:
 :
 head: node
:
```

### Environment

* PyG version: 2.3.0
* PyTorch version: 1.13.1
* OS: MacOS Ventura Version 13.1 
* Python version: 3.8.15
* CUDA/cuDNN version: CPU?
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): none

**Comment by rusty1s** [comment]
Thanks for reporting. Do you have interest in sending a PR?

**Comment by Sann5** [comment]
Not for this particular issue, I'm sorry. But I will send a PR soon for an unrelated issue that I'm working on at the moment.
