### ISSUE TITLE
GraphGym must be run with a train, test and validation split. 

### ISSUE THREAD

**Issue by Sann5** [pyg-team/pytorch_geometric#6475]
### 🐛 Describe the bug

Let's say that you clone PyG and want to give GraphGym a run. You choose one of the configs that come with and run `python main.py --cfg configs/example.yaml --repeat 1`. You will get an error because in that config, only two splits of the data are specified (`split: [0.8, 0.2]`), and the `GraphGymDataModule` class in `torch_geometric/graphgym/train.py` expects the list `self.loaders` to have exactly 3 entries (namely one loader for each split, test, train and validation). 

I'm not sure if this is intended by design, but I'm suspicious since there is an example config where the data is only split in 2. Anyway, it might be cool to have the flexibility to run GraphGym only on two or even one split. 

Reproduce the error:

1. Clone or beach PyG
2. Run `python main.py --cfg configs/example.yaml --repeat 1`

```
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    train(model, datamodule, logger=True)
  File "/Users/ast/Documents/GitHub/pytorch_geometric/torch_geometric/graphgym/train.py", line 53, in train
    trainer.test(model, datamodule=datamodule)
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 780, in test
    return call._call_and_handle_interrupt(
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 829, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1174, in _run_stage
    return self._run_evaluate()
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1206, in _run_evaluate
    self._evaluation_loop._reload_evaluation_dataloaders()
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 231, in _reload_evaluation_dataloaders
    self.trainer.reset_test_dataloader()
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1650, in reset_test_dataloader
    self.num_test_batches, self.test_dataloaders = self._data_connector._reset_eval_dataloader(
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 357, in _reset_eval_dataloader
    dataloaders = self._request_dataloader(mode)
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 446, in _request_dataloader
    dataloader = source.dataloader()
  File "/Users/ast/opt/anaconda3/envs/graph_cl/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 524, in dataloader
    return method()
  File "/Users/ast/Documents/GitHub/pytorch_geometric/torch_geometric/graphgym/train.py", line 28, in test_dataloader
    return self.loaders[2]
IndexError: list index out of range
```

### Environment

- PyG version: 2.3.0
- PyTorch version: 1.13.1
- OS: MacOS Ventura Version 13.1
- Python version: 3.8.15
- CUDA/cuDNN version: CPU?
- How you installed PyTorch and PyG (conda, pip, source): pip
- Any other relevant information (e.g., version of torch-scatter): none

**Comment by EdisonLeeeee** [comment]
It works fine on my end by running `python main.py --cfg configs/example.yaml --repeat 1` directly. Is that fixed now?

**Comment by rusty1s** [comment]
1. No, I think this is definitely not intended.
2. Yes :(
3. Yes :(

This seems to be indeed pretty bugged, but I am not sure how much time I have to fix this.

**Comment by flhammer** [comment]
Thanks for your reply, @rusty1s.

I spent a bit more time on it and found a bit of a hackish solution.

In the end I took advantage of the `custom_graphgym` functionality to create my own training function and `GraphGymDataModule`. This is what my custom class and training function in the `custom_graphgym.train` folder looks like


```python
@register_train("CustomGraphGymDataModule")
class CustomGraphGymDataModule(LightningDataModule):
    def __init__(self):
        super().__init__(has_val=True, has_test=True)
        self._create_dataset_splits()
        self._create_data_loaders()

    def _create_dataset_splits(self):
        dataset = load_dataset()
        fit_datatset, self.test_dataset = train_test_split(dataset)
        self.train_dataset, self.val_dataset = train_test_split(fit_datatset)

    def _create_data_loaders(self):
        pw = cfg.num_workers > 0
        self._train_dataloader = DataLoader(
            dataset=self.train_dataset,
            batch_size=cfg.train.batch_size,
            shuffle=True,
            num_workers=cfg.num_workers,
            pin_memory=True,
            persistent_workers=pw,
        )

        self._val_dataloader = DataLoader(
            dataset=self.val_dataset,
            batch_size=cfg.train.batch_size,
            shuffle=True,
            num_workers=cfg.num_workers,
            pin_memory=True,
            persistent_workers=pw,
        )

        self._test_dataloader = DataLoader(
            dataset=self.test_dataset,
            batch_size=cfg.train.batch_size,
            shuffle=True,
            num_workers=cfg.num_workers,
            pin_memory=True,
            persistent_workers=pw,
        )

    def train_dataloader(self) -> DataLoader:
        return self._train_dataloader

    def val_dataloader(self) -> DataLoader:
        return self._val_dataloader

    def test_dataloader(self) -> DataLoader:
        return self._test_dataloader
```
So I also hard coded `super().__init__(has_val=True, has_test=True)`, because I want to have a validation and test loader for the training step. I then go on and load my own `InMemoryDataset` with my own function `load_dataset` The dataset contains a set of 200 graphs, which I split with my custom split function `train_test_split`. Based on this split train, validation and test dataloaders are created and returned during the model training.

The custom training function looks as follows:

```python
@register_train("train_pl")
def train(
    model,
    datamodule,
    logger: bool = True,
    trainer_config: Optional[dict] = None,
):
    callbacks = []
    if logger:
        callbacks.append(LoggerCallback())
    if cfg.train.enable_ckpt:
        ckpt_cbk = pl.callbacks.ModelCheckpoint(dirpath=get_ckpt_dir())
        callbacks.append(ckpt_cbk)

    trainer_config = trainer_config or {}
    trainer = pl.Trainer(
        **trainer_config,
        enable_checkpointing=cfg.train.enable_ckpt,
        callbacks=callbacks,
        default_root_dir=cfg.out_dir,
        max_epochs=cfg.optim.max_epoch,
        accelerator=cfg.accelerator,
        devices="auto" if not torch.cuda.is_available() else cfg.devices,
    )

    trainer.fit(model, datamodule=datamodule)
    trainer.test(model, datamodule=datamodule)
```

However, the `pytorch_lightning.trainer.Trainer` class at some point checks if the dataset has attributes `train_mask`, `val_mask` and `test_mask`, I had to add them to my custom dataset. I simply added the following lines of code to my dataset.

```python
data.train_mask = torch.ones(graph.number_of_nodes(), dtype=bool)
data.val_mask = data.train_mask
data.test_mask = data.train_mask
```

This is now working for me, but I will see if I can develop a proper fix and create a pull request.
