### ISSUE TITLE
Data.update() fails with 'TypeError: 'list' object is not callable'

### ISSUE THREAD

**Issue by j-mesnil** [pyg-team/pytorch_geometric#6502]
### 🐛 Describe the bug

The [data.Data.update()](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.data.Data.html#torch_geometric.data.Data.update) method fails in the following minimal example.

```python
import torch
from torch_geometric.data import Data

x1 = torch.Tensor([[1.0, 0.0]])
x2 = torch.Tensor([[0.0, 1.0]])
d1 = Data(x=x1)
d2 = Data(x=x2)
d2.update(d1)

```

The following exception is thrown:

```
Traceback (most recent call last):
  File "(/path/to/minimal_example.py)", line 8, in <module>
    d2.update(d1)
  File "/usr/lib/python3.8/_collections_abc.py", line 834, in update
    for key in other.keys():
TypeError: 'list' object is not callable
```

The `update` method in `_collections_abc.py` will run
```python
elif hasattr(other, "keys"):
    for key in other.keys():
        self[key] = other[key]
```
The `Data` class from PyG has a list of keys `keys`, so the call to `other.keys()` fails here.

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.12.1+cu113
* OS: Linux
* Python version: 3.8
* CUDA/cuDNN version: 11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): `pip`
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by j-mesnil** [comment]
I see, thanks!
