### ISSUE TITLE
Batch not working with HeteroData

### ISSUE THREAD

**Issue by florpi** [pyg-team/pytorch_geometric#6509]
There seems to be an issue when using a DataLoader with a list of HeteroData objects. I've pinned it down to Batch not storing the batch argument as you can see in this code snippet

 ```python  import torch
from torch_geometric.data.batch import Batch
from torch_geometric.data import Data, HeteroData


def generate_data():
    edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)
    return Data(
        x=torch.rand((10, 3)),
        edge_index=edge_index,
    ) 


def generate_hetero_data():
    data = HeteroData()

    data["paper"].x = torch.randn(10, 2)
    data["author"].x = torch.randn(20, 3)
    data["author", "writes", "paper"].edge_index = torch.tensor(
        [[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long
    )
    return data


print(Batch.from_data_list([generate_data(), generate_data()]).batch)
print(Batch.from_data_list([generate_hetero_data(), generate_hetero_data()]).batch)
```

This is the output I get

```
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
Traceback (most recent call last):
  File "/n/home11/ccuestalazaro/GRACE/Notebooks/data/issue.py", line 26, in <module>
    print(Batch.from_data_list([generate_hetero_data(), generate_hetero_data()]).batch)
  File "/n/home11/ccuestalazaro/.conda/envs/geometric/lib/python3.10/site-packages/torch_geometric/data/hetero_data.py", line 133, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' has no "
AttributeError: 'HeteroDataBatch' has no attribute 'batch'
```

Is there a reason why HeteroDataBatch wouldn't have a batch attribute?

**Comment by rusty1s** [comment]
The `batch` attribute is present for each node type, e.g., `data['paper'].batch`.
