### ISSUE TITLE
conda installation from official channels fails with undefined symbol (_ZN5torch3jit17parseSchemaOrNameERKSs)

### ISSUE THREAD

**Issue by mrceresa** [pyg-team/pytorch_geometric#6513]
### 🐛 Describe the bug

Dear all,
I read all the similar threads that I could find, and they all say that this is due to an ABI incompability and to solve it by using default channles or by building from source.
However, even after installing everything from official channel, I cannot get binary compatibility with pyg:

```
$ conda create --prefix /scratch/ceresma/envs/j2 python=3.10
$ mamba install pytorch-gpu cudatoolkit -c pytorch
$ mamba install pyg -c pyg
$ python
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch_scatter import scatter_mean
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/ceresma/envs/j2/lib/python3.10/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/scratch/ceresma/envs/j2/lib/python3.10/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/scratch/ceresma/envs/j2/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /scratch/ceresma/envs/j2/lib/python3.10/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
```

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.12
* OS: linux
* Python version: 3.10
* CUDA/cuDNN version: 11.6/8.4.1
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by mrceresa** [comment]
```
$ mamba list

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     22.11.1         py310hff52083_1    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
cryptography              39.0.0          py310h34c0648_0    conda-forge
cudatoolkit               11.6.0              hecad31d_11    conda-forge
cudnn                     8.4.1.50             hed8a83a_0    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
libarchive                3.6.2                h3d51595_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.87.0               hdc1c0ab_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libhwloc                  2.8.0                h32351e8_1    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libmamba                  1.2.0                hcea66bb_0    conda-forge
libmambapy                1.2.0           py310h1428755_0    conda-forge
libnghttp2                1.51.0               hff17c54_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libprotobuf               3.21.12              h3eb15da_0    conda-forge
libsolv                   0.7.23               h3eb15da_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               15.0.7               h0cdce71_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
magma                     2.5.4                hc72dce7_4    conda-forge
mamba                     1.2.0           py310h51d5547_0    conda-forge
markupsafe                2.1.2           py310h1fa729e_0    conda-forge
mkl                       2022.2.1         h84fe81f_16997    conda-forge
nccl                      2.14.3.1             h0800d71_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
numpy                     1.24.1          py310h08bbf29_0    conda-forge
openssl                   3.0.7                h0b41bf4_1    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
psutil                    5.9.4           py310h5764c6d_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py310h5764c6d_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyg                       2.2.0           py310_torch_1.12.0_cu116    pyg
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.8          h4a9ceb5_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytorch                   1.12.1          cuda112py310he33e0d6_201    conda-forge
pytorch-cluster           1.6.0           py310_torch_1.12.0_cu116    pyg
pytorch-gpu               1.12.1          cuda112py310h7c68dbd_201    conda-forge
pytorch-scatter           2.1.0           py310_torch_1.12.0_cu116    pyg
pytorch-sparse            0.6.16          py310_torch_1.12.0_cu116    pyg
readline                  8.1.2                h0f457ee_0    conda-forge
reproc                    14.2.4               h0b41bf4_0    conda-forge
reproc-cpp                14.2.4               hcb278e6_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21         py310h5764c6d_2    conda-forge
ruamel.yaml.clib          0.2.7           py310h1fa729e_1    conda-forge
scikit-learn              1.2.1           py310h209a8ca_0    conda-forge
scipy                     1.10.0          py310h8deb116_0    conda-forge
setuptools                66.1.1             pyhd8ed1ab_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
tbb                       2021.7.0             h924138e_1    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
zstandard                 0.19.0          py310hdeb6495_1    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

**Comment by mrceresa** [comment]
Solved by installing from source as in:
https://github.com/pyg-team/pytorch_geometric/issues/3850#issuecomment-1013224165

Not sure why installing from official channels didn't work though!

**Comment by rusty1s** [comment]
This is because you are installing the PyTorch version from `conda-forge`, not from `-c pytorch` :(

**Comment by mrceresa** [comment]
Oooh I see, I didn't even noticed! Thanks for answering :)
