### ISSUE TITLE
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Wooks-git** [pyg-team/pytorch_geometric#6544]
### 🐛 Describe the bug

/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py:64: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
/workspace/mmaction/models/backbones/resnet_tin.py:12: UserWarning: Please install mmcv-full to support "tin_shift"
  warnings.warn('Please install mmcv-full to support "tin_shift"')
Traceback (most recent call last):
  File "query_attack/decompose_query.py", line 265, in <module>
    main()
  File "query_attack/decompose_query.py", line 135, in main
    env_info_dict = collect_env()
  File "/workspace/mmaction/utils/collect_env.py", line 8, in collect_env
    env_info = collect_basic_env()
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/env.py", line 85, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 10, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory

### Environment

* PyG version:
* PyTorch version: 
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

This is my docker image version
pytorch : 1.5.1
cuda : 10.1
cudnn : cudnn7

This is my linux server version
cuda : 9.1

I need to using docker environment to running my code, but i met this error "ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory"

How can i solve it?

**Comment by rusty1s** [comment]
Is this related to PyG? It seems to rash inside `mmcv`. In addition, can you share some information about how you tried to install PyG?

**Comment by TristonC** [comment]
@Wooks-git Looks like you have two different versions of cuda. What version of cuda  container did you used for your PyG container?
