### ISSUE TITLE
Installation for amazon DL1 EC2 instances (Gaudi processors, Habana labs)

### ISSUE THREAD

**Issue by dhall1995** [pyg-team/pytorch_geometric#6663]
### 😵 Describe the installation problem

I recently gained access to an [amazon EC2 DL1 instance](https://aws.amazon.com/ec2/instance-types/dl1/) which use [Gaudi accelerators](https://habana.ai/training/) rather than nvidia. I was wondering whether it is even possible to install pytorch geometric with this accelerator or if this will just be impossible with any current torch geometric version

### Environment

* PyG version: cpu
* PyTorch version: 1.12.0
* OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
* Python version: 3.8.10
* CUDA/cuDNN version: na
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): I ran - `pip install pyg-lib torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.12.0+cpu.html`

**Comment by dhall1995** [comment]
Oh sorry I should add - the error when installing pytorch geometric is:

`ubuntu@ip-172-31-87-189:~$ python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_geometric as pyg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch_sparse/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/usr/local/lib/python3.8/dist-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ubuntu/.local/lib/python3.8/site-packages/torch_sparse/_version_cpu.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
>>> `

**Comment by rusty1s** [comment]
We just dropped any requirements of dependencies of `torch-scatter` and `torch-sparse` and PyG can now run now natively using PyTorch. Can you try to install PyG from master without any of these extensions?
