### ISSUE TITLE
Pytorch Geometric CPU only version ImportError:  <$python_path>/lib/python3.6/site-packages/torch_sparse-0.4.0-py3.6-linux-x86_64.egg/torch_sparse/spspmm_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by HYDesmondLiu** [pyg-team/pytorch_geometric#673]
## 📚 Installation
Hi Experts,
    Actually installation is without any warning and error, it is the problem while importing torch_geometric. (details appended below) How do I solve this issue?

## Error Log Importing torch_geometric
>>> import torch
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_sparse-0.4.0-py3.6-linux-x86_64.egg/torch_sparse/__init__.py", line 6, in <module>
    from .spspmm import spspmm
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_sparse-0.4.0-py3.6-linux-x86_64.egg/torch_sparse/spspmm.py", line 4, in <module>
    import torch_sparse.spspmm_cpu
ImportError: /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_sparse-0.4.0-py3.6-linux-x86_64.egg/torch_sparse/spspmm_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

## Installation Log
> pip install torch-geometric
Collecting torch-geometric
Requirement already satisfied: plyfile in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from torch-geometric) (0.7)
Requirement already satisfied: scipy in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from torch-geometric) (1.3.1)
Requirement already satisfied: pandas in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from torch-geometric) (0.24.2)
Requirement already satisfied: scikit-learn in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from torch-geometric) (0.21.3)
Requirement already satisfied: h5py in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from torch-geometric) (2.9.0)
Requirement already satisfied: networkx in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from torch-geometric) (2.2)
Requirement already satisfied: numpy in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from torch-geometric) (1.16.4)
Requirement already satisfied: googledrivedownloader in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from torch-geometric) (0.4)
Requirement already satisfied: rdflib in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from torch-geometric) (4.2.2)
Requirement already satisfied: pytz>=2011k in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from pandas->torch-geometric) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from pandas->torch-geometric) (2.8.0)
Requirement already satisfied: joblib>=0.11 in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from scikit-learn->torch-geometric) (0.13.2)
Requirement already satisfied: six in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from h5py->torch-geometric) (1.12.0)
Requirement already satisfied: decorator>=4.3.0 in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from networkx->torch-geometric) (4.4.0)
Requirement already satisfied: pyparsing in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from rdflib->torch-geometric) (2.3.1)
Requirement already satisfied: isodate in /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages (from rdflib->torch-geometric) (0.6.0)
Installing collected packages: torch-geometric
Successfully installed torch-geometric-1.3.1

## Environment
* OS: CentOS Linux release 7.6.1810 (Core)
* Python version: Python 3.6.8 :: Anaconda custom (64-bit)
* PyTorch version: 
    torch==1.2.0+cpu
    torch-cluster==1.4.4
    torch-geometric==1.3.1
    torch-scatter==1.3.1
    torch-sparse==0.4.0
    torch-spline-conv==1.1.0
    torchvision==0.4.0+cpu
* CUDA/cuDNN version: None
* GCC version: gcc-8.2.0
* How did you try to install PyTorch Geometric and its extensions (pip, source):  pip install torch-geometric
* Any other relevant information:

## Checklist
- [ V] I followed the installation guide.
- [ V] I cannot find my error message in the FAQ.
- [ X] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ X] I have cloned the repository and tried a manual installation from source.
- [ X] I do have multiple CUDA versions on my machine.
- [ X] I checked if the official extension example runs on my machine.
- [ X] The offical extension example runs on my machine.

**Comment by rusty1s** [comment]
Do you have multiple PyTorch versions installed? This could be an issue. If not, maybe downgrading `gcc` to 5.4 helps.

**Comment by HYDesmondLiu** [comment]
I uninstalled the torch_geometric and downgrade gcc to 5.4.0 then re-install torch_geometric again, it shows the same ImportError:

//======================================================
>>> import torch
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_sparse-0.4.0-py3.6-linux-x86_64.egg/torch_sparse/__init__.py", line 6, in <module>
    from .spspmm import spspmm
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_sparse-0.4.0-py3.6-linux-x86_64.egg/torch_sparse/spspmm.py", line 4, in <module>
    import torch_sparse.spspmm_cpu
ImportError: /home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_sparse-0.4.0-py3.6-linux-x86_64.egg/torch_sparse/spspmm_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by HYDesmondLiu** [comment]
Is it because I install under virtual Conda environment since I do not have superuser permission?  I've tried to create another virtual environment and install again same problem comes out.

**Comment by rusty1s** [comment]
Sudo rights should bot cause a problem in conda environments. Are you sure you do not have multiple PyTorch versions installed?

**Comment by HYDesmondLiu** [comment]
Sorry, this might be a very stupid question but how do I check if I have multiple versions installed?

**Comment by HYDesmondLiu** [comment]
I've uninstalled PyTorch and re-install again, still with the same problem.

**Comment by rusty1s** [comment]
Eventually [this thread](https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627/9) is helpful to you.

**Comment by HYDesmondLiu** [comment]
Thanks, I think I've removed a redundant version of PyTorch, now it's showing other error.

```
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 1, in <module>
    from .meta import MetaLayer
  File "/home/hliu/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_geometric/nn/meta.py", line 4, in <module>
    class MetaLayer(torch.nn.Module):
AttributeError: module 'torch' has no attribute 'nn'
```

**Comment by rusty1s** [comment]
Your PyTorch version sounds broken to me.
