### ISSUE TITLE
Help!!!RuntimeError: Not compiled with CUDA support 

### ISSUE THREAD

**Issue by Serious-H** [pyg-team/pytorch_geometric#6755]
### 😵 Describe the installation problem

‘’‘I am reproducing the code of a paperr in which pytorch-geometric and pytorch lightning are used. After I install it, I run the program and report an error. I also looked at other issues with the same problem as mine, but didn't find a solution that I could use.

Traceback (most recent call last):
  File "main.py", line 487, in <module>
    main(args)
  File "main.py", line 450, in main
    trainer.fit(model)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 241, in _run_optimization
    closure()
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 135, in closure
    step_output = self._step_fn()
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 419, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 378, in training_step
    return self.model.training_step(*args, **kwargs)
  File "main.py", line 330, in training_step
    loss = self.forward(*batch, is_Train=True)
  File "main.py", line 237, in forward
    KHGT_output = self.kg_encoder(hetero_data.x_dict, hetero_data.edge_index_dict)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/Paper_Project/HQ/RT-KGD-Project/RT-KGD/utils/HGT.py", line 34, in forward
    x_dict = conv(x_dict, edge_index_dict)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch_geometric/nn/conv/hgt_conv.py", line 165, in forward
    out = self.propagate(edge_index, k=k, q=q_dict[dst_type], v=v,
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 437, in propagate
    out = self.message(**msg_kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch_geometric/nn/conv/hgt_conv.py", line 191, in message
    alpha = softmax(alpha, index, ptr, size_i)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch_geometric/utils/softmax.py", line 62, in softmax
    src_max = scatter(src, index, dim, dim_size=N, reduce='max')
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch_scatter/scatter.py", line 160, in scatter
    return scatter_max(src, index, dim, out, dim_size)[0]
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch/_ops.py", line 442, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Not compiled with CUDA support
Epoch 0:   0%|          | 0/1244 [00:01<?, ?it/s] ’‘’

### Environment

* PyTorch version:1.13.1
* OS:Ubuntu 20.04
* Python version:3.8.15
* CUDA/cuDNN version:11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source):conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):
* I installed it with the following command:
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://data.pyg.org/whl/torch-1.13.1+${cu117}.html

My final installation results are as follows：
torch-scatter                2.1.0
torch-sparse                 0.6.16
torch-geometric              2.2.0
I did not install torch-cluster: torch-spline-conv, because installing them will report  AttributeError: 'NoneType' object has no attribute 'origin' error

Let me know if you need more information.

**Comment by Serious-H** [comment]
> You need to run
> 
> ```
> pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.13.0+cu117.html
> ```
> 
> Let me know if this works.

According to your answer, I reinstalled torch-scatter separately, and now it can run, thank you very much
