### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x0 and 600x768)

### ISSUE THREAD

**Issue by Serious-H** [pyg-team/pytorch_geometric#6761]
### 🐛 Describe the bug

Hello, I'm a novice. I encountered this error when reproducing a HGT-related paper. Do you know the reason for this, because I see the error message torch_ Geometric So ask.
Traceback (most recent call last):
  File "main.py", line 490, in <module>
    main(args)
  File "main.py", line 453, in main
    trainer.fit(model)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 241, in _run_optimization
    closure()
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 135, in closure
    step_output = self._step_fn()
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 419, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 378, in training_step
    return self.model.training_step(*args, **kwargs)
  File "main.py", line 330, in training_step
    loss = self.forward(*batch, is_Train=True)
  File "main.py", line 237, in forward
    KHGT_output = self.kg_encoder(hetero_data.x_dict, hetero_data.edge_index_dict)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/Paper_Project/HQ/RT-KGD-Project/RT-KGD/utils/HGT.py", line 37, in forward
    x_dict[node_type] = self.lin_dict[node_type](x).relu_()     # 将x通过线性层转为设定的维度hidden-channels
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/hq/lib/python3.8/site-packages/torch_geometric/nn/dense/linear.py", line 136, in forward
    return F.linear(x, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x0 and 600x768)
Epoch 0:   0%|          | 34/9964 [00:09<48:16,  3.43it/s, loss=8.59, v_num=25]  

### Environment

* PyG version:
* PyTorch version:1.13.1
* OS:Ubuntu 20.04
* Python version:3.8.15
* CUDA/cuDNN version:11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source):conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch-geometric 2.2.0

**Comment by rusty1s** [comment]
Looks like one of your input features is empty (shape `[1, 0]`), while it expects a feature dimension of `600`.
