### ISSUE TITLE
DataLoader Error

### ISSUE THREAD

**Issue by mgao97** [pyg-team/pytorch_geometric#6779]
### 🐛 Describe the bug

Hi! I want to use the min-batch function to extract graph data. Here each data is composed of a pair of graph data, like PairData(edge_index_s=[2, 0], x_s=[1, 166], edge_index_t=[2, 0], x_t=[1, 166]).

I have encountered the following error,
Traceback (most recent call last):
  File "run_Bitcoin5.py", line 581, in <module>
    batch = next(iter(train_loader))
  File "/conda/envs/env_torch13/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/conda/envs/env_torch13/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/conda/envs/env_torch13/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/conda/envs/env_torch13/lib/python3.8/site-packages/torch_geometric/loader/dataloader.py", line 19, in __call__
    return Batch.from_data_list(batch, self.follow_batch,
  File "/conda/envs/env_torch13/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 76, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/conda/envs/env_torch13/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 84, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/conda/envs/env_torch13/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 133, in _collate
    incs = get_incs(key, values, data_list, stores)
  File "/conda/envs/env_torch13/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 262, in get_incs
    repeats = [
  File "/conda/envs/env_torch13/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 263, in <listcomp>
    data.__inc__(key, value, store)
TypeError: __inc__() takes 3 positional arguments but 4 were given

Any solutions or suggestions to solve it?

Thanks!

### Environment

* PyG version: 2.2.4
* PyTorch version: 1.13.0
* OS: Linux
* Python version: 3.8.0
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Do you have a custom `__inc__` function within `Data` defined?

**Comment by mgao97** [comment]
Do you mean this one?

`def __inc__(self, key, value):
        if key == 'edge_index_s':
            return self.x_s.size(0)
        if key == 'edge_index_t':
            return self.x_t.size(0)
        else:
            return super().__inc__(key, value)`

**Comment by rusty1s** [comment]
Yes, you should change it to `__inc__(self, key, value, *args, **kwargs)` from PyG >= 2.0 onwards.

**Comment by mgao97** [comment]
Got it！Thank you！
