### ISSUE TITLE
oserror winerror 127 the specified procedure could not be found

### ISSUE THREAD

**Issue by Yunx1aoyuj1** [pyg-team/pytorch_geometric#6931]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "C:\Users\liao\Desktop\GDN-pyg1.5.0\main.py", line 18, in <module>
    from models.GDN import GDN
  File "C:\Users\liao\Desktop\GDN-pyg1.5.0\models\GDN.py", line 8, in <module>
    from torch_geometric.nn import GCNConv, GATConv, EdgeConv
  File "C:\Users\liao\.conda\envs\cuda117\lib\site-packages\torch_geometric\__init__.py", line 4, in <module>
    import torch_geometric.data
  File "C:\Users\liao\.conda\envs\cuda117\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\Users\liao\.conda\envs\cuda117\lib\site-packages\torch_geometric\data\data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "C:\Users\liao\.conda\envs\cuda117\lib\site-packages\torch_sparse\__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "C:\Users\liao\.conda\envs\cuda117\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "C:\Users\liao\.conda\envs\cuda117\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] the specified procedure could not be found

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.13.0/2.0.0
* OS: win11 Professional
* Python version: 3.9
* CUDA/cuDNN version: cuda11.8 for rtx4090
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Looks like an issue during `torch-sparse` installation. Can you share more details on how you installed `torch-sparse`?

**Comment by Yunx1aoyuj1** [comment]
> Looks like an issue during `torch-sparse` installation. Can you share more details on how you installed `torch-sparse`?
i installed torch-sparse by
pip install torch_scatter torch_sparse torch_cluster torch_spline_conv torch_geometric -f https://data.pyg.org/whl/torch-1.13.0+cu117.html,
