### ISSUE TITLE
when using captum explainer forward() missing 1 required positional argument: 'batch'

### ISSUE THREAD

**Issue by affanahmed373** [pyg-team/pytorch_geometric#7039]
### 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/56910741/227738299-a9311914-6452-4068-ab8a-12d74be45bb0.png)

Explainer.__call__() requires an input argument of batch

error : 
TypeError: forward() missing 1 required positional argument: 'batch'

### Environment

* PyG version: latest
* PyTorch version: 1.13.1+cu116
* OS: Colab
* Python version:
* CUDA/cuDNN version: cu116
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
The input to the explainer has to match with the input your model expects. If `batch` is a required argument to your model, then you also need to pass it to the explainer. Does that fix your problems?

**Comment by affanahmed373** [comment]
yes my model uses batch argument. But the explainer class/__call__ signature/arguments does not include batch(as optional or compulsory). or probably I am naive and maybe can use *args or **kwargs for the batch arguments?

**Comment by rusty1s** [comment]
Yes, you can just do something like `explainer(x, edge_index, batch)`.

**Comment by rusty1s** [comment]
Yeah, sorry. You need to use `explainer(x, edge_index, batch=batch, ...)`.

**Comment by affanahmed373** [comment]
![image](https://user-images.githubusercontent.com/56910741/228581063-60890afa-f37e-4236-9956-fb700c853447.png)
 so you are probably not getting the point. Like I said the explainer class does not have the "batch" argument at all. So I cannot use it.
![image](https://user-images.githubusercontent.com/56910741/228582186-054ed6a0-402b-40cb-9c69-e11066fa171d.png)

So this is something that needs to be added to the explainer library.

**Comment by rusty1s** [comment]
Not sure I understand. The `Explainer.__class__` method signals that additional attributes to the GNN can be passed via `**kwargs`, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/explain.html#torch_geometric.explain.Explainer.__call__). Note that you don't add `batch` to the `explainer` construction, but it's forward pass instead.

**Comment by elisagdelope** [comment]
I have a similar problem with passing edge attributes to the explainer function. I am not using captum explainer but GNNExplainer, yet I think the error is the same: it somehow doesn't recognize the kwarg... Could you please help me?

My model is:
```
class GCNN(nn.Module):
    def __init__(self, in_f ,CL1_F, CL2_F, out_f):
        super(GCNN, self).__init__()
        # graph CL1
        self.conv1 = GCNConv(in_channels=in_f, out_channels=CL1_F)
        # graph CL2
        self.conv2 = GCNConv(in_channels=CL1_F, out_channels=CL2_F)
        # FC1
        self.lin1 = nn.Linear(CL2_F, out_f)
        self.bn1 = nn.BatchNorm1d(CL1_F)
        self.bn2 = nn.BatchNorm1d(CL2_F)
    def forward(self, x, edge_index, edge_weights):
        #x, edge_index, edge_weight = data.x, data.edge_index, data.edge_weight
        # node embeddings:
        x = F.relu(self.conv1(x, edge_index, edge_weights))
        x = self.bn1(x)
        x = F.dropout(x, p=0.7, training=self.training)
        x = F.relu(self.conv2(x, edge_index, edge_weights))
        x = self.bn2(x)
        x = F.dropout(x, p=0.7, training=self.training)
        out = self.lin1(x)
        return out # returns the embedding x & prediction out
```
And then the call for the explanation is:
```
explainer = Explainer(
        model=model,
        algorithm=GNNExplainer(epochs=200),
        explanation_type='model',
        node_mask_type='attributes',
        edge_mask_type='object',
        model_config=dict(
            mode='multiclass_classification',
            task_level='node',
            return_type='log_probs',
        ),
    )
 explanation = explainer(x=data.x, edge_index=data.edge_index, edge_weights=data.edge_attr.to(torch.float32))
```

The error is: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/irisgpfs/users/egomez/Projects/graph-venv37/lib/python3.7/site-packages/torch_geometric/explain/explainer.py", line 193, in __call__
    prediction = self.get_prediction(x, edge_index, **kwargs)
  File "/mnt/irisgpfs/users/egomez/Projects/graph-venv37/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/irisgpfs/users/egomez/Projects/graph-venv37/lib/python3.7/site-packages/torch_geometric/explain/explainer.py", line 115, in get_prediction
    out = self.model(*args, **kwargs)
  File "/mnt/irisgpfs/users/egomez/Projects/graph-venv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'edge_weights'
```
