### ISSUE TITLE
Implementing `InMemoryDataset` using Zachary data file causes error after processing.

### ISSUE THREAD

**Issue by fingertap** [pyg-team/pytorch_geometric#706]
## 🐛 Bug

Implementing `InMemoryDataset` using Zachary data file causes error after processing.
The download and process seems OK, but when I try to print the dataset, it raises an AttributeError. I found that the `dataset.slice` is `None`.

## To Reproduce

Just run the following script:

```python
import torch
import numpy as np
import torch_geometric as pyg

from os.path import join as pjoin
from urllib.request import urlretrieve


class MyDataset(pyg.data.InMemoryDataset):
    def __init__(self, root, transform=None, pre_transform=None):
        super(MyDataset, self).__init__(root, transform, pre_transform)

    def download(self):
        print('Downloading...')
        url = 'http://vlado.fmf.uni-lj.si/pub/networks/data/ucinet/zachary.dat'
        urlretrieve(url, pjoin(self.raw_dir, self.raw_file_names[0]))

    def process(self):
        N = 34
        # Extract respectively the binary graph and weighted graph
        with open(pjoin(self.raw_dir, self.raw_file_names[0]), 'r') as f:
            content = f.read()
        content = [x.strip().split() for x in content.splitlines()
                   if x.startswith(' ')]

        def str2tensor(x):
            return torch.from_numpy(np.array(x, dtype=int))

        def matx2edgeindx(x):
            return torch.LongTensor([
                (s, t) for s in range(N) for t in range(N) if x[s][t]
            ])

        zache, zachc = str2tensor(content[:N]), str2tensor(content[N:])
        datalist = [
            pyg.data.Data(edge_index=matx2edgeindx(zache)),
            pyg.data.Data(edge_index=matx2edgeindx(zachc)),
        ]

        # Apply transforms if any
        if self.pre_filter is not None:
            datalist = [x for x in datalist if self.pre_filter(x)]

        if self.pre_transform is not None:
            datalist = [self.pre_transform(x) for x in datalist]

        # Construct a big pyg.data.Data object and use torch.save to store
        torch.save(
            self.collate(datalist),
            pjoin(self.processed_dir, self.processed_file_names[0])
        )

    @property
    def raw_file_names(self):
        return ['zachary.dat']

    @property
    def processed_file_names(self):
        return ['data.pt']


dataset = MyDataset('/tmp/zachary')
print(dataset)
```

The error message:

```
Downloading...
Processing...
Done!
Traceback (most recent call last):
  File "test.py", line 63, in <module>
    print(dataset)
  File "/Users/han/miniconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 139, in __repr__
    return '{}({})'.format(self.__class__.__name__, len(self))
  File "/Users/han/miniconda3/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 63, in __len__
    return self.slices[list(self.slices.keys())[0]].size(0) - 1
AttributeError: 'NoneType' object has no attribute 'keys'
```

## Expected behavior

No errors and I should see the edge index.

## Environment

* OS: Mac Pro
* Python version: 3.7.3
* PyTorch version: 1.2.0
* CUDA/cuDNN version:  No CUDA.
* GCC version: LLVM 10.0.1
* Any other relevant information:

**Comment by rusty1s** [comment]
You need to load the data from disk in the `__init__` method:
```python
self.data, self.slices = torch.load(path)
```

**Comment by fingertap** [comment]
Oh, I miss that. But I think it is better organizing the reading into a function `read`.

**Comment by youdar** [comment]
`NotImplementedError` on `InMemoryDataset` when trying to follow [PyG CREATING YOUR OWN DATASETS](https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html)

Reproduce Error Code:
```  
from torch_geometric.data import InMemoryDataset
import os

path = os.path.join(os.getenv('HOME'), 'Downloads/tmp/data')
assert os.path.isdir(path)
o = InMemoryDataset(path)
```     

Mac OS: Monterey 12.3
Python 3.8.10
torch	1.11.0
torch-cluster	1.6.0
torch-geometric	2.0.4
torch-scatter	2.0.9
torch-sparse	0.6.13
torchvision	0.12.0

The error is triggered by:
`../venv/lib/python3.8/site-packages/torch_geometric/data/dataset.py`
line 84 `self._download()`

Which goes to line 40  
```  
@property
    def raw_file_names(self) -> Union[str, List[str], Tuple]:
        r"""The name of the files in the :obj:`self.raw_dir` folder that must
        be present in order to skip downloading."""
        raise NotImplementedError
```  

What am I missing ?
I am trying to create my own dataset in `~/Downloads/tmp/data`
