### ISSUE TITLE
RuntimeError: Triton Error [CUDA]: misaligned address upon using compile() on custom PyG model

### ISSUE THREAD

**Issue by kbali1297** [pyg-team/pytorch_geometric#7102]
### 🐛 Describe the bug

So I declared a custom PyG model layer using : https://pytorch-geometric.readthedocs.io/en/latest/notes/create_gnn.html#implementing-the-edge-convolution 
that inherits from the MessagePassing Class and append a feature to the tensor getting passed through the edge-convolution mlp. I then use these layers to build a resnet kind of graph network in the GCN class. I then use the torch_geometric.compile() method to create a jittable version of my model: 

``` python
 
import torch, torch_geometric
import numpy as np
from torch_geometric.nn import GCNConv, MessagePassing
from torch.nn import Sequential as Seq, Linear, ReLU

device = 'cuda:0' if torch.cuda.is_available() else 'cpu'

class Directional_EdgeConv(MessagePassing):
    def __init__(self, in_channels, out_channels):
        #super().__init__(aggr='sum') #  "Sum" aggregation.
        super().__init__(aggr='mean') # 'Mean' Aggregation
        self.mlp = Seq(Linear(2 * in_channels + 1, out_channels))

        

    def forward(self, x: torch.Tensor, edge_index: torch.Tensor) -> torch.Tensor:
        # x has shape [N, in_channels]
        # edge_index has shape [2, E]

        

        #self.directional_ft = direction_feature(edge_index)
    
        edge_ft = torch.unsqueeze(edge_index[0,:] - edge_index[1,:],1)

        #Shape: [2,E] edge_indices[0,:] has all other nodes connecting to edge_indices[1,:] (less often changing)
        for i in range(edge_ft.shape[0]):
            if edge_ft[i,0] < 0:
                edge_ft[i,0] = -1
            elif edge_ft[i,0] > 0:
                edge_ft[i,0] = 1

        self.directional_ft = edge_ft

        # propagate_type: (x: Tensor)

        return self.propagate(edge_index=edge_index, x=x, size=None)

    def message(self, x_i, x_j):
        # x_i has shape [E, in_channels]
        # x_j has shape [E, in_channels]

        #Expand edge_feature for the entire batch of data
        edge_feature =  self.directional_ft.unsqueeze(0).repeat(x_i.shape[0],1,1)
        
        tmp = torch.cat([x_i, x_j - x_i, edge_feature], dim=-1)  # tmp has shape [E, 2 * in_channels + 1]
        #tmp = torch.cat([x_i, x_j - x_i], dim=-1)
        return self.mlp(tmp)

class GCN(torch.nn.Module):
    def __init__(self, hidden_channels, depth=3, device="", nn_inputs = 1):
        super().__init__()
        torch.manual_seed(1234567)

        self.depth = depth
        self.convIn = Directional_EdgeConv(nn_inputs, hidden_channels).to(device)

        for i in range(1, depth * 2 + 1):
            self.add_module(f'GCNConv{i}', 
                            Directional_EdgeConv(hidden_channels, hidden_channels).to(device))

        self.convOut = Directional_EdgeConv(hidden_channels,1).to(device)

    def forward(self, x: torch.Tensor, edge_index: torch.Tensor):

        #print(edge_index.dtype)
        #print(edge_index.shape)
        x_2 =  self.convIn(x, edge_index)
        
        for i in range(1, self.depth * 2 + 1, 2):
            x_1 = torch.nn.LeakyReLU(inplace=True)(getattr(self, f'GCNConv{i}')(x_2, edge_index))
            x_2 = torch.nn.LeakyReLU(inplace=True)(getattr(self, f'GCNConv{i + 1}')(x_1, edge_index) + x_2)

        x_out = self.convOut(x_2, edge_index) + x
        
        return x_out

SN = 48
# build edge list
def I(i):
    return (i % SN)  # periodic

neighbour_range = 1
edge_index = []
for i in range(SN):
    edge_index.append([I(i), I(i)])
    for j in range(1, neighbour_range + 1):
        edge_index.append([I(i), I(i - j)])
        edge_index.append([I(i), I(i + j)])

edges_torch = torch.from_numpy( np.array(edge_index)).to(device).long()
depth_ = 3
net = GCN(hidden_channels=32,depth=depth_, device=device)
net = torch_geometric.compile(net)

op = net(torch.rand(128,48,1).to(device), edges_torch.transpose(0,1))
print(op)
```
Upon executing the above script I get a traceback as follows:
```
/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_inductor/compile_fx.py:90: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
Traceback (most recent call last):
  File "/home/kartikbali/recurrent-timesteps-sol/Test/Test_script.py", line 110, in <module>
    op = net(torch.rand(128,48,1).to(device), edges_torch.transpose(0,1))
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/kartikbali/recurrent-timesteps-sol/Test/Test_script.py", line 82, in forward
    x_2 =  self.convIn(x, edge_index)
  File "/home/kartikbali/recurrent-timesteps-sol/Test/Test_script.py", line 85, in <graph break in forward>
    x_1 = torch.nn.LeakyReLU(inplace=True)(getattr(self, f'GCNConv{i}')(x_2, edge_index))
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/kartikbali_pyg/tmpxqtibrh5.py", line 232, in forward
    return self.propagate(edge_index=edge_index, x=x, size=None)
  File "/tmp/kartikbali_pyg/tmpxqtibrh5.py", line 186, in propagate
    def propagate(self, edge_index, x, size=None):
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2819, in forward
    return compiled_fn(full_args)
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1222, in g
    return f(*args)
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2386, in debug_compiled_function
    return compiled_function(*args)
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1898, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1247, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1222, in g
    return f(*args)
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2151, in forward
    fw_outs = call_func_with_args(
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1247, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 248, in run
    return model(new_inputs)
  File "/tmp/torchinductor_kartikbali/kw/ckwuzdtzrnuq37sx7enpucbsdwnqko2z565relq7h463ekepeh4y.py", line 203, in call
    triton__1.run(primals_3, buf2, 18432, grid=grid(18432), stream=stream0)
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 190, in run
    result = launcher(
  File "<string>", line 6, in launcher
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/triton/compiler.py", line 1678, in __getattribute__
    self._init_handles()
  File "/home/kartikbali/anaconda3/envs/torch_graph/lib/python3.10/site-packages/triton/compiler.py", line 1671, in _init_handles
    mod, func, n_regs, n_spills = cuda_utils.load_binary(self.metadata["name"], self.asm["cubin"], self.shared, device)
RuntimeError: Triton Error [CUDA]: misaligned address
```
Could anyone let me know what's the problem here?
Note: The above error pops only when I use torch_geometric.compile() on my model. The rest of the script runs fine.

### Environment

* PyG version: 2.3.0
* PyTorch version: 2.0.0
* OS: Ubuntu 20.04
* Python version: 3.10.10
* CUDA/cuDNN version: 11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for reporting. Need to run this on my own as well to dig deeper, but I think you should definitely avoid the LeakyRELU class instantiation inside the model forward pass. Can you check if dropping this resolves the issue?

**Comment by kbali1297** [comment]
Thank you for the reply! I dropped it and instantiated the leaky relu layer inside the init method. Unfortunately it still throws the same error.

**Comment by kbali1297** [comment]
Hi, just to make the discussion active once again. Is there a solution to this yet? I just want to append a direction tensor to tmp before it passes through the mlp.

**Comment by rusty1s** [comment]
Sorry for the late reply, I was on vacation. This is an interesting bug, and I am quite certain it is coming from PyTorch directly. If I replace `edge_ft` in `message` by
```python
edge_ft = x_i.new_ones(x_i.shape[0], x_i.shape[1], 4)
```
it is working fine, but when I use
```python
edge_ft = x_i.new_ones(x_i.shape[0], x_i.shape[1], 1)
```
the misaligned address error appears. It appears to me that PyTorch somehow assumes a certain feature dimension.

**Comment by kbali1297** [comment]
Yes you're right. When the number of channels of edge_ft tensor (edge_ft.shape[-1]) equals those of x_i, there doesn't seem to be an error. Does misalignement mean that the number of channels of x_i and edge_ft aren't the same ?

**Comment by rusty1s** [comment]
I imagine this is a PyTorch bug, which somehow has trouble to with compiling concatenation + scatter when feature dimension is not a power of 2. I'm not sure how I can resolve this on our end :(

**Comment by kbali1297** [comment]
Thank you for clarifying this. I hope this issue gets resolved or at least addressed in the future versions.

**Comment by akihironitta** [comment]
Closing this as it's not reproducible on the latest PyG and a PyTorch nightly release. Please let me know if you're still encountering the issue as I'm happy to follow up on this if reproducible.
