### ISSUE TITLE
Shape of mask error in remove_self_loops() while calling cheb_conv

### ISSUE THREAD

**Issue by LaurentBerder** [pyg-team/pytorch_geometric#7123]
### 🐛 Describe the bug

Hi,

I've recently been working on temporal graphs with pytorch_geometric_temporal, and am hitting a roadblock with a call to pytorch_geometric functions, so I thought I'd see if I can get help here (as a complement to the [issue I posted on torch_geometric_temporal's Github](https://github.com/benedekrozemberczki/pytorch_geometric_temporal/issues/224)).

So my dataset is a `torch_geometric_temporal.signal.dynamic_graph_temporal_signal.DynamicGraphTemporalSignal`, basically a stack of temporal snapshots, which are all `torch_geometric.data.data.Data` themselves.

Here's a breakdown of what the dataset looks like:
Here are some values to explain the shape of my dataset:

```python
nb_nodes = 715
nb_edges = 13339
nb_node_features = 3
nb_edge_features = 2
nb_timesteps = 385
days_in = 30
days_out = 30
```

dataset
|--node_features: (nb_timesteps, nb_nodes, nb_node_features, days_in)
|--node_targets: (nb_timesteps, nb_nodes, days_out)
|--edge_index: (nb_timesteps, 2, nb_edges, days_in)
|--edge_features: (nb_timesteps, nb_edge_features, nb_edges, days_in)

If I take one of the 385 timesteps, I get a Data such as this one:
```python
snapshot = next(iter(train_dataset))
snapshot
>>>Data(x=[715, 3, 30], edge_index=[2, 13339, 30], edge_attr=[2, 13339, 30], y=[715, 30])
```

I designed a rather simple model 
```python
from torch_geometric_temporal.nn import GConvLSTM

class DynGraphModel(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, K):
        super(DynGraphModel, self).__init__()
        self.conv = GConvLSTM(input_dim, hidden_dim, K)
        self.linear = torch.nn.Linear(hidden_dim, output_dim)
    def forward(self, x, edge_index, edge_attr, H, C):
        h_0, c_0 = self.conv(x, edge_index, edge_attr, H, C)
        h = F.relu(h_0)
        out = self.linear(h)
        return h, h_0, c_0

hidden_channels = 32

#K is the number of hops in the graph
model = DynGraphModel(input_dim=nb_node_features, hidden_dim=hidden_channels, output_dim=1, K=1)
H = None
C = None
```

But when I try to forward it, it fails with the below stacktrace:
```python
y_hat = model(x=snapshot.x, edge_index=snapshot.edge_index, edge_attr=snapshot.edge_attr, H=H, C=C)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<stdin>", line 7, in forward
  File "python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "python3.7/site-packages/torch_geometric_temporal/nn/recurrent/gconv_lstm.py", line 231, in forward
    I = self._calculate_input_gate(X, edge_index, edge_weight, H, C, lambda_max)
  File "site-packages/torch_geometric_temporal/nn/recurrent/gconv_lstm.py", line 167, in _calculate_input_gate
    I = self.conv_x_i(X, edge_index, edge_weight, lambda_max=lambda_max)
  File "python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "python3.7/site-packages/torch_geometric/nn/conv/cheb_conv.py", line 165, in forward
    batch=batch,
  File "python3.7/site-packages/torch_geometric/nn/conv/cheb_conv.py", line 122, in __norm__
    edge_index, edge_weight = remove_self_loops(edge_index, edge_weight)
  File "python3.7/site-packages/torch_geometric/utils/loop.py", line 66, in remove_self_loops
    return edge_index, edge_attr[mask]
IndexError: The shape of the mask [13339, 30] at index 0 does not match the shape of the indexed tensor [2, 13339, 30] at index 0
```

What's frustrating (apart from the fact that it's not working) is that the fail happens when trying to remove self loops, while my data doesn't contain any:
```python
snapshot.has_self_loops()
>>>False
```

What could I be doing wrong?

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.12.1
* OS: Linux
* Python version: 3.7
* CUDA/cuDNN version: cu116
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* torch_geometric_temporal: 0.54.0

**Comment by EdisonLeeeee** [comment]
Your `edge_attr` should be in the shape `(13339, 30)` (`(num_edges, num_attributes)`), indicating the attribute of each edge.

**Comment by LaurentBerder** [comment]
Hi @EdisonLeeeee, thanks for coming back to me.
You mean `(13339, 2)` then? Since there are only 2 features per edge.

However, the `30` dimension comes from the fact that I wanted each of my snapshot to carry the information of the past 30 timesteps (it's the same thing for the node features).

I'll try without this and tell you if it worked.

**Comment by EdisonLeeeee** [comment]
Oh, your `edge_attr` should be in the shape `(13339, 30, 2)` then. You need to make sure the first two dimensions of `edge_attr` are matching the last two dimensions of `edge_index`. 

However, PyG does not recommend the 3D input of `edge_index`. It will merge the 30 days of `edges_index` into one after `remove_self_loops`, i.e., `(2, 13999, 30)` -> `(2, 13999*30)`

**Comment by LaurentBerder** [comment]
Awesome, I've had the time to test it, and it does work!

I need to rethink my data shaping (so far I just used some `np.swapaxis()` with the previously existing shapes.

And I probably need to understand a bit more about what you said there:
`However, PyG does not recommend the 3D input of edge_index. It will merge the 30 days of edges_index into one after remove_self_loops, i.e., (2, 13999, 30) -> (2, 13999*30)`
Because the output seems to be in the requested format.

**Comment by EdisonLeeeee** [comment]
Sorry for the late response. TBH, I'm not so familiar with PyTorch-Geometric-Temporal library and the `GConvLSTM` layer. If I understood it right, the shape of `edge_index` in each snapshot should be `(2, num_edges)`, which is also expected by PyG.

**Comment by Sanjaykrishnamurthy** [comment]
I knw its quite sometime.. but for others, the edge_index should be 2d and the temporal is included by having it as list of edge_indexes. like [edge_index_day1, edge_index_day2 ... ] etc
