### ISSUE TITLE
Model transformer can't trace global pooling layers

### ISSUE THREAD

**Issue by adamjsanders277** [pyg-team/pytorch_geometric#7165]
### 🐛 Describe the bug

The global pooling layers, for example `global_add_pool`, cannot be traced using a Transformer object. 

Reproducer:
```python
import torch
from torch_geometric.nn.fx import Transformer
from torch_geometric.nn.pool import global_add_pool


class DummyTransformer(Transformer):
    def __init__(self, module, debug=False):
        super().__init__(module, debug=debug)

    def call_global_pooling_module(self, node, target, name):
        print("Global pool transform")


class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x, batch):
        return global_add_pool(x, batch)


model = Model()
transformer = DummyTransformer(model)
transformer.transform()
```

Error:
```
Traceback (most recent call last):
  File "/Users/adams/repro.py", line 23, in <module>
    transformer = DummyTransformer(model)
  File "/Users/adams/repro.py", line 8, in __init__
    super().__init__(module, debug=debug)
  File "/Users/adams/test_venv/lib/python3.9/site-packages/torch_geometric/nn/fx.py", line 73, in __init__
    self.gm = symbolic_trace(module)
  File "/Users/adams/test_venv/lib/python3.9/site-packages/torch_geometric/nn/fx.py", line 366, in symbolic_trace
    return GraphModule(module, Tracer().trace(module, concrete_args))
  File "/Users/adams/test_venv/lib/python3.9/site-packages/torch_geometric/nn/fx.py", line 359, in trace
    'output', 'output', (self.create_arg(fn(*args)), ), {},
  File "/Users/adams/repro.py", line 19, in forward
    return global_add_pool(x, batch)
  File "/Users/adams/test_venv/lib/python3.9/site-packages/torch_geometric/nn/pool/glob.py", line 29, in global_add_pool
    dim = -1 if x.dim() == 1 else -2
  File "/Users/adams/test_venv/lib/python3.9/site-packages/torch/fx/proxy.py", line 413, in __bool__
    return self.tracer.to_bool(self)
  File "/Users/adams/test_venv/lib/python3.9/site-packages/torch/fx/proxy.py", line 276, in to_bool
    raise TraceError('symbolically traced variables cannot be used as inputs to control flow')
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```

### Environment

* PyG version:2.4.0.dev20230412
* PyTorch version: 2.0.0
* OS: MacOS
* Python version: 3.9.1
* CUDA/cuDNN version: NA
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Try
```python
import torch

from torch_geometric.nn import SumAggregation
from torch_geometric.nn.fx import Transformer


class DummyTransformer(Transformer):
    def __init__(self, module, debug=False):
        super().__init__(module, debug=debug)

    def call_global_pooling_module(self, node, target, name):
        print("Global pool transform")


class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.pool = SumAggregation()

    def forward(self, x, batch):
        return self.pool(x, batch)


model = Model()
transformer = DummyTransformer(model)
transformer.transform()
