### ISSUE TITLE
The doc example for "Heterogeneous Convolution Wrapper" can't work?

### ISSUE THREAD

**Issue by zhijiejia** [pyg-team/pytorch_geometric#7175]
### Describe the bug
```https://pytorch-geometric.readthedocs.io/en/latest/notes/heterogeneous.html```, the example network code for ```Heterogeneous Convolution Wrapper``` can't work sucessfully.

#### error info
```
Traceback (most recent call last):
  File "/mnt/workspace/OGB_back.py", line 64, in <module>
    out = model(batch.x_dict, batch.edge_index_dict)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/workspace/OGB_back.py", line 37, in forward
    x_dict = conv(x_dict, edge_index_dict)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/torch_geometric/nn/conv/hetero_conv.py", line 138, in forward
    out = conv((x_dict[src], x_dict[dst]), edge_index, *args,
KeyError: 'author'
```

### env
```bash
torch                        1.12.1
torch-cluster                1.6.1
torch-geometric              2.3.0
torch-scatter                2.1.1
torch-sparse                 0.6.17
```

### whole code
```python
import torch
from tqdm import tqdm
import torch.nn.functional as F
import torch_geometric.transforms as T
from torch_geometric.datasets import OGB_MAG        
from torch_geometric.loader import NeighborLoader  
from torch_geometric.nn import HeteroConv, GCNConv, SAGEConv, GATConv, GraphConv, Linear

import warnings
warnings.filterwarnings("ignore")

import torch_geometric.transforms as T
from torch_geometric.datasets import OGB_MAG
from torch_geometric.nn import HeteroConv, GCNConv, SAGEConv, GATConv, Linear


dataset = OGB_MAG(root='./data', preprocess='metapath2vec', transform=T.ToUndirected())
data = dataset[0]

class HeteroGNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels, num_layers):
        super().__init__()

        self.convs = torch.nn.ModuleList()
        for _ in range(num_layers):
            conv = HeteroConv({
                ('paper', 'cites', 'paper'): GCNConv(-1, hidden_channels),
                ('author', 'writes', 'paper'): SAGEConv((-1, -1), hidden_channels),
                ('paper', 'rev_writes', 'author'): GATConv((-1, -1), hidden_channels, add_self_loops=False),
            }, aggr='sum')
            self.convs.append(conv)

        self.lin = Linear(hidden_channels, out_channels)

    def forward(self, x_dict, edge_index_dict):
        for conv in self.convs:
            x_dict = conv(x_dict, edge_index_dict)
            x_dict = {key: x.relu() for key, x in x_dict.items()}
        return self.lin(x_dict['author'])



dataset = OGB_MAG(root='./data', preprocess='metapath2vec')#, transform=T.ToUndirected(merge=True))
data = dataset[0]
model = HeteroGNN(hidden_channels=64, out_channels=dataset.num_classes, num_layers=2)

print(data)

loader = NeighborLoader(data, num_neighbors=[20] * 3, batch_size=64, input_nodes=('paper', data['paper'].train_mask), num_workers=4, shuffle=True)

train_epoch = 5
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=train_epoch * len(loader), eta_min=0)

for e in range(train_epoch):
    epoch_loss = 0
    tbar = tqdm(loader)
    for idx, batch in enumerate(tbar):
        if idx == 0:
            print(batch)
        batch_size = batch['paper'].batch_size
        out = model(batch.x_dict, batch.edge_index_dict)
        loss = F.cross_entropy(out[:batch_size], batch['paper'].y[:batch_size])
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        scheduler.step()
        epoch_loss += loss.item()
        tbar.set_postfix(loss=epoch_loss / (idx + 1), lr=scheduler.get_lr()[-1])
```

### Environment

* OS: Linus
* Python version: 3.9
* CUDA/cuDNN version: CPU
* How you installed PyTorch and PyG (`conda`, `pip`, source):  pip 
* Any other relevant information (*e.g.*, version of `torch-scatter`):
```bash
  torch                        1.12.1
  torch-cluster                1.6.1
  torch-geometric              2.3.0
  torch-scatter                2.1.1
  torch-sparse                 0.6.17
```

**Comment by EdisonLeeeee** [comment]
It appears that you are loading the dataset twice, and the last one is missing `T.ToUndirected` which is necessary.

**Comment by zhijiejia** [comment]
Thank you for your answer. May I ask why is it necessary to use `T.ToUndirected`?

**Comment by zhijiejia** [comment]
Hi, The question you raised is why `x_dict['author']` is used in example instead of `x_dict['paper']` when inferring the venue of a paper, as the OGB_MAG dataset should infer the publication venue of papers? 
![image](https://user-images.githubusercontent.com/43838913/232184881-b1fa4283-3f8b-4447-9c54-2c0d5dbf61de.png)

**Comment by zhijiejia** [comment]
> Thank you for your answer. May I ask why is it necessary to use `T.ToUndirected`?

I find the answer, `https://github.com/pyg-team/pytorch_geometric/issues/3131`
