### ISSUE TITLE
NotImplementedError occurs when doing "to_hetero"

### ISSUE THREAD

**Issue by CrazyIvanChu** [pyg-team/pytorch_geometric#7234]
### 🐛 Describe the bug

I've been learning how to apply torch_geometric to heterogeneous graphs, and this is the video I followed on YouTube:
https://www.youtube.com/watch?v=qL09oshDKww

Basically I did exactly what Giovanni did in the tutorial, and here is the code:
```
import torch
from torch_geometric.data import HeteroData
import numpy as np

authors = torch.rand((10, 8))
papers = torch.rand((20, 4))

authors_y = torch.rand(10).round()
write_from = torch.tensor(np.random.choice(10, 50, replace=True))
write_to = torch.tensor(np.random.choice(20, 50, replace=True))
write = torch.concat((write_from, write_to)).reshape(-1, 50).long()

cite_from = torch.tensor(np.random.choice(20, 15, replace=True))
cite_to = torch.tensor(np.random.choice(20, 15, replace=True))
cite = torch.concat((cite_from, cite_to)).reshape(-1, 15).long()

data = HeteroData({"author": {"x": authors, "y": authors_y}, "paper": {"x": papers}},
                      author__write__paper={"edge_index": write}, paper__cite__paper={"edge_index": cite})

homogeneous_data = data.to_homogeneous()

import torch_geometric.transforms as T
from torch_geometric.nn import Sequential, Linear
from torch.nn import ReLU

transform = T.RandomNodeSplit()
data = transform(data)

from torch_geometric.nn import SAGEConv, to_hetero

class GNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = SAGEConv((-1,-1), hidden_channels)
        self.conv2 = SAGEConv((-1,-1), out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        x = self.conv2(x, edge_index)
        return x

model = GNN(hidden_channels=64, out_channels=2)
model= to_hetero(model, data_backup.metadata(), aggr='sum')
```

And this is what I got:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Input In [44], in <cell line: 15>()
     12         return x
     14 model = GNN(hidden_channels=64, out_channels=2)
---> 15 model= to_hetero(model, data_backup.metadata(), aggr='sum')

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/to_hetero_transformer.py:120, in to_hetero(module, metadata, aggr, input_map, debug)
     30 r"""Converts a homogeneous GNN model into its heterogeneous equivalent in
     31 which node representations are learned for each node type in
     32 :obj:`metadata[0]`, and messages are exchanged between each edge type in
   (...)
    117         transformation in debug mode. (default: :obj:`False`)
    118 """
    119 transformer = ToHeteroTransformer(module, metadata, aggr, input_map, debug)
--> 120 return transformer.transform()

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/fx.py:157, in Transformer.transform(self)
    155     elif is_global_pooling_op(self.module, op, node.target):
    156         op = 'call_global_pooling_module'
--> 157     getattr(self, op)(node, node.target, node.name)
    159 # Remove all unused nodes in the computation graph, i.e., all nodes
    160 # which have been replaced by node type-wise or edge type-wise variants
    161 # but which are still present in the computation graph.
    162 # We do this by iterating over the computation graph in reversed order,
    163 # and try to remove every node. This does only succeed in case there
    164 # are no users of that node left in the computation graph.
    165 for node in reversed(list(self.graph.nodes)):

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/to_hetero_transformer.py:308, in ToHeteroTransformer.call_method(self, node, target, name)
    306 self.graph.inserting_after(node)
    307 for key in self.metadata[int(self.is_edge_level(node))]:
--> 308     args, kwargs = self.map_args_kwargs(node, key)
    309     out = self.graph.create_node('call_method', target=target,
    310                                  args=args, kwargs=kwargs,
    311                                  name=f'{name}__{key2str(key)}')
    312     self.graph.inserting_after(out)

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/to_hetero_transformer.py:414, in ToHeteroTransformer.map_args_kwargs(self, node, key)
    411     else:
    412         return value
--> 414 args = tuple(_recurse(v) for v in node.args)
    415 kwargs = {k: _recurse(v) for k, v in node.kwargs.items()}
    416 return args, kwargs

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/to_hetero_transformer.py:414, in <genexpr>(.0)
    411     else:
    412         return value
--> 414 args = tuple(_recurse(v) for v in node.args)
    415 kwargs = {k: _recurse(v) for k, v in node.kwargs.items()}
    416 return args, kwargs

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/to_hetero_transformer.py:404, in ToHeteroTransformer.map_args_kwargs.<locals>._recurse(value)
    399         return (
    400             self.find_by_name(f'{value.name}__{key2str(key[0])}'),
    401             self.find_by_name(f'{value.name}__{key2str(key[-1])}'),
    402         )
    403     else:
--> 404         raise NotImplementedError
    405 elif isinstance(value, dict):
    406     return {k: _recurse(v) for k, v in value.items()}

NotImplementedError:
```

### Environment

* PyG version: 2.3.0
* PyTorch version: 2.0.0+cu117
* OS: Linux
* Python version: 3.10.4
* CUDA/cuDNN version: no CUDA/cuDNN
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
This is fixable by adding reverse edge types:
```
data = T.ToUndirected()(data)
```
I will look into the reason for this error though.

**Comment by rusty1s** [comment]
Added a more descriptive error message in https://github.com/pyg-team/pytorch_geometric/pull/7238.

**Comment by CrazyIvanChu** [comment]
> This is fixable by adding reverse edge types:
> 
> ```
> data = T.ToUndirected()(data)
> ```
> 
> I will look into the reason for this error though.

Hi rusty1s, it helps, thank you very much for help! However there is another concern, is the undirected version of the data completely equivalent to the original one?

**Comment by rusty1s** [comment]
It will also make the `paper_cite_paper` relationship undirected. If you do not want this, you can simply do
```python
data['paper', 'written_by', 'author'].edge_index = data['author', 'writes', 'paper'].edge_index.flip([0])

**Comment by CrazyIvanChu** [comment]
Thanks for such quick reply! You're really cool!
So it seems one have to make each of the node types to be the "destination_node_type" for at least once, right?
For a graph like this, I cannot make something like "mline, power_ratio_by, pa", because it just doesn't mean anything, what should I do then?
```
HeteroData(
  mline={ x=[16, 2] },
  pa={ x=[4, 6] },
  (mline, match, mline)={ edge_index=[2, 16] },
  (pa, power_ratio, mline)={ edge_index=[2, 4] }
)
```

**Comment by rusty1s** [comment]
Adding reverse edges is commonly done in heterogeneous GNNs. In your example, only `mline` will receive messages during propagation, and `pa` will never get updated. What do you mean by "it just doesn't mean anything"? I assume that the reverse connection always has a meaning :)

**Comment by CrazyIvanChu** [comment]
Exactly, pa will never get updated...... Actually is there any better way to do this other than make pa a new node type?

**Comment by rusty1s** [comment]
Isn't `pa` already a node type?

**Comment by CrazyIvanChu** [comment]
Yes, it is. I mean since ```pa``` never get updated in my case, is it necessary to involve ```pa``` as a node and make the graph a heterogeneous graph? 
![image](https://user-images.githubusercontent.com/13133542/234800413-f9fcc3b9-f960-4ad1-a7a0-b2dd9f54f7c1.png)
And back to the problem, do I have to make ```"pa, power_ratio, mline"``` undirected in order to make the code run properly?

**Comment by CrazyIvanChu** [comment]
> Isn't `pa` already a node type?

@rusty1s Hi rusty1s, another problem occurs when I'm trying to apply ```global_mean_pool``` to readout the heterogeneous graph:
```
class GNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = SAGEConv((-1,-1), hidden_channels)
        self.conv2 = SAGEConv((-1,-1), out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu
        x = self.conv2(x, edge_index)
        x = global_mean_pool(x["mline"], 1)
        return x
```
And the error:
```
TraceError                                Traceback (most recent call last)
Input In [17], in <cell line: 17>()
     15 # data = T.ToUndirected()(data)
     16 model = GNN(hidden_channels=64, out_channels=2)
---> 17 model= to_hetero(model, data.metadata(), aggr='sum')
     18 out = model.forward(data.x_dict, data.edge_index_dict)

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/to_hetero_transformer.py:119, in to_hetero(module, metadata, aggr, input_map, debug)
     27 def to_hetero(module: Module, metadata: Metadata, aggr: str = "sum",
     28               input_map: Optional[Dict[str, str]] = None,
     29               debug: bool = False) -> GraphModule:
     30     r"""Converts a homogeneous GNN model into its heterogeneous equivalent in
     31     which node representations are learned for each node type in
     32     :obj:`metadata[0]`, and messages are exchanged between each edge type in
   (...)
    117             transformation in debug mode. (default: :obj:`False`)
    118     """
--> 119     transformer = ToHeteroTransformer(module, metadata, aggr, input_map, debug)
    120     return transformer.transform()

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/to_hetero_transformer.py:143, in ToHeteroTransformer.__init__(self, module, metadata, aggr, input_map, debug)
    135 def __init__(
    136     self,
    137     module: Module,
   (...)
    141     debug: bool = False,
    142 ):
--> 143     super().__init__(module, input_map, debug)
    145     self.metadata = metadata
    146     self.aggr = aggr

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/fx.py:73, in Transformer.__init__(self, module, input_map, debug)
     66 def __init__(
     67     self,
     68     module: Module,
     69     input_map: Optional[Dict[str, str]] = None,
     70     debug: bool = False,
     71 ):
     72     self.module = module
---> 73     self.gm = symbolic_trace(module)
     74     self.input_map = input_map
     75     self.debug = debug

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/fx.py:366, in symbolic_trace(module, concrete_args)
    362         self.submodule_paths = None
    364         return self.graph
--> 366 return GraphModule(module, Tracer().trace(module, concrete_args))

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/fx.py:359, in symbolic_trace.<locals>.Tracer.trace(self, root, concrete_args)
    355     for module in self._autowrap_search:
    356         st._autowrap_check(patcher, module.__dict__,
    357                            self._autowrap_function_ids)
    358     self.create_node(
--> 359         'output', 'output', (self.create_arg(fn(*args)), ), {},
    360         type_expr=fn.__annotations__.get('return', None))
    362 self.submodule_paths = None
    364 return self.graph

Input In [17], in GNN.forward(self, x, edge_index)
     10 x = self.conv1(x, edge_index).relu
     11 x = self.conv2(x, edge_index)
---> 12 x = global_mean_pool(x["paper"], 1)
     13 return x

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch_geometric/nn/pool/glob.py:58, in global_mean_pool(x, batch, size)
     37 def global_mean_pool(x: Tensor, batch: Optional[Tensor],
     38                      size: Optional[int] = None) -> Tensor:
     39     r"""Returns batch-wise graph-level-outputs by averaging node features
     40     across the node dimension, so that for a single graph
     41     :math:`\mathcal{G}_i` its output is computed by
   (...)
     56             Automatically calculated if not given. (default: :obj:`None`)
     57     """
---> 58     dim = -1 if x.dim() == 1 else -2
     60     if batch is None:
     61         return x.mean(dim=dim, keepdim=x.dim() <= 2)

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch/fx/proxy.py:413, in Proxy.__bool__(self)
    410             self.tracer.create_proxy('call_function', assert_fn, (self,), {})
    411             return True
--> 413 return self.tracer.to_bool(self)

File ~/anaconda3/envs/play/lib/python3.10/site-packages/torch/fx/proxy.py:276, in TracerBase.to_bool(self, obj)
    269 @compatibility(is_backward_compatible=True)
    270 def to_bool(self, obj: 'Proxy') -> bool:
    271     """Called when a proxy object is being converted to a boolean, such as
    272     when used in control flow.  Normally we don't know what to do because
    273     we don't know the value of the proxy, but a custom tracer can attach more
    274     information to the graph node using create_node and can choose to return a value.
    275     """
--> 276     raise TraceError('symbolically traced variables cannot be used as inputs to control flow')

TraceError: symbolically traced variables cannot be used as inputs to control flow
```
So here is the question: how do I perform "readout" for heterogeneous graphs?

**Comment by rusty1s** [comment]
You would need to write something like
```python
    def forward(self, x, edge_index, batch):
        x = self.conv1(x, edge_index).relu
        x = self.conv2(x, edge_index)
        x = global_mean_pool(x, batch)
        return x

**Comment by CrazyIvanChu** [comment]
> You would need to write something like
> 
> ```python
>     def forward(self, x, edge_index, batch):
>         x = self.conv1(x, edge_index).relu
>         x = self.conv2(x, edge_index)
>         x = global_mean_pool(x, batch)
>         return x
> ```

Sorry rusty1s, I'm a bit confused, this is exactly what I wrote, except I hard coded "batch" to 1. And you saw the error.

**Comment by rusty1s** [comment]
Note that `batch` needs to be a vector, not a scalar. For example,
```python
x = global_mean_pool(x, x.new_zeros(x.size(0), dtype=torch.long)

**Comment by CrazyIvanChu** [comment]
> Note that `batch` needs to be a vector, not a scalar. For example,
> 
> ```python
> x = global_mean_pool(x, x.new_zeros(x.size(0), dtype=torch.long))
> ```

Now I change to this:
```
x = global_mean_pool(x["mline"], x["mline"].new_zeros(x["mline"].size(0), dtype=torch.long))
```
But I still get the same error:
```
......
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```

**Comment by EdisonLeeeee** [comment]
It appears a type here:
```python
x = self.conv1(x, edge_index).relu # should be `relu()`
```

**Comment by CrazyIvanChu** [comment]
> It appears a typo here:
> 
> ```python
> x = self.conv1(x, edge_index).relu # should be `relu()`
> ```

Oh, yes, it's a typo, but somehow I do have relu() for my local code, and I also get the same error.

**Comment by rusty1s** [comment]
Can you show us a minimal reproducible example?

**Comment by CrazyIvanChu** [comment]
> 

My bad, sorry. Here is the minimal reproducible example:

```
from torch_geometric.nn import to_hetero, SAGEConv, global_mean_pool
from torch_geometric.data import HeteroData
import torch


class GNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = SAGEConv((-1, -1), hidden_channels)
        self.conv2 = SAGEConv((-1, -1), out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        x = self.conv2(x, edge_index)
        x = global_mean_pool(x["A"], x["A"].new_zeros(1, dtype=torch.long))
        return x


if __name__ == '__main__':

    A_nodes = torch.tensor([[0.0000, 0.0000],
                            [0.0000, 0.0000],
                            [0.0000, 0.0000],
                            [0.0000, 0.0000],
                            [0.0000, 0.0000],
                            [0.0000, 0.0000],
                            [1.1958, 5.9772],
                            [1.1958, 5.9772],
                            [3.1085, 5.7231],
                            [3.1085, 5.7231],
                            [2.0350, 5.8262],
                            [2.0350, 5.8262],
                            [1.2074, 5.9742],
                            [1.2074, 5.9742],
                            [1.9638, 5.8356],
                            [1.9638, 5.8356]])
    B_nodes = torch.tensor([[2.9253e+01, 2.0026e+01, -3.7300e-02, 6.2484e+00, 0.0000e+00, 4.4500e-02],
                            [2.9253e+01, 2.0000e+01, -1.9000e-03, 1.8299e+00, -2.7001e+02, 4.4500e-02],
                            [2.9253e+01, 2.3081e+01, -6.7800e-02, 7.0000e+00, 8.9998e+01, 4.4500e-02],
                            [2.9253e+01, 3.7495e+01, -1.1590e-01, 5.4700e+00, 3.6000e+02, 4.4500e-02]])
    A_to_A = torch.tensor([[0, 1, 6, 2, 3, 8, 4, 0, 10, 2, 5, 12, 3, 4, 5, 14],
                           [6, 7, 7, 8, 9, 9, 10, 11, 11, 12, 13, 13, 5, 14, 15, 15]])
    B_to_A = torch.tensor([[0, 1, 2, 3],
                           [0, 1, 2, 3]])
    A_to_by_B = torch.tensor([[0, 1, 2, 3],
                              [0, 1, 2, 3]])
    h_data = HeteroData(
        {"A": {"x": A_nodes},
         "B": {"x": B_nodes}},
        A__to__A={"edge_index": A_to_A},
        B__to__A={"edge_index": B_to_A},
        A__toby__B={"edge_index": A_to_by_B}
    )

    model_gnn = GNN(hidden_channels=4, out_channels=1)
    model = to_hetero(model_gnn, metadata=h_data.metadata(), aggr='sum')
    out = model.forward(h_data.x_dict, h_data.edge_index_dict)
    print(out)
```
Here is the error:

```
C:\Users\xxxxx\.conda\envs\env_xxx\python.exe D:\xxxxx\tasks\yyy_controller\minimal.py 
Traceback (most recent call last):
  File "D:\xxxxx\tasks\yyy_controller\minimal.py", line 56, in <module>
    model = to_hetero(model_gnn, metadata=h_data.metadata(), aggr='sum')
  File "C:\Users\xxxxx\.conda\envs\env_xxx\lib\site-packages\torch_geometric\nn\to_hetero_transformer.py", line 119, in to_hetero
    transformer = ToHeteroTransformer(module, metadata, aggr, input_map, debug)
  File "C:\Users\xxxxx\.conda\envs\env_xxx\lib\site-packages\torch_geometric\nn\to_hetero_transformer.py", line 143, in __init__
    super().__init__(module, input_map, debug)
  File "C:\Users\xxxxx\.conda\envs\env_xxx\lib\site-packages\torch_geometric\nn\fx.py", line 73, in __init__
    self.gm = symbolic_trace(module)
  File "C:\Users\xxxxx\.conda\envs\env_xxx\lib\site-packages\torch_geometric\nn\fx.py", line 366, in symbolic_trace
    return GraphModule(module, Tracer().trace(module, concrete_args))
  File "C:\Users\xxxxx\.conda\envs\env_xxx\lib\site-packages\torch_geometric\nn\fx.py", line 359, in trace
    'output', 'output', (self.create_arg(fn(*args)), ), {},
  File "D:\xxxxx\tasks\yyy_controller\minimal.py", line 15, in forward
    x = global_mean_pool(x["A"], x["A"].new_zeros(1, dtype=torch.long))
  File "C:\Users\xxxxx\.conda\envs\env_xxx\lib\site-packages\torch_geometric\nn\pool\glob.py", line 58, in global_mean_pool
    dim = -1 if x.dim() == 1 else -2
  File "C:\Users\xxxxx\.conda\envs\env_xxx\lib\site-packages\torch\fx\proxy.py", line 413, in __bool__
    return self.tracer.to_bool(self)
  File "C:\Users\xxxxx\.conda\envs\env_xxx\lib\site-packages\torch\fx\proxy.py", line 276, in to_bool
    raise TraceError('symbolically traced variables cannot be used as inputs to control flow')
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```

**Comment by rusty1s** [comment]
I see. Currently you have to register the global pooling operator as a module, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/test/nn/test_to_hetero_transformer.py#L443) for an example.

**Comment by CrazyIvanChu** [comment]
> I see. Currently you have to register the global pooling operator as a module, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/test/nn/test_to_hetero_transformer.py#L443) for an example.

I guess it's too early to be happy, because when I create a dataset, I failed to do pool. Please help. This is the code:
```
from torch_geometric.nn import to_hetero, SAGEConv, MeanAggregation, Linear
from torch_geometric.data import HeteroData
import torch
from torch_geometric.loader import DataLoader


class GNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = SAGEConv((-1, -1), hidden_channels)
        self.conv2 = SAGEConv((-1, -1), out_channels)
        self.pool = MeanAggregation()
        self.lin = Linear(out_channels, 1)

    def forward(self, x, edge_index, batch_dict):
        x = self.conv1(x, edge_index).relu()
        x = self.conv2(x, edge_index)
        x = self.pool(x, batch_dict)
        x = self.lin(x)
        return x


if __name__ == '__main__':

    A_nodes = torch.tensor([[0.0000, 0.0000],
                            [0.0000, 0.0000],
                            [0.0000, 0.0000],
                            [0.0000, 0.0000],
                            [0.0000, 0.0000],
                            [0.0000, 0.0000],
                            [1.1958, 5.9772],
                            [1.1958, 5.9772],
                            [3.1085, 5.7231],
                            [3.1085, 5.7231],
                            [2.0350, 5.8262],
                            [2.0350, 5.8262],
                            [1.2074, 5.9742],
                            [1.2074, 5.9742],
                            [1.9638, 5.8356],
                            [1.9638, 5.8356]])
    B_nodes = torch.tensor([[2.9253e+01, 2.0026e+01, -3.7300e-02, 6.2484e+00, 0.0000e+00, 4.4500e-02],
                            [2.9253e+01, 2.0000e+01, -1.9000e-03, 1.8299e+00, -2.7001e+02, 4.4500e-02],
                            [2.9253e+01, 2.3081e+01, -6.7800e-02, 7.0000e+00, 8.9998e+01, 4.4500e-02],
                            [2.9253e+01, 3.7495e+01, -1.1590e-01, 5.4700e+00, 3.6000e+02, 4.4500e-02]])
    A_to_A = torch.tensor([[0, 1, 6, 2, 3, 8, 4, 0, 10, 2, 5, 12, 3, 4, 5, 14],
                           [6, 7, 7, 8, 9, 9, 10, 11, 11, 12, 13, 13, 5, 14, 15, 15]])
    B_to_A = torch.tensor([[0, 1, 2, 3],
                           [0, 1, 2, 3]])
    A_to_by_B = torch.tensor([[0, 1, 2, 3],
                              [0, 1, 2, 3]])
    h_data = HeteroData(
        {"A": {"x": A_nodes},
         "B": {"x": B_nodes}},
        A__to__A={"edge_index": A_to_A},
        B__to__A={"edge_index": B_to_A},
        A__toby__B={"edge_index": A_to_by_B}
    )

    BATCH_SIZE = 32
    dataset = [h_data] * 8000
    data_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

    batch_dict = {
        "A": torch.zeros(BATCH_SIZE, dtype=torch.long),
        "B": torch.zeros(BATCH_SIZE, dtype=torch.long)
    }

    batch = list(data_loader)[0]

    model_gnn = GNN(hidden_channels=4, out_channels=2)
    model = to_hetero(model_gnn, metadata=h_data.metadata(), aggr='sum')
    out = model.forward(batch.x_dict, batch.edge_index_dict, batch_dict)
    print(out)
```
And the error:
```
C:\Users\xxxxxxx\.conda\envs\xxx_opt\python.exe D:\xxxxxxx\tasks\xxx_controller\test.py 
Traceback (most recent call last):
  File "D:\xxxxxxx\tasks\xxx_controller\test.py", line 72, in <module>
    out = model.forward(batch.x_dict, batch.edge_index_dict, batch_dict)
  File "<eval_with_key>.1", line 25, in forward
  File "C:\Users\xxxxxxx\.conda\envs\xxx_opt\lib\site-packages\torch_geometric\nn\aggr\base.py", line 116, in __call__
    raise e
  File "C:\Users\xxxxxxx\.conda\envs\xxx_opt\lib\site-packages\torch_geometric\nn\aggr\base.py", line 109, in __call__
    return super().__call__(x, index, ptr, dim_size, dim, **kwargs)
  File "C:\Users\xxxxxxx\.conda\envs\xxx_opt\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xxxxxxx\.conda\envs\xxx_opt\lib\site-packages\torch_geometric\nn\aggr\basic.py", line 34, in forward
    return self.reduce(x, index, ptr, dim_size, dim, reduce='mean')
  File "C:\Users\xxxxxxx\.conda\envs\xxx_opt\lib\site-packages\torch_geometric\nn\aggr\base.py", line 155, in reduce
    return scatter(x, index, dim, dim_size, reduce)
  File "C:\Users\xxxxxxx\.conda\envs\xxx_opt\lib\site-packages\torch_geometric\utils\scatter.py", line 81, in scatter
    index = broadcast(index, src, dim)
  File "C:\Users\xxxxxxx\.conda\envs\xxx_opt\lib\site-packages\torch_geometric\utils\scatter.py", line 21, in broadcast
    return src.view(size).expand_as(ref)
RuntimeError: The expanded size of the tensor (512) must match the existing size (32) at non-singleton dimension 0.  Target sizes: [512, 2].  Tensor sizes: [32, 1]
```
However, it OK if I set ```BATCH_SIZE``` to 1, which is usually meaningless though. Besides, I find it's impossible to debug the ```forward``` function.
