### ISSUE TITLE
`examples/multi_gpu/distributed_batching.py` hangs indefinitely

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#7289]
### 🐛 Describe the bug
using latest pyg+pyg-lib
```
cd /opt/pyg; pip uninstall -y torch-geometric; rm -rf pytorch_geometric; git clone -b master https://github.com/pyg-team/pytorch_geometric.git; cd /opt/pyg/pytorch_geometric; pip install .; python3 examples/multi_gpu/distributed_batching.py 
Downloading http://snap.stanford.edu/ogb/data/graphproppred/csv_mol_download/hiv.zip
Downloaded 0.00 GB: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  9.90it/s]
Extracting ../../data/OGB/hiv.zip
Processing...
Loading necessary files...
This might take a while.
Processing graphs...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41127/41127 [00:00<00:00, 101908.89it/s]
Converting graphs into PyG objects...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41127/41127 [00:01<00:00, 31035.39it/s]
Saving...
Done!
Let's use 8 GPUs!
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:12355 (errno: 99 - Cannot assign requested address).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:12355 (errno: 99 - Cannot assign requested address).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:12355 (errno: 99 - Cannot assign requested address).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:12355 (errno: 99 - Cannot assign requested address).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:12355 (errno: 99 - Cannot assign requested address).



```

**Comment by puririshi98** [comment]
can repro on a 4 gpu and an 8 gpu machine the same

**Comment by rusty1s** [comment]
Will look into. Thanks for spotting.

**Comment by puririshi98** [comment]
confirmed that using latest pyg+pyg-lib+torch-sparse it works, but once i uninstall torch-sparse then it will hang indefinitely.

also with the same container on a CI machine (instead of running locally on a node i ssh into)(note the sed command):
```
sed -i 's/num_workers=0, persistent_workers=False/num_workers=4, persistent_workers=True/' /workspace/examples/multi_gpu/distributed_sampling.py
+ python3 /workspace/examples/multi_gpu/distributed_batching.py
Downloading http://snap.stanford.edu/ogb/data/graphproppred/csv_mol_download/hiv.zip
Downloaded 0.00 GB: 100%|██████████| 3/3 [00:00<00:00, 25.68it/s]
Processing...
Extracting ../../data/OGB/hiv.zip
Loading necessary files...
This might take a while.
Processing graphs...
100%|██████████| 41127/41127 [00:00<00:00, 56165.32it/s]
Converting graphs into PyG objects...
100%|██████████| 41127/41127 [00:02<00:00, 19707.41it/s]
Done!
Saving...
Let's use 4 GPUs!
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:12355 (errno: 99 - Cannot assign requested address).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:12355 (errno: 99 - Cannot assign requested address).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:12355 (errno: 99 - Cannot assign requested address).
Traceback (most recent call last):
  File "/workspace/examples/multi_gpu/distributed_batching.py", line 145, in <module>
    mp.spawn(run, args=args, nprocs=world_size, join=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 
-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/workspace/examples/multi_gpu/distributed_batching.py", line 88, in run
    for data in train_loader:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/loader/dataloader.py", line 20, in __call__
    return Batch.from_data_list(batch, self.follow_batch,
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/data/batch.py", line 76, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/data/collate.py", line 87, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/data/collate.py", line 174, in _collate
    value = cat(values, dim=cat_dim)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/sparse.py", line 394, in cat
    edge_index, edge_attr = to_edge_index(tensor)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/sparse.py", line 306, in to_edge_index
    return adj.indices().detach().long(), adj.values()
RuntimeError: Cannot get indices on an uncoalesced tensor, please call .coalesce() first
```

**Comment by puririshi98** [comment]
thanks!
