### ISSUE TITLE
FiLMConv explainability fails

### ISSUE THREAD

**Issue by fratajcz** [pyg-team/pytorch_geometric#7303]
### 🐛 Describe the bug

Hi! The new explainer interface fails when we have more than one relation type with the FiLMConv layer:

```
from torch_geometric.explain import Explainer, CaptumExplainer
from torch_geometric.nn import FiLMConv
import torch

from torch_sparse import SparseTensor

class GNN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.gnn = FiLMConv(in_channels=5, out_channels=1, num_relations=2)

    def forward(self, x, edge_index, edge_type=None):
        return self.gnn(x, edge_index, edge_type=edge_type)
    

x = torch.rand((4,5))

edges = torch.LongTensor([[0,1,2,3],
                          [1,2,3,0]])

edge_types = torch.LongTensor([0,1,0,1])

edges_sparse = SparseTensor.from_edge_index(edges, edge_types, (x.shape[0], x.shape[0]))

model = GNN()

out = model(x, edges, edge_types)

print(out)

out = model(x, edges_sparse)

print(out)
```

gives us the following output:
```
tensor([[0.9199],
        [0.1592],
        [0.9595],
        [0.0655]], grad_fn=<AddBackward0>)
tensor([[0.3001],
        [0.4120],
        [0.4261],
        [1.0065]], grad_fn=<AddBackward0>)
```
Interestingly, the outputs are different when we pass edges and edge types seperately than when we pass them together as a SparseTensor. Is this expected? I observed the same for RGCNConv, even though the docs read as if the two cases should be similar.

Then, when we use the SparseTensor for explainability, it fails due to an assertion:
```

explainer = Explainer(
    model,  # It is assumed that model outputs a single tensor.
    algorithm=CaptumExplainer('IntegratedGradients'),
    explanation_type='model',
    node_mask_type='attributes',
    edge_mask_type='object',
    model_config = dict(
        mode='regression',
        task_level="node",
        return_type='raw',  # Model returns probabilities.
    ),
)

hetero_explanation = explainer(
    x,
    edges_sparse,
   index=torch.tensor([1]).cpu(),
)
```

We get the following Error:

```
Traceback (most recent call last):
  File "/home/ubuntu/speos/minimal_example.py", line 49, in <module>
    hetero_explanation = explainer(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/explain/explainer.py", line 198, in __call__
    explanation = self.algorithm(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/explain/algorithm/captum_explainer.py", line 134, in forward
    inputs, add_forward_args = to_captum_input(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/explain/algorithm/captum.py", line 228, in to_captum_input
    raise ValueError(
ValueError: 'x' and 'edge_index' need to be either'Dict' or 'Tensor' got(<class 'torch.Tensor'>, <class 'torch_sparse.tensor.SparseTensor'>)
```

However, when we do the same with only the edges and the edge types seperate:

```
hetero_explanation = explainer(
    x,
    edges,
    edge_type=edge_types,
    index=torch.tensor([1]).cpu(),
)
````

we also get an error:

```
Traceback (most recent call last):
  File "/home/ubuntu/speos/minimal_example.py", line 57, in <module>
    hetero_explanation = explainer(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/explain/explainer.py", line 198, in __call__
    explanation = self.algorithm(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/explain/algorithm/captum_explainer.py", line 162, in forward
    attributions = self.attribution_method.attribute(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/captum/log/__init__.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/captum/attr/_core/integrated_gradients.py", line 274, in attribute
    attributions = _batch_attribution(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/captum/attr/_utils/batching.py", line 78, in _batch_attribution
    current_attr = attr_method._attribute(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/captum/attr/_core/integrated_gradients.py", line 351, in _attribute
    grads = self.gradient_func(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/captum/_utils/gradient.py", line 112, in compute_gradients
    outputs = _run_forward(forward_fn, inputs, target_ind, additional_forward_args)
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/captum/_utils/common.py", line 482, in _run_forward
    output = forward_func(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/explain/algorithm/captum.py", line 66, in forward
    x = self.model(mask.squeeze(0), *args)
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/speos/minimal_example.py", line 14, in forward
    return self.gnn(x, edge_index, edge_type=edge_type)
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/nn/conv/film_conv.py", line 148, in forward
    out = out + self.propagate(edge_index[:, mask], x=lin(
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/nn/conv/message_passing.py", line 476, in propagate
    out = self.explain_message(out, **explain_msg_kwargs)
  File "/mnt/storage/anaconda3/envs/speos/lib/python3.10/site-packages/torch_geometric/nn/conv/message_passing.py", line 589, in explain_message
    assert inputs.size(self.node_dim) == edge_mask.size(0)
AssertionError
```

The first also fails with RGCNConv and RGATConv, but the latter only fails for FiLMConv. 

Is there a way I can make this work for FiLMConv?

Thanks, Florin

### Environment

* PyG version: 2.3.0
* PyTorch version: 2.0.0
* OS: Ubuntu 20.04
* Python version: 3.10.11
* CUDA/cuDNN version: 12.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch_sparse version 0.6.17

**Comment by rusty1s** [comment]
Yes, really sorry about that. This is currently expected for any message passing layers that dynamically adjust the graph-structure on the fly (in `FiLMConv` we do masking per edge type). We have plans to re-write this logic with @Rishi8991 which should hopefully unblock this.

**Comment by fratajcz** [comment]
Ah crap. Thanks for answering, looking forward and hoping you can make it work :)
