### ISSUE TITLE
Issue with the METIS Support on torch_sparse

### ISSUE THREAD

**Issue by beppe2hd** [pyg-team/pytorch_geometric#7304]
### 😵 Describe the installation problem

Hi, I'm going crazy with the `RuntimeError: Not compiled with METIS support` issue. 

I went through the issue: https://github.com/pyg-team/pytorch_geometric/issues/1313 but it did not solve.
This is the final test

```
conda create --name  GNNtest2  python=3.9
conda activate GNNtest2
pip install torch==1.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.12.0+${CUDA}.html
pip install torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+${CUDA}.html
```

That results in the following list of installed libraries

```
torch==1.13.1+cu116
torch-geometric==2.3.1
torch-scatter==2.1.1
torch-sparse==0.6.17
```

But if I run the following pice of code (from Notebook "Customizing Aggregations within Message Passing") it still rise the error `RuntimeError: Not compiled with METIS support`

```
import torch
from torch_geometric.datasets import Planetoid
from torch_geometric.transforms import NormalizeFeatures

dataset = Planetoid(root='data/Planetoid', name='PubMed',
                    transform=NormalizeFeatures())

print()
print(f'Dataset: {dataset}:')

data = dataset[0]  # Get the first graph object.

import torch_sparse
from torch_geometric.loader import ClusterData, ClusterLoader

seed = 42
torch.manual_seed(seed)
cluster_data = ClusterData(data, num_parts=128)  # 1. Create subgraphs.
train_loader = ClusterLoader(cluster_data, batch_size=32,
                             shuffle=True)  # 2. Stochastic partioning scheme.
```

What I'm doing wrong? Any suggestion?

### Environment

* PyG version:2.3.1
* PyTorch version:1.13
* OS: Ubuntu 20.04
* Python version:3.9
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip on conda env
* Any other relevant information (*e.g.*, version of `torch-scatter`): 
*  torch-scatter==2.1.1
*  torch-sparse==0.6.17

**Comment by LukeLIN-web** [comment]
refer https://github.com/pyg-team/pytorch_geometric/issues/1313

**Comment by rusty1s** [comment]
I don't think you are installing the wheels but rather from source. Try
```
pip uninstall torch-scatter torch-sparse
pip install torch-scatter==2.1.0 torch-sparse==0.6.16 -f https://data.pyg.org/whl/torch-1.12.0+cu116.html

**Comment by beppe2hd** [comment]
> I don't think you are installing the wheels but rather from source. Try
> 
> ```
> pip uninstall torch-scatter torch-sparse
> pip install torch-scatter==2.1.0 torch-sparse==0.6.16 -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
> ```

Under this configuration, when I try to `import torch_geometric` I get a **segmentation fault**.
Sorry for the trivial question? How can I install the wheels? 
Could you suggest the right installation command sequence starting form a new conda environment?

**Comment by rusty1s** [comment]
The installation commands look absolutely fine to me. Do you have an installation log when running with `pip install --verbose`? Where does the segfault happen? Can you run this minimal example here?
```python
import torch
from torch_scatter import scatter_max

src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])

out, argmax = scatter_max(src, index, dim=-1)
```

**Comment by beppe2hd** [comment]
> The installation commands look absolutely fine to me. Do you have an installation log when running with `pip install --verbose`? Where does the segfault happen? Can you run this minimal example here?
> 
> ```python
> import torch
> from torch_scatter import scatter_max
> 
> src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
> index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])
> 
> out, argmax = scatter_max(src, index, dim=-1)
> ```

I tried to recreate the environment from scratch (everything like in my original installation but with `pip install torch-scatter==2.1.0 torch-sparse==0.6.16 -f https://data.pyg.org/whl/torch-1.12.0+cu116.html`).
Unfortunately, I got the same:

```
(base) daitan3@daitan3-workstation:~/pythonProjects/myGNNtests$ nvidia-smi
Tue May  9 11:50:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    Off  | 00000000:01:00.0 Off |                  N/A |
| 41%   32C    P8     2W / 280W |     15MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1127      G   /usr/lib/xorg/Xorg                  9MiB |
|    0   N/A  N/A      2853      G   /usr/bin/gnome-shell                4MiB |
+-----------------------------------------------------------------------------+
(base) daitan3@daitan3-workstation:~/pythonProjects/myGNNtests$ conda create --name  GNNtest2  python=3.9
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/daitan3/miniconda3/envs/GNNtest2

  added / updated specs:
    - python=3.9


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main None
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu None
  ca-certificates    pkgs/main/linux-64::ca-certificates-2023.01.10-h06a4308_0 None
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1 None
  libffi             pkgs/main/linux-64::libffi-3.4.2-h6a678d5_6 None
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1 None
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1 None
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1 None
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0 None
  openssl            pkgs/main/linux-64::openssl-1.1.1t-h7f8727e_0 None
  pip                pkgs/main/linux-64::pip-23.0.1-py39h06a4308_0 None
  python             pkgs/main/linux-64::python-3.9.16-h7a1cb2a_2 None
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0 None
  setuptools         pkgs/main/linux-64::setuptools-66.0.0-py39h06a4308_0 None
  sqlite             pkgs/main/linux-64::sqlite-3.41.2-h5eee18b_0 None
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0 None
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0 None
  wheel              pkgs/main/linux-64::wheel-0.38.4-py39h06a4308_0 None
  xz                 pkgs/main/linux-64::xz-5.4.2-h5eee18b_0 None
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_0 None


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate GNNtest2
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... done
(base) daitan3@daitan3-workstation:~/pythonProjects/myGNNtests$ conda activate GNNtest2

(GNNtest2) daitan3@daitan3-workstation:~/pythonProjects/myGNNtests$ pip install torch==1.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Collecting torch==1.13.1+cu116
  Using cached https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp39-cp39-linux_x86_64.whl (1977.9 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.13.1+cu116 typing-extensions-4.5.0

(GNNtest2) daitan3@daitan3-workstation:~/pythonProjects/myGNNtests$ pip install --verbose torch-scatter==2.1.0 torch-sparse==0.6.16 -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
Using pip 23.0.1 from /home/daitan3/miniconda3/envs/GNNtest2/lib/python3.9/site-packages/pip (python 3.9)
Looking in links: https://data.pyg.org/whl/torch-1.12.0+cu116.html
Collecting torch-scatter==2.1.0
  Using cached https://data.pyg.org/whl/torch-1.12.0%2Bcu116/torch_scatter-2.1.0%2Bpt112cu116-cp39-cp39-linux_x86_64.whl (9.0 MB)
Collecting torch-sparse==0.6.16
  Using cached https://data.pyg.org/whl/torch-1.12.0%2Bcu116/torch_sparse-0.6.16%2Bpt112cu116-cp39-cp39-linux_x86_64.whl (3.6 MB)
Collecting scipy
  Using cached scipy-1.10.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
Collecting numpy<1.27.0,>=1.19.5
  Using cached numpy-1.24.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Installing collected packages: torch-scatter, numpy, scipy, torch-sparse
  changing mode of /home/daitan3/miniconda3/envs/GNNtest2/bin/f2py to 775
  changing mode of /home/daitan3/miniconda3/envs/GNNtest2/bin/f2py3 to 775
  changing mode of /home/daitan3/miniconda3/envs/GNNtest2/bin/f2py3.9 to 775
Successfully installed numpy-1.24.3 scipy-1.10.1 torch-scatter-2.1.0+pt112cu116 torch-sparse-0.6.16+pt112cu116

(GNNtest2) daitan3@daitan3-workstation:~/pythonProjects/myGNNtests$ pip install --verbose torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+${CUDA}.html
Using pip 23.0.1 from /home/daitan3/miniconda3/envs/GNNtest2/lib/python3.9/site-packages/pip (python 3.9)
Looking in links: https://data.pyg.org/whl/torch-1.12.0+.html
Collecting torch-geometric
  Using cached torch_geometric-2.3.1-py3-none-any.whl
Requirement already satisfied: numpy in /home/daitan3/miniconda3/envs/GNNtest2/lib/python3.9/site-packages (from torch-geometric) (1.24.3)
Collecting requests
  Using cached requests-2.30.0-py3-none-any.whl (62 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.2.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.6 MB)
Collecting tqdm
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting psutil>=5.8.0
  Using cached psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
Requirement already satisfied: scipy in /home/daitan3/miniconda3/envs/GNNtest2/lib/python3.9/site-packages (from torch-geometric) (1.10.1)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting pyparsing
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.2-py3-none-any.whl (123 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting joblib>=1.1.1
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Installing collected packages: urllib3, tqdm, threadpoolctl, pyparsing, psutil, MarkupSafe, joblib, idna, charset-normalizer, certifi, scikit-learn, requests, jinja2, torch-geometric
  changing mode of /home/daitan3/miniconda3/envs/GNNtest2/bin/tqdm to 775
  changing mode of /home/daitan3/miniconda3/envs/GNNtest2/bin/normalizer to 775
Successfully installed MarkupSafe-2.1.2 certifi-2023.5.7 charset-normalizer-3.1.0 idna-3.4 jinja2-3.1.2 joblib-1.2.0 psutil-5.9.5 pyparsing-3.0.9 requests-2.30.0 scikit-learn-1.2.2 threadpoolctl-3.1.0 torch-geometric-2.3.1 tqdm-4.65.0 urllib3-2.0.2

(GNNtest2) daitan3@daitan3-workstation:~/pythonProjects/myGNNtests$ python
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch_scatter import scatter_max
Segmentation fault (core dumped)
```


On the other hand, following the installation at the top of this tread, your example works perfectly but the `ClusterData` module still fails.

```
(GNNtest) daitan3@daitan3-workstation:~/pythonProjects/myGNNtests$ python
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch_scatter import scatter_max
>>> src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
>>> index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])
>>> out, argmax = scatter_max(src, index, dim=-1)
>>> out
tensor([[0, 0, 4, 3, 2, 0],
        [2, 4, 3, 0, 0, 0]])
>>> 
>>> 
>>> 
>>> from torch_geometric.datasets import Planetoid
>>> from torch_geometric.transforms import NormalizeFeatures
>>> dataset = Planetoid(root='data/Planetoid', name='PubMed', transform=NormalizeFeatures())
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.x
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.tx
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.allx
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.y
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.ty
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.ally
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.graph
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.test.index
Processing...
Done!
>>> data = dataset[0]  # Get the first graph object
>>> from torch_geometric.loader import ClusterData, ClusterLoader
>>> seed = 42
>>> torch.manual_seed(seed)
<torch._C.Generator object at 0x7f342854c990>
>>> cluster_data = ClusterData(data, num_parts=128) 
Computing METIS partitioning...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daitan3/miniconda3/envs/GNNtest/lib/python3.9/site-packages/torch_geometric/loader/cluster.py", line 54, in __init__
    adj, partptr, perm = adj.partition(num_parts, recursive)
  File "/home/daitan3/miniconda3/envs/GNNtest/lib/python3.9/site-packages/torch_sparse/metis.py", line 67, in partition
    cluster = torch.ops.torch_sparse.partition(rowptr, col, value,
  File "/home/daitan3/miniconda3/envs/GNNtest/lib/python3.9/site-packages/torch/_ops.py", line 442, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Not compiled with METIS support
>>> 
```

What do you suggest?

**Comment by beppe2hd** [comment]
I tried the "from source"option and it finally worked (both on linux and MacM1 device)
First of all I installed METIS, and then I worked in the following way.


MAC M1
```
conda create -n GNN_M1  python=3.10
conda activate GNN_M1
pip3 install torch torchvision torchaudio
WITH_METIS=1 python -m pip --no-cache-dir  install  torch-sparse -f https://data.pyg.org/whl/torch-2.0.0+cpu.html 
WITH_METIS=1 python -m pip --no-cache-dir  install  torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
python -m pip --no-cache-dir  install  torch_cluster -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
python -m pip --no-cache-dir  install  torch_spline_conv -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
python -m pip --no-cache-dir  install torch_geometric -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
```


UBUNTU with CUDA support
```
conda create -n GNN_CUDA  python=3.10
conda activate GNN_CUDA
WITH_METIS=1 python -m pip --no-cache-dir  install  torch-sparse -f https://data.pyg.org/whl/torch-2.0.0+cu117.html 
WITH_METIS=1 python -m pip --no-cache-dir  install  torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+cu117.html
python -m pip --no-cache-dir  install  torch_cluster -f https://data.pyg.org/whl/torch-2.0.0+cu117.html
python -m pip --no-cache-dir  install  torch_spline_conv -f https://data.pyg.org/whl/torch-2.0.0+cu117.html
python -m pip --no-cache-dir  install torch_geometric -f https://data.pyg.org/whl/torch-2.0.0+cu117.html
```

I hope this could be useful

Thanks for your support :)
