### ISSUE TITLE
Fail to import Nell dataset

### ISSUE THREAD

**Issue by PangTiger** [pyg-team/pytorch_geometric#7386]
### 🐛 Describe the bug

I tried to import Nell data set using NELL class:
from torch_geometric.datasets import NELL

dataset = NELL(root='data/Nell')
data = dataset[0]

But I got the following error message:
Traceback (most recent call last):
  File "c:\Users\13466\Desktop\USTLab\LabDoc\HPCA23\Nell.py", line 10, in <module>
    dataset = NELL(root='data/Nell')
  File "C:\Users\13466\anaconda3\lib\site-packages\torch_geometric\datasets\nell.py", line 62, in __init__
    super().__init__(root, transform, pre_transform)
  File "C:\Users\13466\anaconda3\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "C:\Users\13466\anaconda3\lib\site-packages\torch_geometric\data\dataset.py", line 97, in __init__
    self._process()
  File "C:\Users\13466\anaconda3\lib\site-packages\torch_geometric\data\dataset.py", line 230, in _process
    self.process()
  File "C:\Users\13466\anaconda3\lib\site-packages\torch_geometric\datasets\nell.py", line 82, in process
    data = read_planetoid_data(self.raw_dir, 'nell.0.001')
  File "C:\Users\13466\anaconda3\lib\site-packages\torch_geometric\io\planetoid.py", line 53, in read_planetoid_data
    row, col, value = SparseTensor.from_dense(x).coo()
AttributeError: type object 'SparseTensor' has no attribute 'from_dense'

### Environment

* PyG version:2.3.1
* PyTorch version:2.0.1
* OS:Windows 11
* Python version:3.10
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
You need to install `torch_sparse` to fix it.
