### ISSUE TITLE
models/basic_gnn.py", line 256, in inference     assert isinstance(loader, NeighborLoader) AssertionError

### ISSUE THREAD

**Issue by LukeLIN-web** [pyg-team/pytorch_geometric#7492]
### 🐛 Describe the bug

```python
dataset = Planetoid("/data/Planetoid", name="Cora")
data = dataset[0]
subgraph_loader = NeighborLoader(copy.copy(data), input_nodes=None,
                                num_neighbors=[-1],
                                batch_size=1024,
                                shuffle=False)
# No need to maintain these features during evaluation:
del subgraph_loader.data.x, subgraph_loader.data.y
subgraph_loader.data.num_nodes = data.num_nodes
subgraph_loader.data.n_id = torch.arange(data.num_nodes)
model = GraphSAGE(
    dataset.num_features,
    hidden_channels=64,
    out_channels=dataset.num_classes,
    num_layers=2,
)
print(subgraph_loader)
print(isinstance(subgraph_loader, NeighborLoader))
y_hat = model.inference(data.x, subgraph_loader).argmax(dim=-1)
```
The output is 
```
NeighborLoader()
True
Traceback (most recent call last):
  File "/root/share/test.py", line 42, in <module>
    y_hat = model.inference(data.x, subgraph_loader).argmax(dim=-1)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch_geometric/nn/models/basic_gnn.py", line 256, in inference
    assert isinstance(loader, NeighborLoader)
AssertionError
```

But I ran `examples/reddit.py` smoothly. The codes look the same.

### Environment

* PyG version: 2.3.1
* PyTorch version: 1.13
* OS: Ubuntu 18.04.6 LTS (x86_64)
* Python version: 3.10.8
* CUDA/cuDNN version:11.6
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip 
* Any other relevant information (*e.g.*, version of `torch-scatter`): 2.1.1+pt113cu116

**Comment by rusty1s** [comment]
I think this needs to be
```python
y_hat = model.inference(subgraph_loader).argmax(dim=-1)

**Comment by LukeLIN-web** [comment]
> I think this needs to be
> 
> ```python
> y_hat = model.inference(subgraph_loader).argmax(dim=-1)
> ```

Thank you for your help. Can I open a PR to using GraphSAGE in  reddit.py?

**Comment by LukeLIN-web** [comment]
When I try to use GraphSAGE in reddit.py, I meet another problem
```python
@torch.no_grad()
def test():
    model.eval()
    y_hat = model.inference(subgraph_loader).argmax(dim=-1)
    y = data.y.to(y_hat.device)

    accs = []
    for mask in [data.train_mask, data.val_mask, data.test_mask]:
        accs.append(int((y_hat[mask] == y[mask]).sum()) / int(mask.sum()))
    return accs
```

```
Traceback (most recent call last):
  File "/root/share/pytorch_geometric/examples/reddit.py", line 72, in <module>
    train_acc, val_acc, test_acc = test()
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/share/pytorch_geometric/examples/reddit.py", line 60, in test
    y_hat = model.inference(subgraph_loader).argmax(dim=-1)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch_geometric/nn/models/basic_gnn.py", line 277, in inference
    x = self.convs[i](x, edge_index)[:batch.batch_size]
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch_geometric/nn/conv/sage_conv.py", line 133, in forward
    out = self.lin_l(out)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch_geometric/nn/dense/linear.py", line 132, in forward
    return F.linear(x, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_addmm)
```
This is because (x.device in GPU, edge_index.device is too big so cannot fit in CPU.

**Comment by rusty1s** [comment]
Yes, you would need to add the `device` argument to the `inference` call I believe. Feel free to open a PR :)
