### ISSUE TITLE
global_max_pool deterministic implementation

### ISSUE THREAD

**Issue by kou18n** [pyg-team/pytorch_geometric#7525]
### 🐛 Describe the bug

I use PyTorch lightning to implement GraphGPS model.
Everything is ok, and I set `deterministic=True`.
```python
  trainer = pl.Trainer(strategy=strategy, devices=devices, max_epochs=args.epochs,
                         log_every_n_steps=5, callbacks=[checkpoint],deterministic=True,logger=logger,precision="16-mixed")
```
Currently, I think no need to use SparseTensor, the results can be reproduced.
For the graph pooling, `global_add_pool` and `global_mean_pool` works good, but `global_max_pool` has some problem.
```python
Traceback (most recent call last):
  File "/home/kou2n/Projects/MalNet_Research/GraphGPS/gps.py", line 335, in <module>
    trainer.fit(model, datamodule)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 92, in launch
    return function(*args, **kwargs)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 976, in _run_stage
    self._run_sanity_check()
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1005, in _run_sanity_check
    val_loop.run()
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 375, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 339, in validation_step
    return self.model(*args, **kwargs)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/pytorch_lightning/overrides/base.py", line 102, in forward
    return self._forward_module.validation_step(*inputs, **kwargs)
  File "/home/kou2n/Projects/MalNet_Research/GraphGPS/gps.py", line 241, in validation_step
    y_hat = self(data.x, data.edge_index, data.batch)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kou2n/Projects/MalNet_Research/GraphGPS/gps.py", line 221, in forward
    x = global_max_pool(x, batch)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch_geometric/nn/pool/glob.py", line 92, in global_max_pool
    return scatter(x, batch, dim=dim, dim_size=size, reduce='max')
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch_geometric/utils/scatter.py", line 98, in scatter
    return src.new_zeros(size).scatter_reduce_(
RuntimeError: scatter_reduce_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
```
Model:
```python
class Model(pl.LightningModule):
    def __init__(self,in_channels: int, hidden_channels: int, out_channels: int, num_layers: int):
        super().__init__()

        self.node_lin = Linear(in_channels, hidden_channels)

        self.convs = ModuleList()
        self.batch_norms= torch.nn.ModuleList()

        for _ in range(num_layers):
            nn = Sequential(
                Linear(hidden_channels, 2 * hidden_channels),
                BatchNorm(2 * hidden_channels),
                ReLU(),
                Linear(2 * hidden_channels, hidden_channels),
            )
            conv = GPSConv(hidden_channels, GINConv(nn), heads=4, attn_dropout=0.5)
            self.convs.append(conv)
            self.batch_norms.append(BatchNorm(hidden_channels))

            in_channels = hidden_channels

        self.lin1 = Linear(hidden_channels, hidden_channels)
        self.batch_norm1 = BatchNorm(hidden_channels)
        self.lin2 = Linear(hidden_channels, out_channels)

        self.train_acc = Accuracy(task='multiclass', num_classes=out_channels)
        self.val_acc = Accuracy(task='multiclass', num_classes=out_channels)
        self.test_acc = Accuracy(task='multiclass', num_classes=out_channels)

    def forward(self, x, edge_index, batch):
        x = self.node_lin(x.squeeze(-1))
        for conv, batch_norm in zip(self.convs, self.batch_norms):
            x = F.relu(batch_norm(conv(x, edge_index, batch)))
        x = global_max_pool(x, batch)
        x = F.relu(self.batch_norm1(self.lin1(x)))
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.lin2(x)
        return F.log_softmax(x, dim=-1)
```

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
If you wanna use `segment_csr`, you need to pass `ptr` from the `Batch` object to this function rather than `batch`. Sorry that this wasn't clear.

**Comment by kou18n** [comment]
> If you wanna use `segment_csr`, you need to pass `ptr` from the `Batch` object to this function rather than `batch`. Sorry that this wasn't clear.

Thank you very much. Problem solved!
