### ISSUE TITLE
Getting `OSError` when trying to import `torch_geometric`(although it seemed that the installation of the package was successful)

### ISSUE THREAD

**Issue by nhadziosma1** [pyg-team/pytorch_geometric#7579]
### 📚 Installation of `torch_geometric`

Hello, I get the same error as described in the issue https://github.com/pyg-team/pytorch_geometric/issues/3575#issue-1064250956, i.e. it seems on the first glance that I am able to install the package `torch_geometric` properly, but after trying to import it I get:
```OSError: /home/my_user/.conda/envs/conda_env_p39_torchGeometric_try5/lib/python3.9/site-packages/torch_cluster/_grid_cuda.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIsEEPT_v```

My setup is different from the setup of the person from the original issue, and I use:
1. Python version `3.9`
2. OS: Linux
3. `torch` version `1.8.0` with CUDA `11.1`, but I have a local installation of CUDA which is `11.5` (that I get after running the shell-command `nvcc --version`).
4. working in a `conda` virtual environment 

I installed `torch` using one of the shell-commands which is provided in the web-page of `pytorch`:
`!conda install --yes --prefix {sys.prefix} pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch`
from which you can see that the version of CUDA used by the package is `11.1`. Thus, by running the following code:
```
import torch

print(torch.version.cuda)
```
I get as output `11.1`.

But, when I run the shell-command:
`!nvcc --version`
I get that the local version of CUDA is `11.5`.

I installed `torch_geometric` using the shell-commands below, and the installation wen through like everything was fine:
```
TORCH = torch.__version__.split("+")[0]
CUDA = "cu" + torch.version.cuda.replace(".","")

!{sys.executable} -m pip install torch-scatter -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!{sys.executable} -m pip install torch-sparse -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!{sys.executable} -m pip install torch-cluster -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!{sys.executable} -m pip install  torch-spline-conv -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!{sys.executable} -m pip install torch-geometric -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
```
where  the actual link from which the packages (libraries) are installed is:   https://data.pyg.org/whl/torch-1.8.0+cu111.html.

I am able to run `torch` itself, although the local version of CUDA, and the version installed together when installing package `torch` are different. Nevertheless, the answer from @rusty1s on the original issue I mentioned (https://github.com/pyg-team/pytorch_geometric/issues/3575#issuecomment-979884919) made me think that in order for `torch_geometric` to work we are not allowed to install a different version of CUDA together with package `torch`, from the one we have installed locally. Is this correct?

I have to run code from some repo which uses `torch_geometric` (and which I need badly for the use case that I am working on). In the repo there is a `requirements.txt` file which specifies that they used version `1.6.1`. After failing to perform the installations from the `requirements.txt`, I quick jumped to try and install all the packages by myself, but up until this point without any luck, because installation of `torch_geometric` gives me headaches. 

I am working on a machine which belongs to my company, and I am restricted from changing the local CUDA version. So, can you give me some advice, what should be my steps in order to install `torch_geometric` on the machine and make the code work? 

It is my first time working with `torch_geometric`, so any help from you would be very helpful to me. Thank you in advance for your help and time.

**Comment by nhadziosma1** [comment]
My second try was to try to make a new `conda` virtual-environment, and do all the installations from scratch, but this time to install a version of `torch` without a GPU at all (i.e. to use CPU). 

It again seemed that the installation of the package `torch_geometric` went through just fine, but when trying to import the package I am getting the following error: 
```
/home/my_user/.conda/envs/conda_env_p39_torchGeometric_try6/lib/python3.9/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: libc10_cuda.so: cannot open shared object file: No such file or directory
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/home/my_user/.conda/envs/conda_env_p39_torchGeometric_try6/lib/python3.9/site-packages/torch_geometric/typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: libc10_cuda.so: cannot open shared object file: No such file or directory
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[31], line 1
----> 1 import torch_geometric
      3 print(f"The location in which the package (i.e. library) called 'torch_geometric'" 
      4       f" is saved is:\n\t '{torch_geometric.__file__}'")
      6 print(f"The version of the package (i.e. library) called 'torch_geometric' is:"
      7       f" \n\t '{torch_geometric.__version__}'\n")

File ~/.conda/envs/conda_env_p39_torchGeometric_try6/lib/python3.9/site-packages/torch_geometric/__init__.py:1
----> 1 import torch_geometric.utils
      2 import torch_geometric.data
      3 import torch_geometric.sampler

File ~/.conda/envs/conda_env_p39_torchGeometric_try6/lib/python3.9/site-packages/torch_geometric/utils/__init__.py:8
      6 from .degree import degree
      7 from .softmax import softmax
----> 8 from .dropout import dropout_adj, dropout_node, dropout_edge, dropout_path
      9 from .augmentation import shuffle_node, mask_feature, add_random_edge
     10 from .sort_edge_index import sort_edge_index

File ~/.conda/envs/conda_env_p39_torchGeometric_try6/lib/python3.9/site-packages/torch_geometric/utils/dropout.py:6
      3 import torch
      5 try:
----> 6     import torch_cluster  # noqa
      7     random_walk = torch.ops.torch_cluster.random_walk
      8 except ImportError:

File ~/.conda/envs/conda_env_p39_torchGeometric_try6/lib/python3.9/site-packages/torch_cluster/__init__.py:18
     16 spec = cuda_spec or cpu_spec
     17 if spec is not None:
---> 18     torch.ops.load_library(spec.origin)
     19 else:  # pragma: no cover
     20     raise ImportError(f"Could not find module '{library}_cpu' in "
     21                       f"{osp.dirname(__file__)}")

File ~/.conda/envs/conda_env_p39_torchGeometric_try6/lib/python3.9/site-packages/torch/_ops.py:104, in _Ops.load_library(self, path)
     99 path = torch._utils_internal.resolve_library_path(path)
    100 with dl_open_guard():
    101     # Import the shared library into the process, thus running its
    102     # static (global) initialization code in order to register custom
    103     # operators with the JIT.
--> 104     ctypes.CDLL(path)
    105 self.loaded_libraries.add(path)

File ~/.conda/envs/conda_env_p39_torchGeometric_try6/lib/python3.9/ctypes/__init__.py:382, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    379 self._FuncPtr = _FuncPtr
    381 if handle is None:
--> 382     self._handle = _dlopen(self._name, mode)
    383 else:
    384     self._handle = handle

OSError: libc10_cuda.so: cannot open shared object file: No such file or directory
```

To describe a little bit in more detail what I used in the new `conda` virtual-environment:
1. Python-version `3.9`
2. `torch`, version `1.8.0` with only CPU. But, I have a local installation of CUDA which is `11.5` (which is what I get after running the shell-command `!nvcc --version`).

I installed `torch` using one of the shell-commands which is provided in the web-page of `pytorch`:
`!conda install --yes --prefix {sys.prefix} pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cpuonly -c pytorch`
from which you can see that the version of CUDA used by the package is `None`. Thus, by running the following code:
```
import torch

print(torch.version.cuda)
```
I get as output `None`. But, when I run the shell-command:
`!nvcc --version`
I get that the local version of CUDA is `11.5`.

I installed `torch_geometric` using the shell-commands below, and the installation went through (so it seemed that everything was fine):
```
TORCH = torch.__version__.split("+")[0]
CUDA_OR_CPU = ("cu" + torch.version.cuda.replace(".","")
               if(torch.version.cuda is not None)
               else
               "cpu"
              )

!{sys.executable} -m pip install torch-scatter -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
!{sys.executable} -m pip install torch-sparse -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
!{sys.executable} -m pip install torch-cluster -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
!{sys.executable} -m pip install  torch-spline-conv -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
!{sys.executable} -m pip install torch-geometric -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
```
where the actual link from which the packages (libraries) are installed is: https://data.pyg.org/whl/torch-1.8.0+cpu.html.
****
The fact that the installation of the package `torch_geometric` doesn't work for me even when I use only a CPU confused me even more. I am not able to delete or change the local-version of GPU because it is simply not possible to do on the company laptop that I am working on, and I don't know if that is the reason why I am having these much problem with the installation, nor how to solve it.

**Comment by nhadziosma1** [comment]
Is it the case that if we have any version of  `pytorch` and/or `torch` that we can install `torch_geometric` without installing `torch-cluster`, if I am installing `torch_geometric` from wheel-files? In other words, can I then just use the code:
```
TORCH = torch.__version__.split("+")[0]
CUDA = "cu" + torch.version.cuda.replace(".","")

!{sys.executable} -m pip install torch-scatter -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!{sys.executable} -m pip install torch-sparse -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!{sys.executable} -m pip install  torch-spline-conv -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!{sys.executable} -m pip install torch-geometric -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html 
```
to install `torch_geometric`, no matter of the version of `torch` which I am using?

Also, as I am quite new to `pytorch` and `torch` as well, so I don't know if the cause of my problems can be related to the fact that I have a local version of CUDA installed, but that I install `torch` using another version of CUDA? There is no shell-command on the web-page of `pytorch` (i.e. on web-page: https://pytorch.org/get-started/previous-versions/) for the CUDA-version 11.5 which is locally installed on the machine on which I run code, so I am forced to install `torch` with a different CUDA-version. How to know in the first place which CUDA-versions are supported by (i.e. compatible to) the machine on which I am running code? Maybe this is a little bit of the topic, but it can help me (and people who face same issues) to understand the problem with installing the `torch_geometric` package.

**Comment by nhadziosma1** [comment]
I tried as you suggested, got rid of the installation of the package `torch_cluster`, and I am still not able to do the installation. 

I created a new `conda` virtual-environment, installed 'torch' using the shell-command:
`!conda install --yes --prefix {sys.prefix} pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 cudatoolkit=11.3 -c pytorch `

I checked if the CUDA-version 11.3. is compatible with the GPU that I am using, and it is compatible (do this is not the source of the problem).

 Then I used the following shell-commands, just to make sure that none of the packages (i.e. libraries) needed by `toch_geometric` are pre-installed in the `conda` virtual-environment:
```
import sys

!{sys.executable} -m pip uninstall torch-scatter -y
!{sys.executable} -m pip uninstall torch-sparse -y
!{sys.executable} -m pip uninstall torch-cluster -y
!{sys.executable} -m pip uninstall torch-spline-conv -y
!{sys.executable} -m pip uninstall torch-geometric -y
```

I used the following shell-commands to install `torch_geometric` (and all the packages/libraries which it needs to work properly), where according to your suggestion I got rid of the shell-command that installs package (i.e. library) `torch_cluster`:
```
import torch
import sys

TORCH = torch.__version__.split("+")[0]
CUDA_OR_CPU = ("cu" + torch.version.cuda.replace(".","")
               if(torch.version.cuda is not None)
               else
               "cpu"
              )

#Note that the package (i.e. library) called 'torhc_cluster' which in the past had to be installed in order for
#    package (i.e. library) 'torch_geometric' to work properly, is no longer needed (so don't install it).
!{sys.executable} -m pip install torch-scatter -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
!{sys.executable} -m pip install torch-sparse -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
!{sys.executable} -m pip install  torch-spline-conv -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
!{sys.executable} -m pip install torch-geometric -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
```
where the actual link from which the packages (libraries) are installed is: https://data.pyg.org/whl/torch-1.10.0+cu113.html.

Then I tried importing the packages (i.e. libraries) `torch-scatter`, `torch-sparse`, `torch-spline-conv`, and `torch-geometric` one by one. I was able to import packages (i.e. libraries) `torch-scatter`, and `torch-spline-conv`, without getting any errors. 
Unfortunately, when I try to import the package (i.e. library) `torch_sparse` I get the following error:
```
RuntimeError                              Traceback (most recent call last)
Cell In[34], line 14
     11 import torch_scatter
     12 getInfoAboutInstalledPackage(torch_scatter)
---> 14 import torch_sparse
     15 getInfoAboutInstalledPackage(torch_sparse)
     17 import torch_spline_conv

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch_sparse/__init__.py:40
     32         raise RuntimeError(
     33             f'Detected that PyTorch and torch_sparse were compiled with '
     34             f'different CUDA versions. PyTorch has CUDA version '
     35             f'{t_major}.{t_minor} and torch_sparse has CUDA version '
     36             f'{major}.{minor}. Please reinstall the torch_sparse that '
     37             f'matches your PyTorch install.')
     39 from .storage import SparseStorage  # noqa
---> 40 from .tensor import SparseTensor  # noqa
     41 from .transpose import t  # noqa
     42 from .narrow import narrow, __narrow_diag__  # noqa

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch_sparse/tensor.py:13
      7 from torch_scatter import segment_csr
      9 from torch_sparse.storage import SparseStorage, get_layout
     12 @torch.jit.script
---> 13 class SparseTensor(object):
     14     storage: SparseStorage
     16     def __init__(
     17         self,
     18         row: Optional[torch.Tensor] = None,
   (...)
     24         trust_data: bool = False,
     25     ):

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch/jit/_script.py:1294, in script(obj, optimize, _frames_up, _rcb, example_inputs)
   1292     if _rcb is None:
   1293         _rcb = _jit_internal.createResolutionCallbackFromFrame(_frames_up + 1)
-> 1294     _compile_and_register_class(obj, _rcb, qualified_name)
   1295     return obj
   1296 elif inspect.isfunction(obj) or inspect.ismethod(obj):

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch/jit/_recursive.py:44, in _compile_and_register_class(obj, rcb, qualified_name)
     42     ast = get_jit_class_def(obj, obj.__name__)
     43     defaults = torch.jit.frontend.get_default_args_for_class(obj)
---> 44     script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
     45     _add_script_class(obj, script_class)
     47 return script_class

RuntimeError: 
object has no attribute sparse_csc_tensor:
  File "/home/q610979/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch_sparse/tensor.py", line 520
            value = torch.ones(self.nnz(), dtype=dtype, device=self.device())
    
        return torch.sparse_csc_tensor(colptr, row, value, self.sizes())
               ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

Also, when I try to import the package (i.e. library) `torch_geometric` I get an error, but I suppose that this is expectable, since importing the package (i.e. library) `torch_sparse` throws an error (which is needed for `torch_geometric` to work properly). The error-message which I get in when I try to import the `torch_geometric` package (i.e. library) is:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[35], line 20
     17 import torch_spline_conv
     18 getInfoAboutInstalledPackage(torch_spline_conv)
---> 20 import torch_geometric
     21 getInfoAboutInstalledPackage(torch_geometric)

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch_geometric/__init__.py:1
----> 1 import torch_geometric.utils
      2 import torch_geometric.data
      3 import torch_geometric.sampler

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch_geometric/utils/__init__.py:3
      1 import copy
----> 3 from .scatter import scatter
      4 from .segment import segment
      5 from .sort import index_sort

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch_geometric/utils/scatter.py:7
      4 import torch
      5 from torch import Tensor
----> 7 import torch_geometric.typing
      8 from torch_geometric.typing import torch_scatter
     10 major, minor, _ = torch.__version__.split('.', maxsplit=2)

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch_geometric/typing.py:37
     34     WITH_TORCH_SCATTER = False
     36 try:
---> 37     import torch_sparse  # noqa
     38     from torch_sparse import SparseTensor
     39     WITH_TORCH_SPARSE = True

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch_sparse/__init__.py:40
     32         raise RuntimeError(
     33             f'Detected that PyTorch and torch_sparse were compiled with '
     34             f'different CUDA versions. PyTorch has CUDA version '
     35             f'{t_major}.{t_minor} and torch_sparse has CUDA version '
     36             f'{major}.{minor}. Please reinstall the torch_sparse that '
     37             f'matches your PyTorch install.')
     39 from .storage import SparseStorage  # noqa
---> 40 from .tensor import SparseTensor  # noqa
     41 from .transpose import t  # noqa
     42 from .narrow import narrow, __narrow_diag__  # noqa

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch_sparse/tensor.py:13
      7 from torch_scatter import segment_csr
      9 from torch_sparse.storage import SparseStorage, get_layout
     12 @torch.jit.script
---> 13 class SparseTensor(object):
     14     storage: SparseStorage
     16     def __init__(
     17         self,
     18         row: Optional[torch.Tensor] = None,
   (...)
     24         trust_data: bool = False,
     25     ):

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch/jit/_script.py:1294, in script(obj, optimize, _frames_up, _rcb, example_inputs)
   1292     if _rcb is None:
   1293         _rcb = _jit_internal.createResolutionCallbackFromFrame(_frames_up + 1)
-> 1294     _compile_and_register_class(obj, _rcb, qualified_name)
   1295     return obj
   1296 elif inspect.isfunction(obj) or inspect.ismethod(obj):

File ~/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch/jit/_recursive.py:44, in _compile_and_register_class(obj, rcb, qualified_name)
     42     ast = get_jit_class_def(obj, obj.__name__)
     43     defaults = torch.jit.frontend.get_default_args_for_class(obj)
---> 44     script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
     45     _add_script_class(obj, script_class)
     47 return script_class

RuntimeError: 
object has no attribute sparse_csc_tensor:
  File "/home/q610979/.conda/envs/conda_env_p39_torchGeometric_try8/lib/python3.9/site-packages/torch_sparse/tensor.py", line 520
            value = torch.ones(self.nnz(), dtype=dtype, device=self.device())
    
        return torch.sparse_csc_tensor(colptr, row, value, self.sizes())
               ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

I suppose that my problems are caused by the package (i.e. library) `torch_scatter`, and I saw in a few more issues that people were struggling with it, but I have no idea how I am I supposed to try to solve the problem. You help would be amazing.

**Comment by rusty1s** [comment]
That looks better :) The issue is that you are using PyTorch 1.10 which does not support `torch.sparse_csc_tensor` yet. The most easiest fix is probably to upgrade your PyTorch version to a later version.

**Comment by nhadziosma1** [comment]
I tried as you suggested, got rid of the installation of the package torch_cluster, and used a later version of `pytorch`, but I am still not able to do the installation.

I created a new `conda` virtual-environment, installed `torch` using the shell-command:
`!conda install --yes --prefix {sys.prefix} pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch`

I checked if the CUDA-version 11.3. is compatible with the GPU that I am using, and it is compatible (so this is not the source of the problem).

Then I used the following shell-commands, just to make sure that none of the packages (i.e. libraries) needed by `toch_geometric` are pre-installed in the `conda` virtual-environment:
```
import sys
!{sys.executable} -m pip uninstall torch-scatter -y
!{sys.executable} -m pip uninstall torch-sparse -y
!{sys.executable} -m pip uninstall torch-cluster -y
!{sys.executable} -m pip uninstall torch-spline-conv -y
!{sys.executable} -m pip uninstall torch-geometric -y
```
I used the following shell-commands to install `torch_geometric` (and all the packages/libraries which it needs to work properly):
```
import torch
import sys

TORCH = torch.__version__.split("+")[0]
CUDA_OR_CPU = ("cu" + torch.version.cuda.replace(".","")
               if(torch.version.cuda is not None)
               else
               "cpu"
              )

#Note that the package (i.e. library) called 'torhc_cluster' which in the past had to be installed in order for
#    package (i.e. library) 'torch_geometric' to work properly, is no longer needed (so don't install it).
!{sys.executable} -m pip install torch-scatter -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
!{sys.executable} -m pip install torch-sparse -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
!{sys.executable} -m pip install  torch-spline-conv -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
!{sys.executable} -m pip install torch-geometric -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA_OR_CPU}.html
```
where the actual link from which the packages (libraries) are installed is: https://data.pyg.org/whl/torch-1.12.1+cu113.html.

Then I tried importing the packages (i.e. libraries) `torch-scatter`, `torch-sparse`, `torch-spline-conv`, and `torch-geometric` one by one. Then a strange thing happens, because the code-cell in which I try to import one of these packages (i.e. libraries) starts the execution (you can see that the execution started because of the `*` symbol left to the code-cell), but in a few seconds it just stops with the execution. It doesn't output any error, but it doesn't execute the code which comes before an import-statement, or the code which comes after the import-statement. I tried to make two `conda` virtual-environments, thinking that maybe I made a mistake somewhere while setting it up, but both times I got the same behaviour. What might be the reason of this problem?

Also, when you say "higher version of `torch`", which exactly versions of the package (i.e. library) `torch` are you referring to?

**Comment by rusty1s** [comment]
Ok, good to see that it finally works with PyTorch 1.13. To install on PyTorch 1.10, you likely have to jump back to earlier versions, see https://data.pyg.org/whl/torch-1.10.1%2Bcu113.html:
```
pip install torch-cluster==1.6.0 torch-scatter==2.0.9 torch-sparse==0.6.13 torch-spline-conv==1.2.1 -f https://data.pyg.org/whl/torch-1.10.1+cu113.html
```
I am not totally sure what's the latest version of PyG that supports PyTorch 1.10, so you may likely try `torch-geometric==2.0` or `torch-geometric==2.1`.
