### ISSUE TITLE
About the edge_index SparseTensor error.

### ISSUE THREAD

**Issue by kou18n** [pyg-team/pytorch_geometric#7583]
### 🐛 Describe the bug

I'm plan to implement the GraphCL model, if the edge_index does not use the SparseTensor everything is good.  

When I apply the edge_index as SparseTensor, and return random_x  `Graph(x=random_x, adj_t=sparse_edge_index, edge_weights=edge_weights)` is also working. 

But directly return x or mask_select_x get the following errors! 
`Graph(x=mask_select_x, adj_t=sparse_edge_index, edge_weights=edge_weights)`

## Code:
```python
import torch
from GCL.augmentors.augmentor import Graph, Augmentor
from torch_geometric.utils import dropout_node,to_edge_index,mask_select
from torch_geometric.utils.num_nodes import maybe_num_nodes
from torch_sparse import SparseTensor

class NodeDropping(Augmentor):
    def __init__(self, pn: float):
        super(NodeDropping, self).__init__()
        self.pn = pn

    def augment(self, g: Graph) -> Graph:        
        x, edge_index, edge_weights = g.unfold()
        edge_index, _ = to_edge_index(edge_index)
        num_nodes = maybe_num_nodes(edge_index)


        retained_edge_index, _, retained_node_mask = dropout_node(edge_index,p=0.1)
        sparse_edge_index = SparseTensor(row = retained_edge_index[0], col = retained_edge_index[1])
        
        
        retained_num_nodes = maybe_num_nodes(retained_edge_index)
        # data.x 's dim is 5.
        random_x = torch.rand(retained_num_nodes,5).to(edge_index.device)
        mask_select_x = mask_select(x,0,retained_node_mask)

        return  Graph(x=mask_select_x, adj_t=sparse_edge_index, edge_weights=edge_weights)

```
## Errors:
```python
Traceback (most recent call last):
  File "/home/kou2n/Projects/MalNet_Research/GraphCL/graphcl_sparse.py", line 270, in <module>
    loss = train(encoder_model, contrast_model, train_loader, optimizer)
  File "/home/kou2n/Projects/MalNet_Research/GraphCL/graphcl_sparse.py", line 126, in train
    _, _, _, _, g1, g2 = encoder_model(data.x, data.adj_t, data.ptr)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kou2n/Projects/MalNet_Research/GraphCL/graphcl_sparse.py", line 111, in forward
    z2, g2 = self.encoder(x2, edge_index2, batch)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kou2n/Projects/MalNet_Research/GraphCL/graphcl_sparse.py", line 90, in forward
    z = conv(z, adj_t)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kou2n/miniconda3/envs/MalNet/lib/python3.10/site-packages/torch_geometric/nn/conv/gin_conv.py", line 85, in forward
    out = out + (1 + self.eps) * x_r
RuntimeError: The size of tensor a (365177) must match the size of tensor b (365178) at non-singleton dimension 0
```

**Comment by rusty1s** [comment]
I assume you need to set `sparse_sizes` when creating the `SparseTensor`. Otherwise, a minimally sized tensor is returned which may no longer match your node dimension.
