### ISSUE TITLE
`assert edge_label_index is not None` when using train_dataloaders in Lightning `trainer.fit()`

### ISSUE THREAD

**Issue by sostema** [pyg-team/pytorch_geometric#7610]
### 🐛 Describe the bug

When using Lightning in conjunction with Pytorch Geometric to train on heterogenous graphs via DDP, there seems to be a bug with using multiple train dataloaders. During debugging, I was able to pinpoint the moment the problem occurs - when updating dataloaders and reinstating wrapped classes. Seems like not all kwargs are being found in the original dataloader, specifically, `input_type` (which is used in my dataloader to sample specific edge types). 

Here's a minimal example of encountering this error, dummy model wrapped into LightningModule and and two dataloaders of FakeDataset. 
```python
import torch
from torch.optim import Adam
from torch_geometric.nn import Linear, HGTConv
from torch_geometric.datasets.fake import FakeHeteroDataset
from torch_geometric.data.lightning import LightningLinkData
import pytorch_lightning as pl

class MLight(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.lin = Linear(-1, 64)
        self.save_hyperparameters()

    def training_step(self, batch, batch_idx):
        z0 = self.lin(list(batch[0].x_dict.values())[0])
        z1 = self.lin(list(batch[1].x_dict.values())[0])
        return None

    def configure_optimizers(self):
        return Adam(self.parameters(), lr=1e-4)

def main():
    fake_data = FakeHeteroDataset().generate_data()
    
    datamodule_1 = LightningLinkData(
        fake_data,
        input_train_edges=fake_data.edge_types[0],
        batch_size=1,
        num_neighbors=[1],
        neg_sampling="binary",
        num_workers=1,
        pin_memory=True,
    )
    datamodule_2 = LightningLinkData(
        fake_data,
        input_train_edges=fake_data.edge_types[1],
        batch_size=1,
        num_neighbors=[1],
        neg_sampling="binary",
        num_workers=1,
        pin_memory=True,
    )
    dl = pl.utilities.CombinedLoader(
        [datamodule_1.train_dataloader(), datamodule_2.train_dataloader()]
    )
    model = MLight()
    for batch in dl:
        model.training_step(batch, 0)
        break
        
    trainer = pl.Trainer(
        strategy=pl.strategies.DDPStrategy(
            static_graph=True,
        ),
    )
    
    trainer.fit(model, train_dataloaders=[datamodule_1.train_dataloader(), datamodule_2.train_dataloader()])

    
if __name__ == "__main__":
    main()
```

Here's the error:
```
Traceback (most recent call last):
  File "/home/testing/testing.py", line 97, in <module>
    main()
  File "/home/testing/testing.py", line 93, in main
    trainer.fit(model, train_dataloaders=[datamodule_1.train_dataloader(), datamodule_2.train_dataloader()])
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 92, in launch
    return function(*args, **kwargs)
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 978, in _run_stage
    self.fit_loop.run()
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 193, in run
    self.setup_data()
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 237, in setup_data
    dl = _process_dataloader(trainer, dl)
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 487, in _process_dataloader
    dataloader = trainer._data_connector._prepare_dataloader(dataloader, shuffle=is_shuffled, mode=stage)
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 200, in _prepare_dataloader
    dataloader = _update_dataloader(dataloader, sampler, mode=mode)
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py", line 134, in _update_dataloader
    dataloader = _reinstantiate_wrapped_cls(dataloader, *dl_args, **dl_kwargs)
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/lightning_fabric/utilities/data.py", line 262, in _reinstantiate_wrapped_cls
    result = constructor(*args, **kwargs)
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/torch_geometric/loader/link_loader.py", line 148, in __init__
    input_type, edge_label_index = get_edge_label_index(
  File "/home/user/conda/envs/testing-env/lib/python3.10/site-packages/torch_geometric/loader/utils.py", line 290, in get_edge_label_index
    assert edge_label_index is not None
AssertionError
```

### Environment

* PyG version: 2.4.0 (installed from git master)
* PyTorch version: 2.0.1
* OS: Ubuntu 18.04.6
* Python version: 3.10.11
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): PyTorch: via mamba, PyG: via pip install from git master
* Any other relevant information (*e.g.*, version of `torch-scatter`): installed latest stable version pyg-lib

**Comment by sostema** [comment]
Looking closer into the issue, apparently, when Lightning collects args and kwargs of an unwrapped dataloader, it collects vars and compares them against signature of `__init__` method of dataloader (`LinkLoader` in this case). But there is no `input_type` in its signature.
Code where attrs are collected:
```python
> /home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py(154)_get_dataloader_init_args_and_kwargs()
-> attrs = {k: v for k, v in vars(dataloader).items() if not k.startswith("_")}
```
Code where params of `__init__` method are collected:
```python
> /home/user/conda/envs/testing-env/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py(163)_get_dataloader_init_args_and_kwargs()
-> params = dict(inspect.signature(dataloader.__init__).parameters)  # type: ignore[misc]
```
As of now, I don't quite grasp how it could be fixed without introducing breaking changes, as it seems to require changing the signature of `LinkLoader().__init__()`. Monkey patching might do the trick, but I am not sure.

**Comment by rusty1s** [comment]
Thanks for reporting. I think I fixed this in https://github.com/pyg-team/pytorch_geometric/pull/7624.
