### ISSUE TITLE
`self.training` is not passed to dropout layer after `to_hetero()` converts model

### ISSUE THREAD

**Issue by akihironitta** [pyg-team/pytorch_geometric#7745]
### 🐛 Describe the bug

Even when a user runs `model.eval()`, the model runs the dropout layer still with `training=True` if the model is converted with `to_hetero(model)`.

```python
import torch
import torch.nn.functional as F

from torch_geometric.nn import SAGEConv, to_hetero
from torch_geometric.data import HeteroData


class GNN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = SAGEConv((-1, -1), 1)

    def forward(self, x, edge_index):
        x = self.conv(x, edge_index)
        return F.dropout(x, p=0.5, training=self.training)


def main():
    data = HeteroData()
    data["paper"].x = torch.randn(100, 3)
    data["author"].x = torch.randn(100, 5)
    data["author", "writes", "paper"].edge_index = torch.randint(0, 100, (2, 100))
    data["paper", "written", "author"].edge_index = torch.randint(0, 100, (2, 100))
    model = GNN()
    model = to_hetero(model, data.metadata(), aggr="sum")
    model.graph.print_tabular()

    model.eval()
    out1 = model(data.x_dict, data.edge_index_dict)
    out2 = model(data.x_dict, data.edge_index_dict)
    assert all(torch.allclose(o1, o2) for o1, o2 in zip(out1.values(), out2.values()))


if __name__ == "__main__":
    main()
```

```
opcode         name                                target                                 args                                                         kwargs
-------------  ----------------------------------  -------------------------------------  -----------------------------------------------------------  ----------------------------------------------
placeholder    x                                   x                                      ()                                                           {}
call_function  x_dict                              <function get_dict at 0x7f1a4ab8dea0>  (x,)                                                         {}
call_method    x__paper                            get                                    (x_dict, 'paper', None)                                      {}
call_method    x__author                           get                                    (x_dict, 'author', None)                                     {}
placeholder    edge_index                          edge_index                             ()                                                           {}
call_function  edge_index_dict                     <function get_dict at 0x7f1a4ab8dea0>  (edge_index,)                                                {}
call_method    edge_index__author__writes__paper   get                                    (edge_index_dict, ('author', 'writes', 'paper'), None)       {}
call_method    edge_index__paper__written__author  get                                    (edge_index_dict, ('paper', 'written', 'author'), None)      {}
call_module    conv__paper                         conv.author__writes__paper             ((x__author, x__paper), edge_index__author__writes__paper)   {}
call_module    conv__author                        conv.paper__written__author            ((x__paper, x__author), edge_index__paper__written__author)  {}
call_function  dropout__paper                      <function dropout at 0x7f1a61582170>   (conv__paper,)                                               {'p': 0.5, 'training': True, 'inplace': False}
call_function  dropout__author                     <function dropout at 0x7f1a61582170>   (conv__author,)                                              {'p': 0.5, 'training': True, 'inplace': False}
output         output                              output                                 ({'paper': dropout__paper, 'author': dropout__author},)      {}
Traceback (most recent call last):
  File "/workspaces/pytorch_geometric/test.py", line 34, in <module>
    main()
  File "/workspaces/pytorch_geometric/test.py", line 30, in main
    assert all(torch.allclose(o1, o2) for o1, o2 in zip(out1.values(), out2.values()))
AssertionError
```

### Environment

* PyG version: 9bc701731
* PyTorch version: 2.0.1
* OS: Linux codespaces-dc5000 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Python version: 3.10.8
* CUDA/cuDNN version: n/a
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by akihironitta** [comment]
This issue stems from `torch.fx.symbolic_trace` being unable to preserve the reference to `self.training`. During symbolic tracing, it sets a bool constant as the argument of `torch.nn.functional.dropout(..., training=True|False)`.

### Workaround
One way to avoid this issue is to replace the functional form `torch.nn.functional.dropout(...)` with its class form `torch.nn.Dropout(...)`

```diff
 class GNN(torch.nn.Module):
     def __init__(self):
         super().__init__()
         ...
+    self.dropout = torch.nn.Dropout(p=0.5)
     def forward(self, x, edge_index):
         ...
-        return F.dropout(x, p=0.5, training=self.training)
+        return self.dropout(x)
```

However, I cannot think of a way to fix this issue on PyG side so that all existing user code is automatically fixed in a newer PyG release.

References:
- https://pytorch.org/docs/2.0/fx.html#miscellanea
- https://pytorch.org/docs/2.0/fx.html#dynamic-control-flow

**Comment by rusty1s** [comment]
Thank you for this great catch. Shall we add a warning for this in `to_hetero`? Furthermore, is there any other workaround for this from PyTorch side (except using the module instance)?

**Comment by rusty1s** [comment]
Added a warning via https://github.com/pyg-team/pytorch_geometric/pull/7772.
