### ISSUE TITLE
Issue with torch-geometric 1.6.3 installation. Error: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_14DispatchKeySetE

### ISSUE THREAD

**Issue by Raymvp** [pyg-team/pytorch_geometric#7815]
### 😵 Describe the installation problem

I tried to reproduce the results of a paper called ["patchGCN"](https://github.com/mahmoodlab/Patch-GCN) I used the author's original code in an environment with the latest packages (like torch-geometric==2.3.1) and achieved results that far exceeded the original paper. However, the authors of the paper used version 1.6.3, so I decided to replicate patchGCN again with this version.

Now, I encounter an error when I try to run it:

> Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from datasets.dataset_survival import Generic_WSI_Survival_Dataset, Generic_MIL_Survival_Dataset
  File "/home/ubuntu/Patch-GCN-master/datasets/dataset_survival.py", line 17, in <module>
    from utils.utils import generate_split, nth
  File "/home/ubuntu/Patch-GCN-master/utils/utils.py", line 20, in <module>
    import torch_geometric
  File "/home/ubuntu/anaconda3/envs/patchGCN1/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/ubuntu/anaconda3/envs/patchGCN1/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/ubuntu/anaconda3/envs/patchGCN1/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/ubuntu/anaconda3/envs/patchGCN1/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/ubuntu/anaconda3/envs/patchGCN1/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/ubuntu/anaconda3/envs/patchGCN1/lib/python3.7/site-packages/torch_sparse/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/ubuntu/anaconda3/envs/patchGCN1/lib/python3.7/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/home/ubuntu/anaconda3/envs/patchGCN1/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ubuntu/anaconda3/envs/patchGCN1/lib/python3.7/site-packages/torch_sparse/_convert.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_14DispatchKeySetE

My Ubuntu 22.04 server does not have CUDA installed. I installed CUDA and cuDNN in the conda environment by installing the cudatoolkit, therefore nvcc is not available.

` 
>>> print(torch.version.cuda)
10.2
>>> print(torch.backends.cudnn.version())
7605
`
I checked my torch and CUDA versions, and found that they were 1.6 and 10.2 respectively. Then I found and successfully installed the corresponding torch_sparse package and other packages from https://pytorch-geometric.com/whl/. After that, I installed torch-geometric==1.6.3 using pip.

When I tried to run my patchGCN model, I got the above error. After searching for related information, I suspect that the issue lies in the mismatch of CUDA, PyTorch, and torch-geometric versions. How should I proceed? Could this be a CUDA issue?

Another question I have is, would different versions of torch-geometric cause differences in model performance? Looking forward to your reply, thank you.

### Environment

* PyG version: OSError: /home/ubuntu/anaconda3/envs/patchGCN1/lib/python3.7/site-packages/torch_sparse/_convert.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_14DispatchKeySetE
* PyTorch version:1.6.0
* OS: ubuntu22.04
* Python version:3.7
* CUDA/cuDNN version:10.2/ 7.6.5
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):torch-cluster 1.5.9  torch-geometric  1.6.3  torch-scatter 2.0.6 torch-sparse 0.6.8 torch-spline-conv 1.2.1

**Comment by rusty1s** [comment]
Yes, you are right with the meaning of this error. How did you install `torch-scatter` and `torch-sparse`? If you are installing from wheels, try the `pip install --no-index` option.
