### ISSUE TITLE
I have already installed pyg and relevant packages, but shows FileNotFoundError: Could not find module 'D:\Python\pythonProject\venv\Lib\site-packages\torch_cluster\_grid_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by fxsxjtu** [pyg-team/pytorch_geometric#8003]
### 🐛 Describe the bug

This is my report:
D:\Python\pythonProject\venv\Scripts\python.exe D:\Python\pythonProject\dynamic_graph\dataset.py 
D:\Python\pythonProject\venv\lib\site-packages\torch_geometric\typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: [WinError 127] The specified procedure could not be found by PyTorch.
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
  File "D:\Python\pythonProject\dynamic_graph\dataset.py", line 9, in <module>
    from torch_geometric.utils import to_undirected
  File "D:\Python\pythonProject\venv\lib\site-packages\torch_geometric\__init__.py", line 1, in <module>
    import torch_geometric.utils
  File "D:\Python\pythonProject\venv\lib\site-packages\torch_geometric\utils\__init__.py", line 8, in <module>
    from .dropout import dropout_adj, dropout_node, dropout_edge, dropout_path
  File "D:\Python\pythonProject\venv\lib\site-packages\torch_geometric\utils\dropout.py", line 6, in <module>
    import torch_cluster  # noqa
  File "D:\Python\pythonProject\venv\lib\site-packages\torch_cluster\__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "D:\Python\pythonProject\venv\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "C:\Users\huawei\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Python\pythonProject\venv\Lib\site-packages\torch_cluster\_grid_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

Process finished with exit code 1

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.1
* OS: windows 11
* Python version: 3.9.13
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip 
* Any other relevant information (*e.g.*, version of `torch-scatter`): 
torch                    2.0.1
torch-cluster            1.6.1+pt20cu118
torch-geometric          2.3.1
torch-sparse             0.6.13
torch-spline-conv        1.2.2+pt20cu118

Can anyone help me? It's very appreciated!

**Comment by rusty1s** [comment]
Can you remove the `torch-cluster` dependency via `pip uninstall torch-cluster` and try again?
