### ISSUE TITLE
some torch-cluster based examples still need torch-cluster installed even w/ faiss

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#8077]
### 🐛 Describe the bug

```
root@riship-dt:/workspace/examples# yes | python3 randlanet_classification.py
Downloading http://vision.princeton.edu/projects/2014/3DShapeNets/ModelNet10.zip
Extracting /workspace/data/ModelNet10/ModelNet10.zip
Processing...
Done!
  0%|                                                                                                                                                              | 0/125 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/examples/randlanet_classification.py", line 220, in <module>
    loss = train(epoch)
  File "/workspace/examples/randlanet_classification.py", line 184, in train
    out = model(data.x, data.pos, data.batch, data.ptr)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/examples/randlanet_classification.py", line 162, in forward
    b1 = self.block1(self.fc0(x), pos, batch)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/examples/randlanet_classification.py", line 119, in forward
    edge_index = knn_graph(pos, self.num_neighbors, batch=batch, loop=True)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/pool/__init__.py", line 166, in knn_graph
    if not torch_geometric.typing.WITH_TORCH_CLUSTER_BATCH_SIZE:
AttributeError: module 'torch_geometric.typing' has no attribute 'WITH_TORCH_CLUSTER_BATCH_SIZE'
```

### Environment

latest versions

**Comment by rusty1s** [comment]
Yes, that's correct. We haven't yet transitioned `knn_graph` to use `faiss`. Need to look into it.
