### ISSUE TITLE
When using DataLoader, the batch attribute of the firsts batch is all zeros

### ISSUE THREAD

**Issue by isaacgg** [pyg-team/pytorch_geometric#8125]
### 🐛 Describe the bug

I'm trying to feed my model using DataLoader with n number of workers, but for some reason, in the first n batches, the batch attribute is a tensor of all zeros, causing my training to fail. 
I leave you here a minimum reproducible example:

`import torch
import numpy as np
from torch_geometric.data import DataLoader, Data

torch.set_default_device("cuda")

data = []
for i in range(16273):
    n_nodes = np.random.randint(1, 1000)
    data.append(Data(x=torch.tensor(np.random.randn(5, 17), dtype=torch.float),
                     edge_index=torch.tensor(np.random.randint(0, 5, (2, 10)), dtype=torch.long).T,
                     y=torch.tensor(np.random.randint(0, 1), dtype=torch.uint8),
                     ))

loader = DataLoader(data, batch_size=32, shuffle=True, num_workers=4, generator=torch.Generator(device="cuda"))
batches = []
for batch in loader:
    batches.append(batch.batch)
`

It's also producing these warnings which I guess they are the real problem:
[W ..\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[W ..\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[W ..\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[W ..\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.1+cu118
* OS: Win10
* Python version: 3.10.8
* CUDA/cuDNN version: 
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip env
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
I am sorry, but can you clarify the issue for me? Printing out `batch.batch` in the loader loop yields the correct result for me:
```
tensor([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,
         3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
         7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10,
        10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14,
        14, 14, 14, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17,
        18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21,
        21, 21, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25,
        25, 25, 25, 25, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28,
        28, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31])

**Comment by isaacgg** [comment]
But batch.batch is the last sample of the list, the problem is in the first batches.
In my case at least, if I print out `batches[0]` or `batches[3]` (up until the `num_workers`) yields this output:

```
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
```
along with the warnings I copied in the op.

Batches after this first ones yields a correct batch value, as in your case

**Comment by rusty1s** [comment]
Do you have a reproducible script? I cannot get your script to work, since you are using `cuda` as the default device, which does not support `num_workers > 0`. Running this on CPU works totally fine.

**Comment by isaacgg** [comment]
My reproducible script is in the first message but yeah I'm using cuda. 
In fact, this code works fine with `num_workers = 1`

**Comment by rusty1s** [comment]
I am getting
```
Traceback (most recent call last):
  File "/home/matthias/github/pytorch_geometric/alpha/bug8.py", line 22, in <module>
    for batch in loader:
  File "/home/matthias/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "/home/matthias/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 386, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/matthias/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1084, in __init__
    self._reset(loader, first_iter=True)
  File "/home/matthias/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1117, in _reset
    self._try_put_index()
  File "/home/matthias/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1351, in _try_put_index
    index = self._next_index()
  File "/home/matthias/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/matthias/miniconda3/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 283, in __iter__
    for idx in self.sampler:
  File "/home/matthias/miniconda3/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 165, in __iter__
    yield from map(int, torch.randperm(n, generator=generator).numpy())
  File "/home/matthias/miniconda3/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```
when running the script on PyTorch 2.1.

**Comment by rusty1s** [comment]
Yes, I was running the entire script, but I am on PyTorch 2.1 now and it is hard to downgrade for me. Anyway, I find it very confusing that this scripts works on your end, since `num_workers>0` on CUDA tensors is not supported.
