### ISSUE TITLE
Assertion Error raised in metapath2vec without an explicit error message

### ISSUE THREAD

**Issue by SHamda** [pyg-team/pytorch_geometric#8205]
### 🐛 Describe the bug

I am encountering inconsistent error messages when using the MetaPath2Vec module from the torch_geometric library. The issue arises when I try to set the values for `walk_length` and `context_size`. Depending on the values I choose, I receive different error messages that make it challenging to resolve the problem.

I have a heterogeneous graph as shown in the provided code snippet. I'm using the MetaPath2Vec module to perform node embedding with the following configuration:

```
HeteroData(
  word={ x=[32390, 8] },
  root={ x=[2252, 8] },
  lemma={ x=[14944, 8] },
  tweet={
    x=[9682, 8],
    y=[9682],
  },
  (lemma, links, tweet)={ edge_index=[2, 88662] },
  (root, links, tweet)={ edge_index=[2, 80569] },
  (word, in, tweet)={ edge_index=[2, 93776] }
)
```
The configuration:

```
from torch_geometric.nn import MetaPath2Vec
metapath = [
    ('word', 'in', 'tweet'),
    ('lemma', 'links', 'tweet'),
    ('root', 'links', 'tweet'),
]

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = MetaPath2Vec(data.edge_index_dict, embedding_dim=64,
                     metapath=metapath, walk_length=2, context_size=6,
                     walks_per_node=5, num_negative_samples=5,
                     sparse=True).to(device)

loader = model.loader(batch_size=128, shuffle=True, num_workers=6)
optimizer = torch.optim.SparseAdam(list(model.parameters()), lr=0.01)
```
When walk_length + 1 is less than context_size, I receive an AssertionError indicating the problem:
```
AssertionError                            Traceback (most recent call last)

[<ipython-input-58-bbd9357b905c>](https://localhost:8080/#) in <cell line: 9>()
      7 
      8 device = 'cuda' if torch.cuda.is_available() else 'cpu'
----> 9 model = MetaPath2Vec(data.edge_index_dict, embedding_dim=64,
     10                      metapath=metapath, walk_length=2, context_size=6,
     11                      walks_per_node=5, num_negative_samples=5,

[/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/models/metapath2vec.py](https://localhost:8080/#) in __init__(self, edge_index_dict, embedding_dim, metapath, walk_length, context_size, walks_per_node, num_negative_samples, num_nodes_dict, sparse)
     83             self.rowcount_dict[keys] = rowptr[1:] - rowptr[:-1]
     84 
---> 85         assert walk_length + 1 >= context_size
     86         if walk_length > len(metapath) and metapath[0][0] != metapath[-1][-1]:
     87             raise AttributeError(

AssertionError:
```

When I increase walk_length, I receive a different AttributeError indicating the problem:

```
AttributeError                            Traceback (most recent call last)

[<ipython-input-59-2d4888523ad8>](https://localhost:8080/#) in <cell line: 9>()
      7 
      8 device = 'cuda' if torch.cuda.is_available() else 'cpu'
----> 9 model = MetaPath2Vec(data.edge_index_dict, embedding_dim=64,
     10                      metapath=metapath, walk_length=5, context_size=6,
     11                      walks_per_node=5, num_negative_samples=5,

[/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/models/metapath2vec.py](https://localhost:8080/#) in __init__(self, edge_index_dict, embedding_dim, metapath, walk_length, context_size, walks_per_node, num_negative_samples, num_nodes_dict, sparse)
     85         assert walk_length + 1 >= context_size
     86         if walk_length > len(metapath) and metapath[0][0] != metapath[-1][-1]:
---> 87             raise AttributeError(
     88                 "The 'walk_length' is longer than the given 'metapath', but "
     89                 "the 'metapath' does not denote a cycle")

AttributeError: The `walk_length` is longer than the given `metapath`, but the `metapath` does not denote a cycle
```
I've tried various values for `walk_length` and `context_size`, but I can't find a value that avoids getting trapped between these two error messages.

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
The second error suggests that the metapaths used need to form a cycle, for example, a valid metapath could be
```
metapath = [
    ('author', 'writes', 'paper'),
    ('paper', 'published_in', 'venue'),
    ('venue', 'publishes', 'paper'),
    ('paper', 'written_by', 'author'),
]
```
where `author -> paper -> venue -> paper -> author` forms a cycle.

**Comment by SHamda** [comment]
But that's not conceivable since I cant link nodes unless it's semantically sound. Any approach to tackle this constraint ?

**Comment by EdisonLeeeee** [comment]
Doesn't  that metapath work for you?
```
data = T.ToUndirected()(data) # make undirected
metapath = [
    ('word', 'in', 'tweet'),
    ('tweet', 'links', 'lemma'),
    ('lemma', 'links', 'tweet'),
    ('tweet', 'links', 'root'),
    ('root', 'links', 'tweet'),
    ('tweet', 'in', 'word'),
]
or
metapath = [
    ('word', 'in', 'tweet'),
    ('tweet', 'links', 'lemma'),
    ('lemma', 'links', 'tweet'),
    ('tweet', 'in', 'word'),
]
```

**Comment by SHamda** [comment]
Yes that solved the error, thank you very much.
```
def train(epoch, log_steps=100, eval_steps=2000):
    model.train()

    total_loss = 0
    for i, (pos_rw, neg_rw) in enumerate(loader):
        optimizer.zero_grad()
        loss = model.loss(pos_rw.to(device), neg_rw.to(device))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        if (i + 1) % log_steps == 0:
            print((f'Epoch: {epoch}, Step: {i + 1:05d}/{len(loader)}, '
                   f'Loss: {total_loss / log_steps:.4f}'))
            total_loss = 0

        if (i + 1) % eval_steps == 0:
            acc = test()
            print((f'Epoch: {epoch}, Step: {i + 1:05d}/{len(loader)}, '
                   f'Acc: {acc:.4f}'))
```
This train function raised this error, is it related to edge_index dict ? I already ran this same graph with HGT and it caused no issue so I'm fairly certain that edge_index is properly initiated
```
---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

[<ipython-input-73-050f25229b34>](https://localhost:8080/#) in <cell line: 16>()
     15 
     16 for epoch in range(1, 6):
---> 17     train(epoch)
     18     acc = test()
     19     print(f'Epoch: {epoch}, Accuracy: {acc:.4f}')

4 frames

[<ipython-input-72-6113361ebfc3>](https://localhost:8080/#) in train(epoch, log_steps, eval_steps)
      3 
      4     total_loss = 0
----> 5     for i, (pos_rw, neg_rw) in enumerate(loader):
      6         optimizer.zero_grad()
      7         loss = model.loss(pos_rw.to(device), neg_rw.to(device))

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in __next__(self)
    631                 # TODO(https://github.com/pytorch/pytorch/issues/76750)
    632                 self._reset()  # type: ignore[call-arg]
--> 633             data = self._next_data()
    634             self._num_yielded += 1
    635             if self._dataset_kind == _DatasetKind.Iterable and \

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in _next_data(self)
   1343             else:
   1344                 del self._task_info[idx]
-> 1345                 return self._process_data(data)
   1346 
   1347     def _try_put_index(self):

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in _process_data(self, data)
   1369         self._try_put_index()
   1370         if isinstance(data, ExceptionWrapper):
-> 1371             data.reraise()
   1372         return data
   1373 

[/usr/local/lib/python3.10/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    642             # instantiate since we don't know how to
    643             raise RuntimeError(msg) from None
--> 644         raise exception
    645 
    646 

IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/models/metapath2vec.py", line 193, in _sample
    return self._pos_sample(batch), self._neg_sample(batch)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/models/metapath2vec.py", line 151, in _pos_sample
    batch = sample(
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/models/metapath2vec.py", line 245, in sample
    rand *= rowcount[subset].to(rand.dtype).view(-1, 1)
IndexError: index 3480 is out of bounds for dimension 0 with size 2252                
```

**Comment by SHamda** [comment]
No I dont have dangling nodes each node is at least connected to another node. A node that is fully disconnected from the graph is impossible to have based on the graph creation procedure I followed.

This is the data_edge index:

```
{('lemma',
  'links',
  'tweet'): tensor([[    0,     0,     0,  ..., 14939, 14940, 14941],
         [    0,     1,     2,  ...,  8488,  6358,  6358]]),
 ('root',
  'links',
  'tweet'): tensor([[   0,    0,    0,  ..., 2249, 2250, 2251],
         [   0,    1,    2,  ..., 4471, 2369, 4927]]),
 ('word',
  'in',
  'tweet'): tensor([[    0,     0,     0,  ..., 32387, 32388, 32389],
         [    0,     1,     2,  ...,  5247,  5247,  5575]]),
 ('tweet',
  'rev_links',
  'lemma'): tensor([[    0,     1,     2,  ...,  8488,  6358,  6358],
         [    0,     0,     0,  ..., 14939, 14940, 14941]]),
 ('tweet',
  'rev_links',
  'root'): tensor([[   0,    1,    2,  ..., 4471, 2369, 4927],
         [   0,    0,    0,  ..., 2249, 2250, 2251]]),
 ('tweet',
  'rev_in',
  'word'): tensor([[    0,     1,     2,  ...,  5247,  5247,  5575],
         [    0,     0,     0,  ..., 32387, 32388, 32389]])}
```

**Comment by EdisonLeeeee** [comment]
Do you have a minimal example to reproduce?

**Comment by SHamda** [comment]
These are snippets of the dataframes used to build the graph; if needed I can send the full files if that's possible via github:
df_word_instances:
```
Source 	Target 	Weight
W2 	4468735746878955843 	0.639834
W2 	3863119955210405694 	0.292875
W2 	1072576979316715367 	0.413152
W2 	4171912979828082315 	0.250924
W2 	9651611344453744816 	0.320057
```
df_l_r:
```
Source 	Target 	Weight
L2 	4468735746878955843 	0.685274
L2 	8285519424784232400 	0.371808
L2 	3863119955210405694 	0.299002
L2 	1072576979316715367 	0.429556
L2 	4171912979828082315 	0.296800
```
df_w_l:
```
Source 	Target 	Weight
R1 	4468735746878955843 	0.268376
R1 	2433367445389738284 	0.263840
R1 	2588481614342210554 	0.210462
R1 	1855514191727701419 	0.219064
R1 	7139934092196747894 	0.200607
```
This is the code used to build edge indexes
```
import torch
from torch_geometric.data import Data, HeteroData


tww_node_indices = {node_id: index for index, node_id in enumerate(df_word_instances['Target'].unique())}
twr_node_indices = {node_id: index for index, node_id in enumerate(df_l_r['Target'].unique())}
twl_node_indices = {node_id: index for index, node_id in enumerate(df_w_l['Target'].unique())}

lemma_node_indices = {node_id: index for index, node_id in enumerate(df_w_l['Source'].unique())}


word_node_indices = {node_id: index for index, node_id in enumerate(df_word_instances['Source'].unique())}

root_node_indices = {node_id: index for index, node_id in enumerate(df_l_r['Source'].unique())}


# Create edge indices

#link between tweets and lemmas
edge_index_w_l = []
for index, row in df_w_l.iterrows():
    edge_index_w_l.append((lemma_node_indices[row['Source']], twl_node_indices[row['Target']]))
edge_index_w_l = torch.tensor(edge_index_w_l, dtype=torch.long).t().contiguous()


#link between tweets and roots
edge_index_l_r = []
for index, row in df_l_r.iterrows():
    edge_index_l_r.append((root_node_indices[row['Source']], twr_node_indices[row['Target']] ))
edge_index_l_r = torch.tensor(edge_index_l_r, dtype=torch.long).t().contiguous()


#link between words and tweets
edge_index_w_t = []
for index, row in df_word_instances.iterrows():
    edge_index_w_t.append((word_node_indices[row['Source']], tww_node_indices[row['Target']]))
edge_index_w_t = torch.tensor(edge_index_w_t, dtype=torch.long).t().contiguous()

```

This code is used to build the heterodata object (features should be ignored since they are pointless in this context)
```
data = HeteroData()
roots_f = torch.ones(2252,8)
words_f = torch.ones(32390,8)
lemma_f = torch.ones(14944,8)
data['word'].x = words_f.float()
data['root'].x = roots_f.float()
data['lemma'].x = lemma_f.float()
data['tweet'].x = torch.ones(9682,8).float()
data['lemma', 'links', 'tweet'].edge_index = edge_index_w_l
data['root', 'links', 'tweet'].edge_index = edge_index_l_r
data['word', 'in', 'tweet'].edge_index = edge_index_w_t
data['word'].y = None
data['lemma'].y = None
data['root'].y = None
data['tweet'].y = torch.tensor(tw_vec['Class'], dtype=torch.long)
print(data.metadata())
data.validate()
```
The pre-processing:
```
import torch_geometric.transforms as T
data = T.ToUndirected()(data)
```
The use of metapath2vec:
```
from torch_geometric.nn import MetaPath2Vec
metapath = [
    ('word', 'in', 'tweet'),
    ('lemma', 'links', 'tweet'),
    ('root', 'links', 'tweet'),
    ('tweet', 'rev_links', 'lemma'),
    ('tweet', 'rev_links', 'root'),
    ('tweet', 'rev_in', 'word'),
]

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = MetaPath2Vec(data.edge_index_dict, embedding_dim=64,
                     metapath=metapath, walk_length=5, context_size=6,
                     walks_per_node=5, num_negative_samples=5,
                     sparse=True).to(device)

loader = model.loader(batch_size=128, shuffle=True, num_workers=6)
optimizer = torch.optim.SparseAdam(list(model.parameters()), lr=0.01)
```
The training and test loops:
```
def train(epoch, log_steps=100, eval_steps=2000):
    model.train()

    total_loss = 0
    for i, (pos_rw, neg_rw) in enumerate(loader):
        optimizer.zero_grad()
        loss = model.loss(pos_rw.to(device), neg_rw.to(device))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        if (i + 1) % log_steps == 0:
            print((f'Epoch: {epoch}, Step: {i + 1:05d}/{len(loader)}, '
                   f'Loss: {total_loss / log_steps:.4f}'))
            total_loss = 0

        if (i + 1) % eval_steps == 0:
            acc = test()
            print((f'Epoch: {epoch}, Step: {i + 1:05d}/{len(loader)}, '
                   f'Acc: {acc:.4f}'))

@torch.no_grad()
def test(train_ratio=0.1):
    model.eval()

    z = model('tweet', batch=data['tweet'].y_index.to(device))
    y = data['tweet'].y

    perm = torch.randperm(z.size(0))
    train_perm = perm[:int(z.size(0) * train_ratio)]
    test_perm = perm[int(z.size(0) * train_ratio):]

    return model.test(z[train_perm], y[train_perm], z[test_perm], y[test_perm],
                      max_iter=150)


for epoch in range(1, 6):
    train(epoch)
    acc = test()
    print(f'Epoch: {epoch}, Accuracy: {acc:.4f}')
```

**Comment by SHamda** [comment]
Forgot to provide the content of the labels vector y; just assign it 1/0 values randomly.

**Comment by EdisonLeeeee** [comment]
Your code looks good to me overall. I think the problem lies in the `edge_index` data. Could you share me with your data, including
```
data['lemma', 'links', 'tweet'].edge_index = edge_index_w_l
data['root', 'links', 'tweet'].edge_index = edge_index_l_r
data['word', 'in', 'tweet'].edge_index = edge_index_w_t
```

**Comment by SHamda** [comment]
I sent the files to your email, since it's not practical nor possible to share them on github.

**Comment by EdisonLeeeee** [comment]
Received. The problem is solved on my end by changing the metapath to
```
metapath = [
    ('word', 'in', 'tweet'),
    ('tweet', 'rev_links', 'lemma'),
    ('lemma', 'links', 'tweet'),
    ('tweet', 'rev_links', 'root'),
    ('root', 'links', 'tweet'),
    ('tweet', 'rev_in', 'word'),
]
```

Please note that the metapath must be ordered, and the end of the last path should be the start of the next one.

**Comment by EdisonLeeeee** [comment]
You don't need the `y_index` because all the nodes already have associated labels., so
```python
z = model('tweet')
```

**Comment by SHamda** [comment]
The returned embedding vector has the shape ``Embedding(59267, 64, sparse=True) `` how can I extract only the _tweet_ embedding since that's what would be useful in my use case.
All issues were solved and I would appreciate if you could advise me on any potential documentation that would remedy my lack of understanding in heteregenous graphs embedding in general and metapath2vec specifically.

**Comment by EdisonLeeeee** [comment]
> how can I extract only the tweet embedding since that's what would be useful in my use case.

`model('tweet')` can return only the embedding of `tweet` nodes

Related docs: https://pytorch-geometric.readthedocs.io/en/latest/notes/heterogeneous.html
