### ISSUE TITLE
`an illegal memory access was encountered` in `examples/rev_gnn.py` when using `torch.sparse` backend

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#8213]
### 🐛 Describe the bug

```
CUDA_LAUNCH_BLOCKING=1 python3 /workspace/examples/rev_gnn.py
Traceback (most recent call last):
  File "/workspace/examples/rev_gnn.py", line 187, in <module>
    loss = train(epoch)
  File "/workspace/examples/rev_gnn.py", line 125, in train
    out = model(data.x, data.adj_t)[data.train_mask]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/examples/rev_gnn.py", line 76, in forward
    x = conv(x, edge_index, mask)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/models/rev_gnn.py", line 166, in forward
    return self._fn_apply(args, self._forward, self._inverse)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/models/rev_gnn.py", line 181, in _fn_apply
    out = InvertibleFunction.apply(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/models/rev_gnn.py", line 52, in forward
    outputs = ctx.fn(*x)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/models/rev_gnn.py", line 283, in _forward
    y_in = xs[i] + self.convs[i](y_in, edge_index, *args[i])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/examples/rev_gnn.py", line 35, in forward
    return self.conv(x, edge_index)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/conv/sage_conv.py", line 130, in forward
    out = self.propagate(edge_index, x=x, size=size)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/conv/message_passing.py", line 431, in propagate
    out = self.message_and_aggregate(edge_index, **msg_aggr_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/conv/sage_conv.py", line 149, in message_and_aggregate
    return spmm(adj_t, x[0], reduce=self.aggr)
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/spmm.py", line 99, in spmm
    return torch.sparse.mm(src, other) / deg.view(-1, 1).clamp_(min=1)
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

tested to occur on A100, A5000, and even hopper systems

### Environment

latest stack but no torch-sparse, using torch native sparse

**Comment by puririshi98** [comment]
if i break it into:
```
            step1= torch.sparse.mm(src, other)
            step2 = deg.view(-1, 1).clamp_(min=1)
            step3 = step1 / step2
            return step3
```

i get:
```
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/spmm.py", line 99, in spmm
    step2 = deg.view(-1, 1).clamp_(min=1)
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by puririshi98** [comment]
even printing after deg.view(-1, 1) breaks
```
            step1= torch.sparse.mm(src, other)
            step2 = deg.reshape(-1, 1)
            #step21 = torch.clamp(step2, min=1)
            print("deg=", deg)
            print("deg.size=", deg.size())
            step21 = torch.maximum(step2, torch.ones_like(step2))
            step3 = step1 / step21
```
->
```
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/spmm.py", line 101, in spmm
    print("deg=", deg)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 430, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 664, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 595, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 347, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 373, in get_summarized_data
    return torch.cat(
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by puririshi98** [comment]
```
        # Simulate `mean` reduction by dividing by degree:
        if reduce == 'mean':
            if src.layout == torch.sparse_csr:
                print("path 1")
                ptr = src.crow_indices()
                deg = ptr[1:] - ptr[:-1]
                assert not (deg.isnan()).any()
            else:
                print("path 2")
                assert src.layout == torch.sparse_csc
                deg = scatter(torch.ones_like(src.values()), src.row_indices(),
                              dim=0, dim_size=src.size(0), reduce='sum')
            print("deg (fresh off making it)", deg)
            deg1=deg.clone()
            del deg
            deg=deg1
            step21 = torch.clamp(deg, min=1)
            step22 = step21.view(-1, 1)
            step1= torch.sparse.mm(src, other)
            step3 = step1 / step22
            return step3
```

->
`            step3 = step1 / step22
`

definitely an issue with torch native sparse operations

**Comment by puririshi98** [comment]
moved issue to PyTorch: https://github.com/pytorch/pytorch/issues/111574
