### ISSUE TITLE
Can not run gat

### ISSUE THREAD

**Issue by wjlpku** [pyg-team/pytorch_geometric#823]
## To Reproduce
python gat.py

1. cd example
1. python gat.py
1.

Traceback (most recent call last):
  File "gat_demo.py", line 56, in <module>
    train()
  File "gat_demo.py", line 41, in train
    F.nll_loss(model()[data.train_mask], data.y[data.train_mask]).backward()
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "gat_demo.py", line 27, in forward
    x = F.elu(self.conv1(x, data.edge_index))
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/gat_conv.py", line 91, in forward
    return self.propagate(edge_index, size=size, x=x)
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 126, in propagate
    out = self.message(*message_args)
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/gat_conv.py", line 103, in message
    alpha = softmax(alpha, edge_index_i, size_i)
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch_geometric/utils/softmax.py", line 23, in softmax
    out = src - scatter_max(src, index, dim=0, dim_size=num_nodes)[0][index]
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)

## Expected behavior
Can run 

## Environment

* OS:                          Ubuntu
* Python version:       Python 3.7.3
* PyTorch version:      1.3.1
* CUDA/cuDNN version: 10.0, V10.0.130
* GCC version:    7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
* Any other relevant information:

**Comment by rusty1s** [comment]
This seems like `torch-scatter` was not installed successfully. Can you try to check that by running the test suite of `torch-scatter`?

**Comment by wjlpku** [comment]
Thanks for your reply, I wonder how to run the test suite of torch-scatter, and when I install torch-scatter, it seems that I have scuccessfully.
