### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 64 but got size 24 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by nickponline** [pyg-team/pytorch_geometric#8237]
### 🐛 Describe the bug

When I increase batch size > 1 I get the above error. My task is predicting a class for each edge in a graph. My graphs have different sizes. The first few are:

```python
HeteroData(
  x=[55, 3],
  edge_index=[2, 64],
  edge_label=[64]
)
HeteroData(
  x=[21, 3],
  edge_index=[2, 24],
  edge_label=[24]
)
HeteroData(
  x=[38, 3],
  edge_index=[2, 44],
  edge_label=[44]
)
HeteroData(
  x=[16, 3],
  edge_index=[2, 19],
  edge_label=[19]
)
```

And the error is: 
```
Traceback (most recent call last):
  File "/Users/nickp/mr/learning-pygeometric/main.py", line 119, in <module>
    loss = train(loader)
  File "/Users/nickp/mr/learning-pygeometric/main.py", line 57, in train
    for batch in data:
  File "/opt/anaconda3/envs/dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/anaconda3/envs/dev/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/opt/anaconda3/envs/dev/lib/python3.10/site-packages/torch_geometric/loader/dataloader.py", line 55, in collate_fn
    return self(batch)
  File "/opt/anaconda3/envs/dev/lib/python3.10/site-packages/torch_geometric/loader/dataloader.py", line 28, in __call__
    return Batch.from_data_list(
  File "/opt/anaconda3/envs/dev/lib/python3.10/site-packages/torch_geometric/data/batch.py", line 93, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/opt/anaconda3/envs/dev/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 92, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/opt/anaconda3/envs/dev/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 177, in _collate
    value = torch.cat(values, dim=cat_dim or 0, out=out)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 64 but got size 24 for tensor number 1 in the list.
```

Repro:
```python
for x, edge_index, edge_labe in graph_datasets:
  data = HeteroData()
  data.x = x  # [num_users, num_features_users]
  data.edge_index = edge_index  # [2, num_ratings]
  data.edge_label = edge_label
  data = T.ToUndirected()(data)
  graphs.append(data)

loader = DataLoader(graphs, batch_size=2,  shuffle=False)
```

### Environment

* PyG version: '2.4.0'
* PyTorch version: '2.1.0.dev20230312'
* OS: OSX
* Python version: Python 3.10.6

**Comment by rusty1s** [comment]
It looks like you are operating on homogeneous graphs, but use `HeteroData` to store the data. I think this is easily fixable by using `Data` instead of `HeteroData`.

**Comment by nickponline** [comment]
Thank you! Solved. Can close
