### ISSUE TITLE
`Linear.weight` is lazily intialised on CPU after `to_hetero` leading to device mismatch

### ISSUE THREAD

**Issue by akihironitta** [pyg-team/pytorch_geometric#8305]
### 🐛 Describe the bug

See title and the erorr below.

Haven't spent making this repro minimal yet:
```python
import torch
from torch_geometric.nn import to_hetero, GATv2Conv
from torch_geometric.datasets import FakeHeteroDataset

class Encoder(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = GATv2Conv(
            (-1, -1),
            out_channels=2,
            add_self_loops=False,
            edge_dim=-1,
            heads=1,
        ).to("cuda")

    def forward(self, x, edge_index, edge_attr):
        return self.layer(x, edge_index, edge_attr)

class Model(torch.nn.Module):
    def __init__(self, metadata):
        super().__init__()
        self.encoder = Encoder()
        self.encoder = to_hetero(self.encoder, metadata)

    def forward(self, x_dict, edge_index_dict, edge_attr_dict):
        return self.encoder(x_dict, edge_index_dict, edge_attr_dict)

if __name__ == '__main__':
    data = FakeHeteroDataset(edge_dim=10)._data.to("cuda")
    model = Model(data.metadata())
    model(data.x_dict, data.edge_index_dict, data.edge_attr_dict)
```

```
Traceback (most recent call last):
  File "/home/akihiro/work/github.com/pyg-team/pytorch_geometric/test_lazy_to_hetero.py", line 31, in <module>
    model(data.x_dict, data.edge_index_dict, data.edge_attr_dict)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akihiro/work/github.com/pyg-team/pytorch_geometric/test_lazy_to_hetero.py", line 26, in forward
    return self.encoder(x_dict, edge_index_dict, edge_attr_dict)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/fx/graph_module.py", line 678, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/fx/graph_module.py", line 284, in __call__
    raise e
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/fx/graph_module.py", line 274, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.1", line 23, in forward
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akihiro/work/github.com/pyg-team/pytorch_geometric/torch_geometric/nn/conv/gatv2_conv.py", line 229, in forward
    x_l = self.lin_l(x_l).view(-1, H, C)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akihiro/.conda/envs/pyg310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/akihiro/work/github.com/pyg-team/pytorch_geometric/torch_geometric/nn/dense/linear.py", line 130, in forward
    return F.linear(x, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_addmm)
```

*Orignally reported in https://torchgeometricco.slack.com/archives/C01DN0B3B1N/p1698722394182739*

---

Haven't spent time yet, but the issue occurs when lazy init is used with `to_hetero`.

Code that's possibly relevant is:
https://github.com/pyg-team/pytorch_geometric/blob/de6d46dff2bcdf8f47521fb30065c4fa1e88dd75/torch_geometric/nn/dense/linear.py#L136

### Environment

* PyG version: master
* PyTorch version: 2.1.0+cu118
* OS: Debian-based
* Python version: 3.10.12
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): source
* Any other relevant information (*e.g.*, version of `torch-scatter`): n/a

**Comment by rusty1s** [comment]
I can take a look.
