### ISSUE TITLE
KPConv

### ISSUE THREAD

**Issue by tchaton** [pyg-team/pytorch_geometric#832]
## ❓ Questions & Help

 Hey @rusty1s, what is your intuition for implementing KPconv in the best manner within pytorch geometric. 

1) I was thinking to perform two radius search. One to create the balls of the same size of the kernels, a second one to perform kernel search from the neighbooring points of the center to the kernels based on sigma we defined within those balls. Calculte ratio between distance / sigma * torch. Index select weights. Perform a first scatter add to create the weights and then a mat prod between weights and features at those neighboors and a scatter max/mean on the center of the sphere and so on.

But I am afraid it will be slow. 

2) Using a first radius + a custom cuda kernel between 2 spheres. But it will make it hard for people to change things into it.

What do you think ?

**Comment by rusty1s** [comment]
I am not sure why you need to perform two radius searchs. Actually, the radius search is IMO not part of the `KPConv` and should be viewed as given input `edge_index`.

I believe the basic idea of `KPConv` can be easily implemented with the `MessagePassing` interface. Simply compute the linear correlation between all kernel weights and `pos_j - pos_i` in the `message` function. You should apply the kernel deformation here too. Initializing the kernel positions is a bit tricky, since it needs to solve an optimization problem in `reset_parameters`.

**Comment by tchaton** [comment]
Hey @rusty1s,

I have almost finished to implement KPConv, but I have a wierd bug from cublas you might know about.
Can you have a look at the code and help me to debug it ?
It is on the branch: Implement_Point_Kernel
https://github.com/tchaton/KP_Conv/invitations

Best,
Thomas Chaton.

**Comment by rusty1s** [comment]
Thanks for your implementation! I will have a closer look as soon as possible. Currently on a paper deadline, so I do not think I will have time to look at it in detail this week. Do you have any error messages for me? In which line does the error occur?

**Comment by tchaton** [comment]
Hey @rusty1s,

I am getting: RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:331
But I think it is liked to my cuda installation, as it is working fine on cpu.

**Comment by JohnRomanelis** [comment]
Hey! I am also trying to make a KPConv implementation using torch_geometric. However, i am running into some unexpected memory issues (i think i am allocating more memory than necessary)
@tchaton did you manage to finish your implementation and if so, could i have a peak at your code to figure out what i am doing wrong ?

**Comment by JohnRomanelis** [comment]
Hey! I am also trying to implement KPConv using torch_geometric. However, i am running into some memory issues ( i think i am allocating more memory than necessary)
@tchaton did you manage to finish your implementation and if so, could i have a peak at your code to figure out what i am doing wrong (the link you posted above doesn't seem to work and i couldn't find it your repositories)? 
Also, my implementation is here :  https://github.com/JohnRomanelis/KPConv_torch_geometric/

Thank you in advance!

**Comment by tchaton** [comment]
Hey @JohnRomanelis, yes, it is implemented in torchpoints3d repo

**Comment by caizhongang** [comment]
> Hey @rusty1s,
> 
> Thanks you very much :) We will also share Relation Shape which is almost PointNet++.
> 
> bug #1.
> Here are the shapes: torch.Size([793, 16, 16]) torch.Size([793, 16, 3])
> Should be fine on gpu and works fine on cpu.
> Traceback (most recent call last):
> File "kp_train.py", line 162, in
> train()
> File "kp_train.py", line 112, in train
> out = model(data)
> File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "kp_train.py", line 91, in forward
> kp1_out = self.kp1_module(*input)
> File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/thomas/HELIX/research/KPConv/modules.py", line 166, in forward
> x = self.conv(x, (pos, pos[idx]), edge_index)
> File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/thomas/HELIX/research/KPConv/modules.py", line 80, in forward
> return self.propagate(edge_index, pos=pos)
> File "/home/thomas/.cache/pypoetry/virtualenvs/superpoint-graph-job-py3.6/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 126, in propagate
> out = self.message(*message_args)
> File "/home/thomas/HELIX/research/KPConv/modules.py", line 85, in message_pos
> return self.message_forward(pos_i=pos_i, pos_j=pos_j)
> File "/home/thomas/HELIX/research/KPConv/modules.py", line 139, in message_forward
> weighted_features = torch.matmul(all_weights, features)
> RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:450
> 
> (superpoint-graph-job-py3.6) ➜ KPConv git:(Implement_Point_Kernel) python
> Python 3.6.8 (default, Oct 1 2019, 16:49:07)
> [GCC 7.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import torch
> > > > x = torch.randn((1000,))
> > > > x = torch.randn((793, 16, 16)).cuda()
> > > > y = torch.randn((793, 16, 3)).cuda()
> > > > torch.matmul(x, y)
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:450
> 
> bug #2, the loss gets to nan after one element.

Hi, any updates on KPConv?

**Comment by caizhongang** [comment]
> Hey! I am also trying to implement KPConv using torch_geometric. However, i am running into some memory issues ( i think i am allocating more memory than necessary)
> @tchaton did you manage to finish your implementation and if so, could i have a peak at your code to figure out what i am doing wrong (the link you posted above doesn't seem to work and i couldn't find it in your repositories)?
> Also, my implementation is here : https://github.com/JohnRomanelis/KPConv_torch_geometric/
> 
> Thank you in advance!

Hi @JohnRomanelis , did you manage to add KPConv in Pytorch Geometric?

**Comment by JohnRomanelis** [comment]
Hey @caizhongang , if i get it right the torch-points3d isn't using the torch-geometric message passing scheme to implement the KPConv. Unfortunately, i haven't made an implementation of my own yet.
