### ISSUE TITLE
run python gcn.py report "__init__() got an unexpected keyword argument 'normalize'"

### ISSUE THREAD

**Issue by HeCongjie** [pyg-team/pytorch_geometric#836]
Traceback (most recent call last):
  File "gcn.py", line 51, in <module>
    model, data = Net().to(device), data.to(device)
  File "gcn.py", line 33, in __init__
    normalize=not args.use_gdc)
  File "/home/world/anaconda3/envs/DeepGCN/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 43, in __init__
    super(GCNConv, self).__init__(aggr='add', **kwargs)
TypeError: __init__() got an unexpected keyword argument 'normalize'

**Comment by rusty1s** [comment]
You can just omit the normalize flag. The GCNConv changed slightly in master by providing this argument. Alternatively, install PyTorch Geometric from source.
