### ISSUE TITLE
examples/compile/ folder broken: `compile(model, fullgraph=True)` -> `cache_size_limit reached`

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#8418]
### 🐛 Describe the bug

```
root@riship-dt:/workspace# python3 examples/compile/gcn.py 
Epoch: 001, Loss: 1.9472, Train: 0.3643, Val: 0.2660, Test: 0.2820
Epoch: 002, Loss: 1.9246, Train: 0.5429, Val: 0.3920, Test: 0.4100
Epoch: 003, Loss: 1.8910, Train: 0.5643, Val: 0.4200, Test: 0.4380
Epoch: 004, Loss: 1.8459, Train: 0.7000, Val: 0.5340, Test: 0.5380
[2023-11-21 23:37:52,070] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (8)
[2023-11-21 23:37:52,070] torch._dynamo.convert_frame: [WARNING]    function: 'forward' (/workspace/examples/compile/gcn.py:36)
[2023-11-21 23:37:52,070] torch._dynamo.convert_frame: [WARNING] to diagnose recompilation issues, set env variable TORCHDYNAMO_REPORT_GUARD_FAILURES=1 and also see https://pytorch.org/docs/master/compile/troubleshooting.html.
Traceback (most recent call last):
  File "/workspace/examples/compile/gcn.py", line 83, in <module>
    loss = train()
  File "/workspace/examples/compile/gcn.py", line 62, in train
    out = model(data.x, data.edge_index, data.edge_weight)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 549, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 141, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 352, in _convert_frame_assert
    unimplemented("cache_size_limit reached")
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/exc.py", line 176, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: cache_size_limit reached
```

same occurs for the gin example

using `model=torch.compile(model)` w/o the fullgraph=True part, works fine

### Environment

latest stack

**Comment by akihironitta** [comment]
What's your env detail? I see no issue with the two scripts in the directory in my env:

```
Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-1031-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         2499.998
BogoMIPS:                        4999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        8 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] numpy==1.24.1
[pip3] onnx==1.14.1
[pip3] onnxruntime==1.16.0
[pip3] pytorch_frame==0.1.0
[pip3] pytorch-lightning==2.0.9.post0
[pip3] pytorch-memlab==0.3.0
[pip3] torch==2.1.0+cu118
[pip3] torch_frame==0.1.0
[pip3] torch_geometric==2.4.0
[pip3] torchmetrics==1.2.0
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-frame             0.1.0                    pypi_0    pypi
[conda] pytorch-lightning         2.0.9.post0              pypi_0    pypi
[conda] pytorch-memlab            0.3.0                    pypi_0    pypi
[conda] torch                     2.1.0+cu118              pypi_0    pypi
[conda] torch-frame               0.1.0                    pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torchmetrics              1.2.0                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pyp
```

**Comment by puririshi98** [comment]
this is mine:
```
root@riship-dt:/workspace# python collect_env.py
Collecting environment information...
PyTorch version: 2.2.0a0+29c30b1
Is debug build: False
CUDA used to build PyTorch: 12.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.7
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.3.52
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A5000
GPU 1: NVIDIA RTX A5000

Nvidia driver version: 530.41.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        4
CPU max MHz:                     4500.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        7599.80
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        8 MiB (8 instances)
L3 cache:                        16.5 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] onnx==1.14.1
[pip3] optree==0.9.2
[pip3] pytorch_frame==0.1.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.2.0a0+29c30b1
[pip3] torch_geometric==2.4.0
[pip3] torch-tensorrt==2.2.0a0
[pip3] torchdata==0.7.0a0
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.16.0a0
[pip3] torchvision==0.17.0a0
[pip3] triton==2.1.0+6e4932c
[pip3] tritonclient==2.39.0
[conda] Could not collect
root@riship-dt:/workspace# 

```

**Comment by rusty1s** [comment]
Hey @puririshi98, if `fullgraph=False` option work, I am okay with dropping this argument altogether. Can you take care of it?

**Comment by akihironitta** [comment]
@puririshi98 I wonder why it makes error out with `fullgraph=True` in your env. Have you had a chance to try to investigate it with `torch._dynamo.explain` or `torch._dynamo.utils.CompileProfiler`?

**Comment by puririshi98** [comment]
@rusty1s yes i will take care of it if we can't find an easy fix. it works fine w/o fullgraph=True.

@akihironitta havent yet but i will take a look when i get some bandwidth

**Comment by akihironitta** [comment]
Thanks @puririshi98! I'm not sure from this log though. Given `explain` might not be reliable (https://github.com/pytorch/pytorch/issues/113443), can you also try `CompileProfiler`? It should give us some insight into what caused these recompilations (and also the number of graph breaks 😉).

**Comment by puririshi98** [comment]
```
Torchdynamo Profiler Report
===========================

Graph Breaks
------------
Graph breaks happen when torchdynamo encounters code it can't safely trace.
If you want to find out why breaks are happening, check below for each break reason
You may gain additional insight by passing `fullgraph=True` to torch.compile,
to stop at the first break.

No graph breaks detected.

Recompilation
-------------
These subgraphs were recompiled more than once due to guard failures
Guard failures indicate some condition assumed to be static by the tracer changed,
making it unsafe to reuse the compiled program.

Function                 Recompiles  Recompile Reasons
---------------------  ------------  -----------------------
'forward' (gcn.py:36)             8  ___check_global_state()
                                     ___check_global_state()
                                     ___check_global_state()
                                     ___check_global_state()
                                     ___check_global_state()
                                     ___check_global_state()
                                     ___check_global_state()
                                     ___check_global_state()

Set torch._dynamo.config.cache_size_limit to 8 to avoid being cache limited.
```

thanks that helped.
I tried increasing the cach_size_limit to 8, 16, 32, 64, 128, 256,512,1024... each time it runs a few more epochs until hitting the same original error. the furthest it gets is epoch 32

using cach_size of 1024 w/ profiler i get:
```
------------
Graph breaks happen when torchdynamo encounters code it can't safely trace.
If you want to find out why breaks are happening, check below for each break reason
You may gain additional insight by passing `fullgraph=True` to torch.compile,
to stop at the first break.

No graph breaks detected.

Recompilation
-------------
These subgraphs were recompiled more than once due to guard failures
Guard failures indicate some condition assumed to be static by the tracer changed,
making it unsafe to reuse the compiled program.

Function               Recompiles  Recompile Reasons
-------------------  ------------  -----------------------
'forward' (x.py:36)            64  ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()
                                   ___check_global_state()

Set torch._dynamo.config.cache_size_limit to 64 to avoid being cache limited.

Traceback (most recent call last):
  File "/workspace/x.py", line 87, in <module>
    loss = train()
  File "/workspace/x.py", line 67, in train
    loss = F.cross_entropy(out[data.train_mask], data.y[data.train_mask])
UnboundLocalError: local variable 'out' referenced before assignment


```

based on these outcomes i think the best way forward would be to just remove fullgraph=True from the examples unless @akihironitta or @rusty1s you have a better suggestion

**Comment by puririshi98** [comment]
https://github.com/pyg-team/pytorch_geometric/pull/8471
this should solve
