### ISSUE TITLE
Edge index error when working with batching

### ISSUE THREAD

**Issue by thomascesare99** [pyg-team/pytorch_geometric#8489]
### 🐛 Describe the bug

Hi, I know there are similar issues already posted, but I didn't find in them any solution suitable for my case. I want to train a graph convolutional network for node classification. My dataset is a list of Data objects, with attributes x=feature matrix (dimensions num_nodes x num_node_features), edge_index (2 x num_edges, that contains in the first row all the source nodes indexes, and in the second row the target row indexes), edge_attributes and y (the label of each node). When I generate these Data objects, starting from a graph file and converting all my attributes, I also check that edge_index.max().item() == len(graph.nodes)-1, so that the larger index contained in edge_index points to the "last" node of the network. I also call data.validate(), and no error ever arises. 
The index error pops up during the training loop: this (as in a normal training loop) takes a batch of graphs from a DataLoader object and predicts labels for all the nodes in every graph in the batch. Here is what I get: 
''' Traceback (most recent call last):
  File "/Users/thomascesare/Neuro23_GNN/Neuro23_GNN/gnn.py", line 211, in <module>
    main()
  File "/Users/thomascesare/Neuro23_GNN/Neuro23_GNN/gnn.py", line 209, in main
    train(dataset, task='node', args=args)
  File "/Users/thomascesare/Neuro23_GNN/Neuro23_GNN/gnn.py", line 85, in train
    pred = model(batch)
           ^^^^^^^^^^^^
  File "/Users/thomascesare/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomascesare/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomascesare/Neuro23_GNN/Neuro23_GNN/gnn.py", line 47, in forward
    x = conv(x, edge_index, edge_attr)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomascesare/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomascesare/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomascesare/anaconda3/lib/python3.11/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 244, in forward
    out = self.propagate(edge_index, x=x, edge_weight=edge_weight,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomascesare/anaconda3/lib/python3.11/site-packages/torch_geometric/nn/conv/message_passing.py", line 455, in propagate
    coll_dict = self._collect(self._user_args, edge_index, size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomascesare/anaconda3/lib/python3.11/site-packages/torch_geometric/nn/conv/message_passing.py", line 329, in _collect
    data = self._lift(data, edge_index, dim)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomascesare/anaconda3/lib/python3.11/site-packages/torch_geometric/nn/conv/message_passing.py", line 269, in _lift
    raise IndexError(
IndexError: Encountered an index error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, 77963] (got interval [0, 127165])'''
The weird thing about this error is also that the indexes 77963 and 127165 are completely out of the range of my data (the biggest graph has around 17000 edges). That's why I think it is due to the batch mechanism that stacks graphs on top of each other and progressively increases the indexes in the edge_index matrix. But I thought it could handle internally the conversion to the original graph, but apparently there are some conflicts. Interestingly enough also I tried to set the batch_size to 1 , so to load in the model one graph at a time. It turns out that the first batch gets always processed successfully, while it is usually at the second graph that this error arises. The indexes shown in the output are as follows: the expected range goes from 0 to num_nodes of the second batch, while the interval that gives the problem goes from 0 to num_nodes of the first batch. If the first batch had a number of nodes greater then the new one the index error arises. I have no idea of why is that...
I know it is a lot of Information and it may not be totally understandable, but I hope someone has an idea of what's happening... I can provide my code also 

### Versions

PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.0.1 (x86_64)
GCC version: Could not collect
Clang version: 11.0.0 (clang-1100.0.33.16)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.5 (main, Sep 11 2023, 08:19:27) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] numpydoc==1.5.0
[pip3] torch==2.1.1
[pip3] torch_geometric==2.4.0
[pip3] torchaudio==2.1.1
[pip3] torchvision==0.16.1
[conda] numpy                     1.24.3          py311hd0e4f0d_0  
[conda] numpy-base                1.24.3          py311h947b413_0  
[conda] numpydoc                  1.5.0           py311hecd8cb5_0  
[conda] torch                     2.1.1                    pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torchaudio                2.1.1                    pypi_0    pypi
[conda] torchvision               0.16.1                   pypi_0    pypi

**Comment by rusty1s** [comment]
I would assume that
```python
for batch in loader:
    batch.validate()
```
fails. It's hard to give advice here without knowing how the data looks like. Do you have a minimal reproducible example?
