### ISSUE TITLE
ARPACK error -1: No convergence

### ISSUE THREAD

**Issue by khainguyen20** [pyg-team/pytorch_geometric#8530]
### 🐛 Describe the bug

When I train my model, it runs fine for about 40 epochs before I get this error:

```
Traceback (most recent call last):
  File "/home2/s438168/python/python-applications/receptors/interKinetics/interactionKineticsGNN/scriptPredictInteractions.py", line 93, in <module>
    model, results = train_test(
  File "/home2/s438168/python/python-applications/receptors/interKinetics/interactionKineticsGNN/trainInteractions.py", line 250, in train_test
    residualTrainAP += [trainResults[2]]
  File "/home2/s438168/python/python-applications/receptors/interKinetics/interactionKineticsGNN/trainInteractions.py", line 110, in test
    residuals_testDR = []
  File "/home2/s438168/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home2/s438168/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home2/s438168/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home2/s438168/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home2/s438168/.local/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 290, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home2/s438168/.local/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 240, in __getitem__
    data = data if self.transform is None else self.transform(data)
  File "/home2/s438168/.local/lib/python3.7/site-packages/torch_geometric/transforms/compose.py", line 24, in __call__
    data = transform(data)
  File "/home2/s438168/.local/lib/python3.7/site-packages/torch_geometric/transforms/add_positional_encoding.py", line 84, in __call__
    **self.kwargs,
  File "/home2/s438168/.local/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1346, in eigs
    params.iterate()
  File "/home2/s438168/.local/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 756, in iterate
    self._raise_no_convergence()
  File "/home2/s438168/.local/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 376, in _raise_no_convergence
    raise ArpackNoConvergence(msg % (num_iter, k_ok, self.k), ev, vec)
scipy.sparse.linalg.eigen.arpack.arpack.ArpackNoConvergence: ARPACK error -1: No convergence (32221 iterations, 8/11 eigenvectors converged)
```

When I resume training, it works fine until the next couple iterations when I get this error again. Can anybody please help explain to me what this error is and how I can avoid it in the future so that my training runs smoother? I would greatly appreciate the help! Please let me know what other additional information I should provide.

**Comment by EdisonLeeeee** [comment]
Could you please share your code snippet? This issue seems to be more related to the eigen decomposition of `scipy`.

**Comment by khainguyen20** [comment]
Thank you for the response! Here is the part, where I am calling the train and test function:

```
for epoch in range(n_epochs):
        # training results
        trainResults = train(device, train_loader, model, time_step, optimizer, criterion)
        loss += [trainResults[0]]
        lossDC += [trainResults[4]]
        lossAP += [trainResults[5]]
        lossDR += [trainResults[6]]
        residualTrainDC += [trainResults[1]]
        residualTrainAP += [trainResults[2]]
        residualTrainDR += [trainResults[3]]
        # validation on train data
        train_validation = test(device, train_loader, model, edge_col_name,time_step,criterion)
        trainAccuracy = train_validation[0]
        trainAccuracyResidualDC += [train_validation[1]]
        trainAccuracyResidualAP += [train_validation[2]]
        trainAccuracyResidualDR += [train_validation[3]]
        train_score += [trainAccuracy[0]]
        train_scoreDC += [trainAccuracy[1]]
        train_scoreAP += [trainAccuracy[2]]
        train_scoreDR += [trainAccuracy[3]]
        # validation on test data
        test_validation = test(device,test_loader, model, edge_col_name,time_step,criterion)
        testAccuracy = test_validation[0]
        testAccuracyResidualDC += [test_validation[1]]
        testAccuracyResidualAP += [test_validation[2]]
        testAccuracyResidualDR += [test_validation[3]]
        test_score += [testAccuracy[0]]
        test_scoreDC += [testAccuracy[1]]
        test_scoreAP += [testAccuracy[2]]
        test_scoreDR += [testAccuracy[3]]
```
Here is my train function:

```
def train(device,train_loader, model, time_step, optimizer, criterion):
    model.train()
    
    lossesDC = []
    lossesAP = []
    lossesDR = []
    losses = []
    residuals_trainDC = [] 
    residuals_trainAP = [] 
    residuals_trainDR = [] 
    
    for data in train_loader:  # Iterate in batches over the training dataset.
        tModel = time.time()
        #optimizer.zero_grad()  # Clear gradients
        if torch.cuda.device_count() > 1:
            node_out, edge_out, global_out, DC, AP, DR = model(data)

            true_DC = torch.cat([datalist.DC.reshape(1) for datalist in data]).to(DC.device)
            true_DC = torch.sqrt(2*true_DC*time_step)
            true_DC = true_DC.reshape(true_DC.size()[0],1)

            true_AP = torch.cat([datalist.AP.reshape(1) for datalist in data]).to(AP.device)
            true_AP = true_AP.reshape(true_AP.size()[0],1)

            true_DR = torch.cat([datalist.DR.reshape(1) for datalist in data]).to(DR.device)
            true_DR = true_DR.reshape(true_DR.size()[0],1)
        else:
            # getting outputs from model
            
            node_out, edge_out, global_out, DC, AP, DR = model(data.x.to(device), data.edge_attr.to(device),data.edge_index.long().to(device), data.batch.to(device))   
            #print('time: ',time.time()-tModel)   

            true_DC = torch.sqrt(2*data.DC.float()*time_step).to(device)  #getting the true DC values
            true_DC = true_DC.reshape(true_DC.size()[0],1)
            true_AP = data.AP.float().to(device)  # getting the true AP values
            true_AP = true_AP.reshape(true_AP.size()[0],1)
            true_DR = data.DR.float().to(device)  # getting the true DR values
            true_DR = true_DR.reshape(true_DR.size()[0],1)

        lossDC, lossAP, lossDR, loss = criterion([true_DC, true_AP,true_DR],[DC,AP,DR]) # calculate loss for DC, AP, DR, and summed losses

        residual_trainDC = true_DC - DC
        residual_trainAP = true_AP - AP
        residual_trainDR = true_DR - DR
        tBack = time.time()
        loss.backward()  # Derive gradients.
        #print('time back: ',time.time()-tBack)
        tOpt = time.time()
        optimizer.step()  # Update parameters based on gradients.
        optimizer.zero_grad()  # Clear gradients.
        losses.append(loss.item())
        lossesDC.append(lossDC.item())
        lossesAP.append(lossAP.item())
        lossesDR.append(lossDR.item())
        residuals_trainDC.append(residual_trainDC.tolist())
        residuals_trainAP.append(residual_trainAP.tolist())
        residuals_trainDR.append(residual_trainDR.tolist())
        
        
    return np.mean(losses), np.asarray(residuals_trainDC).flatten(), np.asarray(residuals_trainAP).flatten(), np.asarray(residuals_trainDR).flatten(), np.mean(lossesDC), np.mean(lossesAP), np.mean(lossesDR)
```
Here is my test function:
```
def test(device,loader, model, edge_col_name, time_step,criterion):
    
    model.eval()
   
    losses = []
    lossesDC = []
    lossesAP = []
    lossesDR = []
    scores = []
    y_pred = 0
    y_true = 0
    results = []
    residuals_testDC = []
    residuals_testAP = []
    residuals_testDR = []

    with torch.no_grad():
        for data in loader:

            if torch.cuda.device_count() > 1:
                node_out, edge_out, global_out, DC, AP, DR = model(data)

                #getting true DC values
                true_DC = torch.cat([datalist.DC.reshape(1) for datalist in data]).to(DC.device)
                true_DC = torch.sqrt(2*true_DC*time_step)
                true_DC = true_DC.reshape(true_DC.size()[0],1)
                #getting true AP values
                true_AP = torch.cat([datalist.AP.reshape(1) for datalist in data]).to(AP.device)
                true_AP = true_AP.reshape(true_AP.size()[0],1)
                #getting true DR values
                true_DR = torch.cat([datalist.DR.reshape(1) for datalist in data]).to(DR.device)
                true_DR = true_DR.reshape(true_DR.size()[0],1)
            else:
            # getting outputs from model
                if edge_col_name==None:
                    node_out, edge_out, global_out, DC, AP, DR = model(data.x.to(device), data.edge_attr.to(device),data.edge_index.long().to(device), data.batch.to(device))  
                   
                true_DC = torch.sqrt(2*data.DC.float()*time_step).to(device)  #getting the true DC values
                true_DC = true_DC.reshape(true_DC.size()[0],1)
                true_AP = data.AP.float().to(device)  # getting the true AP values
                true_AP = true_AP.reshape(true_AP.size()[0],1)
                true_DR = data.DR.float().to(device)  # getting the true DR values
                true_DR = true_DR.reshape(true_DR.size()[0],1)


            lossDC, lossAP, lossDR, loss = criterion([true_DC, true_AP,true_DR],[DC,AP,DR]) # calculate loss for DC, AP, DR, and summed losses

            

            residual_testDC = true_DC - DC
            residual_testAP = true_AP - AP
            residual_testDR = true_DR - DR

            losses.append(loss.item())
            lossesDC.append(lossDC.item())
            lossesAP.append(lossAP.item())
            lossesDR.append(lossDR.item())
            
            residuals_testDC.append(residual_testDC.tolist())
            residuals_testAP.append(residual_testAP.tolist())
            residuals_testDR.append(residual_testDR.tolist())
            
    
    
    accuracy = np.mean(losses)
    accuracyDC = np.mean(lossesDC)
    accuracyAP = np.mean(lossesAP)
    accuracyDR = np.mean(lossesDR)
    results.append(accuracy)
    results.append(accuracyDC)
    results.append(accuracyAP)
    results.append(accuracyDR)
    
    
    return results, np.asarray(residuals_testDC).flatten(), np.asarray(residuals_testAP).flatten(), np.asarray(residuals_testDR).flatten()
```
I should have also included that am training this on multi-GPU. Additionally, I have used the 'AddLaplacianEigenvectorPE' function to transform my dataset before training. Please let me know if I should include any other information that could be helpful.

**Comment by rusty1s** [comment]
I pushed some changes in latest master that will utilize dense eigenvector computation for smaller graphs, which should resolve this issue. Can you do me a favor and try if this problem is also present for you on latest PyG master?

**Comment by rusty1s** [comment]
You can do
```
pip uninstall torch-geometric
pip install git+https://github.com/pyg-team/pytorch_geometric.git

**Comment by khainguyen20** [comment]
This worked! I don't have this issue anymore. Once again, thank you for the help!
