### ISSUE TITLE
`torch.compile`:`Cannot call sizes() on tensor with symbolic sizes/strides` when using `knn_graph`

### ISSUE THREAD

**Issue by CharlesGaydon** [pyg-team/pytorch_geometric#8747]
### 🐛 Describe the bug

Compilation fails when using `knn_graph`. I am able to reproduce the problem with the following code:
```
import torch
import torch_geometric
from torch_geometric.nn.pool import knn_graph
datas = [torch_geometric.data.Data(pos=torch.rand((50, 3))) for i in range(5)]
batch = torch_geometric.data.Batch.from_data_list(datas)

class MyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, pos, batch):
        edge_index = knn_graph(pos, 5, batch=batch, loop=True)
        return edge_index
    
model = MyModel()
model = torch_geometric.compile(model, dynamic=True)
output = model(batch.pos, batch.batch)
print(output.shape)
```
My environment contains:
```
# Name                    Version                   Build  Channel
pytorch-lightning         2.1.2                    pypi_0    pypi
torch                     2.1.2+cu118              pypi_0    pypi
torch-cluster             1.6.3+pt21cu118          pypi_0    pypi
torch-geometric           2.4.0                    pypi_0    pypi
torch-scatter             2.1.2+pt21cu118          pypi_0    pypi
torch-sparse              0.6.18+pt21cu118          pypi_0    pypi
torchmetrics              1.2.1                    pypi_0    pypi
torchvision               0.16.2+cu118             pypi_0    pypi
```

Here is the full traceback of the exception:
```
/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/overrides.py:110: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda,
/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/overrides.py:111: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  torch.has_cudnn,
/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/overrides.py:117: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  torch.has_mps,
/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/overrides.py:118: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  torch.has_mkldnn,
Traceback (most recent call last):
  File "/home/CGaydon/repositories/mre_compile.py", line 23, in <module>
    output = model(batch.pos, batch.batch)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/CGaydon/repositories/mre_compile.py", line 16, in forward
    edge_index = knn_graph(pos, 5, batch=batch, loop=True)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch_geometric/nn/pool/__init__.py", line 169, in knn_graph
    return torch_cluster.knn_graph(x, k, batch, loop, flow, cosine,
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch_cluster/knn.py", line 132, in knn_graph
    edge_index = knn(x, x, k if loop else k + 1, batch, batch, cosine,
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch_cluster/knn.py", line 66, in knn
    batch_size = int(batch_x.max()) + 1
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch_cluster/knn.py", line 69, in <resume in knn>
    batch_size = max(batch_size, int(batch_y.max()) + 1)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2069, in run
    super().run()
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 719, in run
    and self.step()
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 683, in step
    getattr(self, inst.opname)(inst)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1110, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 557, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/variables/torch.py", line 729, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 1191, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 1278, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1376, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1337, in get_fake_value
    return wrap_fake_exception(
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 916, in wrap_fake_exception
    return fn()
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1338, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1410, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1397, in run_node
    return node.target(*args, **kwargs)
  File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
torch._dynamo.exc.TorchRuntimeError: Failed running call_function torch_cluster.knn(*(FakeTensor(..., size=(s2, s3)), FakeTensor(..., size=(s2, s3)), FakeTensor(..., size=(s0 + 1,), dtype=torch.int64), FakeTensor(..., size=(s0 + 1,), dtype=torch.int64), 5, False, 1), **{}):
Cannot call sizes() on tensor with symbolic sizes/strides

from user code:
   File "/var/data/CGaydon/mambaforge/envs/myria3d_upgrade/lib/python3.9/site-packages/torch_cluster/knn.py", line 81, in <resume in knn>
    return torch.ops.torch_cluster.knn(x, y, ptr_x, ptr_y, k, cosine,

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

PyTorch version: 2.1.2+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32)  [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40
GPU 2: NVIDIA A40

Nvidia driver version: 535.104.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          96
On-line CPU(s) list:             0-95
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7413 24-Core Processor
CPU family:                      25
Model:                           1
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
Stepping:                        1
Frequency boost:                 enabled
CPU max MHz:                     3630,8101
CPU min MHz:                     1500,0000
BogoMIPS:                        5289.80
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca
Virtualization:                  AMD-V
L1d cache:                       1,5 MiB (48 instances)
L1i cache:                       1,5 MiB (48 instances)
L2 cache:                        24 MiB (48 instances)
L3 cache:                        256 MiB (8 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.2
[pip3] pytorch-lightning==2.1.2
[pip3] torch==2.1.2+cu118
[pip3] torch-cluster==1.6.3+pt21cu118
[pip3] torch_geometric==2.4.0
[pip3] torch-scatter==2.1.2+pt21cu118
[pip3] torch-sparse==0.6.18+pt21cu118
[pip3] torchmetrics==1.2.1
[pip3] torchvision==0.16.2+cu118
[pip3] triton==2.1.0
[conda] numpy                     1.26.2           py39h474f0d3_0    conda-forge
[conda] pytorch-lightning         2.1.2                    pypi_0    pypi
[conda] torch                     2.1.2+cu118              pypi_0    pypi
[conda] torch-cluster             1.6.3+pt21cu118          pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torch-scatter             2.1.2+pt21cu118          pypi_0    pypi
[conda] torch-sparse              0.6.18+pt21cu118          pypi_0    pypi
[conda] torchmetrics              1.2.1                    pypi_0    pypi
[conda] torchvision               0.16.2+cu118             pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by rusty1s** [comment]
I am afraid that this is not supported yet, since `torch.compile` doesn't play nicely with custom C++/CUDA kernels :(

**Comment by akihironitta** [comment]
@CharlesGaydon You should be able to work around the error and run `knn_graph` in eager by wrapping `knn_graph` with `torch.compiler.disable`. Reference: https://pytorch.org/docs/stable/torch.compiler_faq.html#how-do-i-graph-break-on-a-function

**Comment by CharlesGaydon** [comment]
Nice, thank you for the workaround. I am able to remove the error, and the rest of my model works just fine. Closing the issue :)
```
knn_graph = torch.compiler.disable(knn_graph)
knn_interpolate = torch.compiler.disable(knn_interpolate)
```
