### ISSUE TITLE
Installation of `pyg-lib` and other  wheels with `pipenv`

### ISSUE THREAD

**Issue by khbalhandawi** [pyg-team/pytorch_geometric#8791]
### 😵 Describe the installation problem

I would like to use `pipenv` for my package management and have a dependancy on :
* `torch-cluster` version 1.6.3+pt21cu118
* `torch-scatter` version 2.1.2+pt21cu118
* `torch-sparse` version 0.6.18+pt21cu118
* `torch-spline-conv` version 1.2.2+pt21cu118
* `pyg-lib` version 0.3.1+pt21cu118
I have installed all the required depandencies such as `pytorch` 2.1.0+cu118 and CUDA 11.8, `torchvision` 0.16.0+cu118, `torchaudio` 2.1.0+cu118, and `torch_geometric` 2.4.0 using the `Pipfile` below:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/"
verify_ssl = false

[[source]]
name = "pyg"
url = "https://data.pyg.org/whl/torch-2.1.0+cu118.html"
verify_ssl = false

[packages]
torch = {index = "pytorch",version = "==2.1.0+cu118"}
torchaudio = {index = "pytorch",version = "==2.1.0+cu118"}
torchvision = {index = "pytorch",version = "==0.16.0+cu118"}
torch_geometric = {index = "pypi",version = "==2.4.0"}
networkx = "*"
tabulate = "*"
pandas = "*"
scikit-learn = "*"
tables = "*"

# torch-cluster = {index = "pyg",version = "==1.6.3+pt21cu118"}
# torch-scatter = {index = "pyg",version = "==2.1.2+pt21cu118"}
# torch-sparse = {index = "pyg",version = "==0.6.18+pt21cu118"}
# torch-spline-conv = {index = "pyg",version = "==1.2.2+pt21cu118"}
# pyg-lib = {index = "pyg",version = "==0.3.1+pt21cu118"}

[dev-packages]
ipykernel = "*"

[requires]
python_version = "3.10"
```

However, when trying to install `pyg-lib` and the others directly from the pyg wheel source: [https://data.pyg.org/whl/torch-2.1.0+cu118.html](https://data.pyg.org/whl/torch-2.1.0+cu118.html) (by uncommenting the line `pyg-lib = {index = "pyg",version = "==0.3.1+pt21cu118"}` for example), I get:

```
Pipfile.lock (028743) out of date, updating to (6c9602)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠦ Locking...False
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement pyg-lib==0.3.1+pt21cu118 (from versions: none)
[ResolutionFailure]:   File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 645, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 612, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 592, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 908, in resolve_deps
[ResolutionFailure]:       results, hashes, internal_resolver = actually_resolve_deps(
[ResolutionFailure]:   File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 681, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 442, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for pyg-lib==0.3.1+pt21cu118

Traceback (most recent call last):
  File "/home/khalil/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/cli/command.py", line 209, in install
    do_install(
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/routines/install.py", line 164, in do_install
    do_init(
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/routines/install.py", line 648, in do_init
    do_lock(
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/routines/lock.py", line 65, in do_lock
    venv_resolve_deps(
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 849, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
  File "/home/khalil/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 718, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!
```

I think that the issue is with Pipenv not recognizing the wheels from the [source](https://data.pyg.org/whl/torch-2.1.0+cu118.html) due to the absence of SHA256 hashes. Pipenv relies heavily on these hashes for security and integrity verification of packages. When you specify a package in a Pipfile, Pipenv tries to resolve it along with its dependencies and lock them with their respective hashes in Pipfile.lock. If the custom wheels don't have associated hashes, Pipenv might fail to lock them.

Could verify that this is indeed the issue and if so update the pyg sources with sha256 hashes?

Thank you 

### Environment

* PyG version: 2.4.0
* PyTorch version: 2.1.0
* OS: Ubuntu 22.04
* Python version: 3.10
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): Using `pipenv`

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/"
verify_ssl = false

torch = {index = "pytorch",version = "==2.1.0+cu118"}
torchaudio = {index = "pytorch",version = "==2.1.0+cu118"}
torchvision = {index = "pytorch",version = "==0.16.0+cu118"}
torch_geometric = {index = "pypi",version = "==2.4.0"}
```

**Comment by rusty1s** [comment]
Thanks for reporting. I try to fix this in the next upcoming release.
