### ISSUE TITLE
TorchScript instance from torch.jit.script() runs successfully but throws type mismatch when loading from file

### ISSUE THREAD

**Issue by conormcg94** [pyg-team/pytorch_geometric#8867]
### 🐛 Describe the bug

In my example below, I can compile a Torchscript model of GENConv and compute the result Y1, however when I load the model from the saved file and try to calculate Y2 it throws a Type mismatch error. This is related to the input validation of Union[Tensor, OptPairTensor] in the Message Passing class. Torchscript requires the type to be the same for the true/false branches.

I'm not sure how to resolve this and am happy to contribute if someone can point me in the right direction.

I'm using the latest nightly build of pyg.

```
import torch
from torch import nn, Tensor
from torch_geometric.typing import Adj, OptTensor, Union, OptPairTensor
from torch_geometric.nn.conv import GENConv, GraphConv

class MyConv(nn.Module):
    def __init__(self):
        super(MyConv, self).__init__()
        self.conv = GENConv(64,
                            64,
                            learn_p=True,
                            num_layers=1)

    def forward(self, x: Union[Tensor, OptPairTensor], edge_index: Adj,
                edge_attr: OptTensor = None):
        y = self.conv(x, edge_index, edge_attr)
        return y

if __name__ == "__main__":
    device = 'cpu'
    save_path = "example.pt"
    model = MyConv()
    scripted_model = torch.jit.script(model)
    scripted_model.save(save_path)

    n_nodes = 200
    n_edges = 100
    x = torch.rand((n_nodes, 64), dtype=torch.float32, device=device)
    edge_index = torch.randint(2, (2, n_edges), dtype=torch.int64, device=device)
    edge_attr = torch.rand((n_edges, 64), dtype=torch.float32, device=device)
   
    y1 = scripted_model(x=x,
                                     edge_index=edge_index,
                                     edge_attr=edge_attr)

    model_from_file = torch.jit.load(save_path)
    y2 = model_from_file(x=x,
                                       edge_index=edge_index,
                                       edge_attr=edge_attr)
```

**Error:**
```
/miniforge3/envs/pyg/bin/python ...../Example.py 
Traceback (most recent call last):
  File "......../Example.py", line 38, in <module>
    model_from_file = torch.jit.load(save_path)
  File "......../lib/python3.10/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: 

Type mismatch: edge_index0 is set to type __torch__.torch_geometric.typing.SparseTensor (of Python compilation unit at: 0x561bb9716290) in the true branch and type Tensor in the false branch:
  File "code/__torch__/torch_geometric/nn/conv/gen_conv.py", line 52
      x0 = x2
    _7 = isinstance(edge_index, __torch__.torch_geometric.typing.SparseTensor)
    if _7:
    ~~~~~~
      edge_index1 = unchecked_cast(__torch__.torch_geometric.typing.SparseTensor, edge_index)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      edge_attr1 = ((edge_index1).__storage_getter()).value()
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      edge_attr0, edge_index0 = edge_attr1, edge_index1
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    else:
    ~~~~~
      edge_index2 = unchecked_cast(Tensor, edge_index)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      if _4(edge_index2, ):
      ~~~~~~~~~~~~~~~~~~~~~
        _8, value, = _5(edge_index2, )
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if torch.gt(torch.dim(value), 1):
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _9 = True
          ~~~~~~~~~
        else:
        ~~~~~
          _10 = torch.__not__(bool(torch.all(value)))
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _9 = _10
          ~~~~~~~~
        if _9:
        ~~~~~~
          edge_attr3 : Optional[Tensor] = value
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        else:
        ~~~~~
          edge_attr3 = edge_attr
          ~~~~~~~~~~~~~~~~~~~~~~
        edge_attr2 : Optional[Tensor] = edge_attr3
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      else:
      ~~~~~
        edge_attr2 = edge_attr
        ~~~~~~~~~~~~~~~~~~~~~~
      edge_attr0, edge_index0 = edge_attr2, edge_index2
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    if torch.__isnot__(edge_attr0, None):
      edge_attr5 = unchecked_cast(Tensor, edge_attr0)
and was used here:
  File "code/__torch__/torch_geometric/nn/conv/gen_conv.py", line 88
    else:
      edge_attr6 = edge_attr4
    out = (self).propagate(edge_index0, x0, edge_attr6, size, )
                           ~~~~~~~~~~~ <--- HERE
    x_dst = (x0)[1]
    if torch.__isnot__(x_dst, None):


Process finished with exit code 1
```

### Versions

pyg-nightly         2.4.0.dev20240205

pytorch                   2.1.2           py3.10_cuda12.1_cudnn8.9.2_0    pytorch
pytorch-cluster           1.6.3           py310_torch_2.1.0_cu121    pyg
pytorch-cuda              12.1                 ha16c6d3_5    pytorch
pytorch-lightning         2.1.3              pyhd8ed1ab_0    conda-forge
pytorch-mutex             1.0                        cuda    pytorch
pytorch-scatter           2.1.2           py310_torch_2.1.0_cu121    pyg
onnx                      1.15.0          py310heee6c8b_1    conda-forge
onnxruntime               1.16.3          py310hd4b7fbc_4_cpu    conda-forge
cuda-opencl               12.3.101                      0    nvidia
cuda-runtime              12.1.0                        0    nvidia

**Comment by rusty1s** [comment]
Thanks for reporting. Will be fixed in https://github.com/pyg-team/pytorch_geometric/pull/8870.

**Comment by lee-clement-oxb** [comment]
Hi, unfortunately I think this issue has resurfaced in 2.5.x 😞. With the example GNN from the docs as well as standard GAT and GCN models, I can script and save the models just fine but torch.jit.load raises a type mismatch error. 

```python
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.nn.models import GAT, GCN


# example from https://pytorch-geometric.readthedocs.io/en/latest/advanced/jit.html
class GNN(torch.nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv1 = GCNConv(in_channels, 64)
        self.conv2 = GCNConv(64, out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)


def main():
    save_path = "model.pt2"
    # model = models.GAT(64, 64, num_layers=1, out_channels=2)
    # model = models.GCN(64, 64, num_layers=1, out_channels=2)
    model = GNN(64, 2)
    scripted_model = torch.jit.script(model)
    torch.jit.save(scripted_model, save_path)
    model_from_file = torch.jit.load(save_path)


if __name__ == "__main__":
    main()
```

```
RuntimeError: 

Type mismatch: edge_index1 is set to type Tensor in the true branch and type __torch__.torch_geometric.typing.SparseTensor (of Python compilation unit at: 0x14ce6b158) in the false branch:
  File "code/__torch__/torch_geometric/nn/conv/gcn_conv.py", line 54
    if normalize:
      _6 = isinstance(edge_index, Tensor)
      if _6:
      ~~~~~~
        edge_index2 = unchecked_cast(Tensor, edge_index)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        _cached_edge_index = self._cached_edge_index
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        _7 = torch.__is__(_cached_edge_index, None)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if _7:
        ~~~~~~
          node_dim = self.node_dim
          ~~~~~~~~~~~~~~~~~~~~~~~~
          _8 = torch.size(x0, node_dim)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          improved = self.improved
          ~~~~~~~~~~~~~~~~~~~~~~~~
          add_self_loops = self.add_self_loops
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          flow = self.flow
          ~~~~~~~~~~~~~~~~
          _9 = _4(edge_index2, edge_weight, _8, improved, add_self_loops, flow, ops.prim.dtype(x0), )
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          edge_index4, edge_weight3, = _9
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          cached = self.cached
          ~~~~~~~~~~~~~~~~~~~~
          if cached:
          ~~~~~~~~~~
            self._cached_edge_index = (edge_index4, edge_weight3)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          else:
          ~~~~~
            pass
            ~~~~
          edge_index3, edge_weight2 = edge_index4, edge_weight3
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        else:
        ~~~~~
          cache = unchecked_cast(Tuple[Tensor, Optional[Tensor]], _cached_edge_index)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          edge_index3, edge_weight2 = (cache)[0], (cache)[1]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        edge_index1, edge_weight1 = edge_index3, edge_weight2
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      else:
      ~~~~~
        edge_index5 = unchecked_cast(__torch__.torch_geometric.typing.SparseTensor, edge_index)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        edge_index6 = unchecked_cast(__torch__.torch_geometric.typing.SparseTensor, edge_index5)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        _cached_adj_t = self._cached_adj_t
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        _10 = torch.__is__(_cached_adj_t, None)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if _10:
        ~~~~~~~
          node_dim0 = self.node_dim
          ~~~~~~~~~~~~~~~~~~~~~~~~~
          _11 = torch.size(x0, node_dim0)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          improved0 = self.improved
          ~~~~~~~~~~~~~~~~~~~~~~~~~
          add_self_loops0 = self.add_self_loops
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          flow0 = self.flow
          ~~~~~~~~~~~~~~~~~
          edge_index8 = _5(edge_index6, edge_weight, _11, improved0, add_self_loops0, flow0, ops.prim.dtype(x0), )
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          cached0 = self.cached
          ~~~~~~~~~~~~~~~~~~~~~
          if cached0:
          ~~~~~~~~~~~
            self._cached_adj_t = edge_index8
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          else:
          ~~~~~
            pass
            ~~~~
          edge_index7 = edge_index8
          ~~~~~~~~~~~~~~~~~~~~~~~~~
        else:
        ~~~~~
          cache0 = unchecked_cast(__torch__.torch_geometric.typing.SparseTensor, _cached_adj_t)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          edge_index7 = cache0
          ~~~~~~~~~~~~~~~~~~~~
        edge_index1, edge_weight1 = edge_index7, edge_weight
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
      edge_index0, edge_weight0 = edge_index1, edge_weight1
    else:
and was used here:
  File "code/__torch__/torch_geometric/nn/conv/gcn_conv.py", line 98
          edge_index7 = cache0
        edge_index1, edge_weight1 = edge_index7, edge_weight
      edge_index0, edge_weight0 = edge_index1, edge_weight1
                                  ~~~~~~~~~~~ <--- HERE
    else:
      edge_index0, edge_weight0 = edge_index, edge_weight
```

Versions:
torch                         2.2.2
torch_geometric               2.5.3

**Comment by rusty1s** [comment]
Mh, it's not necessarily resurfacing. It works fine for `GENConv` but e.g., fails for `GCNConv`/`GATConv`. This is interesting, and I am pretty sure this is a TorchScript bug. I keep digging.

**Comment by zjuadurey** [comment]
Any progress? I met this problem too.
I downloaded jit/gcn.py and used torch.jit.save to get a model.
Then in another script I used "torch.jit.load" to use it and then I reproduced this error.

**Comment by zjuadurey** [comment]
Any progress? I met this problem too.
I downloaded _jit/gcn.py_ and used _torch.jit.save_ to get a model.
Then in another script I used "_torch.jit.load_" to use it and then I reproduced this error.

**Comment by FatemehFathiNiazi** [comment]
Hello, I get the same error  when I want to load a saved scripted model. Any suggestion to fix it?

Type mismatch: edge_index1 is set to type Tensor in the true branch and type __torch__.torch_sparse.tensor.SparseTensor (of Python compilation unit at: 0x55923129cd80) in the false branch:
  File "code/__torch__/models/encoder/gin.py", line 186
      x0 = x2
    _27 = isinstance(edge_index, Tensor)
    if _27:
    ~~~~~~~
      edge_index2 = unchecked_cast(Tensor, edge_index)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      if torch.__isnot__(edge_attr, None):
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        edge_attr2 = unchecked_cast(Tensor, edge_attr)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        edge_attr1 = edge_attr2
        ~~~~~~~~~~~~~~~~~~~~~~~
      else:
      ~~~~~
        ops.prim.RaiseException("AssertionError: ")
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        edge_attr1 = _25
        ~~~~~~~~~~~~~~~~
      _28 = torch.eq(torch.size((x0)[0], -1), torch.size(edge_attr1, -1))
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      if _28:
      ~~~~~~~
        pass
        ~~~~
      else:
      ~~~~~
        ops.prim.RaiseException("AssertionError: ")
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      edge_index1, edge_attr0 = edge_index2, edge_attr1
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    else:
    ~~~~~
      edge_index3 = unchecked_cast(__torch__.torch_sparse.tensor.SparseTensor, edge_index)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      edge_index4 = unchecked_cast(__torch__.torch_sparse.tensor.SparseTensor, edge_index3)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      _29 = torch.eq(torch.size((x0)[0], -1), (edge_index4).size(-1, ))
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      if _29:
      ~~~~~~~
        pass
        ~~~~
      else:
      ~~~~~
        ops.prim.RaiseException("AssertionError: ")
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      edge_index1, edge_attr0 = edge_index4, edge_attr
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    x3 = unchecked_cast(Tuple[Tensor, Optional[Tensor]], x0)
    _30 = isinstance(edge_index1, __torch__.torch_sparse.tensor.SparseTensor)
and was used here:
  File "code/__torch__/models/encoder/gin.py", line 210
      edge_index1, edge_attr0 = edge_index4, edge_attr
    x3 = unchecked_cast(Tuple[Tensor, Optional[Tensor]], x0)
    _30 = isinstance(edge_index1, __torch__.torch_sparse.tensor.SparseTensor)
                     ~~~~~~~~~~~ <--- HERE
    if _30:
      edge_index6 = unchecked_cast(__torch__.torch_sparse.tensor.SparseTensor, edge_index1)


versions:
pytorch                   2.3.1           py3.10_cuda12.1_cudnn8.9.2_0    pytorch
pytorch-cuda              12.1                 ha16c6d3_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytorch-scatter           2.1.2           py310_torch_2.3.0_cu121    pyg
torch-cluster             1.6.3+pt23cu121          pypi_0    pypi
torch-geometric           2.5.3                    pypi_0    pypi
torch-sparse              0.6.18+pt23cu121          pypi_0    pypi

**Comment by FatemehFathiNiazi** [comment]
@rusty1s 

Hello! I have the same problem when loading the saved scripted model in both C++ and Python scripts. I’ve checked #8870 , and the changes you made to fix this problem have already been applied to my torch_geometric/nn/conv/collect.jinja and gen_conv.py, but I’m still struggling with this error. Do you have any suggestions on how I can fix this issue?

@zjuadurey @lee-clement-oxb Were you able to fix the error?

Thanks!

versions:
 torch-cluster             1.6.3+pt23cu121          pypi_0    pypi
torch-geometric           2.5.3                    pypi_0    pypi
torch-sparse              0.6.18+pt23cu121          pypi_0    pypi
pytorch-scatter           2.1.2           py310_torch_2.3.0_cu121    pyg

**Comment by XtremeHammond** [comment]
I have the same thing with GCN not loading in Nvidia Triton as torch.jit.script object. 
However, GENConv worked flawlessly. Seems like this part was fixed.

Versions: 
torch 2.4.1
torch-geometric 2.6.1
triton 3.0.0
tritonclient 2.49.0

**Comment by lucasstarepravo** [comment]
Hi! I'm facing the same issue when calling a scritped model with GCNConv layers in Fortran.

<pre> terminate called after throwing an instance of 'torch::jit::ErrorReport'
  what():  

Type mismatch: edge_index1 is set to type Tensor in the true branch and type __torch__.torch_geometric.typing.SparseTensor (of Python compilation unit at: 0x5f65c3085bf0) in the false branch:
  File "code/__torch__/torch_geometric/nn/conv/gcn_conv.py", line 54
    if normalize:
      _6 = isinstance(edge_index, Tensor)
      if _6:
      ~~~~~~
        edge_index2 = unchecked_cast(Tensor, edge_index)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        _cached_edge_index = self._cached_edge_index
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        _7 = torch.__is__(_cached_edge_index, None)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if _7:
        ~~~~~~
          node_dim = self.node_dim
          ~~~~~~~~~~~~~~~~~~~~~~~~
          _8 = torch.size(x0, node_dim)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          improved = self.improved
          ~~~~~~~~~~~~~~~~~~~~~~~~
          add_self_loops = self.add_self_loops
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          flow = self.flow
          ~~~~~~~~~~~~~~~~
          _9 = _4(edge_index2, edge_weight, _8, improved, add_self_loops, flow, ops.prim.dtype(x0), )
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          edge_index4, edge_weight3, = _9
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          cached = self.cached
          ~~~~~~~~~~~~~~~~~~~~
          if cached:
          ~~~~~~~~~~
            self._cached_edge_index = (edge_index4, edge_weight3)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          else:
          ~~~~~
            pass
            ~~~~
          edge_index3, edge_weight2 = edge_index4, edge_weight3
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        else:
        ~~~~~
          cache = unchecked_cast(Tuple[Tensor, Optional[Tensor]], _cached_edge_index)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          edge_index3, edge_weight2 = (cache)[0], (cache)[1]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        edge_index1, edge_weight1 = edge_index3, edge_weight2
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      else:
      ~~~~~
        edge_index5 = unchecked_cast(__torch__.torch_geometric.typing.SparseTensor, edge_index)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        edge_index6 = unchecked_cast(__torch__.torch_geometric.typing.SparseTensor, edge_index5)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        _cached_adj_t = self._cached_adj_t
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        _10 = torch.__is__(_cached_adj_t, None)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if _10:
        ~~~~~~~
          node_dim0 = self.node_dim
          ~~~~~~~~~~~~~~~~~~~~~~~~~
          _11 = torch.size(x0, node_dim0)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          improved0 = self.improved
          ~~~~~~~~~~~~~~~~~~~~~~~~~
          add_self_loops0 = self.add_self_loops
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          flow0 = self.flow
          ~~~~~~~~~~~~~~~~~
          edge_index8 = _5(edge_index6, edge_weight, _11, improved0, add_self_loops0, flow0, ops.prim.dtype(x0), )
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          cached0 = self.cached
          ~~~~~~~~~~~~~~~~~~~~~
          if cached0:
          ~~~~~~~~~~~
            self._cached_adj_t = edge_index8
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          else:
          ~~~~~
            pass
            ~~~~
          edge_index7 = edge_index8
          ~~~~~~~~~~~~~~~~~~~~~~~~~
        else:
        ~~~~~
          cache0 = unchecked_cast(__torch__.torch_geometric.typing.SparseTensor, _cached_adj_t)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          edge_index7 = cache0
          ~~~~~~~~~~~~~~~~~~~~
        edge_index1, edge_weight1 = edge_index7, edge_weight
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
      edge_index0, edge_weight0 = edge_index1, edge_weight1
    else:
and was used here:
  File "code/__torch__/torch_geometric/nn/conv/gcn_conv.py", line 98
          edge_index7 = cache0
        edge_index1, edge_weight1 = edge_index7, edge_weight
      edge_index0, edge_weight0 = edge_index1, edge_weight1
                                  ~~~~~~~~~~~ <--- HERE
    else:
      edge_index0, edge_weight0 = edge_index, edge_weight </pre>

Versions:
pytorch_geometric 2.6.1
torch 2.8.0 
I don't have any dependencies (torch_scatter, sparse, etc.) in the venv used for scripting

@rusty1s do you have any recommendations how to bypass this? I'm happy to contribute
