### ISSUE TITLE
Running PYG on (2.1, py39, cu113) on HPC system, success on CPU but not on GPU

### ISSUE THREAD

**Issue by starwingc** [pyg-team/pytorch_geometric#8919]
### 😵 Describe the installation problem

I can run the inference on CPU, but there are AttributeError everytime I try it on the GPU node on HPC system. 

The Error is below:

```shell
Traceback (most recent call last):
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs/work/tur54445/git/DiffDock/inference.py", line 16, in <module>
    from utils.utils import get_model
  File "/gpfs/work/tur54445/git/DiffDock/utils/utils.py", line 12, in <module>
    from torch_geometric.nn.data_parallel import DataParallel
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-env/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .sequential import Sequential
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-env/lib/python3.9/site-packages/torch_geometric/nn/sequential.py", line 8, in <module>
    from torch_geometric.nn.conv.utils.jit import class_from_module_repr
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-env/lib/python3.9/site-packages/torch_geometric/nn/conv/__init__.py", line 25, in <module>
    from .spline_conv import SplineConv
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-env/lib/python3.9/site-packages/torch_geometric/nn/conv/spline_conv.py", line 16, in <module>
    from torch_spline_conv import spline_basis, spline_weighting
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-env/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
``` 

### Environment

* PyG version:2.1.0.post1
* PyTorch version:1.12.1
* OS: Node: 2x Intel Xeon E5-2667v4 (8 cores,3.2GHz), 500GB RAM, 2x Nvidia Tesla P100 12GB
* Python version: 3.9
* CUDA/cuDNN version: 12.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):
* - torch-cluster==1.6.0
*  - torch-geometric==2.1.0.post1
*  - torch-scatter==2.0.9
*  - torch-sparse==0.6.15
*  - torch-spline-conv==1.2.1

**Comment by starwingc** [comment]
When I try to start a new conda env, and installation from wheel following:

```python
conda create --name diffdock-gpu python=3.9
conda activate diffdock-gpu
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.2.0+cu121.html
``` 

when I try to import one of the package in python

```python
import pyg_lib
```

The error out put is 
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-gpu/lib/python3.9/site-packages/pyg_lib/__init__.py", line 39, in <module>
    load_library('libpyg')
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-gpu/lib/python3.9/site-packages/pyg_lib/__init__.py", line 36, in load_library
    torch.ops.load_library(spec.origin)
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-gpu/lib/python3.9/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-gpu/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /gpfs/work/tur54445/anaconda3_2023/envs/diffdock-gpu/lib/python3.9/site-packages/libpyg.so)
```

**Comment by starwingc** [comment]
I solved it by installation from wheel. With the pytorch 2.2, cuda 12.1, and python 3.9 version.
