### ISSUE TITLE
Error in gnn_explainer.py example: ValueError - Could not compute gradients for edges

### ISSUE THREAD

**Issue by Takaogahara** [pyg-team/pytorch_geometric#8966]
### 🐛 Describe the bug

Hey folks,

I was going through the `explain/gnn_explainer.py` example, which uses GNNExplainer, and ran into a little snag. It seems like I'm getting this pesky error: 

`ValueError: Could not compute gradients for edges. Please make sure that edges are used via message passing inside the model or disable it via edge_mask_type=None.`

I also tested it using the CaptumExplainer on a binary classification dataset and the issue persists. Any ideas on what might be going on? I'm scratching my head here. 

Here is a code to reproduce the error (the same as `explain/gnn_explainer.py` example):
```
import os.path as osp

import torch
import torch.nn.functional as F

from torch_geometric.datasets import Planetoid
from torch_geometric.explain import Explainer, GNNExplainer
from torch_geometric.nn import GCNConv

dataset = 'Cora'
path = osp.join(osp.dirname(osp.realpath(__file__)), "Planetoid")
dataset = Planetoid(path, dataset)
data = dataset[0]


class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(dataset.num_features, 16)
        self.conv2 = GCNConv(16, dataset.num_classes)

    def forward(self, x, edge_index):
        x = F.relu(self.conv1(x, edge_index))
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = GCN().to(device)
data = data.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

for epoch in range(1, 201):
    model.train()
    optimizer.zero_grad()
    out = model(data.x, data.edge_index)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()

explainer = Explainer(
    model=model,
    algorithm=GNNExplainer(epochs=200),
    explanation_type='model',
    node_mask_type='attributes',
    edge_mask_type='object',
    model_config=dict(
        mode='multiclass_classification',
        task_level='node',
        return_type='log_probs',
    ),
)
node_index = 10
explanation = explainer(data.x, data.edge_index, index=node_index)
print(f'Generated explanations in {explanation.available_explanations}')

path = 'feature_importance.png'
explanation.visualize_feature_importance(path, top_k=10)
print(f"Feature importance plot has been saved to '{path}'")

path = 'subgraph.pdf'
explanation.visualize_graph(path)
print(f"Subgraph visualization plot has been saved to '{path}'")
```
This is the Traceback I received:

```
Traceback (most recent call last):
  File "/media/takaogahara/external/code/GraphChemTools/temp/example.py", line 55, in <module>
    explanation = explainer(data.x, data.edge_index, index=node_index)
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/torch_geometric/explain/explainer.py", line 205, in __call__
    explanation = self.algorithm(
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/torch_geometric/explain/algorithm/gnn_explainer.py", line 87, in forward
    self._train(model, x, edge_index, target=target, index=index, **kwargs)
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/torch_geometric/explain/algorithm/gnn_explainer.py", line 154, in _train
    raise ValueError("Could not compute gradients for edges. "
ValueError: Could not compute gradients for edges. Please make sure that edges are used via message passing inside the model or disable it via `edge_mask_type=None`.
```

I appreciate the help!

### Versions

PyTorch version: 2.2.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.5.0-21-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA RTX A4000
Nvidia driver version: 525.147.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.26.1
[pip3] torch==2.2.1
[pip3] torch_geometric==2.5.0
[pip3] torchaudio==2.2.1
[pip3] torchvision==0.17.1
[pip3] triton==2.2.0
[conda] Could not collect

**Comment by rusty1s** [comment]
Mh, weird. Runs fine on my end. Looks like `edge_mask.grad` is `None` in your case, which explains the error. Is there any chance you can help debugging here to find out why `edge_mask` is not correctly used?
