### ISSUE TITLE
Add typing_extensions support for python 3.7

### ISSUE THREAD

**Issue by pdx97** [pyg-team/pytorch_geometric#9169]
### 🚀 The feature, motivation and pitch

Please Add typing_extensions support for python version 3.7
- Traceback (most recent call last):
  File "torchbeast/monobeast.py", line 19, in <module>
    from agent.geometric.gnnagent import GNNAgent
  File "/home/pdx/Desktop/GTG/agent/geometric/gnnagent.py", line 4, in <module>
    from pytorch_geometric.torch_geometric.nn import RGCNConv, FastRGCNConv
  File "/home/pdx/Desktop/GTG/pytorch_geometric/torch_geometric/__init__.py", line 2, in <module>
    from .edge_index import EdgeIndex
  File "/home/pdx/Desktop/GTG/pytorch_geometric/torch_geometric/edge_index.py", line 4, in <module>
    from typing import (
ImportError: cannot import name 'Literal' from 'typing' (/home/pdx/anaconda3/envs/GTG_1/lib/python3.7/typing.py)

![error_modifiedGCN](https://github.com/pyg-team/pytorch_geometric/assets/28250686/56c06c70-735a-4f54-881e-093234fc6f6a)

**Comment by akihironitta** [comment]
Since many projects already dropped Python 3.7 support as per [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), it may not make sense to have the support back in PyG.

I'd simply recommend using an older version of PyG if you'd like to use Python 3.7.
