### ISSUE TITLE
`torch_geometric.loader.utils.filter_custom_store` Doesn't Work with Edge Features

### ISSUE THREAD

**Issue by alexbarghi-nv** [pyg-team/pytorch_geometric#9566]
### 🐛 Describe the bug

When calling `filter_custom_store`, the node index is used to address edge features.  This is not correct.  No error occurs when there are more edges than nodes, but the output features are incorrect.  If there are more nodes than edges, the output below is possible.

Note that `filter_custom_store` has a [comment](https://github.com/pyg-team/pytorch_geometric/blob/8c849a482c3cf2326c1f493e79d04169b26dfb0b/torch_geometric/loader/utils.py#L229) that states that edge features are unsupported.  However, it still attempts to access them using the node index.

There are two possible solutions here:
1. Preferred: Fix the bug by checking whether features are node/edge features and using the appropriate index (as is done [here](https://github.com/rapidsai/cugraph/blob/35897c6148f633c6cbca7a8693bbb7a11e5e3f54/python/cugraph-pyg/cugraph_pyg/sampler/sampler_utils.py#L423) in a temporary workaround).
2. Modify the remote data API so that edge features are not accessed at all when filtering.

Reproducer:
```
import torch
import torch_geometric

from cugraph_pyg.data import (
    TensorDictFeatureStore,
    GraphStore
)

graph_store = GraphStore(is_multi_gpu=False)
graph_store.put_edge_index(
    torch.tensor([
        [3,4,5],
        [0,1,2],
    ]),
    ('n','r','n'),
    'coo'
)

feature_store = TensorDictFeatureStore()
feature_store[('n','r','n'), 'feat'] = torch.tensor([0,1,2])
feature_store['n', 'feat'] = torch.tensor([1,2,3,4,5,6])

torch_geometric.loader.utils.filter_custom_store(
    feature_store,
    graph_store,
    torch.tensor([0,1,3,4]), # node
    torch.tensor([2,3]), # row
    torch.tensor([0,1]), # col
    torch.tensor([0,1]), # edge
    None
)
```

Output:
```
Traceback (most recent call last):
  File "/home/nfs/abarghi/deleteme.py", line 23, in <module>
    torch_geometric.loader.utils.filter_custom_store(
  File "/home/nfs/abarghi/miniconda3/envs/rapids/lib/python3.11/site-packages/torch_geometric/loader/utils.py", line 236, in filter_custom_store
    tensors = feature_store.multi_get_tensor(required_attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nfs/abarghi/miniconda3/envs/rapids/lib/python3.11/site-packages/torch_geometric/data/feature_store.py", line 389, in multi_get_tensor
    tensors = self._multi_get_tensor(attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nfs/abarghi/miniconda3/envs/rapids/lib/python3.11/site-packages/torch_geometric/data/feature_store.py", line 351, in _multi_get_tensor
    return [self._get_tensor(attr) for attr in attrs]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nfs/abarghi/miniconda3/envs/rapids/lib/python3.11/site-packages/torch_geometric/data/feature_store.py", line 351, in <listcomp>
    return [self._get_tensor(attr) for attr in attrs]
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nfs/abarghi/cugraph6/python/cugraph-pyg/cugraph_pyg/data/feature_store.py", line 100, in _get_tensor
    else tensor[attr.index]
         ~~~~~~^^^^^^^^^^^^
IndexError: index 3 is out of bounds for dimension 0 with size 3
```

### Versions

[pip3] numpy==1.26.4
[pip3] numpydoc==1.7.0
[pip3] torch==2.1.2.post304
[pip3] torch_geometric==2.5.3
[pip3] torch_scatter==2.1.1
[pip3] torchdata==0.7.1+3e9e148
[pip3] triton==2.0.0
[conda] libmagma                  2.7.2                h173bb3b_2    conda-forge
[conda] libmagma_sparse           2.7.2                h173bb3b_3    conda-forge
[conda] libtorch                  2.1.2           cuda120_he0d6596_304    conda-forge
[conda] mkl                       2023.2.0         h84fe81f_50496    conda-forge
[conda] numpy                     1.26.4          py311h64a7726_0    conda-forge
[conda] numpydoc                  1.7.0              pyhd8ed1ab_0    conda-forge
[conda] pytorch                   2.1.2           cuda120_py311h2667f23_304    conda-forge
[conda] torch-geometric           2.5.3                    pypi_0    pypi
[conda] torch-scatter             2.1.1           py311h29ae67e_4    conda-forge
[conda] torchdata                 0.7.1           py311haa783bd_4    conda-forge
[conda] triton                    2.0.0           cuda120py311h6fb472e_4    conda-forge

**Comment by alexbarghi-nv** [comment]
> The issue is caused by filter_custom_store blindly treating all attributes from the feature store as node attributes and using the node index to slice them, which leads to IndexError when an edge attribute is fetched using the node index tensor.
> 
> // Fix in torch_geometric/loader/utils.py
> def filter_custom_store(
>     feature_store: FeatureStore,
>     graph_store: GraphStore,
>     node_index: Tensor,
>     row: Tensor,
>     col: Tensor,
>     edge_index: Tensor,
>     custom_cls: Optional[FeatureStore] = None,
>     **kwargs,
> ) -> Data:
>     # ... (existing code to initialize out object) ...
> 
>     # Filter features:
>     # TODO support edge attributes
>     required_attrs = []
>     for attr in feature_store.get_all_tensor_attrs():
>         if attr.group_name in ['node', 'edge'] or isinstance(attr.group_name, tuple):
>             if attr.group_name == 'edge' or (isinstance(attr.group_name, tuple) and len(attr.group_name) == 3):
>                 attr.index = edge_index
>             else:
>                 attr.index = node_index
>             required_attrs.append(attr)
> 
>     tensors = feature_store.multi_get_tensor(required_attrs)
>     
>     # ... (remaining assignment loop) ...

Yeah, I realized this too.  I can think of a few different solutions, but I think they all ran into some edge cases.  For now I've been using the output edge ids to get edge features from the original feature store.
