### ISSUE TITLE
RuntimeError: derivative for aten::_coalesced_ is not implemented in utils.to_torch_coo_tensor

### ISSUE THREAD

**Issue by p-haddadian** [pyg-team/pytorch_geometric#9613]
### 🐛 Describe the bug

Hey, 

I don't know whether this is a bug. But I am trying to use `torch_geometric.utils.to_torch_coo_tensor` on a CUDA backend, and as the title suggests I keep getting the following error on `loss.backward()`:

```
Traceback (most recent call last):
  File "C:\Users\ASuS\Desktop\Papers\Cheb&Jacobi\code_local\JacobiPool\train.py", line 168, in <module>
    main(arg_parse())
  File "C:\Users\ASuS\Desktop\Papers\Cheb&Jacobi\code_local\JacobiPool\train.py", line 128, in main
    loss.backward()
  File "C:\Users\ASuS\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "C:\Users\ASuS\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\autograd\__init__.py", line 289, in backward
    _engine_run_backward(
  File "C:\Users\ASuS\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\autograd\graph.py", line 768, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: derivative for aten::_coalesced_ is not implemented
```

it came to my attention that the issue may be raised because of the last line of `torch_geometric.utils.to_torch_coo_tensor`:

```python
def to_torch_coo_tensor(
    edge_index: Tensor,
    edge_attr: Optional[Tensor] = None,
    size: Optional[Union[int, Tuple[Optional[int], Optional[int]]]] = None,
    is_coalesced: bool = False,
) -> Tensor:

    if size is None:
        size = int(edge_index.max()) + 1

    if isinstance(size, (tuple, list)):
        num_src_nodes, num_dst_nodes = size
        if num_src_nodes is None:
            num_src_nodes = int(edge_index[0].max()) + 1
        if num_dst_nodes is None:
            num_dst_nodes = int(edge_index[1].max()) + 1
        size = (num_src_nodes, num_dst_nodes)
    else:
        size = (size, size)

    if not is_coalesced:
        edge_index, edge_attr = coalesce(edge_index, edge_attr, max(size))

    if edge_attr is None:
        # Expanded tensors are not yet supported in all PyTorch code paths :(
        # edge_attr = torch.ones(1, device=edge_index.device)
        # edge_attr = edge_attr.expand(edge_index.size(1))
        edge_attr = torch.ones(edge_index.size(1), device=edge_index.device)

    adj = torch.sparse_coo_tensor(
        indices=edge_index,
        values=edge_attr,
        size=tuple(size) + edge_attr.size()[1:],
        device=edge_index.device,
    )
    adj = adj._coalesced_(True)

    return adj
```

I am not sure but I think this issue can be resolved by adding the `is_coalesced=True` argument to `torch.sparse_coo_tensor()` instead of using `adj = adj._coalesced_(True)`.

### Versions

```
PyTorch version: 2.4.0+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 12.5.82
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 950M
Nvidia driver version: 556.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2601
DeviceID=CPU0
Family=198
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2601
Name=Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
ProcessorType=3
Revision=15363

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] torch==2.4.0+cu124
[pip3] torch_cluster==1.6.3+pt24cu124
[pip3] torch_geometric==2.5.3
[pip3] torch_scatter==2.1.2+pt24cu124
[pip3] torch_sparse==0.6.18+pt24cu124
[pip3] torch_spline_conv==1.2.2+pt24cu124
[conda] Could not collect
```

**Comment by Kh4L** [comment]
@p-haddadian could you share a repro?

**Comment by p-haddadian** [comment]
Yeah sure,

Here are two reproductions that can generate the above error:
```python
import torch
import torch_geometric as pyg
from torch_geometric.utils import to_torch_coo_tensor

num_nodes = 5
num_edges = 7
device = 'cuda'

edge_index = torch.randint(0, num_nodes, (2, num_edges)).to(device)
edge_index = pyg.utils.remove_self_loops(edge_index)[0]

edge_attr = torch.rand(edge_index.size(1), 1, requires_grad=True).to(device)

def f(edge_index, edge_attr): return to_torch_coo_tensor(edge_index, edge_attr).to_dense(masked_grad=True)
print(torch.autograd.gradcheck(f, (edge_index, edge_attr.requires_grad_())))
```
The above code should be expected to result in `True`

and for calculating the grads:
```python
import torch
import torch_geometric as pyg
from torch_geometric.utils import to_torch_coo_tensor

num_nodes = 5
num_edges = 7
device = 'cuda'

edge_index = torch.randint(0, num_nodes, (2, num_edges)).to(device)
edge_index = pyg.utils.remove_self_loops(edge_index)[0]
edge_attr = torch.rand(edge_index.size(1), 1, requires_grad=True).to(device)

sparse_sum = to_torch_coo_tensor(edge_index, edge_attr).sum()

sparse_sum.backward()
```

**Comment by rusty1s** [comment]
Will be fixed by https://github.com/pyg-team/pytorch_geometric/pull/9626
