### ISSUE TITLE
Error when downloading `ShapeNet` dataset.

### ISSUE THREAD

**Issue by nachoogriis** [pyg-team/pytorch_geometric#9739]
### 🐛 Describe the bug

I am trying to download the `ShapeNet` dataset for a project in which I need to use PyTorch Geometric. However, I am dealing with some problems when downloading the dataset. It seems that there might be an error in the url from which the dataset is downloaded or something like that, as it is refusing the connection.

To reproduce the error you can execute the following.

```python
import torch
from torch_geometric.data import Data

import urllib.error
from torch_geometric.datasets import ShapeNet

try:
    dataset = ShapeNet(
        root='tmp/ShapeNet',
        categories = ["Airplane"]
    )
except urllib.error.URLError as e:
    print(f"Error al intentar descargar el dataset: {e}")
```

I am getting the following error:

```bash
Downloading https://shapenet.cs.stanford.edu/media/shapenetcore_partanno_segmentation_benchmark_v0_normal.zip
Error al intentar descargar el dataset: <urlopen error [Errno 61] Connection refused>
```

Has anyone already experienced this error? How can I solve it? I need to process the ShapeNet dataset using PyTorch Geometric.

### Versions

.

**Comment by omertalmi5** [comment]
Happen to me also while downloading ogbg-molhiv :
`Traceback (most recent call last):
  File "/home/omertalmi/expiriments/code2/WeightedGraphGPS/main.py", line 142, in <module>
    loaders = create_loader()
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/site-packages/torch_geometric/graphgym/loader.py", line 311, in create_loader
    dataset = create_dataset()
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/site-packages/torch_geometric/graphgym/loader.py", line 234, in create_dataset
    dataset = load_dataset()
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/site-packages/torch_geometric/graphgym/loader.py", line 182, in load_dataset
    dataset = func(format, name, dataset_dir)
  File "/home/omertalmi/expiriments/code2/WeightedGraphGPS/graphgps/loader/master_loader.py", line 153, in load_dataset_master
    dataset = preformat_OGB_Graph(dataset_dir, name.replace('_', '-'))
  File "/home/omertalmi/expiriments/code2/WeightedGraphGPS/graphgps/loader/master_loader.py", line 331, in preformat_OGB_Graph
    dataset = PygGraphPropPredDataset(name=name, root=dataset_dir)
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/site-packages/ogb/graphproppred/dataset_pyg.py", line 66, in __init__
    super(PygGraphPropPredDataset, self).__init__(self.root, transform, pre_transform)
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/site-packages/torch_geometric/data/in_memory_dataset.py", line 81, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log,
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 112, in __init__
    self._download()
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 229, in _download
    self.download()
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/site-packages/ogb/graphproppred/dataset_pyg.py", line 108, in download
    if decide_download(url):
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/site-packages/ogb/utils/url.py", line 12, in decide_download
    d = ur.urlopen(url)
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/omertalmi/anaconda3/envs/try_exact_as_notebook/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>`

**Comment by Kh4L** [comment]
https://github.com/pyg-team/pytorch_geometric/blob/b823c7e80d9396ee5095c2ef8cea0475d8ce7945/torch_geometric/datasets/shapenet.py#L80-L82

seems like it's a known issue, so you can get it manually on kaggle https://www.kaggle.com/datasets/mitkir/shapenet/download?datasetVersionNumber=1
