### ISSUE TITLE
MinCut loss example not running

### ISSUE THREAD

**Issue by Lolash** [pyg-team/pytorch_geometric#993]
## 🐛 Bug

When I try to run `proteins_mincut_pool.py` it's not working.

`Traceback (most recent call last):

  File "C:/Projects/degree-project/gap-implementation/main.py", line 101, in <module>
    train_loss = train(epoch)

  File "C:/Projects/degree-project/gap-implementation/main.py", line 75, in train
    out, mc_loss, o_loss = model(data.x, data.edge_index, data.batch)

  File "C:\Users\michal\Anaconda3\envs\degree-project\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:/Projects/degree-project/gap-implementation/main.py", line 48, in forward
    x, adj, mc1, o1 = dense_mincut_pool(x, adj, s, mask)

  File "C:\Users\michal\Anaconda3\envs\degree-project\lib\site-packages\torch_geometric\nn\dense\mincut_pool.py", line 82, in dense_mincut_pool
    ss / torch.norm(ss, dim=(-1, -2), keepdim=True) -

  File "C:\Users\michal\Anaconda3\envs\degree-project\lib\site-packages\torch\functional.py", line 755, in norm
    return torch._C._VariableFunctions.frobenius_norm(input, dim, keepdim=keepdim)

**RuntimeError: Could not run 'aten::conj.out' with arguments from the 'CUDATensorId' backend. 'aten::conj.out' is only available for these backends: [CPUTensorId, VariableTensorId].**`
## Environment

* OS: Windows 10
* Python version: 3.7.6
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 10.1

## Additional context

https://github.com/pytorch/pytorch/issues/30704 is this issue related? I tried the nightly build, but there are a lot of dependencies on 1.4.0 and the nightly one is 1.5.0.

**Comment by snubeaver** [comment]
you can bypass this issue by adding p=2
   
In this case, 
 ortho_loss = torch.norm(
        ss / torch.norm(ss, dim=(-1, -2), keepdim=True, p=2) -
        i_s / torch.norm(i_s), dim=(-1, -2), p=2)
 ortho_loss = torch.mean(ortho_loss)

will work:D
